### PR TITLE
[9.4-stable] Enable pprof 9.4 lts

### PR DESCRIPTION
**Pull request by christoph-zededa**
As we are backporting features to increase debugging capabilities, I hereby want to start a discussion to backporting pprof capability via edgeview to the stable branch 9.4-stable.

This is still untested.

### CODE REVIEW

**Comment by eriknordmark** [comment]
> As we are backporting features to increase debugging capabilities, I hereby want to start a discussion to backporting pprof capability via edgeview to the stable branch 9.4-stable.

Are there specific issues which we've seen in the past where this would help?
I don't know if pprof has been helpful with OOM crashes but my personal experience is that it isn't very using to get sampled memory usage data.

**Comment by christoph-zededa** [comment]
> > As we are backporting features to increase debugging capabilities, I hereby want to start a discussion to backporting pprof capability via edgeview to the stable branch 9.4-stable.
> 
> Are there specific issues which we've seen in the past where this would help? I don't know if pprof has been helpful with OOM crashes but my personal experience is that it isn't very using to get sampled memory usage data.

We used it successfully to find the memleak in https://github.com/lf-edge/eve-libs/pull/15 .

**Comment by rouming** [comment]
> > As we are backporting features to increase debugging capabilities, I hereby want to start a discussion to backporting pprof capability via edgeview to the stable branch 9.4-stable.
> 
> Are there specific issues which we've seen in the past where this would help? I don't know if pprof has been helpful with OOM crashes but my personal experience is that it isn't very using to get sampled memory usage data.

That thingy was very helpful to reveal the timer leak in pillar. Would be great to have this in our LTSes.

**Comment by eriknordmark** [comment]
Do we already have it in 10.4.X?

**Comment by christoph-zededa** [comment]
> Do we already have it in 10.4.X?

Yes, actually we do.

**Comment by christoph-zededa** [comment]
> LGTM.
> 
> But it might make sense to separately document on a page in the LF-Edge EVE wiki the criteria we have for what to backport. One of them should be "tools which have been necessary to debug issues in the field".

Like this: https://wiki.lfedge.org/display/EVE/Release+Policies ?

**Review by eriknordmark — APPROVED** [review]
Run eden again

**Pull request merged**
