### PR TITLE
Split pubsub into files in prep for abstracting into interface

### PR DESCRIPTION
**Pull request by deitch**
As requested by @eriknordmark [here](https://github.com/lf-edge/eve/pull/416#pullrequestreview-323869891), this makes almost no real changes to pubsub, just splits it out into files, so that #416 can focus just on the structural changes.

* split into files
* resolve 3 linting errors around unchecked error, and not using the `agentName` in `func (sub *Subscription) nameString() string {`, since lint would not pass without it

### CODE REVIEW

**Comment by deitch** [comment]
> the fix in sub.nameString you also have to change FixedDirName

Drat! This seemed so painfully obvious that I added it later at a last phase. 

I don't get it. The code before was:

```go
func (sub *Subscription) nameString() string {
	agentName := sub.agentName
	if agentName == "" {
		agentName = fixedName
	}
	if sub.agentScope == "" {
		return fmt.Sprintf("%s/%s", sub.agentName, sub.topic)
	} else {
		return fmt.Sprintf("%s/%s/%s", sub.agentName, sub.agentScope,
			sub.topic)
	}
 }
```

How was that of any use? It never consumed `agentName` after setting it, since it just used `sub.agentName` (which is what flagged the linter).

**Comment by deitch** [comment]
Updated to pass yetus...

**Comment by eriknordmark** [comment]
> How was that of any use? It never consumed `agentName` after setting it, since it just used `sub.agentName` (which is what flagged the linter).

It wasn't. But the same code in pub.agentName was is useful and different. Just that fixing it in sub will upset the callers assumptions.

**Comment by deitch** [comment]
Makes sense. I will fix it then. We can have a separate PR to fix that along with all dependencies. 

I’ll revert that part in this PR momentarily.

**Comment by deitch** [comment]
Reverted the `nameString()` part, @eriknordmark .

**Comment by deitch** [comment]
Thanks @eriknordmark . I will rebase the other one on this one.

**Comment by deitch** [comment]
Done. Referring to #416 from here on in.

**Pull request merged**
