### PR TITLE
Add API Capability to info message

### PR DESCRIPTION
**Pull request by eriknordmark**
A controller and/or controller UI might want to only attempt operations and features which are supported by EVE-OS.

    As we add new fields/messages to the EdgeDevConfig we need a way for the
    controller to know which additions the device is implementing. This adds
    an explicit ApiCapability field to specify the most recent capability
    the device implements in the EdgeDevConfig API.

Report the shutdown capability in the info message

### CODE REVIEW

**Comment by eriknordmark** [comment]
> 1. When will EVE send this capability data (either feature wise or version indication) to controller? For ex: In the case of upgrade, will EVE wait till the upgrade process to succeed?

No it will send it as soon as it is running the new version. Should it fall back it will send based on the EVE release which is running then.
Basically this isn't trying to predict the future capabilities of what might be running but merely what new parts of the EdgeDevConfig EVE-OS will parse and handle.

> 2. Is this capability data sent periodically or will be a one time action after boot or upgrade?

Sent in every device info message.

**Comment by eriknordmark** [comment]
> Alternatively, can a monotonically incrementing index be embedded into EVE (incremented with every minor EVE release and sent as part of info/metrics) which can be used to lookup for a capability matrix in zedcloud (static capability table added for every minor release in zedcloud). This approach puts some additional load on the release process, but UI apart from enabling/disabling feature can also show the capability matrix of a given device. And EVE/zedcloud do not have to track the capability per feature, instead happens per release.

The problem with this is that it assumes a simple mapping between EVE version strings and EVE API versions, which begs the question whether we'd add the 0.0.0-* EVE version strings to that mapping; in fact we would have to in order to run regression tests on EVE PRs. That seems very painful.
But also, if down the road someone else (some hardware OEM, whoever) issues their own EVE-OS releases we would also have to teach the controller about the mapping from their EVE version strings to the API capabilities.
Doing this explicitly avoids all of those issues.

**Comment by giggsoff** [comment]
Yetus(buflint) suggest renaming of proto enum, probably it is reasonable.
Also I am not sure that we should add unsupported fields there (we can add them as comments now) because of no information about the order of their implementation/testing/done cycle. And we are not sure now that they will have order you defined. I think we should add fields to enum during implementation of capability (in the same PR) or a bit later (in release after testing). Probably it would be nice to define this statement somewhere in docs.

**Review by milan-zededa — APPROVED** [review]
LGTM but agree with @petr-zededa that the unimplemented capabilities should be probably commented out for now.
We could maybe also add something like `CAPABILITY_WWAN_GPS` so that controller can print warning like "GPS not supported" if user configures cellular network with GPS enabled for device with an older EVE (CC @gkodali-zededa).

**Comment by eriknordmark** [comment]
Addressed the comments from @giggsoff and @milan-zededa. Don't know about adding API_CAPABILITY_WWAN_GPS

**Comment by lucas-zededa** [comment]
@eriknordmark I think the unit test failure was recently fixed by @giggsoff , no?

```
commit dee0c391e23f40e08b7e7eacf2e532c03086c846 (HEAD -> master, origin/master, origin/HEAD)
Author: Petr Fedchenkov <giggsoff@gmail.com>
Date:   Mon Jun 6 13:06:42 2022 +0300

    WorkerPool races fixes
    
    "go test -race" indicates several potential races inside workerpool_test
    . Testing CI returns error as well "panic: close of closed channel" in
    Done function. Seems we should add locking around workers and make
    atomic numChan edits.
    
    Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>
```

**Comment by giggsoff** [comment]
> @eriknordmark I think the unit test failure was recently fixed by @giggsoff , no?
> 
> ```
> commit dee0c391e23f40e08b7e7eacf2e532c03086c846 (HEAD -> master, origin/master, origin/HEAD)
> Author: Petr Fedchenkov <giggsoff@gmail.com>
> Date:   Mon Jun 6 13:06:42 2022 +0300
> 
>     WorkerPool races fixes
>     
>     "go test -race" indicates several potential races inside workerpool_test
>     . Testing CI returns error as well "panic: close of closed channel" in
>     Done function. Seems we should add locking around workers and make
>     atomic numChan edits.
>     
>     Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>
> ```

Parent commit of current changes is https://github.com/eriknordmark/eve/commit/71a6ed0790a8f786859c76172bed521c774f57ec (you can see it here https://github.com/eriknordmark/eve/commit/ae9dc377b2d503bcd0f768a6b752e419eaefc8d8).

**Review by giggsoff — APPROVED** [review]
LGTM

**Review by ssat-zededa — APPROVED** [review]

**Pull request merged**
