### PR TITLE
network overlap check; log gcp console; remove unneeded images

### PR DESCRIPTION
**Pull request by giggsoff**
Add checks for networks overlap inside hosted VM and Eden.
Remove unneeded images to save space inside VM.
Add GCP console to log.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by rvs — CHANGES_REQUESTED** [review]
I don't get this change -- why is this needed @giggsoff ? I mean there were issues with GCP clashes for some internal things but IIRC @eriknordmark fixed all of that.

Besides -- it looks weird to simply fail here -- I mean if GCP is not reliable for our testing we need to either change EVE or find a different hosting provider.

**Comment by petr-zededa** [comment]
In fact, when we ran into overlap issues, we [decided](https://github.com/lf-edge/eden/pull/532#pullrequestreview-595330630) to perform checks on top of the workflow. In this case, it is easier to handle changes in the environment that can occur regardless of the tests.

**Comment by eriknordmark** [comment]
> I don't get this change -- why is this needed @giggsoff ? I mean there were issues with GCP clashes for some internal things but IIRC @eriknordmark fixed all of that.

@rvs the only thing I fixed was the use of 129.254.169.254.
@petr-zededa has run into other conflicts e.g., when an eden test is using IP address X and the GCP VPN is also using IP address X. Or Adam's IP address is in the same subnet as that of a network instance.
While we can add some ad-hoc checks for this in EVE (and maybe we should - a network instance creation should never break EVE's ability to reach the controller), I think the real fix has to be to put network instances (the linux bridge etc) in a separate network namespace to avoid any direct impact on the host.
Until then I think the checks in this PR help avoid spending time debugging these issues.

**Review by eriknordmark — APPROVED** [review]
As I said in the comment, I think this helps.
Let it test.

**Review by rvs — APPROVED** [review]
Fair enough -- I suppose it is better than the alternative

**Pull request merged**
