### PR TITLE
[WIP] kvm-tools: Add vhost-user-nvme patch for QEMU

### PR DESCRIPTION
**Pull request by vk-en**
Added patch for QEMU adding functionality to create a vhost-user-nvme handler

### CODE REVIEW

**Review by rvs — APPROVED** [review]
LGTM

**Review by rvs — CHANGES_REQUESTED** [review]
Conceptually this is fine, but obviously the build has to be fixed.

**Comment by temerkhanov** [comment]
There are lots of undefined references which need to be fixed.

**Comment by vk-en** [comment]
The build problem is not complicated and solved, but it is not the only problem that I am currently solving. I will try to release an update today.

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
