### PR TITLE
Enable ethernet on Siemens IPC 227G

### PR DESCRIPTION
**Pull request by mikem-zed**

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Review by eriknordmark — APPROVED** [review]
What's the impact on the size of the image?

**Comment by mikem-zed** [comment]
> What's the impact on the size of the image?

i did not measure but it should be just a few kilobytes

**Review by rene — COMMENTED** [review]
@mikem-zed , LGTM, maybe you could just put a bit more information in the commit message about which controllers you are enabling the support. You've enabled more than one driver, how many ethernet controllers are present on this device?

**Comment by mikem-zed** [comment]
> @mikem-zed , LGTM, maybe you could just put a bit more information in the commit message about which controllers you are enabling the support. You've enabled more than one driver, how many ethernet controllers are present on this device?

@rene Idk what these chipsa are. But I know what modules are loaded for them and I enabled just those modules. the rest was enabled automatically by dependencies in kbuild files

**Pull request merged**
