### PR TITLE
changed example ipxe.cfg url to use EVE-OS release 6.10.0

### PR DESCRIPTION
**Pull request by kgiori**
Signed-off-by: Kathy Giori <kathy.giori@gmail.com>

### CODE REVIEW

**Comment by rvs** [comment]
Hey @kgiori -- you need to navigate here https://github.com/lf-edge/eve/pull/2197/files and make sure you review and fix all the little annoying things flagged by Yetus (they look like white blocky comments inside of the changes you made).

**Review by kgiori — COMMENTED** [review]
hopefully found and deleted extra spaces at end of lines.

**Review by eriknordmark — COMMENTED** [review]
Should we put $REL instead of the specific 6.10.0 string in the examples so avoid having this page become stale very quickly?

**Comment by kgiori** [comment]
DCO seems to be failing and I'm not sure how to fix.

**Review by rvs — APPROVED** [review]
Hey @kgiori -- as it say -- there's a mismatch between  "kgiori kgiori@users.noreply.github.com" vs "Kathy Giori kathy.giori@gmail.com". This is DCO check silliness -- but we kind of have to live with it.

So... for now I'm going to merge it as-is. But going forward -- either don't mix GH UI and cli OR if you do -- make sure to manually edit the signature when you do commits.

**Pull request merged**
