### PR TITLE
Rpi4: new-kernel changes with xen fix

### PR DESCRIPTION
**Pull request by Insei**
To fix Xen on linux 5.10.y, I had to update dtb in u-boot package.

Add rpi4 usb configs changes to 5.10.y kernel config.

If you build EVE with KVM, the old kernel stopped loading, because the new dtb that in u-boot package from 5.10.y does not fit the 5.4.y kernel that is used in kvm. Therefore, changes were added to the grub config to load the correct dtb.

### CODE REVIEW

**Review by rvs — CHANGES_REQUESTED** [review]
This is good work @Insei -- but now that you removed `bcm2711-rpi-4-b.dtb` I recommend you do `git grep -l bcm2711-rpi-4-b` in the repo after this PR is applied and fix whatever left there. Most of it is cosmetics -- but `pkg/eve/runme.sh` is functionality and it must be fixed before this can be merged.

**Comment by Insei** [comment]
> This is good work @Insei -- but now that you removed `bcm2711-rpi-4-b.dtb` I recommend you do `git grep -l bcm2711-rpi-4-b` in the repo after this PR is applied and fix whatever left there. Most of it is cosmetics -- but `pkg/eve/runme.sh` is functionality and it must be fixed before this can be merged.

But I did not delete `bcm2711-rpi-4-b.dtb` is still needed in the efi partition.

**Comment by Insei** [comment]
new info:
dtb file is only needed for u-boot.bin. Rpi4 bootloader does not require them and loads u-boot normally. but the U-boot itself is no longer loaded.

I see this by logs(enable first and second stage logs):
```
PM_RSTS: 0x00001000
RPi: BOOTLOADER release VERSION:c305221a DATE: Sep  3 2020 TIME: 13:11:46 BOOTMODE: 0x00000006 part: 0 BUILD_TIMESTAMP=1599135103 0xca6dd41d 0x00c03111
uSD voltage 3.3V
Initialising SDRAM 'Micron' 16Gb x2 total-size: 32 Gbit 3200
XHCI-STOP
xHC ver: 256 HCS: 05000420 fc000031 00e70004 HCC: 002841eb
xHC ports 5 slots 32 intrs 4
Reset USB port-power 1000 ms
Boot mode: SD (01) order f4
SD HOST: 250000000 CTL0: 0x00000000 BUS: 100000 Hz actual: 100000 HZ div: 2500 (1250) status: 0x1fff0000 delay: 1080
SD HOST: 250000000 CTL0: 0x00000f00 BUS: 100000 Hz actual: 100000 HZ div: 2500 (1250) status: 0x1fff0000 delay: 1080
CID: 00744a60555344553120531077460124
CSD: 400e00325b5900003c1d7f800a400000
SD: bus-width: 4 spec: 2 SCR: 0x02358003 0x00000000
SD HOST: 250000000 CTL0: 0x00000f04 BUS: 50000000 Hz actual: 41666666 HZ div: 6 (3) status: 0x1fff0000 delay: 2
MBR: 0x00000800,   73728 type: 0x0c
MBR: 0x00000001,    2047 type: 0xee
MBR: 0x00000000,       0 type: 0x00
MBR: 0x00000000,       0 type: 0x00
lba: 2048 oem: 'mkfs.fat' volume: ' EVE        '
rsc 32 fat-sectors 567 c-count 72562 c-size 1 r-dir 2 r-sec 0
PM_RSTS: 0x00001000
Partition: 0
lba: 2048 oem: 'mkfs.fat' volume: ' EVE        '
rsc 32 fat-sectors 567 c-count 72562 c-size 1 r-dir 2 r-sec 0
Read config.txt bytes       47 hnd 0x0000088a hash '570fea47bc8decdf'
recover4.elf not found (6)
recovery.elf not found (6)
Read start4.elf bytes  2227200 hnd 0x00001e3e hash '0e07ea2d056832e8'
Read fixup4.dat bytes     5430 hnd 0x00002f3c hash 'c2eb2ff734648cae'
0x00c03111 0x00000000 0x0000003f
MEM GPU: 76 ARM: 948 TOTAL: 1024
Starting start4.elf @ 0xfec00200 partition 0

MESS:00:00:05.402470:0: arasan: arasan_emmc_open
MESS:00:00:05.550994:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:05.553688:0: brfs: File read: 47 bytes
MESS:00:00:05.620981:0: brfs: File read: /mfs/sd/config.txt
MESS:00:00:05.639123:0: brfs: File read: 47 bytes
MESS:00:00:06.119961:0: gpioman: gpioman_get_pin_num: pin DISPLAY_DSI_PORT not defined
MESS:00:00:06.127249:0: *** Restart logging
MESS:00:00:06.132250:0: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
MESS:00:00:06.141607:0: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
MESS:00:00:06.147538:0: HDMI0: hdmi_pixel_encoding: 300000000
MESS:00:00:06.153006:0: HDMI1: hdmi_pixel_encoding: 300000000
MESS:00:00:06.163215:0: dtb_file 'bcm2711-rpi-4-b.dtb'
MESS:00:00:06.165368:0: Failed to load Device Tree file '?'
MESS:00:00:06.170665:0: Failed to open command line file 'cmdline.txt'
MESS:00:00:06.224334:0: brfs: File read: /mfs/sd/u-boot.bin
MESS:00:00:06.226800:0: Loading 'u-boot.bin' to 0x8000 size 0x88c98
MESS:00:00:06.234889:0: uart: Set PL011 baud rate to 103448.300000 Hz
MESS:00:00:06.241919:0: uart: Baud rate change done...
```

**Comment by rvs** [comment]
So why touch DTB to begin with? u-boot seems fine with the one we've got -- and after u-boot you're making GRUB load the correct DTB anyway, right @Insei ?

**Comment by Insei** [comment]
> So why touch DTB to begin with? u-boot seems fine with the one we've got -- and after u-boot you're making GRUB load the correct DTB anyway, right @Insei ?

Yes, at first I updated it to work with xen, but then the direct need to update it disappeared. But dtb is still updated. I don't think this is bad. But if this need, i can rebase without this change. But we can't remove this dtb from u-boot package.

**Comment by rvs** [comment]
That's be my preference @Insei -- if you can leave DTB as-is (just make sure u-boot actually boots all the way through) I can merge it that way and we can test it fully. If we find any issues -- we can always update DTB just for u-boot later on.

**Comment by Insei** [comment]
> That's be my preference @Insei -- if you can leave DTB as-is (just make sure u-boot actually boots all the way through) I can merge it that way and we can test it fully. If we find any issues -- we can always update DTB just for u-boot later on.

Okay, all complete.

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
