### PR TITLE
zedupload: Upgrade to go 1.18, avoid replace directive for nettrace

### PR DESCRIPTION
**Pull request by milan-zededa**
Now that `nettrace` package development is completed, let's reference it from `zedUpload` properly, without using a replace directive. This should fix dependency issues experienced from packages outside of EVE that import `zedUpload`.

### CODE REVIEW

**Comment by OhmSpectator** [comment]
Tested make proto proto-vendor.
Works fine now.

**Comment by OhmSpectator** [comment]
After running make proto proto-vendors, I have the following changes in the files:
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   api/images/devconfig.dot
        modified:   api/images/devconfig.dot.svg
        modified:   api/images/devconfig.png

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        pkg/pillar/vendor/github.com/lf-edge/eve/libs/nettrace/LICENSE

```
Is it ok?

**Comment by milan-zededa** [comment]
@OhmSpectator I forgot to add nettrace license, should be OK now. Not sure about the rendered graph + image and why their differ though...

**Comment by OhmSpectator** [comment]
Ok, LGTM

**Review by eriknordmark — APPROVED** [review]
Thanks for the careful review @OhmSpectator

**Pull request merged**
