### PR TITLE
[GH action] Assets use actions for release creation

### PR DESCRIPTION
**Pull request by dautovri**
The changes primarily involve simplifying the release creation and asset upload processes by utilizing GitHub Actions' built-in functionalities instead of custom scripts.

Improvements to GitHub Actions workflow:

* Simplified the release creation process by replacing the custom script with the `actions/create-release@v1` action and updating the output references accordingly.
* Streamlined the asset upload process by removing the custom upload script and using the `actions/upload-release-asset@v1` action to handle the file uploads.

### CODE REVIEW

**Comment by yash-zededa** [comment]
@dautovri We recently transitioned from using these GitHub Actions to an API. These actions are no longer actively developed, as indicated in the repository:

> The repository was archived by the owner on March 4, 2021.

Additionally, the actions were not well-suited to our use case. Although we switched to a different action, we encountered issues with uploads to the same release.

**Review by deitch — APPROVED** [review]
Anything and everything that lets us use off the shelf is defined as a "good thing".

**Comment by yash-zededa** [comment]
> Anything and everything that lets us use off the shelf is defined as a "good thing".

@deitch I agree, but the actions `create-release@v1` and `upload-release-asset` didn’t work well for us. Since these actions are no longer being maintained, any changes to the underlying scripts or APIs they rely on could potentially cause issues in the future.

We then switched to using `softprops/action-gh-release`, but it also encountered a problem with multiple uploads for the same release. As a result, we opted to use the GitHub API, which has consistently proven to be more reliable than custom actions.

Furthermore, we have tested the assets workflow, and it has performed successfully across all releases up to `12.0-stable`.

**Comment by deitch** [comment]
When it comes to GH Actions, I defer to @yash-zededa wisdom and experience.   😄

**Comment by uncleDecart** [comment]
Second @yash-zededa in using APIs instead of actions, they brought us pain before, best to document it somewhere...

**Comment by dautovri** [comment]
Ok, thanks for the comments.  I will close PR

**Pull request closed without merging**
