### PR TITLE
[11.0 stable] Backport of container app debugging techniques

### PR DESCRIPTION
**Pull request by rouming**
The PR may be controversial and may be closed (depends on the outcome of the ongoing discussion), because PR backports not fixes (according to the backport process), but debugging improvements as the following:

1. Console attach feature helps to debug container applications.
2. More logs from chroot2 utility.
3. EVE_CONTAINER_NO_POWEROFF mode, which helps to avoid Vm shutdown if internal container does not start.

All of these should help customers and customer support to debug problems with applications.

Let's see what will be the decision.

### CODE REVIEW

**Review by OhmSpectator — APPROVED** [review]
I think it makes sense to backport... Most of our debugging happens with older LTS releases, so to benefit from these changes, we must wait too long for the moment when the customers take new releases.
@rouming I would also backport all the changes we have in the collect-info scripts.

**Comment by eriknordmark** [comment]
Makes sense to have others who debug issues in the field comment on the backport of such tools to LTS releases.

**Review by eriknordmark — APPROVED** [review]
LGTM but since we are patching this we need sufficient container-based app tests.

**Comment by rouming** [comment]
Yes, shame on me, I again forgot to include the change for the kvm test. This is the commit https://github.com/lf-edge/eve/pull/3649/commits/bc8f1c3b553974ef62e241077c9a288e642a4a1d
Let's see.

**Comment by rouming** [comment]
@eriknordmark the "Test (TPM required)" test failed because "no operating system" found. Not sure what that can mean.

**Comment by eriknordmark** [comment]
> @eriknordmark the "Test (TPM required)" test failed because "no operating system" found. Not sure what that can mean.

Check with @shjala if he knows more about this test.

**Comment by rouming** [comment]
Rebased on latest 11.0-stable

**Review by eriknordmark — APPROVED** [review]
Run eden again

**Review by eriknordmark — APPROVED** [review]
Kick off eden again

**Pull request merged**
