### PR TITLE
[10.4-stable] Estimating Memory Overhead Before Domain Creation

### PR DESCRIPTION
**Pull request by OhmSpectator**
It's a backport of https://github.com/lf-edge/eve/pull/3588 into 10.4.

I had to refactor the code a bit:

The 10.4 version has no reworked overhead estimation introduced later by @rucoder, so I used the old implementation to get it. This implementation does not take adapters into account.

For the tests, I just checked that an app started successfully. I can perform the tests that touch the new logic, but it has not been done yet.

### CODE REVIEW

**Review by eriknordmark — CHANGES_REQUESTED** [review]
Same issues/concerns as in #3598

**Comment by OhmSpectator** [comment]
The list of the commits to be backported:

Processing PR #3383...
PR #3383 - Master Hash: 10f3ba666fe45258533c265b0e81516a5c694ca6
PR #3383 - Master Hash: c79d3fe8d57b65d0f0958219f234636dec6fb8e7
Processing PR #3504...
PR #3504 - Master Hash: c79d3fe8d57b65d0f0958219f234636dec6fb8e7

**Comment by OhmSpectator** [comment]
I've added the commits related to overhead estimation that were not in the packported before. 
Need to retest.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
