### PR TITLE
[RFC] Add support to readthedocs.io

### PR DESCRIPTION
**Pull request by rene-zededa**
This PR is a RFC. I would like to propose add support to mkdocs to EVE's documentation. By doing, so, the documentation can be generated in a fancy format and get published (automatically) to readthedocs.io or other compatible system.

In fact, you can find EVE's documentation generated by the changes of this PR at: https://eve-os.readthedocs.io/en/latest/

The documentation is generated from EVE's sources, so it can be kept up to date, it provides a structured menu with all main topics, a search system to search throughout the docs and it can also be deployed locally through mkdocs embedded web server.

This PR adds support to mkdocs and readthedocs.io at once. Please, find below the main commit message that explains all the changes:

```
docs: Add support to readthedocs.io

    Add support to mkdocs and readthedocs.io in order to build EVE's
    documentation through mkdocs and allow to publish it at readthedocs.io.
    Document sources (.md, .txt, etc) are located through the whole repository.
    Unfortunately, mkdocs doesn't allow to keep the configuration file along
    with document sources, so this commit adds a python script which
    reassembles the repository's tree only with documentation sources and
    related files, such as figures (.png, .svg). Additionally, it changes all
    relative links that point to some other file in the repository, such as .go
    and .sh files, with the full URL that will point to Github EVE's
    repository.

    The documentation can be also built locally, through the following
    commands:

    python3 docs/mkdocs/prepare-mkdocs.py \
            dist/docs-src \
            "https://github.com/lf-edge/eve/blob/master"
    cp docs/mkdocs/mkdocs.yml .
    mkdocs build

    Documentation files will be built at dist/docs-src and the links for source
    files throughout the documentation will point to master branch.

    To visualize the documentation through a local web server, use:

    mkdocs serve

    And access it through the URL:

    http://127.0.0.1:8000/projects/eve/

    Signed-off-by: Renê de Souza Pinto <rene@zededa.com> 
```

Any comments on that are very welcome.

### CODE REVIEW

**Comment by rene-zededa** [comment]
Updates in this PR: Fix all pylint yetus warnings.

**Comment by rene-zededa** [comment]
Updates in this PR: Fix more spelling errors pointed by yetus.

**Review by eriknordmark — CHANGES_REQUESTED** [review]
I think it makes sense to split this apart into multiple PRs; put the fixes to the typos and links in one and we can get that merged.

For the readthedocs part, you list a bunch of links to package docs in docs/mkdocs/mkdocs.yml.
Ideas for how we would keep that file up to date? Will the build fail if a URL has gone bad? Amd then we manually need to remember to add new URLs for new packages?

**Comment by rene** [comment]
> I think it makes sense to split this apart into multiple PRs; put the fixes to the typos and links in one and we can get that merged.
> 
> For the readthedocs part, you list a bunch of links to package docs in docs/mkdocs/mkdocs.yml. Ideas for how we would keep that file up to date? Will the build fail if a URL has gone bad? Amd then we manually need to remember to add new URLs for new packages?

Indeed @eriknordmark , it does make sense to break the typo fixes from the readthedocs.io support. I will put them into another PR.

Regarding the mkdocs.xml, yes, the links were done manually. They are used to build the left menu shown in the documentation. At one hand we can choose the best logical organization for the topics. At the other hand, we must maintain the file, so new packages will need to be manually added as well....

The lack of links or wrong links will just generate warnings. As of now they will not break the build (fail_on_warning: false), but this can be changed in the future when we get rid of all warnings due to broken links throughout the documentation....

**Comment by rene-zededa** [comment]
@eriknordmark , I've updated this PR. Now it contains only the commit associated to the proposal (add support to mkdocs). All yetus spelling fixes were made into another PR, already active: https://github.com/lf-edge/eve/pull/2815

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
I don't understand why yetus fails without producing any errors. Can you try rebasing on current master to see if it makes a difference?

**Comment by giggsoff** [comment]
> I don't understand why yetus fails without producing any errors. Can you try rebasing on current master to see if it makes a difference?

Let me copy output from `results-yamllint.txt` of yetus's artifacts:
```
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=48,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=51,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=54,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=57,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=61,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=64,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=66,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=69,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=76,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=89,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=93,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=95,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=102,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=213,col=5::[indentation]: wrong indentation: expected 6 but found 4
::warning file=docs/mkdocs/mkdocs.yml,line=1,col=1::[document-start] missing document start "---":::error: file=docs/mkdocs/mkdocs.yml,line=215,col=5::[indentation]: wrong indentation: expected 6 but found 4
```

Seems yamllint want to see `---` in the beginning of the file and 6 spaces as indentation for nested objects.

**Comment by rene** [comment]
@eriknordmark , @giggsoff , I've fixed all yetus errors related to this PR. I opened a new PR (https://github.com/lf-edge/eve/pull/2822) pushed through my regular (default) GitHub account. I will close this one.

**Pull request closed without merging**
