### PR TITLE
Naiming edgeview vendor

### PR DESCRIPTION
**Pull request by naiming-zededa**
Change edgeview dockerfile to use vendor.

### CODE REVIEW

**Review by milan-zededa — APPROVED** [review]

**Comment by deitch** [comment]
Oh this is funny. I am working on builds that do not use network (for compliance reasons), and came across this, and just have been solving the same issue. This is nice, once it is in, I can just rebase on it.

**Comment by milan-zededa** [comment]
@deitch Actually not a coincidence - Erik brought it up: https://github.com/lf-edge/eve/pull/2884#issuecomment-1292165704

**Comment by deitch** [comment]
Heh, I missed that. Either way, I am happy to see this in place.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by deitch** [comment]
Thank you for this. I rebased #2861 on it, and it is much simpler.

**Pull request merged**
