### PR TITLE
[10.4 stable] Timeout calling dhcpcd

### PR DESCRIPTION
**Pull request by rouming**
These are commits originally submitted by @christoph-zededa to the master branch, which target the issue, which was observed on the 9.7 version. I would like to merge them to the 10.4 stable in order to ask the customer to switch to more recent and stable version.

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM.

But it would be nice to have the commit messages refer to the commit hashes in master to make it easier to compare. FWIW I use git cherry-pick -x which does that automatically.

**Comment by rouming** [comment]
Difference to the previous version:
* Add original sha to the cherry-picked commits

**Comment by eriknordmark** [comment]
Hmm - the jenkins ztests job is failing on this, and for some reason the Eden pipeline does not run on the release/patch branches. Needs to be investigated.

**Comment by rouming** [comment]
@eriknordmark I do not see any failures. How can I check those?

**Comment by rouming** [comment]
Jenkins fails because eve can't unlock vault. Why eden has not been started - I have no idea, since I so not see any errors. I asked @yash-zededa , probably he can help. 

What I did here is to reverted those 3 patches (basically make this PR bogus) in order to get better understanding will something pass or not.

**Comment by eriknordmark** [comment]
I manually kicked of a jenkins run for this (now empty) PR.

**Review by yash-zededa — APPROVED** [review]

**Review by yash-zededa — APPROVED** [review]

**Comment by eriknordmark** [comment]
Tried the image manuall on sc-supermicro-zc2 and get the same failure (attestation completes successfully but vault does not get unlocked). Will try 10.4.2-kvm-amd64 as well.

**Comment by eriknordmark** [comment]
I've tried this PR build and various 10.4.X builds.
The conclusion is that the xen variant of this PR and 10.4.3-xen-amd64 fails, but 10.4.1-xen-amd64 and 10.4.2-xen-amd64 are OK. All kvm variants work, including of this PR.
So there must be some interaction between the PRs which went into https://github.com/lf-edge/eve/releases/tag/10.4.3 somehow causes Xen to not unlock the vault.

**Comment by rouming** [comment]
@eriknordmark so we have a xen regression between 10.4.2 and 10.4.3. I will take a look.

**Comment by rouming** [comment]
Difference to the previous version:
* Removed all reverted changes, so now the PR description corresponds to actual commits.

**Comment by eriknordmark** [comment]
We should merge this, but we do need to figure out why 9.4.3-xen-amd64 has issues with the vault.

**Pull request merged**
