### PR TITLE
Update Linux FW and REGDB

### PR DESCRIPTION
**Pull request by rucoder**
**NOTE**: this PR depends on https://github.com/lf-edge/eve/pull/3852

Image size impact: negative, we save about 7Mb of space in rootfs

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by rucoder** [comment]
@eriknordmark I have not updated eve-alpine hash. Do not merge yet

**Comment by eriknordmark** [comment]
> @eriknordmark I have not updated eve-alpine hash. Do not merge yet

The more robust way to handle such situtations is the mark the PR as a draft, which I just did.

**Comment by rucoder** [comment]
> > @eriknordmark I have not updated eve-alpine hash. Do not merge yet
> 
> The more robust way to handle such situtations is the mark the PR as a draft, which I just did.

I agree, the PR https://github.com/lf-edge/eve/pull/3852 build failed initially and we had to rerun it and then I had to run to airport. All green now, we can merge

**Pull request merged**
