### PR TITLE
pillar: Remove residual kernel version check

### PR DESCRIPTION
**Pull request by temerkhanov**
Remove residual kernel version check since the kernel in in the master branch has necessary io_uring fixes

Signed-off-by: Sergey Temerkhanov <s.temerkhanov@gmail.com>

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
Doesn't this mean that the kernelVersionTag() can be removed?

**Comment by temerkhanov** [comment]
> Doesn't this mean that the kernelVersionTag() can be removed?

It could be safely dropped as well

**Review by eriknordmark — CHANGES_REQUESTED** [review]
Looks like kvm_test.go needs to be updated to have io_uring.

**Comment by rvs** [comment]
Hey @temerkhanov this looks much better now -- but there still appears to be a conflict in `pkg/pillar/hypervisor/kvm.go` can you please rebase on the latest master?

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
