### PR TITLE
Fix phylabel/logicallabel confusion in info and metrics messages

### PR DESCRIPTION
**Pull request by eriknordmark**
@bharani-zededa this includes some comment changes in the EVE API, plus the code changes to use the logical label in the info and metrics messages. Have verified this using qemu to date.
Also verifying that things work correctly when all three of logicallabel, physical label, and ifname differ.
(Only issue there seems to be that I can't change the model for an existing device - but creating a new device is working.)

### CODE REVIEW

**Comment by kalyan-nidumolu** [comment]
FWIW - Logical labels can change - user can edit them.. This can cause a bit of complexity in tracking them.. From previous conversations with Bharani, the decision was to include both phy / logical where ever we can.. And if needed - ifname too - but name them explicitly - atleast in the comments.. Thats what we ended up doing.

**Comment by eriknordmark** [comment]
> FWIW - Logical labels can change - user can edit them.. This can cause a bit of complexity in tracking them.. From previous conversations with Bharani, the decision was to include both phy / logical where ever we can.. And if needed - ifname too - but name them explicitly - atleast in the comments.. Thats what we ended up doing.

Where can the user edit them?
FWIW I created a modified model with different logicallabels, and did a model update. The UI+controller got all confused by that.
Creating a new edge-node based on that model worked fine.

**Comment by bharani-zededa** [comment]
Can we just rename the field(s) in the proto definitions appropriately, so it is clear from the field name what it refers to.

**Comment by kalyan-nidumolu** [comment]
The intention is that it will be allowed to change.. it may not yet be
implemented. We don't want to break that

Thanks,
Kalyan

**Comment by eriknordmark** [comment]
> The intention is that it will be allowed to change.. it may not yet be implemented. We don't want to break that

EVE treats such a change as any other change to systemadapters. That should be fine.

**Comment by eriknordmark** [comment]
> Can we just rename the field(s) in the proto definitions appropriately, so it is clear from the field name what it refers to.

@bharani-zededa That could be fairly wide-ranging. Part of the issue is that the System Adapter (on the config side) refers to something as a lower layer. So should we change that to logicallabel as well?
And using "*name", except for "ifname", for any of this is part of the confusion. Either it is an ifname, logicallabel, or physicallabel. But that would touch the config and info/metrics side.

FWIW I realized the network instance is using Adapter.name, so I'm adding a comment for that as well to specify that it is the logicallabel (that is how the code interprets it, which is consistent with the design).

**Pull request merged**
