### PR TITLE
fix go.mod path for edgeview, add v6 flow

### PR DESCRIPTION
**Pull request by naiming-zededa**
- fix the edgeview go.mod module path
- added ipv6 flow
- fixed an issue of tcp channel index check

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by naiming-zededa** [comment]
fixed a newline typo.

**Review by eriknordmark — APPROVED** [review]
Run eden again

**Review by deitch — CHANGES_REQUESTED** [review]
We made the module name `pkg/edge-view` but the path is `pkg/edgeview`

**Review by eriknordmark — APPROVED** [review]
Run eden

**Review by deitch — APPROVED** [review]

**Pull request merged**
