### PR TITLE
vnc password from spec annotation

### PR DESCRIPTION
**Pull request by giggsoff**
Seems, that we miss vnc password annotation 

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by rvs — CHANGES_REQUESTED** [review]
Great catch @giggsoff! While we're at it -- can you please properly introduce it in `containerd/containerd.go` the same way we're handling `org.lfedge.eve.blk_mounts` ?

**Comment by giggsoff** [comment]
Hmm, as I can see, in case of mounts, we need to update it from external action, and no need to get it back from the containerd package. In the case of VNC password, we need to set and get it back for kvm hypervisor. So, we use the direct access to the map with annotations and it is enough as it seems to me.
So, do you suggest to add setter and getter functions for VNC password into containerd package? Or I miss something?

**Comment by rvs** [comment]
> Hmm, as I can see, in case of mounts, we need to update it from external action, and no need to get it back from the containerd package. In the case of VNC password, we need to set and get it back for kvm hypervisor. So, we use the direct access to the map with annotations and it is enough as it seems to me. So, do you suggest to add setter and getter functions for VNC password into containerd package? Or I miss something?

Actually there are two things here @giggsoff -- first of all I'll start slowly moving all the relevant data that is required to launch anything on EVE into OCI spec that we use for the task (the ultimate goal is to put the hypervisor configuration file there as a string as well). All of that will be handled as:

```
spec.Annotations[key] = value
```

So first things first -- I'd like to AT LEAST have a single place in our source code where we collect all the keys we're going to use. So instead of `const vncPasswordAnnotation = "VncPasswd"` lets move that to `containerd/containerd.go` and make it look like: `eveOCIMountPointsLabel = "org.lfedge.eve.vnc_password"` (this will be right next to `eveOCIMountPointsLabel = "org.lfedge.eve.blk_mounts"`).

Makes sense?

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
