### PR TITLE
lshw in debug package

### PR DESCRIPTION
**Pull request by giggsoff**
We need `lshw` to obtain info about hardware in our tests.
https://github.com/lf-edge/eden/pull/461

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by rvs — APPROVED** [review]
Quick question: what's the delta on rootfs.img after this package is added? How much extra space are we consuming @giggsoff

**Comment by rvs** [comment]
Aaaand that's exactly what I'm talking about 
```
ERROR: size of /home/runner/work/eve/eve/dist/amd64/installer/rootfs-0.0.0-pr1767-d15ba5d2-xen-amd64.squash is greater than 250MB (bigger than allocated partition)
```

**Comment by giggsoff** [comment]
lshw consumes 10MB.

Can we delete vim from debug container? It consumes 28MB.

**Comment by rvs** [comment]
> lshw consumes 10MB.

Yeah, but that also drags in GNU libc for some reason. Can we rebuild lshw so that it links against musl (like everything else in EVE)?

> Can we delete vim from debug container? It consumes 28MB.

As a measure of last resort -- we can consider it. But I don't think we're looking at a last resort just yet.

In fact, I think right now is a good time to take a holistic look at all the files in EVE and see where we can do optimizations size-wise.

**Comment by rvs** [comment]
Hey @giggsoff -- I see you're doing good work in #1768 but I think you should also look into just statically building lshw as part of debug package. Just for kicks I tried it and here's what I got:

```
$ curl -L https://www.ezix.org/software/files/lshw-B.02.19.2.tar.gz | tar xzvf -
$ cd lshw-B.02.19.2/src
$ make
$ g++ -static  -L./core/ -g -Wl,--as-needed -o lshw lshw.o -llshw -lresolv -lintl
$ strip lshw
$ ls -lh lshw
-rwxr-xr-x    1 root     root        1.8M Jan  3 05:50 lshw
```

This is a much more acceptable size for inclusion. Btw, for the above don't forget to apply patches from https://git.alpinelinux.org/aports/tree/community/lshw?h=master and also install `gettext-static`

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
