### PR TITLE
pull patch for containerd reader

### PR DESCRIPTION
**Pull request by giggsoff**
We must pull patch for containerd (https://github.com/containerd/containerd/pull/4629) into our environment to resolve issues with memory leaking during large volumes creation.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by eriknordmark — CHANGES_REQUESTED** [review]
Can't you just update the go.mod to get the latest into vendor? 
Shouldn't need to do a local patch.

**Comment by giggsoff** [comment]
No, I cannot, it needs to be updated from edge-containers. If we can wait, I will update it there.

**Comment by deitch** [comment]
Yeah, let's not patch this manually, it is asking for future trouble. I do not know how we got the out-of-date version of containerd, so let's figure that out and fix it.

**Comment by deitch** [comment]
As far as I can tell, the fix merged upstream on Oct 15, 2020. The following versions of containerd were released after that date:

* 1.5.0+
* 1.4.2+
* 1.3.8+

So any of those should be fine.

**Comment by giggsoff** [comment]
Actually, I see tags on the top of page https://github.com/containerd/containerd/pull/4629/commits/de082e5627ada4672882001c28ee279f01386d5e they are started from v1.5.0...

**Comment by deitch** [comment]
You are 100% right. Looks like they were just cherry-picking into 1.3.x and 1.4.x. You need 1.5.x to get this. Really nice catch!

**Comment by deitch** [comment]
https://github.com/lf-edge/edge-containers/pull/37 is merged in @giggsoff ; let's just update to that rather than the patch here.

**Comment by giggsoff** [comment]
Now I put the new version of edge-containers inside and do vendoring.
It resolves the issue with memory leak in my tests.

**Review by rvs — APPROVED** [review]
LGTM

**Review by eriknordmark — CHANGES_REQUESTED** [review]
Seems like all of the vendoring was updated. Was that the intent? Or just update containerd (any updates the new version of containerd might require).

Since this is a bug fix we might need to patch it makes sense to keep the vendoring update to the minimum required.

**Comment by giggsoff** [comment]
Actually, all updates comes from updating of edge-containers. It was my reason to just add the patch as the first variant of this PR

**Review by eriknordmark — COMMENTED** [review]
When I did this without the tidy I get 494 files with changes and you have 566.
Let's compare notes.

**Comment by giggsoff** [comment]
@eriknordmark I put the comment https://github.com/lf-edge/eve/pull/2155#issuecomment-872283181. Actually, I also update pkg/newlog which one depends on pkg/pillar

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
