### PR TITLE
Kernel update and patches cleanup

### PR DESCRIPTION
**Pull request by giggsoff**
We can reduce number of our patches with upstream support:
1. fget-Do-not-loop-with-rcu-lock-held removed because of no upstream
support and fixes inside https://github.com/torvalds/linux/commit/054aa8d4 and
https://github.com/torvalds/linux/commit/e386dfc5.
2. tpm-Rework-open-close-shutdown-to-avoid-races removed in favor of
https://github.com/torvalds/linux/commit/fb5abce6
3. rtl8821CU removed with update of library and also adds support for
arm64

It seems we may have endless loop inside the first patch in branch "if
(file->f_mode & mask)" without explicit setting of "again" to "false".
I can still see the problem handled by our patch for tpm in tests with
TPM-enabled Eden (in [console.log](https://github.com/lf-edge/eve/files/8834370/console.log) from [eden-report-tpm-true-ext4](https://github.com/lf-edge/eden/actions/runs/2382918800)),
so it is nice to have upstreamed version to fix this.

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by giggsoff** [comment]
I can see inside console after reboot
```
[  129.338433][    C1] watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [002-logging:310]
[  129.338784][    C1] Modules linked in: iTCO_wdt intel_pmc_bxt iTCO_vendor_support i2c_i801 i2c_smbus e1000
[  129.339190][    C1] CPU: 1 PID: 310 Comm: 002-logging Tainted: G             L    5.10.119-linuxkit #1
[  129.339503][    C1] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 0.0.0 02/06/2015
[  129.339817][    C1] RIP: 0010:memcg_kmem_enabled+0x0/0xf
[  129.340020][    C1] Code: 44 24 38 65 48 2b 04 25 28 00 00 00 74 05 e8 d6 c1 a3 00 48 83 c4 40 5b 41 5c 41 5d 41 5e 5d c3 e9 f0 7e 0c 00 e9 eb 7e 0c 00 <66> 66 66 66 90 31 c0 eb 02 b0 01 83 f0 01 c3 66 66 66 66 90 89 ff
[  129.340654][    C1] RSP: 0018:ffffbaff403fbcc0 EFLAGS: 00000246
[  129.340871][    C1] RAX: ffff9d48025d1400 RBX: ffff9d4800b08f00 RCX: ffffffffffffffff
[  129.341158][    C1] RDX: 0000000000000014 RSI: 0000000000000024 RDI: ffff9d4800b08f00
[  129.341423][    C1] RBP: 0000000000000000 R08: 0000000000000024 R09: ffffffffa6811d00
[  129.341689][    C1] R10: 0000000000000206 R11: 0000000000000000 R12: ffff9d4802718040
[  129.341968][    C1] R13: ffffe20cc4098640 R14: ffff9d487bd2ecc0 R15: ffff9d48027660c0
[  129.342238][    C1] FS:  00007efe0df61b48(0000) GS:ffff9d487bd00000(0000) knlGS:0000000000000000
[  129.342531][    C1] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  129.342768][    C1] CR2: 00007f1d89e3d070 CR3: 00000001027be000 CR4: 00000000000406a0
[  129.343029][    C1] Call Trace:
[  129.343172][    C1]  free_thread_stack+0x25/0xc7
[  129.343353][    C1]  put_task_stack+0x3c/0x60
[  129.343521][    C1]  finish_task_switch+0x1e8/0x1fe
[  129.343707][    C1]  __schedule+0x523/0x57a
[  129.343872][    C1]  schedule+0x78/0x9e
[  129.344020][    C1]  do_wait+0x1bb/0x218
[  129.344176][    C1]  kernel_wait4+0xc7/0x11c
[  129.344342][    C1]  ? delayed_put_task_struct+0x53/0x53
[  129.344538][    C1]  __do_sys_wait4+0x2f/0x80
[  129.344705][    C1]  ? __schedule+0x557/0x57a
[  129.344866][    C1]  ? lapic_next_event+0x12/0x15
[  129.345038][    C1]  ? clockevents_program_event+0xb4/0xcf
[  129.345243][    C1]  do_syscall_64+0x33/0x40
[  129.345405][    C1]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  129.345614][    C1] RIP: 0033:0x7efe0df20352
[  129.345791][    C1] Code: c3 8b 07 85 c0 75 24 49 89 fb 48 89 f0 48 89 d7 48 89 ce 4c 89 c2 4d 89 ca 4c 8b 44 24 08 4c 8b 4c 24 10 4c 89 5c 24 08 0f 05 <c3> e9 8a d2 ff ff 41 54 b8 02 00 00 00 49 89 f4 be 00 88 08 00 55
[  129.346410][    C1] RSP: 002b:00007fff1d6cc838 EFLAGS: 00000246 ORIG_RAX: 000000000000003d
[  129.346697][    C1] RAX: ffffffffffffffda RBX: 00007efe0df61b48 RCX: 00007efe0df20352
[  129.346959][    C1] RDX: 0000000000000000 RSI: 00007fff1d6cc8ac RDI: ffffffffffffffff
[  129.347221][    C1] RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000
[  129.347482][    C1] R10: 0000000000000000 R11: 0000000000000246 R12: 000000000000003d
[  129.347742][    C1] R13: 00007efe0df62ea0 R14: 0000000000000001 R15: 0000000000000000
```

and

```
[ 1121.298286][    C0] watchdog: BUG: soft lockup - CPU#0 stuck for 23s! [swapper/0:0]
[ 1121.298664][    C0] Modules linked in: iTCO_wdt intel_pmc_bxt iTCO_vendor_support i2c_i801 i2c_smbus e1000
[ 1121.299079][    C0] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G             L    5.10.119-linuxkit #1
[ 1121.299389][    C0] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 0.0.0 02/06/2015
[ 1121.299697][    C0] RIP: 0010:memcg_kmem_enabled+0x0/0xf
[ 1121.299906][    C0] Code: 44 24 38 65 48 2b 04 25 28 00 00 00 74 05 e8 d6 c1 a3 00 48 83 c4 40 5b 41 5c 41 5d 41 5e 5d c3 e9 f0 7e 0c 00 e9 eb 7e 0c 00 <66> 66 66 66 90 31 c0 eb 02 b0 01 83 f0 01 c3 66 66 66 66 90 89 ff
[ 1121.300593][    C0] RSP: 0018:ffffffffa6603de8 EFLAGS: 00000246
[ 1121.300813][    C0] RAX: ffff9d48002b4400 RBX: ffff9d48002e40c0 RCX: ffffffffffffffff
[ 1121.301116][    C0] RDX: 0000000000000014 RSI: 0000000000000024 RDI: ffff9d48002e40c0
[ 1121.301382][    C0] RBP: 0000000000000000 R08: 0000000000000024 R09: ffffffffa6811d00
[ 1121.301670][    C0] R10: ffff9d4802766168 R11: 000000000001d38b R12: ffff9d48002349c0
[ 1121.301943][    C0] R13: ffffe20cc400b040 R14: ffff9d487bc2ecc0 R15: ffffffffa6615940
[ 1121.302208][    C0] FS:  0000000000000000(0000) GS:ffff9d487bc00000(0000) knlGS:0000000000000000
[ 1121.302499][    C0] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1121.302718][    C0] CR2: 00007f1c38c76280 CR3: 0000000102600000 CR4: 00000000000406b0
[ 1121.302980][    C0] Call Trace:
[ 1121.303144][    C0]  free_thread_stack+0x25/0xc7
[ 1121.303333][    C0]  put_task_stack+0x3c/0x60
[ 1121.303501][    C0]  finish_task_switch+0x1e8/0x1fe
[ 1121.303711][    C0]  __schedule+0x523/0x57a
[ 1121.303878][    C0]  schedule_idle+0x2a/0x33
[ 1121.304039][    C0]  do_idle+0x1c8/0x1ea
[ 1121.304194][    C0]  cpu_startup_entry+0x1d/0x1f
[ 1121.304370][    C0]  start_kernel+0x528/0x54b
[ 1121.304544][    C0]  secondary_startup_64_no_verify+0xb0/0xbb
```

Not sure that it is new problems, will try to investigate.

**Comment by milan-zededa** [comment]
@giggsoff First time I saw that kernel issue was back in this PR: https://github.com/lf-edge/eve/pull/2611#issuecomment-1119389074
Then I saw it couple more times in other PRs. So it seems to have appeared about one month ago. But I was never able to reproduce locally. Could be that the problem is somehow specific to the environment run by github actions.

**Comment by eriknordmark** [comment]
FWIW this PR passed the jenkins job which runs ztests against equinix metal servers.

**Comment by milan-zededa** [comment]
@giggsoff 
Here is a stack trace from one of the PRs opened in the last month: [kernel-soft-lockup.log](https://github.com/lf-edge/eve/files/8869211/kernel-soft-lockup.log). Maybe you can compare and determine if your PR introduced a new problem or if this is the same existing issue.

**Comment by giggsoff** [comment]
> @giggsoff Here is a stack trace from one of the PRs opened in the last month: [kernel-soft-lockup.log](https://github.com/lf-edge/eve/files/8869211/kernel-soft-lockup.log). Maybe you can compare and determine if your PR introduced a new problem or if this is the same existing issue.

Thank you! Will check

**Comment by giggsoff** [comment]
Seems in both cases we are sitting with the same pointer to memcg_kmem_enabled inside the same process (mkdir of 002-logging) and I cannot find what we do wrong there. So it is not look like the regression.
What I noticed is that we set `kernel.softlockup_panic` a bit late (inside onboot sysctl process), so it does not issue reboot of the system in our case and we can see endless soft lockups, I set the option `CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC` into kernel config.

**Comment by eriknordmark** [comment]
> What I noticed is that we set `kernel.softlockup_panic` a bit late (inside onboot sysctl process), so it does not issue reboot of the system in our case and we can see endless soft lockups, I set the option `CONFIG_BOOTPARAM_SOFTLOCKUP_PANIC` into kernel config.

Great but would it make sense to then remove it from the sysctl as well?

**Review by rvs — APPROVED** [review]
In general, I'm OK with this -- but can you @giggsoff  try that RISC-V kernel still boots?

**Comment by giggsoff** [comment]
> In general, I'm OK with this -- but can you @giggsoff try that RISC-V kernel still boots?

Yes, at least in qemu with mini version of EVE-OS:
```
can't run '/etc/init.d/rcS': No such file or directory

Please press Enter to activate this console. 
/ # uname -a
Linux (none) 5.15.46 #1 SMP Fri Jun 10 16:32:51 UTC 2022 riscv64 Linux
/ # cat /etc/eve-release 
0.0.0-kernel-update-9bfa1000-mini-riscv64
```

**Pull request merged**
