### PR TITLE
[11.0-stable] Update to OpenZFS 2.2.2

### PR DESCRIPTION
**Pull request by andrewd-zededa**
Kernel update - [amd64-generic, amd64-generic, amd64-rt, arm64-nvidia, arm64-generic, arm64-generic]

eve-kernel-amd64-v5.10.186-generic
    4d7866684f79: Update to OpenZFS 2.2.2

eve-kernel-amd64-v6.1.38-generic
    820be3b1c356: Update to OpenZFS 2.2.2

eve-kernel-amd64-v6.1.38-rt
    7148ced52fc1: Update to OpenZFS 2.2.2

eve-kernel-arm64-v5.10.104-nvidia
    ab0df9cfc431: Update to OpenZFS 2.2.2

eve-kernel-arm64-v5.10.186-generic
    438959506e33: Update to OpenZFS 2.2.2

eve-kernel-arm64-v6.1.38-generic
    50c6e530bbd2: Update to OpenZFS 2.2.2

Update to OpenZFS 2.2.2
Remove modifications to now unused kernel module parameters. Don't apply patches as they're now included in upstream. Remove now unused patches under dom0-ztools
Patch go-libzfs for OpenZFS 2.2.2 support

### CODE REVIEW

**Comment by rouming** [comment]
@andrewd-zededa please don't forget to add a "[stable-branch]" prefix to the PR title. Then it is much easier to find the closed PR by grepping the particular branch.

**Comment by eriknordmark** [comment]
@andrewd-zededa did you redo this to match the PR for master?

@rene @rouming @rucoder given that we need a new kernel for 11.0.X, should we pick this one or the one we are currently putting in master branch (which has some other changes.)?

**Comment by andrewd-zededa** [comment]
@eriknordmark work to match this PR to current https://github.com/lf-edge/eve/pull/3779 is in progress.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by andrewd-zededa** [comment]
Looks like I can't use ADD <gitref> back here, I'll switch back to the tar file here.

**Comment by andrewd-zededa** [comment]
@eriknordmark its updated to the https://github.com/lf-edge/eve/pull/3779 style and rebased to latest 11.0-stable.  It's ready for a decision on which kernel to use.

**Review by deitch — COMMENTED** [review]
Does this move to OpenZFS 2.2.2 eliminate those custom patch files? If so, that is a lovely thing.

Separately, why are we depending on a custom fork of `go-libzfs` which is in a personal repo? I refer to [this](https://github.com/lf-edge/eve/pull/3780/files#diff-9e0528163a12c888aa89b02a6d7776c375380b08733d26d2742baca919fe2b83L12) and about 10 other places.

**Comment by eriknordmark** [comment]
Mergin this while we wait for the upstream and you can do a PR when the fixes make it into the upstream.

**Pull request merged**
