### PR TITLE
Updated device entity enums aligning the zedcloud  device entities

### PR DESCRIPTION
**Pull request by chethan-zededa**
commit 1: pushing the proto changes
commit 2: pushing the generated file with make proto and make proto-vendor

zedcloud proto entity reference: https://github.com/zededa/zedcloud/blob/bcca0acdfe2f9480e227117ef4966437a41b106b/libs/zmsg/zdevicecommon/devicecommon.proto#L23

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

But somewhere we should document that some of these objects (system adapter, vault, attestation, port) do not have a UUID to use to reference them in the error info.

**Comment by chethan-zededa** [comment]
> LGTM
> 
> But somewhere we should document that some of these objects (system adapter, vault, attestation, port) do not have a UUID to use to reference them in the error info.

@eriknordmark I have added the proto details and the above entity details in the doc of yours: https://docs.google.com/document/d/1SwohJqGROHhiY5yO0o0DqApFIB2kd6SheS0zg9-90B8/edit#
can we add something similar in the https://wiki.lfedge.org/display/EVE/EVE+and+API+should+indicate+if+an+error+includes+an+automatic+retry?

**Review by rvs — APPROVED** [review]
LGTM, but yes -- please add to https://wiki.lfedge.org/display/EVE/EVE+and+API+should+indicate+if+an+error+includes+an+automatic+retry

**Comment by eriknordmark** [comment]
> LGTM, but yes -- please add to https://wiki.lfedge.org/display/EVE/EVE+and+API+should+indicate+if+an+error+includes+an+automatic+retry

I copied the @chethan-zededa's text to the above proposal.

**Comment by eriknordmark** [comment]
@chethan-zededa you need to add a DCO statement to each of your commits for this to pass.

**Comment by chethan-zededa** [comment]
> @chethan-zededa you need to add a DCO statement to each of your commits for this to pass.

@eriknordmark  done, please check

**Comment by chethan-zededa** [comment]
> @chethan-zededa can you please tell me more about ENTITY_CONTENT_BLOB: do we plan to show information about it somehow in UI or should I propagate an error directly to the content tree without referencing on ENTITY_CONTENT_BLOB from it? As I can see for now errors from blobs do not send at all.
> 
> I mean, what we need from three variants (or anything else):
> 
> 1. error and repeat condition in blob info and "will wait for ENTITY_CONTENT_BLOB sha" in content tree info
> 2. error and repeat condition in blob info and concatenation of all blob errors as retry condition in content tree info
> 3. no error in blob info (current behavior) and concatenation of all blob errors as retry condition in content tree info


> @chethan-zededa can you please tell me more about ENTITY_CONTENT_BLOB: do we plan to show information about it somehow in UI or should I propagate an error directly to the content tree without referencing on ENTITY_CONTENT_BLOB from it? As I can see for now errors from blobs do not send at all.
> 
> I mean, what we need from three variants (or anything else):
> 
> 1. error and repeat condition in blob info and "will wait for ENTITY_CONTENT_BLOB sha" in content tree info
> 2. error and repeat condition in blob info and concatenation of all blob errors as retry condition in content tree info
> 3. no error in blob info (current behavior) and concatenation of all blob errors as retry condition in content tree info

https://github.com/lf-edge/eve/pull/2215#issuecomment-896719995

**Comment by chethan-zededa** [comment]
> @chethan-zededa can you please tell me more about ENTITY_CONTENT_BLOB: do we plan to show information about it somehow in UI or should I propagate an error directly to the content tree without referencing on ENTITY_CONTENT_BLOB from it? As I can see for now errors from blobs do not send at all.
> 
> I mean, what we need from three variants (or anything else):
> 
> 1. error and repeat condition in blob info and "will wait for ENTITY_CONTENT_BLOB sha" in content tree info
> 2. error and repeat condition in blob info and concatenation of all blob errors as retry condition in content tree info
> 3. no error in blob info (current behavior) and concatenation of all blob errors as retry condition in content tree info

@giggsoff  to get start with we are planning to fill in respective entity error details as per the new errorinfo structure, I am not sure about eve internal implementation about how to fill things, please check with @eriknordmark or @zed-rishabh  for better insights.
Doc: https://docs.google.com/document/d/1SwohJqGROHhiY5yO0o0DqApFIB2kd6SheS0zg9-90B8/edit#

**Pull request merged**
