### PR TITLE
Log the size of logs tarred and copied to /persist/rsyslog-backup

### PR DESCRIPTION
**Pull request by gkodali-zededa**
Signed-off-by: GopiKrishna Kodali <gkodali@zededa.com>

### CODE REVIEW

**Comment by gkodali-zededa** [comment]
> What prevents /persist/rsyslog-backup from using up all of disk?
> I think it would be sufficient to keep a limited (one? more?) tar files in that directory.
Makes sense. What about, two latest non-empty tar files?

**Comment by rvs** [comment]
I am actually not even sure what's the point of taring it up at this point? Is there anybody, and I mean *anybody* on the team who will (or have) ever look into those for debugging?

My understanding is that the only point of keeping those is to try and debug rsyslogd. If that's the case -- I don't even think we should be keeping any of them. Please convince me otherwise.

**Comment by gkodali-zededa** [comment]
> I am actually not even sure what's the point of taring it up at this point? Is there anybody, and I mean _anybody_ on the team who will (or have) ever look into those for debugging?
> 
> My understanding is that the only point of keeping those is to try and debug rsyslogd. If that's the case -- I don't even think we should be keeping any of them. Please convince me otherwise.

By taring this directory, we also save the logs from different sources (and the logmanager.log file) that may not have been exported to cloud. This of course is only useful when we have direct ssh access to device.

**Comment by eriknordmark** [comment]
> My understanding is that the only point of keeping those is to try and debug rsyslogd. If that's the case -- I don't even think we should be keeping any of them. Please convince me otherwise.

Fair enough. Makes sense to at least generate a new log entry indicating that we threw them away.

**Pull request merged**
