### PR TITLE
Add "127.0.0.1" to the edgeview device localIP policy

### PR DESCRIPTION
**Pull request by naiming-zededa**
- add '127.0.0.1' to localIP for device tcp access

### CODE REVIEW

**Review by OhmSpectator — COMMENTED** [review]
I'm confused. Originally in #4230 we were talking about the script that user runs on his local machine to initiate the connection (you download it via UI). It's another one, I guess... Am I wrong?

**Comment by naiming-zededa** [comment]
> I'm confused. Originally in #4230 we were talking about the script that user runs on his local machine to initiate the connection (you download it via UI). It's another one, I guess... Am I wrong?

Ha, i thought you meant the script inside the docker

**Comment by naiming-zededa** [comment]
Although i have noticed on some devices, edgeview session keep resetting. I suspect it is due the script using 'pgrep edge-view' for some reason not returning the PIDs correctly. I have seen this on my redhat linux. But I can not explain that why only on some devices. Was wondering changing to 'bash' will help this or not.

**Review by OhmSpectator — APPROVED** [review]
Looks good!

**Comment by OhmSpectator** [comment]
> Never mind, i'll worry about this later. the 'bash' change is removed.

Yeah! Thanks!

**Pull request merged**
