### PR TITLE
single libs module

### PR DESCRIPTION
**Pull request by deitch**
Everything under `github.com/lf-edge/eve/libs/` was treated as a separate module, so you had

* `github.com/lf-edge/eve/libs/zedUpload`
* `github.com/lf-edge/eve/libs/netfiler`
* `github.com/lf-edge/eve/libs/reconciler`

Etc.

Each of them had their own `go.mod`, but many were cross-referencing others via `../` replace directives. Effectively, they were treated as a single go module, but structured as separate ones.

This reconciles all of that into a single module, with `github.com/lf-edge/eve/libs/go.mod`.

Includes from other packages are unchanged, whether they import directly via full path (as they should), or via relative `replace ../../libs` directives (as they shouldn't, but we will tackle next).

### CODE REVIEW

**Review by milan-zededa — APPROVED** [review]
This will make our life easier

**Comment by rene** [comment]
thanks @deitch , please, don't forget to put the proper explanation (from your PR's description) into your commit message....

**Comment by deitch** [comment]
What @rene ; you want to understand this for more than 5 mins after the PR is merged? Whatever for?? 😆

**Comment by deitch** [comment]
Done

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by rene** [comment]
> What @rene ; you want to understand this for more than 5 mins after the PR is merged? Whatever for?? laughing

@deitch , you gave such a good explanation in your PR's description, I don't understand why you didn't put the same description in your commit's message. Anyways, the PR LGTM, but now there is a typo in your commit message: moduels -> modules.... :wink:

**Comment by deitch** [comment]
Let it go for now. It takes so long to get CI run, I'll save it for the next PR.

**Pull request merged**
