### PR TITLE
oci may have 0 totalsize

### PR DESCRIPTION
**Pull request by giggsoff**
Probably we need deeper investigation, but I see [errors](https://github.com/lf-edge/eve/runs/2757304130?check_suite_focus=true#step:9:2852) on the step on downloading of OCI images: 
```
description:"Found error in content tree itmoeve/eclient:0.4 attached to volume ping2_0_m_0: Retry attempt 1 after Will retry in 10m0s: \nSize '0' provided in image config of 'itmoeve/eclient@sha256:654864fa19a37c13059f91f4f5e227d96c9ace3aaa59b53ef1d2f37a67794127' is incorrect.\nDownload status (6523 / 0). Aborting the download\n\n" timestamp:{seconds:1622987596 nanos:288280129}
```
And seems, it is not the error in case of oci, because we may not have the total size on this step.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by deitch** [comment]
This isn't a bad safety check, but is the core of the issue elsewhere?

**Review by rvs — APPROVED** [review]
I'd say in the spirit of belt and suspenders -- this should probably go in (unless we can quickly identify the root cause)

**Review by eriknordmark — CHANGES_REQUESTED** [review]
This just papers over whatever issue caused the size to be zero. Much better to figure out why the size was incorrectly zero, since we don't know what other issues we can run into if the size is incorrect.

**Comment by giggsoff** [comment]
Well, as I can see, it is expected behavior: we do not pass size for OCI from controller and it is updated from inside of process [here](https://github.com/lf-edge/eve/blob/87f2a9a84bc9907725ca00f2a7f63fdeabc82c69/libs/zedUpload/ociutil/oci.go#L251).
But I will think about another variants of solving the problem.

**Comment by giggsoff** [comment]
Now I put inside PullBlob the honor way of sizes calculation for OCI.

**Review by deitch — APPROVED** [review]
Hats off for finding this.

**Review by eriknordmark — APPROVED** [review]
Cool

**Comment by giggsoff** [comment]
Well, seems, integration tests failed now. I think, we need to merge new variant of Eden tests with fix for nw_switch inside https://github.com/lf-edge/eve/pull/2125

**Comment by giggsoff** [comment]
Also opened PR for change for nw_switch on 6.6 branch: https://github.com/lf-edge/eve/pull/2127

**Review by eriknordmark — APPROVED** [review]
Still looks good

**Review by eriknordmark — APPROVED** [review]
Kicking it again to see if ztests re-run.

**Pull request merged**
