### PR TITLE
pkg: xen-tools: Increase log information for chronyd

### PR DESCRIPTION
**Pull request by rene**
By default, pillar sets console=hvc0 (virtual serial console) as the default output for kernel. However, when VNC is enabled, it also passes console=tty0, so the last console (tty0) will be the default output for applications. This makes very easy to lost messages from the initrd script, specially the information message regarding chronyd daemon.

This commit improves the messages regarding chronyd daemon and send them to the kernel message buffer, so they will be written to all configured consoles.

### CODE REVIEW

**Comment by OhmSpectator** [comment]
Looks good to me.
A general question: do we have other components using /dev/kmsg for logging? And do we get this info in our debugging script?

**Review by OhmSpectator — APPROVED** [review]

**Review by rouming — APPROVED** [review]
Ack

**Comment by rouming** [comment]
> Looks good to me. A general question: do we have other components using /dev/kmsg for logging? And do we get this info in our debugging script?

@OhmSpectator pkg/kdump/kdump.sh does the same. Kernel messages appear in dmesg output, so yes, collect-info.sh collects that as well.

**Review by eriknordmark — COMMENTED** [review]
LGTM

I think chronyd for container  was backported to stable releases hence we should do the same with this PR.

**Pull request merged**
