### PR TITLE
Adding MAINTAINERS.md

### PR DESCRIPTION
**Pull request by rvs**
As per our TSC mailing list discussion

### CODE REVIEW

**Comment by rouming** [comment]
What are the roles of maintainers?

**Comment by rvs** [comment]
@rouming https://wiki.lfedge.org/display/EVE/Community#Committers

@eriknordmark sounds like a good idea -- I'll do PRs for other repos shortly

**Comment by rvs** [comment]
@eriknordmark can you either approve or merge yourself since there doesn't seem to be much else here (and I need a file in the repo to link to in other PRs)

**Comment by eriknordmark** [comment]
LGTM

**Review by eriknordmark — APPROVED** [review]

**Pull request merged**
