### PR TITLE
CODEOWNERS: spread review responsibilities between EVE team members

### PR DESCRIPTION
**Pull request by rouming**
1. Remove @rvs from code reviewers.
2. Assign subproject to each and every EVE team member.

### CODE REVIEW

**Review by rene — APPROVED** [review]

**Comment by rouming** [comment]
@eriknordmark here https://github.com/lf-edge/eve/pull/3350/files# github says that some of the guys are missing permissions.

**Comment by jsfakian** [comment]
Please remove `/pkg/eve-verification/             @jsfakian`, it does not exist.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by rvs** [comment]
It is very surprising to have this kind of a change implemented without even so much as a hint to TSC mailing list and some kind of a sense of consensus there. I was alerted to this PR two days ago and thought I still have time to review it and raise my objections (if needed). But it seems it just got merged :-(

I still think a TSC discussion is in order here, but if the project is slowly becoming a corporate-driven open source, I guess that may no longer be necessary :-(

**Comment by rouming** [comment]
@rvs I take full responsibility for the merge. When I pressed the button, I had no intention of bypassing you or ignoring your objections. My only thought was that you might not be interested in the project anymore, considering your lack of participation in recent reviews and the absence of any discussion on this pull request. 

As a team, we are trying to streamline the review process, which is why we made modifications to the CODEOWNERS file. The purpose of the pull request was solely to clean up the reviewers' list, remove those who don't participate and add active reviewers—nothing more than that (despite the loud name of the file "code owners"). 

If you are willing to participate in future reviews, may I kindly ask you to submit a pull request to have your name added back to the main reviewers' list? Super easy to fix.

**Comment by rvs** [comment]
Hey @rouming don't get me wrong -- I'm actually not upset at all to be removed (in fact it is likely a reasonable thing to do given the amount of time I can give to the project right now). What I'm really upset about is a total lack of any kind of "community focused" process that would help to decide whether an update like this is the right thing to do or not. That has nothing to do with PRs and everything to do with emails on TSC ML (and, to a lesser extent, TSC calls)

**Comment by eriknordmark** [comment]
@rvs On July 14th I sent a DM on slack to the EVE TSC members pointing at this PR and asking for comments. However, I failed to note that in the PR hence it got merged before we had discussions on this. Maybe I should have used the eve-tsc-private mailing list instead (private since we are potentially discussing personel matters as part of this).
But I failed to but a hold on this PR while doing that, and then I left on vacation.

**Pull request merged**
