### PR TITLE
gitignore: ignore conf/{grub.cfg,authorized_keys}

### PR DESCRIPTION
**Pull request by christoph-zededa**
these are locally changed config files that should not be committed

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
I think this makes sense, but I think developers would need a heads up message e.g., on the lf-edge eve mailing list.

I wonder if we should also add conf/device.cert.pem and conf/device.key.pem to .gitignore. I often add them for qemu runs so that each workspace has a well-defined identity which I can onboard to the controller once. And I've yet to accidentally commit and push those, but .gitignore would make that explicit just like for these files.

**Review by rouming — APPROVED** [review]
Ack. @eriknordmark  Do we need to keep the empty authorized_key file in repo at all? What if we create a README in the conf folder and explain what files are expected to be here in this folder?

**Comment by christoph-zededa** [comment]
> Ack. @eriknordmark Do we need to keep the empty authorized_key file in repo at all? What if we create a README in the conf folder and explain what files are expected to be here in this folder?

I renamed the authorized_keys file to authorized_keys.tmpl. That README already exists? https://github.com/lf-edge/eve/blob/master/docs/CONFIG.md?plain=1#L14

**Comment by rouming** [comment]
> I renamed the authorized_keys file to authorized_keys.tmpl. That README already exists? https://github.com/lf-edge/eve/blob/master/docs/CONFIG.md?plain=1#L14

Yeah, that what I'm asking: do we need to keep an empty file with a name, which actually is not used: authorized_keys.tmpl. If it has some valuable info, then yes: you rename the file and get the expected behavior, but this one is empty (with some comments, but who cares), so whats the reason to keep it in the repo at all?

**Comment by rouming** [comment]
The nasty issue I always experience (not this PR related, but grub.cfg related) is that once you switched from another branch and does the "make live", the first time  "set_getty" is not set (but it *is* in the grub.cfg), so you always need to repeat the "make live". I did not investigate that thoroughly. @christoph-zededa have you experienced that? 
(again, this is not this PR related)

**Comment by christoph-zededa** [comment]
> > I renamed the authorized_keys file to authorized_keys.tmpl. That README already exists? https://github.com/lf-edge/eve/blob/master/docs/CONFIG.md?plain=1#L14
> 
> Yeah, that what I'm asking: do we need to keep an empty file with a name, which actually is not used: authorized_keys.tmpl. If it has some valuable info, then yes: you rename the file and get the expected behavior, but this one is empty (with some comments, but who cares), so whats the reason to keep it in the repo at all?

Removed it, put the info into docs/CONFIG.md instead

**Pull request merged**
