### PR TITLE
Bump eve-api

### PR DESCRIPTION
**Pull request by rene**
Update eve-api in order to get new BootMode parameters and other updates.

### CODE REVIEW

**Comment by christoph-zededa** [comment]
@rene I think you missed `newlog/go.mod` and `wwan/mmagent/go.mod`; there is `make bump-eve-api`

**Comment by rene** [comment]
thanks @christoph-zededa for pointing out the missing packages. I've updated the PR.

**Review by deitch — APPROVED** [review]

**Review by christoph-zededa — APPROVED** [review]

**Comment by eriknordmark** [comment]
> @rene I think you missed `newlog/go.mod` and `wwan/mmagent/go.mod`; there is `make bump-eve-api`

Doesn't the make target to update the API take care of all of those?

I think we have all of the API updates in #3841 which is almost ready to merge. @zedi-pramodh I assume you pulled the latest API yesterday.

**Comment by zedi-pramodh** [comment]
Yes I ran  "make bump-eve-api" and update the commit in PR 3841

**Comment by zedi-pramodh** [comment]
That's Eriks call. Not mine. He asking for one more update to PR3841, I am working on it

**Comment by eriknordmark** [comment]
> > > @rene I think you missed `newlog/go.mod` and `wwan/mmagent/go.mod`; there is `make bump-eve-api`
> > 
> > 
> > Doesn't the make target to update the API take care of all of those?
> 
> Yes, I just forgot to use this make target to update the api.
> 
> > I think we have all of the API updates in #3841 which is almost ready to merge. @zedi-pramodh I assume you pulled the latest API yesterday.
> 
> Ok, then if you are about to merge #3841 we can drop this one... if it's going to take more time, we could merge this one and just rebase the #3841

I've merged #3841

**Comment by rene** [comment]
> > > > @rene I think you missed `newlog/go.mod` and `wwan/mmagent/go.mod`; there is `make bump-eve-api`
> > > 
> > > 
> > > Doesn't the make target to update the API take care of all of those?
> > 
> > 
> > Yes, I just forgot to use this make target to update the api.
> > > I think we have all of the API updates in #3841 which is almost ready to merge. @zedi-pramodh I assume you pulled the latest API yesterday.
> > 
> > 
> > Ok, then if you are about to merge #3841 we can drop this one... if it's going to take more time, we could merge this one and just rebase the #3841
> 
> I've merged #3841

Got it, then I'm dropping this PR since we don't need it anymore.

**Pull request closed without merging**
