### PR TITLE
fix an issue of newlog gzip file size too big not split up

### PR DESCRIPTION
**Pull request by naiming-zededa**
Signed-off-by: Naiming Shen <naiming@zededa.com>
Fix an issue of compressed file size too big and skips the split-up algorithm

- base of the compressed size if larger than the maxgzipsize, split the content into
   multiple segments (minimum of 3 just to be sure), and compress them separately
   into filenames with millisecond number increment.

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM.

Do we have a way to test this with different content and sizes? I see for instance it is looking for an end of line to split at, so what happens if some line is extremely long?

**Comment by naiming-zededa** [comment]
I have a test program to check a real gzip file break from 2 to 8 pieces then add all length together to see if equal to original size, and works fine:

length of content 563937
(2), number of contents: 2
len of contents[0]: 282488
len of contents[1]: 281449
total bytes 563937
(3), number of contents: 3
len of contents[0]: 188010
len of contents[1]: 188454
len of contents[2]: 187473
total bytes 563937
(4), number of contents: 4
len of contents[0]: 146553
len of contents[1]: 135935
len of contents[2]: 145819
len of contents[3]: 135630
total bytes 563937
(5), number of contents: 5
len of contents[0]: 113199
len of contents[1]: 117564
len of contents[2]: 107599
len of contents[3]: 113086
len of contents[4]: 112489
total bytes 563937
(6), number of contents: 6
len of contents[0]: 100622
len of contents[1]: 87388
len of contents[2]: 94478
len of contents[3]: 93976
len of contents[4]: 101105
len of contents[5]: 86368
total bytes 563937
(7), number of contents: 7
len of contents[0]: 80743
len of contents[1]: 85166
len of contents[2]: 75882
len of contents[3]: 80998
len of contents[4]: 84278
len of contents[5]: 81162
len of contents[6]: 75708
total bytes 563937
(8), number of contents: 8
len of contents[0]: 70717
len of contents[1]: 75836
len of contents[2]: 66120
len of contents[3]: 69815
len of contents[4]: 70226
len of contents[5]: 75593
len of contents[6]: 70787
len of contents[7]: 64843
total bytes 563937

**Comment by naiming-zededa** [comment]
also I have instrumented the maxgzip size to 20K, and ran this with error message. and the uploaded on kibana site looks fine:

 /persist/newlog/keepSentQueue/dev.log.1632271866993.gz, -- 2021-09-22T00:51:06Z --

 -(1) doMoveCompressFile: split size 23238, segments 3, error, /newlog/cmd/newlogd.go:1037, main.doMoveCompressFile, , newlogd, 2021-09-22T00:49:55.230360045Z(882)

 /persist/newlog/keepSentQueue/dev.log.1632272016272.gz, -- 2021-09-22T00:53:36Z --

 -(1) doMoveCompressFile: split size 49278, segments 4, error, /newlog/cmd/newlogd.go:1037, main.doMoveCompressFile, , newlogd, 2021-09-22T00:51:07.104707211Z(2060)

 /persist/newlog/keepSentQueue/dev.log.1632272320169.gz, -- 2021-09-22T00:58:40Z --

 -(1) doMoveCompressFile: split size 44740, segments 4, error, /newlog/cmd/newlogd.go:1037, main.doMoveCompressFile, , newlogd, 2021-09-22T00:53:36.382619935Z(3104)

**Comment by naiming-zededa** [comment]
the memlogd buffer has the limit of 4k something, and we should be ok.

**Pull request merged**
