### PR TITLE
Pillar: QMP handling improvements

### PR DESCRIPTION
**Pull request by temerkhanov**
- Add more diagnostic output for QMP
- Retry QMP connection

Signed-off-by: Sergey Temerkhanov <s.temerkhanov@gmail.com>

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
Do you see a change in test results due to the retry logic?

**Comment by eriknordmark** [comment]
@temerkhanov Can you fix the yetus complaint and answer my question in the review?

**Comment by rvs** [comment]
+1 to what @eriknordmark is saying -- in principle -- I am not against this change, but I'd like to understand the motivation as well.

**Comment by temerkhanov** [comment]
I have not seen any test result changes, though they still may occur on slower HW

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
