### PR TITLE
Fix app discovery endpoint

### PR DESCRIPTION
**Pull request by uncleDecart**
This PR removes ioutil from msrv_test and fixes bug in discovery route: flag allowToDiscover which is set in EVE-API was disregarded before, i.e. all the application instances were allowed to discover other app instances, now discovery service comply to that flag

### CODE REVIEW

**Review by milan-zededa — APPROVED** [review]
Sorry about that :)
I think this should be also backported to 13.4 (so the PR should have the stable tag)

**Comment by rene** [comment]
Triggering tests.... @uncleDecart , I understand the change for the first commit is pretty simple, but appreciate if you could think in a phrase to get rid of the lint error....

**Comment by uncleDecart** [comment]
@rene I thought that commit message linter was more of a suggestion than the rule and its' purpose to make make developer think about commit message so that other would understand what has been done on a high level.
What would you write in the body of that commit? I can write the same message, but I don't see how it would be beneficial for any of us :man_shrugging:

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
@uncleDecart please fix the commitlint issue
Commit 60cb74443c7608a929d7bddd87c92982cc94b906 has no body.

**Comment by rene** [comment]
> @rene I thought that commit message linter was more of a suggestion than the rule and its' purpose to make make developer think about commit message so that other would understand what has been done on a high level. What would you write in the body of that commit? I can write the same message, but I don't see how it would be beneficial for any of us 🤷‍♂️

Well, commit https://github.com/lf-edge/eve/commit/0aa72b8c3e53b71e7e810a666df1634bfe7a1469 is a good example for the same kind of change:

```
io/ioutil is deprecated
As of Go 1.16, the same functionality is now provided by package io
or package os, and those implementations should be preferred in new
code.

Since we are bombarded with Yetus complains about ioutil in all our
PRs, it is worth getting rid of it.

Signed-off-by: Milan Lenco <milan@zededa.com>
```

You can just use this phrase as the body of the commit:

```
As of Go 1.16, the same functionality is now provided by package io
or package os, and those implementations should be preferred in new
code.
```

**Review by eriknordmark — APPROVED** [review]
Run tests

**Pull request merged**
