### PR TITLE
Shutdown cmd support

### PR DESCRIPTION
**Pull request by giggsoff**
This PR adds support to shutdown node gracefully (which in turn allow to gracefully stop all applications).

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
I understood the request as being for a local graceful shutdown (using the local profile server), and not a shutdown from the controller.Did I misunderstand?

**Comment by eriknordmark** [comment]
I note that the one yetus compaint should be ignored (ZDEVICE_STATE vs Z_DEVICE_STATE prefix when adding an enum to an existing set of enum values).

**Review by rvs — CHANGES_REQUESTED** [review]
Hey @giggsoff -- can you please elaborate why is this capability required? What functionality do we plan to enable this way? A detailed explanation of an end-to-end one would be super helpful.

**Comment by kgiori** [comment]
As a "partial" answer to the question from @rvs -- I recently worked with a developer program participant who installed EVE-OS on a box and onboarded it to a commercial controller (ZEDCloud). Then he needed to ship it to another location. He wanted to shut it down gracefully. All I had to offer was to pull the plug. It emotionally "feels" better to shut down a unit as compared to cutting power suddenly, even if the end result is the same. ;)

**Comment by eriknordmark** [comment]
@rvs The direct request from the customer is not for what @kgiori mentioned, however the request is missing sufficient details to make sure we can design and build the right thing.What we've been told is:
"Need to be able to gracefully stop all the applications on a device and the power off the device.
Customer has power outages in the field and they want to be able to gracefully shut the applications down to avoid disk corruption. They do this while they are on an UPS that does not have long up time."

Perhaps there is sufficient time on the UPS for a human to tell a local-profile-server to tell EVE-OS to shutdown the applications. But such a process will take minutes. 
Alternatively we need an automated way to react to the UPS battery status and perhaps feed that into the guest VMs.

**Pull request closed without merging**
