### PR TITLE
hosts and hostname inside initrd

### PR DESCRIPTION
**Pull request by giggsoff**
We need to set properly /etc/hosts and /etc/hostname for network apps (like apache).

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by gkodali-zededa** [comment]
@giggsoff If I understand what you are trying to achieve right, you update the /etc/hosts file with the local hostname to it's IP mapping. Am I right?
If so, why do you have to check if the hostname or ip addresses changes and only then make the change. Why can't the file be written with latest hostname to latest ip mapping everytime?

Do the app that you work with explicitly required local hostname to it's ip mapping present?

**Comment by giggsoff** [comment]
@gkodali-zededa I try to start wordpress (which depends on apache) and it works, but I see in logs:
`...guest_vm-laughing_bhaskara.1;AH00557: apache2: apr_sockaddr_info_get() failed for (none)`

>written with latest hostname to latest ip mapping everytime

We have several interfaces and we should manage changes in ips of both of them.

**Comment by gkodali-zededa** [comment]
> #1327 (comment)

Got it.
So, if you have two interfaces with different ip addresses, do you add two entries with same hostname in /etc/hosts?

**Comment by giggsoff** [comment]
Yes, I add both of them. And track changes in IPs

**Review by gkodali-zededa — APPROVED** [review]
LGTM
As a last thing, please check if the normal DNS resolution of external hosts work before merge.

**Comment by rvs** [comment]
Thanks @gkodali-zededa -- @giggsoff once you check the last item in Gopi's reply I can merge this.

**Comment by giggsoff** [comment]
I checked access to external service (google.com), the host resolves, the ping passes.

**Pull request merged**
