### PR TITLE
Created test file for types_test.go

### PR DESCRIPTION
**Pull request by archishou**
Signed-off-by: Archishmaan Peyyety <archishou@gmail.com>

### CODE REVIEW

**Comment by archishou** [comment]
I'm not sure why build is failing. I don't see any error messages in the log. The new code I committed builds on my local machine with no problems. I ran go vet and go fmt just to make sure and I got no errors. Anything I am missing?

**Comment by eriknordmark** [comment]
> I'm not sure why build is failing. I don't see any error messages in the log. The new code I committed builds on my local machine with no problems. I ran go vet and go fmt just to make sure and I got no errors. Anything I am missing?

If you click on the build failure link you find both the build log and the yetus failures.

**Comment by rvs** [comment]
Hey @archishou if you click on the yetus link in the checks tab you'll see that there's still one golang issue that remains to be fixed (make sure to click on "more" in the pink panel of the yetus output)

**Comment by archishou** [comment]
Thanks!

**Comment by archishou** [comment]
Should be good to go now!

**Pull request closed without merging**
