### PR TITLE
add cli flag debug.disable.dhcp.all-ones.netmask to control using all ones netmasks for DHCP

### PR DESCRIPTION
**Pull request by gkodali-zededa**
1) Add new flag "debug.disable.dhcp.all-ones.netmask" to turn on/off the all ones netmask setting in DHCP
2) For the case of Junos (VSRX), we need to name cloud-config file as juniper.conf instead of user-data

The above flag debug.disable.dhcp.all-ones.netmask will not change the netmask behavior of apps created before changing the flag itself.
This flag will have to be changed to the desired value before creating app new apps on the device.

Signed-off-by: Gopi krishna Kodali <gkodali@zededa.com>

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

In principle we'd document this in CONFIG-PROPERTIES.md but since this might go away(?) if the app instances can learn to use the optional part of the DHCP RFC. So let's hold of that for now.

It wouldn't be a bad idea to have the junos cloud-init part as a separate commit (in the same PR) to make it easier to find in git log.

**Comment by giggsoff** [comment]
Hi, @gkodali-zededa can you please tell me more about you research on removing of classless-static-routes?

Seems, that CentOS 8 distribution has the problem with them during cloud-init step https://github.com/lf-edge/eve/pull/1951#issuecomment-802003439. I see only
```
[   13.541886] cloud-init[880]: ci-info: ++++++++++++++++++++++++++++Route IPv4 info++++++++++++++++++++++++++++
[   13.547360] cloud-init[880]: ci-info: +-------+-------------+---------+-----------------+-----------+-------+
[   13.552785] cloud-init[880]: ci-info: | Route | Destination | Gateway |     Genmask     | Interface | Flags |
[   13.558227] cloud-init[880]: ci-info: +-------+-------------+---------+-----------------+-----------+-------+
[   13.563654] cloud-init[880]: ci-info: |   0   |  10.11.12.1 | 0.0.0.0 | 255.255.255.255 |    eth0   |   UH  |
[   13.569230] cloud-init[880]: ci-info: +-------+-------------+---------+-----------------+-----------+-------+
```
inside and, respectively, no access to metadata (169.254.169.254).

But with your PR and enabling of `debug.disable.dhcp.all-ones.netmask` it works
```
[   13.816613] cloud-init[879]: ci-info: ++++++++++++++++++++++++++++Route IPv4 info+++++++++++++++++++++++++++++
[   13.822183] cloud-init[879]: ci-info: +-------+-------------+------------+---------------+-----------+-------+
[   13.827733] cloud-init[879]: ci-info: | Route | Destination |  Gateway   |    Genmask    | Interface | Flags |
[   13.833314] cloud-init[879]: ci-info: +-------+-------------+------------+---------------+-----------+-------+
[   13.840880] cloud-init[879]: ci-info: |   0   |   0.0.0.0   | 10.11.12.1 |    0.0.0.0    |    eth0   |   UG  |
[   13.846446] cloud-init[879]: ci-info: |   1   |  10.11.12.0 |  0.0.0.0   | 255.255.255.0 |    eth0   |   U   |
[   13.851995] cloud-init[879]: ci-info: +-------+-------------+------------+---------------+-----------+-------+
```

**Comment by gkodali-zededa** [comment]
> Hi, @gkodali-zededa can you please tell me more about you research on removing of classless-static-routes?
> 
> Seems, that CentOS 8 distribution has the problem with them during cloud-init step [#1951 (comment)](https://github.com/lf-edge/eve/pull/1951#issuecomment-802003439). I see only
> 
> ```
> [   13.541886] cloud-init[880]: ci-info: ++++++++++++++++++++++++++++Route IPv4 info++++++++++++++++++++++++++++
> [   13.547360] cloud-init[880]: ci-info: +-------+-------------+---------+-----------------+-----------+-------+
> [   13.552785] cloud-init[880]: ci-info: | Route | Destination | Gateway |     Genmask     | Interface | Flags |
> [   13.558227] cloud-init[880]: ci-info: +-------+-------------+---------+-----------------+-----------+-------+
> [   13.563654] cloud-init[880]: ci-info: |   0   |  10.11.12.1 | 0.0.0.0 | 255.255.255.255 |    eth0   |   UH  |
> [   13.569230] cloud-init[880]: ci-info: +-------+-------------+---------+-----------------+-----------+-------+
> ```
> 
> inside and, respectively, no access to metadata (169.254.169.254).
> 
> But with your PR and enabling of `debug.disable.dhcp.all-ones.netmask` it works
> 
> ```
> [   13.816613] cloud-init[879]: ci-info: ++++++++++++++++++++++++++++Route IPv4 info+++++++++++++++++++++++++++++
> [   13.822183] cloud-init[879]: ci-info: +-------+-------------+------------+---------------+-----------+-------+
> [   13.827733] cloud-init[879]: ci-info: | Route | Destination |  Gateway   |    Genmask    | Interface | Flags |
> [   13.833314] cloud-init[879]: ci-info: +-------+-------------+------------+---------------+-----------+-------+
> [   13.840880] cloud-init[879]: ci-info: |   0   |   0.0.0.0   | 10.11.12.1 |    0.0.0.0    |    eth0   |   UG  |
> [   13.846446] cloud-init[879]: ci-info: |   1   |  10.11.12.0 |  0.0.0.0   | 255.255.255.0 |    eth0   |   U   |
> [   13.851995] cloud-init[879]: ci-info: +-------+-------------+------------+---------------+-----------+-------+
> ```

Some operating systems do not completely support classless static routes from RFC 3442. By default, we send classless static routes as part of DHCP response. The flag added as part of this PR is to stop EVE from using classless static routes for those operating system that do not have support for RFC 3442.

**Comment by giggsoff** [comment]
In debug mode I see inside logs of cloud-init
```
[   11.294610] cloud-init[754]: Traceback (most recent call last):
[   11.303139] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/sources/__init__.py\", line 760, in find_source
[   11.311143] cloud-init[754]:     if s.update_metadata([EventType.BOOT_NEW_INSTANCE]):
[   11.319099] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/sources/__init__.py\", line 649, in update_metadata
[   11.326866] cloud-init[754]:     result = self.get_data()
[   11.335190] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/sources/__init__.py\", line 273, in get_data
[   11.341955] cloud-init[754]:     return_value = self._get_data()
[   11.349301] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/sources/DataSourceOpenStack.py\", line 131, in _get_data
[   11.358126] cloud-init[754]:     with EphemeralDHCPv4(self.fallback_interface):
[   11.371203] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/net/dhcp.py\", line 57, in __enter__
[   11.378880] cloud-init[754]:     return self.obtain_lease()
[   11.387697] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/net/dhcp.py\", line 109, in obtain_lease
[   11.395189] cloud-init[754]:     ephipv4.__enter__()
[   11.400100] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/net/__init__.py\", line 920, in __enter__
[   11.411536] cloud-init[754]:     self._bringup_static_routes()
[   11.420327] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/net/__init__.py\", line 974, in _bringup_static_routes
[   11.428088] cloud-init[754]:     ['dev', self.interface], capture=True)
[   11.436396] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/util.py\", line 2088, in subp
[   11.442910] cloud-init[754]:     cmd=args)
[   11.450364] cloud-init[754]: cloudinit.util.ProcessExecutionError: Unexpected error while running command.
[   11.458158] cloud-init[754]: Command: ['ip', '-4', 'route', 'add', '0.0.0.0/0', 'via', '10.11.12.1', 'dev', 'eth0']
[   11.467124] cloud-init[754]: Exit code: 2
[   11.474074] cloud-init[754]: Reason: -
[   11.480660] cloud-init[754]: Stdout:
[   11.484429] cloud-init[754]: Stderr: Error: Nexthop has invalid gateway.
```

**Comment by gkodali-zededa** [comment]
> In debug mode I see inside logs of cloud-init
> 
> ```
> [   11.294610] cloud-init[754]: Traceback (most recent call last):
> [   11.303139] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/sources/__init__.py\", line 760, in find_source
> [   11.311143] cloud-init[754]:     if s.update_metadata([EventType.BOOT_NEW_INSTANCE]):
> [   11.319099] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/sources/__init__.py\", line 649, in update_metadata
> [   11.326866] cloud-init[754]:     result = self.get_data()
> [   11.335190] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/sources/__init__.py\", line 273, in get_data
> [   11.341955] cloud-init[754]:     return_value = self._get_data()
> [   11.349301] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/sources/DataSourceOpenStack.py\", line 131, in _get_data
> [   11.358126] cloud-init[754]:     with EphemeralDHCPv4(self.fallback_interface):
> [   11.371203] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/net/dhcp.py\", line 57, in __enter__
> [   11.378880] cloud-init[754]:     return self.obtain_lease()
> [   11.387697] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/net/dhcp.py\", line 109, in obtain_lease
> [   11.395189] cloud-init[754]:     ephipv4.__enter__()
> [   11.400100] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/net/__init__.py\", line 920, in __enter__
> [   11.411536] cloud-init[754]:     self._bringup_static_routes()
> [   11.420327] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/net/__init__.py\", line 974, in _bringup_static_routes
> [   11.428088] cloud-init[754]:     ['dev', self.interface], capture=True)
> [   11.436396] cloud-init[754]:   File \"/usr/lib/python3.6/site-packages/cloudinit/util.py\", line 2088, in subp
> [   11.442910] cloud-init[754]:     cmd=args)
> [   11.450364] cloud-init[754]: cloudinit.util.ProcessExecutionError: Unexpected error while running command.
> [   11.458158] cloud-init[754]: Command: ['ip', '-4', 'route', 'add', '0.0.0.0/0', 'via', '10.11.12.1', 'dev', 'eth0']
> [   11.467124] cloud-init[754]: Exit code: 2
> [   11.474074] cloud-init[754]: Reason: -
> [   11.480660] cloud-init[754]: Stdout:
> [   11.484429] cloud-init[754]: Stderr: Error: Nexthop has invalid gateway.
> ```

Do you see this with classless static routing disabled (debug.disable.dhcp.all-ones.netmask=true)?
I do not see any problem with the route add command pasted in error above. Is 10.11.12.1 the gateway address configured as part of network instance?

**Comment by rvs** [comment]
Hey @giggsoff @gkodali-zededa has this ever been resolved? Is there a tracker or GH issue?

**Pull request merged**
