### PR TITLE
[Require controller changes] Use ContentTree for BaseOS

### PR DESCRIPTION
**Pull request by giggsoff**
We made transition to ContentTrees/Volumes about two years ago but still use Image/Drive in BaseOSConfig. This PR adjusts BaseOSConfig to use ContentTreeUuid from BaseOS as well as a current behavior. This way we can simplify the logic of baseosmgr.

### CODE REVIEW

**Review by eriknordmark — CHANGES_REQUESTED** [review]
I don't think we need any API changes. The BaseOsConfig message should all be commented as deprecated, and we can use the message BaseOS which has the contenttree uuid and the retry counter. (Seems like EVE-OS only uses the retry counter from there right now.)

Presumably we need to have Eden move from using BaseOsConfig to message BaseOS.

**Comment by eriknordmark** [comment]
I don't understand why you retain and use the BaseOsConfig golang type; the BaseOs type (which corresponds to the BaseOs protobuf message) should be sufficient here.

**Comment by giggsoff** [comment]
> I don't understand why you retain and use the BaseOsConfig golang type; the BaseOs type (which corresponds to the BaseOs protobuf message) should be sufficient here.

We use config suffix here and there to define the object we want to create eventually (and expect object with status suffix as a result), so I thing BaseOsConfig is better approach.
But assume your comment is more about fields inside the object:
1. BaseOsVersion detection for novel object is quite [tricky](https://github.com/lf-edge/eve/pull/2048#discussion_r753087433) and I am not sure that we can override display name of contentTree for old implementation (it may affect UI/logic of controller, if not, I can try to implement it).
2. We may have several configs in old implementation, so we need to have split uuid. Let me check, probably we do not respond that uuid to controller, if so, I can jump onto using of contentTreeUUID as a key
3. Activate field again come with old implementation and the logic of having multiple configs.
So it is not so easy to jump completely to the new implementation with less fields if we want to support both logics.

**Comment by eriknordmark** [comment]
> 3\. Activate field again come with old implementation and the logic of having multiple configs.
>     So it is not so easy to jump completely to the new implementation with less fields if we want to support both logics.

Good point. To do that with the BaseOs message we need to at a minumum add an activate boolean to that message.

I think that in terms of multiple BaseOsConfig, today the controller is only expressing one (which may or may not yet be activated) so don't think we need other API modifications.

But this means we need that new API with Activate first, then get the controllers to use BaseOs message including the activate flag, then we should be able to remove the code using BaseOsConfig message a struct definition.

But maybe it would be good to walk through the other concerns you have to see if something else pops up.

**Comment by eriknordmark** [comment]
> What do you think about including of BaseOsVersion? I still cannot understand the logic of hooking displayName of contentTree. 

Once there is a ContentTreeStatus for the uuid you should be able to use the displayName from there.
Do you need the displayName easier? I thought it is used to verify whether 1) we are currently running that image and 2) whether the image we placed in IMGx has a eve-version which matches the displayName.

> Do you suggest me to modify API, wait for controller change and get rid of current logic? I tried to implement compatibility for both cases (old and new logic) here.

I think the wait makes more sense, because the compatibility logic will introduce new cases to test etc and increase the overall complexity.

**Comment by giggsoff** [comment]
> Once there is a ContentTreeStatus for the uuid you should be able to use the displayName from there. Do you need the displayName easier? I thought it is used to verify whether 1) we are currently running that image and 2) whether the image we placed in IMGx has a eve-version which matches the displayName.

I understand how to extract it. The question is about the whole logic of using DisplayName from another object here, it looks not so clear. I put the comment into the message, I think it should be there.

> I think the wait makes more sense, because the compatibility logic will introduce new cases to test etc and increase the overall complexity.

OK, make sense. I opened another PR: https://github.com/lf-edge/eve/pull/2816. And will work on Eden side to support both cases. Let mark this PR as Draft.

**Comment by rvs** [comment]
Hey @eriknordmark -- I am with @giggsoff on the point that we shouldn't overload DisplayName and we should just handle this explicitly. WDYT?

**Comment by eriknordmark** [comment]
@giggsoff when you get a chance (no rush) can you resolve the conflicts and then we can move to get the controller(s) to use the new API? Did you already update eden/adam  to use the new API?

**Comment by giggsoff** [comment]
> @giggsoff when you get a chance (no rush) can you resolve the conflicts and then we can move to get the controller(s) to use the new API? 

Sure, will do. But the API itself was merged previously. so no blocker I hope.

> Did you already update eden/adam to use the new API?

One part is missing in Eden version we use in EVE-OS repo: https://github.com/lf-edge/eden/pull/812, will update Eden version next week.

**Comment by giggsoff** [comment]
Opened PR to update Eden part to support the novel logic: https://github.com/lf-edge/eve/pull/2960

**Comment by eriknordmark** [comment]
I've tested this against the commercial controller which is running on alpha; once that is fully rolled out we can merge this PR.

**Review by eriknordmark — APPROVED** [review]
Ready for tests

**Pull request merged**
