### PR TITLE
remove the wifi configure hack that was needed before UI support wifi…

### PR DESCRIPTION
**Pull request by naiming-zededa**
… cfg

Signed-off-by: Naiming Shen <naiming@zededa.com>

- have tested in patch in various configuration cases.

### CODE REVIEW

**Comment by rvs** [comment]
Hey @naiming-zededa -- great to this this, but what's the e2e story here? Suppose I have a new device with only WiFi (like HiKey), what do I need to configure where to make it work?

**Comment by naiming-zededa** [comment]
@rvs,, first need to configure in the cloud with UI, the 'network' configuration part for the wifi params; then we needed to use USB to put the 'override.json' file into the /config/DevicePortConfig/ directory.

**Comment by eriknordmark** [comment]
> @rvs,, first need to configure in the cloud with UI, the 'network' configuration part for the wifi params; then we needed to use USB to put the 'override.json' file into the /config/DevicePortConfig/ directory.

But with this change it should be sufficient to do it in the UI, correct?

**Comment by naiming-zededa** [comment]
> > @rvs,, first need to configure in the cloud with UI, the 'network' configuration part for the wifi params; then we needed to use USB to put the 'override.json' file into the /config/DevicePortConfig/ directory.
> 
> But with this change it should be sufficient to do it in the UI, correct?

Correct. Except for USB is used for bootstrap.

**Comment by naiming-zededa** [comment]
> LGTM.
> 
> I think we should improve the error handling for the WiFi and APN code. Some errors are logged but we might want to fail things up front if we can't decrypt the credentials or if we can't write the files. That means returning an error from checkAndUpdateWireless and have that result in setting LastFailed/LastError in the caller. But that can be a separate PR.
> 
> I also don't know if we can extract errors when WiFi fails to authenticate and associate.
> That would be useful to be able to feed back to the controller. Perhaps we are getting it as part of the wlan container logs?

today the logs have those:
linuxkit-ac1f6b70fdaa kernel: [   67.157106] wlan0: authenticate with e4:6f:13:3f:73:08
linuxkit-ac1f6b70fdaa kernel: [   67.179534] wlan0: send auth to e4:6f:13:3f:73:08 (try 1/3)
linuxkit-ac1f6b70fdaa kernel: [   67.192639] wlan0: authenticated
linuxkit-ac1f6b70fdaa kernel: [  884.618783] wlan0: deauthenticating from e4:6f:13:3f:73:08 by local choice (Reason: 3=DEAUTH_LEAVING)

**Pull request merged**
