### PR TITLE
temp config for edge-view with configitem

### PR DESCRIPTION
**Pull request by naiming-zededa**
Signed-off-by: Naiming Shen <naiming@zededa.com>

- a temp solution to allow testing edge-view on the EVE device before the zedcloud config/UI are fully supported.

### CODE REVIEW

**Review by eriknordmark — CHANGES_REQUESTED** [review]
The description is a bit lacking, starting with not having any reference to what edgeview is (presumably not the dentist nor the park in Auburn), and how it is installed.
I see the code is reading /run/edgeview but I don't see anything writing there.

**Comment by naiming-zededa** [comment]
@eriknordmark right. I don't have much description on the 'edge-view' itself. 'edge-view' will be installed as a dom0 container service, and has the /run/edge-view mounted to access to read this data from. This patch is to write the authentication data into it for near term testing.
the reading part is a container script:
#!/bin/sh

while true;
do
  sleep 5
  PID=$(pgrep /usr/bin/edge-view)
  if [ -z "$PID" ]; then
    if [ -f /run/edgeview/edge-view-token ]; then
      TOKEN=`cat /run/edgeview/edge-view-token`
      WSADDR=`cat /run/edgeview/edge-view-wss-addr`
      /usr/bin/edge-view -server -ws "$WSADDR" -token "$TOKEN" &
      PID=$(pgrep /usr/bin/edge-view)
      echo "started edge-view with pid $PID"
    fi
  else
    if [ ! -f /run/edgeview/edge-view-token ]; then
      kill -9 $PID
      echo "edge-view killed"
    fi
  fi
done

**Comment by naiming-zededa** [comment]
@rvs understood. lets hold on this PR until the main portion is in later.

**Comment by naiming-zededa** [comment]
No need for this PR. The temporary config will be supported in  Edge-View API and JWT #2427 . Close this.

**Pull request closed without merging**
