### PR TITLE
Fix unlock vault on controller key for zfs

### PR DESCRIPTION
**Pull request by giggsoff**
We should unlock zfs vault in different way on controller key received

### CODE REVIEW

**Review by rvs — APPROVED** [review]
LGTM

**Comment by zedi-pramodh** [comment]
@giggsoff   can please write a brief description on the problem found and how this fix helps.

**Comment by giggsoff** [comment]
> @giggsoff can please write a brief description on the problem found and how this fix helps.

The logic described here #1423. I noticed that we do not handle zfs decryption.

**Comment by zedi-pramodh** [comment]
@giggsoff thank you for the link. LGTM.

**Review by eriknordmark — COMMENTED** [review]
This *might* be sufficient, but it is very hard to tell given the naming and structure in vaultmgr. Hard to tell which functions are generic (such as setupDefaultVault) and I would think that unlockVault should also be generic.

Thus I think it makes sense to refactor/rename things so that there aren't checks for the type in seemingly random places. The cleanest way to do that would be to define an interface with the functions which can then be implemented for ext4 and zfs (and it would make sense to put the ext4/fscrypt specific functions in a new vaultmgrext4 file).
If an interface is too painful one could have the generic functions have a switch on the type and call genericext4() or genericzfs() functions.

But we can go ahead with this fix/PR and do that refactoring as a separate PR.

**Comment by giggsoff** [comment]
> This _might_ be sufficient, but it is very hard to tell given the naming and structure in vaultmgr. Hard to tell which functions are generic (such as setupDefaultVault) and I would think that unlockVault should also be generic.
> 
> Thus I think it makes sense to refactor/rename things so that there aren't checks for the type in seemingly random places. The cleanest way to do that would be to define an interface with the functions which can then be implemented for ext4 and zfs (and it would make sense to put the ext4/fscrypt specific functions in a new vaultmgrext4 file). If an interface is too painful one could have the generic functions have a switch on the type and call genericext4() or genericzfs() functions.
> 
> But we can go ahead with this fix/PR and do that refactoring as a separate PR.

Make sense. Let's schedule it for the next PR

**Pull request merged**
