### PR TITLE
Adding device Serial# in http header for on-boarding troubleshooting

### PR DESCRIPTION
**Pull request by naiming-zededa**
Sending 'serial number' in http header for device, pivotal #165749178. Have tested on zedcloud is receiving the 'serial#'.

### CODE REVIEW

**Comment by rvs** [comment]
A couple of points:
    * please update the title of the PR to be descript
    * how is this interplaying with soft serial
?

**Comment by naiming-zededa** [comment]
> Hey @naiming-zededa before I get to the detailed review, can you please take a look at the previous comment (I couldn't add it to my comment for some reason)

Sorry, changed the title. The do we always have a device 'serial' or we need to consider soft-serial if device serial is not there? I'm not familiar with this

**Comment by rvs** [comment]
Yes @naiming-zededa lots of time the hardware serial # is empty or misformed. My immediate suggestion would be to consider sending both of them for now as part of the header.

E.g. create X-Soft-Serial-Number or something like that

You also need to update our API documentation to explain what the expectations around EVE setting up those: https://github.com/lf-edge/eve/blob/master/api/API.md

**Comment by naiming-zededa** [comment]
Ok @rvs will update with the soft seq#. and update the API doc on this.

**Comment by deitch** [comment]
> You also need to update our API documentation to explain what the expectations around EVE setting up those: https://github.com/lf-edge/eve/blob/master/api/API.md

This was my first reaction. I might even suggest a separate PR to describe what we are updating and why, which should go through first.

**Comment by naiming-zededa** [comment]
> My understanding is that we only need this in the onboarding case i.e., when client.go does the selfRegister. After that we have a uuid which gets included as the X-Request-Id.
> 

I was thinking about even using 'diag' generating serial# is also useful, then if we want to match later the UUID to see what initial messages, we can reference to the serial# to search the logs.

> Also, I wonder whether we should include the product key as the X-Request-Id for the selfRegister. That can be extracted from the CN field in the onboarding certificate. When the CN is a UUID as in the current onboarding cert in lf-edge/eve/conf/
> nordmark@bobo:~/domainmgr/eve$ openssl x509 -in conf/onboard.cert.pem -text
> Certificate:
> Data:
> Version: 3 (0x2)
> Serial Number:
> 56:77:09:6f:b5:8f:b9:8e:02:9c:a3:17:04:35:3a:b2
> Signature Algorithm: ecdsa-with-SHA256
> Issuer: O = Zededa Inc, CN = 5d0767ee-0547-4569-b530-387e526f8cb9
> 
> you can put it in the X-Request-Id.
> I'm sure there are golang routines to extract the CN from the cert.

Same as above item, I had some discussion with Kaylan and Ravi, their opinion were just always send serial# and not to put in the CN# since most likely using serial# can identify the device. I can certainly change them.

**Comment by rvs** [comment]
OK, at this point I'm seriously confused as to what requirement this PR is trying to address.

This doesn't sound like a bug, so it must be some capability that we're building that I'm not aware of?

**Comment by naiming-zededa** [comment]
> OK, at this point I'm seriously confused as to what requirement this PR is trying to address.
> 
> This doesn't sound like a bug, so it must be some capability that we're building that I'm not aware of?

Well, this is to add the capability of identifing the device on cloud side if UUID is not there yet. I was just saying if device always send serial#, there are certain advantages (such as from UUID tracking back to initial messages from the device)

**Comment by deitch** [comment]
Don't we send the serial number as part of the registration `POST`? I am pretty sure it is in the message. What does this add?

**Comment by naiming-zededa** [comment]
> Don't we send the serial number as part of the registration `POST`? I am pretty sure it is in the message. What does this add?

Good point. Then I'll send the Seq# in http only if we don't have the UUID yet to do some savings

**Comment by naiming-zededa** [comment]
> > You also need to update our API documentation to explain what the expectations around EVE setting up those: https://github.com/lf-edge/eve/blob/master/api/API.md
> 
> This was my first reaction. I might even suggest a separate PR to describe what we are updating and why, which should go through first.

Looked at this API.md file, since we are adding some extra data in http header for troubleshooting purpose only, we don't actually change any API. I doubt we need to update this doc for this PR

**Comment by deitch** [comment]
> Good point. Then I'll send the Seq# in http only if we don't have the UUID yet to do some savings

I didn't understand this part.

> Looked at this API.md file, since we are adding some extra data in http header for troubleshooting purpose only, we don't actually change any API. I doubt we need to update this doc for this PR

So is this a standard that is expected? Or is this a temporary change we are doing just to enable some troubleshooting? 

The API is (supposed to be?) the contract that defines the interface between an EVE and a Controller. If we add anything to that (other than, "I am just enabling this for 10 minutes for some testing"), then it should be in there.

Personally, I think that if we might need a debugging channel, then we should add it to the API as well and just make it optional. But just my opinion, not very strongly held... :-)

**Comment by naiming-zededa** [comment]
> > Good point. Then I'll send the Seq# in http only if we don't have the UUID yet to do some savings
> 
> I didn't understand this part.
> 

Only send seq# in http header from device in 'X-Serial-Number', if the device has not learned the UUID yet from the cloud. vs in the current form of the diff, it always send Seq# in http header.

**Comment by eriknordmark** [comment]
> Don't we send the serial number as part of the registration `POST`? I am pretty sure it is in the message. What does this add?

@deitch The http server logs include the http headers, but not a decode of the protobuf messages.
We added the X-Request-Id with the UUID a while back so that one can correlate the server logs with the device UUIDs, but that doesn't help for the onboarding case when the device calls the register, ping, and config API endpoints.

**Comment by eriknordmark** [comment]
> I was thinking about even using 'diag' generating serial# is also useful, then if we want to match later the UUID to see what initial messages, we can reference to the serial# to search the logs.

Makes sense.

**Comment by deitch** [comment]
> @deitch The http server logs include the http headers, but not a decode of the protobuf messages.
We added the X-Request-Id with the UUID a while back so that one can correlate the server logs with the device UUIDs, but that doesn't help for the onboarding case when the device calls the register, ping, and config API endpoints.

Got it. So this is for debugging. I think we should have something in the API definitions, which include headers. It might be as simple as optional headers like `X-Request-Id` and what can be in them, but any comms between EVE and Controller should be defined. It even can be defined as "any headers that start as X-blafoobar-* can contain anything custom" (well, hopefully better than that), but I see this as a pretty desired use case, so we should get it in there.

**Comment by eriknordmark** [comment]
> Same as above item, I had some discussion with Kaylan and Ravi, their opinion were just always send serial# and not to put in the CN# since most likely using serial# can identify the device. I can certainly change them.

If you send both the hardware and software serial that would be the case; the hardware serial can be empty or "Default string" or anything else which is not unique.
With that in place you don't need to extract the CN.

**Comment by naiming-zededa** [comment]
> > Same as above item, I had some discussion with Kaylan and Ravi, their opinion were just always send serial# and not to put in the CN# since most likely using serial# can identify the device. I can certainly change them.
> 
> If you send both the hardware and software serial that would be the case; the hardware serial can be empty or "Default string" or anything else which is not unique.
> With that in place you don't need to extract the CN.

Ok. Going to do both hardware and software seq#s.

**Pull request merged**
