### PR TITLE
Include ZFS in installer

### PR DESCRIPTION
**Pull request by andrewd-zededa**
Needed for ZFS vault, HV=kubevirt

### CODE REVIEW

**Review by OhmSpectator — APPROVED** [review]

**Comment by eriknordmark** [comment]
I assume this needs to be backported to 13.4-stable, so I added the stable label.

**Comment by andrewd-zededa** [comment]
Ok, once merging I'll submit the cherry-pick back port.

**Comment by eriknordmark** [comment]
The Eden tests do go through the onboarding process and it's useful to sanity check that. I thought there were tests running the installer image as well, but clearly not with zfs since then we wouldn't have had this regression.

**Comment by OhmSpectator** [comment]
> there were tests running the installer image as well
wow, I didn't know... I have at least to find what are the test cases that we run))

**Comment by OhmSpectator** [comment]
All green! Merging!
@andrewd-zededa, waiting for backporting PR(s)

**Pull request merged**
