### PR TITLE
While updating, mark baseOs state as DEFERRED instead of throwing an error

### PR DESCRIPTION
**Pull request by adarsh-zededa**
WIP because controller changes are yet to be deployed on alpha. 

Signed-off-by: adarsh-zededa <adarsh@zededa.com>

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM
Does Adam need to support the new deferred enum value?

**Comment by rvs** [comment]
> Does Adam need to support the new deferred enum value?

Are you asking in a sense whether it would keep working (I guess the answer is yes since Eden is passing) or whether it can actually take advantage of the new value @eriknordmark ?

**Review by rvs — APPROVED** [review]
LGTM

**Comment by rvs** [comment]
Hey @eriknordmark @adarsh-zededa -- should we merge this now?

**Comment by adarsh-zededa** [comment]
> Hey @eriknordmark @adarsh-zededa -- should we merge this now?

Yeah @rvs

**Pull request merged**
