### PR TITLE
Reducing rootfs size on ARM to fit into 250M budget

### PR DESCRIPTION
**Pull request by rvs**
Trying this on ARM only for now -- if it works -- we can extend it to x86 (which is under budget for now).

### CODE REVIEW

**Comment by rvs** [comment]
Apparently yetus/hadolint gets confused about the following like:
> RUN [ "$(uname -m)" = "x86_64" ] || strip /dist/zedbox
it would be nice for @aw-was-here to take a look at this since it may actually be a bug (especially since the very same line in the other Dockerfile doesn't seem to trigger the complaint

Aside from that -- I'll force merge if there's no disagreement and it takes too long to fix yetus/hadolint

**Comment by rvs** [comment]
Also, @aw-zededa I am wondering if Dockerfile.in vs. Dockerfile naming would make any difference for yetus

**Comment by aw-was-here** [comment]
> Apparently yetus/hadolint gets confused about the following like:
> 
> > RUN [ "$(uname -m)" = "x86_64" ] || strip /dist/zedbox
> 
> it would be nice for @aw-was-here to take a look at this since it may actually be a bug (especially since the very same line in the other Dockerfile doesn't seem to trigger the complaint

This is almost certainly hadolint/hadolint#362 (which was just filed 5 days ago!).

> Also, @aw-zededa I am wondering if Dockerfile.in vs. Dockerfile naming would make any difference for yetus

No.  Apache Yetus knows all. 😉

**Comment by rvs** [comment]
LOL @aw-was-here -- me and my ability to trigger freshly minted bugs ;-)

**Comment by rvs** [comment]
@nordmark -- yup! that and a whole bunch of other things need to be tested. In a way, I'd like to get back to having ARM as a sort of canary in a coalmine for what we do on intel.

I'll commit this (and an installer fixe) so we can have ARM back again next week and do the needed testing.

**Pull request merged**
