### PR TITLE
Patch for 7.9.1

### PR DESCRIPTION
**Pull request by ruslan-zededa**
This patch contains the following PRs: 
https://github.com/lf-edge/eve/pull/2593
https://github.com/lf-edge/eve/pull/2585
https://github.com/lf-edge/eve/pull/2594

### CODE REVIEW

**Review by milan-zededa — APPROVED** [review]

**Review by eriknordmark — APPROVED** [review]
Again

**Comment by milan-zededa** [comment]
@ruslan-zededa Automatic git-merge is not enough in this case, you need to also remove import of `sync` package in `cmd/zedagent/handleconfig.go`

**Review by milan-zededa — APPROVED** [review]

**Comment by eriknordmark** [comment]
@milan-zededa do you think 2597 should be included here, or was the refactoring done after 7.9?

**Comment by milan-zededa** [comment]
Refactoring was done after 7.9 (in 7.11)

**Pull request merged**
