### PR TITLE
publish networkInstances inside DeviceInfo

### PR DESCRIPTION
**Pull request by giggsoff**
Seems, that we can loose the state of networkInstance in case of problems on controller side https://github.com/lf-edge/eden/issues/372 cause we send it only once inside ZInfoMsg_Niinfo.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by rvs** [comment]
Hey @giggsoff -- I'm not sure I understand what you're trying to solve here. Are you saying that having that same information as part of `ZInfoMsg` is now enough somehow? Also -- would be great for @gkodali-zededa and @eriknordmark to chime in.

**Comment by giggsoff** [comment]
On the Eden side I try to check state is NetworkInstances and show them inside `eden network ls`. But in case of transition to inactivate (or delete) state of NetworkInstance, I can only find it inside single info message of Niinfo type. It will be helpful, if Adam (and Eden) will receive list of NetworkInstances inside DeviceInfo (which is periodically sending one).

**Comment by rvs** [comment]
Yeah @giggsoff -- this definitely needs to be discussed with @eriknordmark then -- it is quite a change to our eventual consistency design.

**Comment by eriknordmark** [comment]
> On the Eden side I try to check state is NetworkInstances and show them inside `eden network ls`. But in case of transition to inactivate (or delete) state of NetworkInstance, I can only find it inside single info message of Niinfo type. It will be helpful, if Adam (and Eden) will receive list of NetworkInstances inside DeviceInfo (which is periodically sending one).

@giggsoff I don't understand the issue. We send an info message for the network instance (as for other objects) each time there is a change to this object. And we retry that forever if the controller doesn't response with a 200. Is the controller forgetting what it received in this case?

**Comment by mydatascience** [comment]
The problem is that if we miss this message for some reason (unlike with apps that have state updated) then we lose the state of the network objects. And we definitely want to see the current state of the network objects as we see apps states.  
Otherwise we need to remember everything (say we were running for days and clean logs) and can't reconstruct the actual state. It will also be useful once we plan to reattach to some working eve with newborn adam that has a certificate. (Say old one dead or we want a HA)

**Comment by eriknordmark** [comment]
> Otherwise we need to remember everything (say we were running for days and clean logs) and can't reconstruct the actual state. It will also be useful once we plan to reattach to some working eve with newborn adam that has a certificate. (Say old one dead or we want a HA)

For that it makes more sense to add some epoch/generation number to the ConfigResponse/EdgeDevConfig and have EVE handle changes to that number by triggering sending the info messages for all the objects (device, all apps, all volumes, all network instances). 
With your approach we'd end up sending all info messages periodically which is either a waste of bandwith (if we do it every minute or so) or very slow (if we do it every 24 hours or so).

**Comment by mydatascience** [comment]
> For that it makes more sense to add some epoch/generation number to the ConfigResponse/EdgeDevConfig and have EVE handle changes to that number by triggering sending the info messages for all the objects (device, all apps, all volumes, all network instances).

Yes, makes sense. But then we have to ask Eve for these parameters  through controller. And we will stress the controller (and need to create some routine/processor in EVE) if we ask too often (we'll probably do it and then wait for answer). 

However the bandwidth should not be too stressed even if we send such data each minute. This way we might also understand that the system is alive and have its actual state. Now we already get DeviceInfo on a regular basis. Just adding networks and potentially other useful info there will not increase the footprint a lot.

**Comment by eriknordmark** [comment]
> Yes, makes sense. But then we have to ask Eve for these parameters through controller. And we will stress the controller (and need to create some routine/processor in EVE) if we ask too often (we'll probably do it and then wait for answer).

I thought it was the controller which "forgot" things, hence asking the controller to have some code to handle its own amnesia isn't too much to ask is it?
Or is it something else which is forgetting?

> However the bandwidth should not be too stressed even if we send such data each minute. This way we might also understand that the system is alive and have its actual state. Now we already get DeviceInfo on a regular basis. Just adding networks and potentially other useful info there will not increase the footprint a lot.

All of the info message might be about 10kbyte. How many gigabytes per month would that make sure the cellular or satelite network subscription? About .5Gbyte. 
That is just to handle the potential for amnesia in a controller.

**Comment by mydatascience** [comment]
Traffic minimization makes sense. But then we should cut all(or most of) log/info/metrics. And make some mechanism to request this data. I'd rather decouple it with sending config itself (which is generally requesting some Eve state change).

**Comment by eriknordmark** [comment]
> The problem is that if we miss this message for some reason (unlike with apps that have state updated) then we lose the state of the network objects. And we definitely want to see the current state of the network objects as we see apps states.

I missed this statement earlier. Note that apps and devices behave exactly the same as network instances when it comes to sending info messages; they are only sent when there is a change. Since the device info contains success timestampts info in the system adapter info it might in practice get sent periodically. But app info messages are definitely not sent periodically.

> Otherwise we need to remember everything (say we were running for days and clean logs) and can't reconstruct the actual state. It will also be useful once we plan to reattach to some working eve with newborn adam that has a certificate. (Say old one dead or we want a HA)

Yes, the controller is assumed to retain state. Sorry if that wasn't clear but that is how the API is done.

**Comment by eriknordmark** [comment]
> Traffic minimization makes sense. But then we should cut all(or most of) log/info/metrics. And make some mechanism to request this data. I'd rather decouple it with sending config itself (which is generally requesting some Eve state change).

Yes, we need to be able to manage the log volume as well. Metrics  can be scaled back by having the device only report metrics every hour or every week; means a loss of metric accuracy in the time domain.

But the logs and metrics are believed to be useful.
Periodically sending the identical info messages just because there is a broken controller with amnesia isn't useful; the controller should be fixed.
Adding the API for a controller to say "I got amnesia - please send me all info messages" is something we can contemplater. But periodic repeat makes zero sense to me.

**Comment by rvs** [comment]
> Adding the API for a controller to say "I got amnesia - please send me all info messages" is something we can contemplater.

Hey @eriknordmark @giggsoff -- I'm also very much in favor of this API (while yes, in general controller is where state is and it needs to work extra hard not to lose the state -- it will happen -- hence having some kind of an epoch scheme that can be triggered on the EVE side to start a new epoch with the controller may be useful).

So.... shall we design this and publish our usual proposal (+email to eve-tsc@)? Who can tackle this? And in the meantime should we close this PR?

**Comment by eriknordmark** [comment]
> Hey @eriknordmark @giggsoff -- I'm also very much in favor of this API (while yes, in general controller is where state is and it needs to work extra hard not to lose the state -- it will happen -- hence having some kind of an epoch scheme that can be triggered on the EVE side to start a new epoch with the controller may be useful).

Some info epoch counter would make sense.

> So.... shall we design this and publish our usual proposal (+email to eve-tsc@)? Who can tackle this? And in the meantime should we close this PR?

Sure, as long as that is the royal "we" ;-)

**Comment by rvs** [comment]
> Sure, as long as that is the royal "we" ;-)

LOL @eriknordmark -- can we start calling you [King Erik](https://en.wikipedia.org/wiki/Erik_Bj%C3%B6rnsson)? ;-)

But seriously -- how do you guys propose we proceed -- I think someone need to do that e2e proposal -- and on this one -- I'll defer to you two.

**Comment by rvs** [comment]
So it seems that @mydatascience is working on an epoch proposal. Shall we close this PR until that happens @giggsoff ?

**Comment by giggsoff** [comment]
Waiting for better design.

**Pull request closed without merging**
