### PR TITLE
Fix openssh build

### PR DESCRIPTION
**Pull request by andrewd-zededa**
removed duplicate add

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by andrewd-zededa** [comment]
@eriknordmark I bumped the build by adding a small change to disable the openssh rekey test which was taking over 30min to run locally.

**Review by christoph-zededa — APPROVED** [review]

**Review by milan-zededa — APPROVED** [review]

**Comment by milan-zededa** [comment]
I see this build error:
```
Error: error building "lfedge/eve-debug:dfd4456a0f41cfea7577a264976b6cf55e6882a4": error building for arch amd64: failed to solve: process "/bin/sh -c gpg --verify openssh-${OPENSSH_VERSION}.tar.gz.asc openssh-${OPENSSH_VERSION}.tar.gz" did not complete successfully: exit code: 2
2024/07/10 00:03:49 error during command execution: error building "lfedge/eve-debug:dfd4456a0f41cfea7577a264976b6cf55e6882a4": error building for arch amd64: failed to solve: process "/bin/sh -c gpg --verify openssh-${OPENSSH_VERSION}.tar.gz.asc openssh-${OPENSSH_VERSION}.tar.gz" did not complete successfully: exit code: 2
```

**Comment by christoph-zededa** [comment]
> I see this build error:
> 
> ```
> Error: error building "lfedge/eve-debug:dfd4456a0f41cfea7577a264976b6cf55e6882a4": error building for arch amd64: failed to solve: process "/bin/sh -c gpg --verify openssh-${OPENSSH_VERSION}.tar.gz.asc openssh-${OPENSSH_VERSION}.tar.gz" did not complete successfully: exit code: 2
> 2024/07/10 00:03:49 error during command execution: error building "lfedge/eve-debug:dfd4456a0f41cfea7577a264976b6cf55e6882a4": error building for arch amd64: failed to solve: process "/bin/sh -c gpg --verify openssh-${OPENSSH_VERSION}.tar.gz.asc openssh-${OPENSSH_VERSION}.tar.gz" did not complete successfully: exit code: 2
> ```

The pipeline behaves strange:
```
#36 [build 21/56] WORKDIR /usr/src/openssh-9.8p1
#36 DONE 0.0s

#37 [build 22/56] ADD https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.8p1.tar.gz /usr/src
#37 DONE 0.0s

#38 [build 23/56] ADD https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.8p1.tar.gz.asc /usr/src
#38 DONE 0.0s

#39 [build 24/56] COPY ssh/RELEASE_KEY.asc /usr/src
#39 DONE 0.0s
``` 
(https://github.com/lf-edge/eve/actions/runs/9865821631/job/27243476619?pr=4073 )

but according to the code in this PR `WORKDIR /usr/src/openssh-9.8p1` comes after `ADD .../openssh-${OPENSSH_VERSION}.tar.gz.asc` (https://github.com/lf-edge/eve/pull/4073/files#diff-eb8b8d5cc8d10e1bd74ad66ca8bb1565b32a21a18220ef586c0a22d2e961aee1L77 )

**Comment by milan-zededa** [comment]
@andrewd-zededa Please rebase onto the latest master. It should fix the failing build.

**Comment by andrewd-zededa** [comment]
@milan-zededa rebased on latest

**Comment by andrewd-zededa** [comment]
and Rate limited...

> 429 Too Many Requests - Server message: toomanyrequests

**Comment by andrewd-zededa** [comment]
The build error is odd see steps 34, 35, 36 below which are the lines removed by the pr.

> #33 [build 18/56] WORKDIR /usr/src
> #33 DONE 0.0s
> 
> #34 [build 19/56] ADD https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.8p1.tar.gz /usr/src
> #34 DONE 0.0s
> 
> #35 [build 20/56] RUN tar xvf openssh-9.8p1.tar.gz
> #0 0.023 openssh-9.8p1
> ...
> ...
> ...
> #35 0.171 openssh-9.8p1/xmss_wots.h
> #35 DONE 0.2s
> 
> #36 [build 21/56] WORKDIR /usr/src/openssh-9.8p1
> #36 DONE 0.0s
> 
> #37 [build 22/56] ADD https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.8p1.tar.gz /usr/src
> #37 DONE 0.0s
> 
> #38 [build 23/56] ADD https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.8p1.tar.gz.asc /usr/src
> #38 DONE 0.0s
> Error: error building "lfedge/eve-debug:dfd4456a0f41cfea7577a264976b6cf55e6882a4": error building for arch amd64: failed to solve: process "/bin/sh -c gpg --verify openssh-${OPENSSH_VERSION}.tar.gz.asc openssh-${OPENSSH_VERSION}.tar.gz" did not complete successfully: exit code: 2
> 2024/07/10 16:14:58 error during command execution: error building "lfedge/eve-debug:dfd4456a0f41cfea7577a264976b6cf55e6882a4": error building for arch amd64: failed to solve: process "/bin/sh -c gpg --verify openssh-${OPENSSH_VERSION}.tar.gz.asc openssh-${OPENSSH_VERSION}.tar.gz" did not complete successfully: exit code: 2
> make: *** [Makefile:1035: eve-debug] Error 1
> Error: Process completed with exit code 2.

**Comment by eriknordmark** [comment]
We know this fix is needed since without it we can't even do a make pkg/debug in a workspace.
Merging.
But we might also need some workflow/actions fixes - I don't know.

**Pull request merged**
