### PR TITLE
workflows: add rt kernel build

### PR DESCRIPTION
**Pull request by christoph-zededa**
currently any tests for the rt kernel are missing; at least try to compile it ...

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
Need to ask LF admins to create lfedge/eve-rt-kernel in dockerhub before we merge this.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by rouming** [comment]
> Need to ask LF admins to create lfedge/eve-rt-kernel in dockerhub before we merge this.

this 'eve-rt-kernel' dockerhub image already created. all we need to push from the corresponding CI build.

**Comment by christoph-zededa** [comment]
I am not sure if it is a good idea to merge this PR as it seems to add an extra one hour build time to every build

**Comment by eriknordmark** [comment]
> I am not sure if it is a good idea to merge this PR as it seems to add an extra one hour build time to every build

That is on master and release builds i assume. Any impact on a developer build?

**Comment by rouming** [comment]
@christoph-zededa outdated? or you want to finish that? or we merge that?

**Comment by christoph-zededa** [comment]
I think this PR does not make sense as it should be implemented on this repo instead: https://github.com/lf-edge/eve-kernel/tree/eve-kernel-amd64-v6.1.38-rt

**Pull request closed without merging**
