### PR TITLE
generate protobuf visual

### PR DESCRIPTION
**Pull request by deitch**
Whenever we regenerate the libraries for the protobufs with `make proto`, it will generate the image as well.

### CODE REVIEW

**Comment by rvs** [comment]
This is super cool! Can you please link to resulting files in the api/README.md @deitch ?

**Comment by deitch** [comment]
> Can you please link to resulting files in the api/README.md

Done. It already had a link to the `.png`, I added to the rest, and moved them into `api/images/`

Ready to go.

**Comment by deitch** [comment]
yetus is complaining about the generated `.dot` file; we can ignore it.

**Comment by deitch** [comment]
And yetus is clean now too.

**Pull request merged**
