### PR TITLE
[13.4-stable] memory-monitor: Fix log files clean up to prevent storage overflow.

### PR DESCRIPTION
**Pull request by OhmSpectator**
It's a backport of #4331

### CODE REVIEW

**Review by christoph-zededa — APPROVED** [review]

**Comment by OhmSpectator** [comment]
All green... @milan-zededa, @rene, @erik, wouldn't you mind to approve it? =)

**Comment by OhmSpectator** [comment]
@deitch approve? (making kitten eyes)

**Comment by deitch** [comment]
Nah, let's drive you crazy with spurious and senseless review ideas. 😆

**Review by deitch — APPROVED** [review]

**Pull request merged**
