### PR TITLE
bring the vendor side to latest by make proto-vendor

### PR DESCRIPTION
**Pull request by naiming-zededa**
Signed-off-by: Naiming Shen <naiming@zededa.com>
- bring to date the vendor side, by 'make proto' and 'make proto-vendor'
- majority of the patch were due to vendor directory changes several days ago

### CODE REVIEW

**Comment by rvs** [comment]
Hey @naiming-zededa please split this into two commit as we've discussed -- then I can review

**Comment by naiming-zededa** [comment]
@rvs Yes, this is the 2nd part of the split. the first part of the split is PR #596 which was merged by Erik hours ago.

**Comment by naiming-zededa** [comment]
sure. I can manually generate the vendor side of files. will have a different PR.
if you checkout before and after the below patch, then run 'make proto-vendor',
you will see the difference:
commit a76019d490c4b47232b626659e339f8c5a371362
Author: Avi Deitcher <avi@deitcher.net>
Date:   Sun Jan 26 13:58:57 2020 +0200

**Comment by naiming-zededa** [comment]
created PR #601, no need for this PR.

**Pull request closed without merging**
