### PR TITLE
Updated 6.8[6.8.3]

### PR DESCRIPTION
**Pull request by dautovri**
new version based on 6.8.2 that includes the following fixes:
- OOM 
- HPE hardware wdog 
- Azure download speed

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
Is there some additional commit to get the code into vendor missing? 
(Did each PR have only one commit?)

**Comment by giggsoff** [comment]
Seems, we also need https://github.com/lf-edge/eve/pull/2163, https://github.com/lf-edge/eve/pull/2170 and https://github.com/lf-edge/eve/pull/2232

**Review by eriknordmark — APPROVED** [review]
Run eden agai

**Review by eriknordmark — APPROVED** [review]
One more try

**Pull request merged**
