### PR TITLE
[WIP] Retry failed update if UUIDandVersion.Version changed

### PR DESCRIPTION
**Pull request by eriknordmark**
Need to run this through your new Eden test @sadov

### CODE REVIEW

**Comment by sadov** [comment]
@eriknordmark Seems like re-updating should be done automatically, without setting UUIDandVersion?

**Review by rvs — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
> @eriknordmark Seems like re-updating should be done automatically, without setting UUIDandVersion?

No, because then EVE would repeatedly retry by itself which is a bad idea if the image is actually bad; would cause reboot loop. So we need some change from the controller to indicate that we want a retry.
Note that to oday we can force a retry by 1) remove the baseos image from the edgedevconfig, 2) wait for EVE to no longer report it as failed 3) add it to the edgedevconfig again. But that means waiting in #2.

**Comment by sadov** [comment]
Thanks @eriknordmark -- I will try.

**Comment by sadov** [comment]
@eriknordmark seems to have some problems with the EVE build (log in attach):
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
[make_eve.002.log](https://github.com/lf-edge/eve/files/6289898/make_eve.002.log)
$ go version
go version go1.16.2 linux/amd64
$ git status
On branch fixes
Your branch is up to date with 'origin/fixes'.

nothing to commit, working tree clean
$ git pull
Already up to date.
$ make eve
...
  Create OCI config for lfedge/eve-pillar:50eb8ba9f017ae583508ca90fb012071813d6bb3-amd64
time="2021-04-10T16:06:22+03:00" level=fatal msg="Could not pull image lfedge/eve-pillar:50eb8ba9f017ae583508ca90fb012071813d6bb3-amd64: error getting manifest for trusted image docker.io/lfedge/eve-pillar:50eb8ba9f017ae583508ca90fb012071813d6bb3-amd64: GET https://index.docker.io/v2/lfedge/eve-pillar/manifests/50eb8ba9f017ae583508ca90fb012071813d6bb3-amd64: MANIFEST_UNKNOWN: manifest unknown; map[Tag:50eb8ba9f017ae583508ca90fb012071813d6bb3-amd64]"
containers/services/guacd/runtime.json: Truncated input file (needed 71 bytes, only 0 available)
bsdtar: Error exit delayed from previous errors.
make: *** [Makefile:482: /data/work/sadov/EVE/github/eriknordmark/eve/dist/amd64/0.0.0-fixes-4cd79370/installer/rootfs.img] Error 1
rm images/rootfs-kvm.yml.in
```

**Comment by eriknordmark** [comment]
> @eriknordmark seems to have some problems with the EVE build (log in attach):

@sadov if you patch pkg/pillar you have to do make pkg/pillar eve
since the Makefiles don't know which docker containers need to be rebuilt.

**Comment by eriknordmark** [comment]
Doing this differently using a retry counter,

**Pull request closed without merging**
