### PR TITLE
Reduce severity for errors with datastore in downloader and retry doInstall on errors from volumeRef

### PR DESCRIPTION
**Pull request by giggsoff**
I can see `Get(zedagent/DatastoreConfig) unknown key` errors from time to time in logs and more important inside info (and in turn in states on cloud side). It comes from concurrence between DatastoreConfig subscribe and ContentTreeConfig on volumemgr side and between Downloader/Resolver Config and DatastoreConfig in downloader. Eventually this error gone (if we have all datastores in place), but the error can confuse user.
In this PR I add small delay in Downloader/Resolver/ContentTree configs (3 seconds for new batch of configs) to give a time for all needed entities to be processed and reduce probability of errors.

### CODE REVIEW

**Review by rvs — APPROVED** [review]
I guess I am fine with this, @eriknordmark ?

**Review by eriknordmark — COMMENTED** [review]
@petr-zededa I know we see this issue in testing when we provisioning a new device and immediately give it a full config (app instance, datastore, volume, etc).
Do we see it in other cases such as provisioning a new volume??

I'm concerned the fix is unnessarily complex to handle that case.
To handle that case I think it should be sufficient to make the downloader.Run first wait for at least one DatastoreConfig in a separate select loop before it goes into the main select loop.

**Comment by giggsoff** [comment]
> @petr-zededa I know we see this issue in testing when we provisioning a new device and immediately give it a full config (app instance, datastore, volume, etc). Do we see it in other cases such as provisioning a new volume??
> 
> I'm concerned the fix is unnessarily complex to handle that case. To handle that case I think it should be sufficient to make the downloader.Run first wait for at least one DatastoreConfig in a separate select loop before it goes into the main select loop.

We can hit it for any new combination of datastore and contentTree. And it may come anytime, not only with the first config. Moreover we want to show error for example in case of no datastore in config (broken controller, why not), so we cannot make any separate datastore waiting.

**Comment by eriknordmark** [comment]
> We can hit it for any new combination of datastore and contentTree. And it may come anytime, not only with the first config. Moreover we want to show error for example in case of no datastore in config (broken controller, why not), so we cannot make any separate datastore waiting.

But delaying for 3  seconds isn't going to be sufficient in all such cases. System might be very busy running and logging for lots of app instances, downloading other stuff, etc.

If what we want to do is delay the error until X seconds/minutes have passed since we received a contenttree referencing a datastore which does not exist, why don't we set the severity based on how long time since we received the contenttree? That way it can be info initially, then after a minute become a warning or error?

**Comment by giggsoff** [comment]
> But delaying for 3 seconds isn't going to be sufficient in all such cases. System might be very busy running and logging for lots of app instances, downloading other stuff, etc.

Good point. What I try to mitigate is to not hit such errors consistently (From inside of volumemgr and downloader itself regardless of any load. Also I hope we try to keep our agents main loop clean of any long-term jobs spreading them into async workers). 

> If what we want to do is delay the error until X seconds/minutes have passed since we received a contenttree referencing a datastore which does not exist, why don't we set the severity based on how long time since we received the contenttree? That way it can be info initially, then after a minute become a warning or error?

I add commit to reduce severity for error in downloader. But in general all errors regardless of severity indicates as errors. I mean it is not only the error in the log, but also the error in the info message (to be send to the user).

**Pull request merged**
