### PR TITLE
eden.yml: checkout Eden 0.9.13

### PR DESCRIPTION
**Pull request by europaul**
This is a change forgotten in #4381.

### CODE REVIEW

**Review by deitch — APPROVED** [review]

**Comment by europaul** [comment]
I thought might as well amend right away, since @OhmSpectator is quick to hit that merge button this evening :smile:

**Comment by OhmSpectator** [comment]
`git rebase origin/master -s` ...

**Comment by OhmSpectator** [comment]
I desperately need this commit 🥹🥹🥹

**Comment by europaul** [comment]
ofc, sorry. lessons learned: never use github.dev, even for small fixes :smile:

**Comment by yash-zededa** [comment]
@europaul just need the commit to be signed. Also the Lint Commit Messages action is failing. Can we add some more description like pointing to the new version with debug enable ?

**Review by yash-zededa — APPROVED** [review]

**Comment by OhmSpectator** [comment]
🥳🥳🥳

**Pull request merged**
