### PR TITLE
[11.0-stable] backport: Make newlogd keep the original msg text and fields

### PR DESCRIPTION
**Pull request by europaul**

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
I see that eden tests are failing due to references to #cloud-config i.e., the tests assume that this support is present in 11.0-stable, which it doesn't seem to be. Are we referring to the wrong version/tag of the eden tests?

**Comment by europaul** [comment]
> I see that eden tests are failing due to references to #cloud-config i.e., the tests assume that this support is present in 11.0-stable, which it doesn't seem to be. Are we referring to the wrong version/tag of the eden tests?

Thank you for noticing this @eriknordmark! Although the Eden version is set correctly to use the workflow from release 0.9.2, it still checks out the repository (including test files) from the latest master. I'm gonna look into this and present a fix, but this will probably have nothing to do with this PR.

**Comment by eriknordmark** [comment]
> Thank you for noticing this @eriknordmark! Although the Eden version is set correctly to use the workflow from release 0.9.2, it still checks out the repository (including test files) from the latest master. I'm gonna look into this and present a fix, but this will probably have nothing to do with this PR.

I wonder if there is some fluke because the PR with the idential backport to 10.4-stable didn't trip on this.
I'll re-run eden once it has all failed.

**Comment by europaul** [comment]
> > Thank you for noticing this @eriknordmark! Although the Eden version is set correctly to use the workflow from release 0.9.2, it still checks out the repository (including test files) from the latest master. I'm gonna look into this and present a fix, but this will probably have nothing to do with this PR.
> 
> I wonder if there is some fluke because the PR with the idential backport to 10.4-stable didn't trip on this. I'll re-run eden once it has all failed.

The workflow has changed in 11.0-stable to use the workflow from Eden which works like [this](https://github.com/actions/checkout/tree/v3/?tab=readme-ov-file#usage)
```
When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event. Otherwise, uses the default branch.
```

**Comment by eriknordmark** [comment]
> So since we trigger that workflow from outside it just uses the latest master.

Can you check with @uncleDecart if we can come up with a better scheme. He and Avi has just redone the Eden workflows in master and I don't know if that would help or hinder coming up with a scheme for running the correct version of the eden tests for a stable branch. In any case I suspect we will need a general solution to this for future LTS releases.

**Review by uncleDecart — APPROVED** [review]
Trying to re-trigger eden tests :magic_wand:

**Review by eriknordmark — APPROVED** [review]
Run eden

**Review by uncleDecart — APPROVED** [review]
Hadouken :fire: (running eden test)

**Review by uncleDecart — APPROVED** [review]
:runner: :runner: :runner:

**Pull request merged**
