### PR TITLE
nographic for container without vnc

### PR DESCRIPTION
**Pull request by giggsoff**
Remove graphic device for containers without vnc to reduce memory usage.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by rvs** [comment]
Hey @giggsoff -- you need to provide all the details above before/after memory usage, usage in steady state, etc.

**Comment by giggsoff** [comment]
[WIP] Also need to check this for kvm.

**Comment by giggsoff** [comment]
The same command to show output `ps -o rss,args`.
Xen. Before:
```
33m /usr/lib/xen/bin/qemu-system-i386 -xen-domid 1 -no-shutdown -chardev socket,id=libxl-cmd,path=/var/run/xen/qmp-libxl-1,server,nowait -mon chardev=libxl-cmd,mode=control -chardev socket,id=libxenstat-cmd,path=/var/run/xen/qmp-libxenstat-1,server,nowait -mon chardev=libxenstat-cmd,mode=control -nodefaults -no-user-config -name reverent_mclaren.3 -vnc none -display none -kernel /hostfs/boot/kernel -initrd /usr/lib/xen/boot/runx-initrd -append  root=9p-xen dhcp=1 -serial pty -device cirrus-vga,vgamem_mb=8 -boot order=dc -net none -machine xenfv -m 90
```
Xen. After:
```
31m /usr/lib/xen/bin/qemu-system-i386 -xen-domid 5 -no-shutdown -chardev socket,id=libxl-cmd,path=/var/run/xen/qmp-libxl-5,server,nowait -mon chardev=libxl-cmd,mode=control -chardev socket,id=libxenstat-cmd,path=/var/run/xen/qmp-libxenstat-5,server,nowait -mon chardev=libxenstat-cmd,mode=control -nodefaults -no-user-config -name reverent_mclaren.3 -vnc none -display none -kernel /hostfs/boot/kernel -initrd /usr/lib/xen/boot/runx-initrd -append  root=9p-xen dhcp=1 -serial pty -nographic -boot order=dc -net none -machine xenfv -m 98
```
KVM. Before:
```
248m /usr/lib/xen/bin/qemu-system-x86_64 -display none -S -no-user-config -nodefaults -no-shutdown -overcommit mem-lock=on -overcommit cpu-pm=on -serial chardev:charserial0 -no-hpet -name reverent_mclaren.3 -readconfig /var/run/domainmgr/xen/xen3.cfg -pidfile /var/run/hypervisor/kvm/reverent_mclaren.3/pid
```
KVM. After:
```
228m /usr/lib/xen/bin/qemu-system-x86_64 -display none -S -no-user-config -nodefaults -no-shutdown -overcommit mem-lock=on -overcommit cpu-pm=on -serial chardev:charserial0 -no-hpet -name reverent_mclaren.3 -readconfig /var/run/domainmgr/xen/xen3.cfg -pidfile /var/run/hypervisor/kvm/reverent_mclaren.3/pid
```

**Comment by rvs** [comment]
Honestly -- looking at this it seems that Xen savings are a bit underwhelming -- so purely for Xen it seems like a wash. For KVM the savings are much more visible (which is not surprising since we're allocating 16M for video RAM).

Hence, my proposal @giggsoff will be for you guys to try and see what's the minimum size of VGA you can allocate (in terms of resolution, etc.) so that the overhead is around a few Mb.

Makes sense?

**Review by rvs — APPROVED** [review]
LGTM

**Review by rvs — CHANGES_REQUESTED** [review]
Hey @giggsoff -- can you please rebase this on the latest master? With testing improving, I think it is time for us to start pulling some of those older PRs.

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
