### PR TITLE
update most of azure to use newer library

### PR DESCRIPTION
**Pull request by deitch**
The azure sdk for go we are using is deprecated. It hurt us specifically in that retries are not built into downloads.

This updates `libs/zedUpload` such that most of azure storage uses the newer SDK. It gets everything except for 3 upload functions, which should be gotten later. This includes the built-in retries.

Once this is in, we would need to update `pkg/pillar` to use the latest `github.com/libs/zedUpload` 

cc @naiming-zededa

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
What type of testing have we done on this?
I think there are some private tests around (which include the credentials for Azure hence can't be open sourced)

**Comment by eriknordmark** [comment]
Also, would it make sense to do the vendor into pkg/pillar as part of the same PR so we can have the various EVE tests use the new code?

**Comment by deitch** [comment]
> What type of testing have we done on this?

Nothing substantial. I had built a private standalone program to determine the underlying issues with our download, then fixed it and tested it. If someone can give me credentials for an Azure storage account via DM, I can do some more extensive testing on it.

> I think there are some private tests around (which include the credentials for Azure hence can't be open sourced)

Can you kick those off?

**Comment by deitch** [comment]
> Also, would it make sense to do the vendor into pkg/pillar as part of the same PR so we can have the various EVE tests use the new code?

It is a bit difficult to do. `pkg/pillar` views it as a completely different library. It might be easier to do it in 2 stages.

**Comment by deitch** [comment]
BTW, I managed to get a few more of the functions converted. The only remaining ones are `UploadBlockListToBlob()` and `UploadPartByChunk()`. Those in turn are used by:

```go
	case SysOpPutPart:
		err = ep.processAzureUploadByChunks(req)
	case SysOpCompleteParts:
		err = ep.processPutBlockListIntoBlob(req)
```

Do we still need those?

**Comment by deitch** [comment]
OK, I managed to get the deprecated library out entirely. I _really_ want another pair of eyes on this, as well as those private tests you mentioned @eriknordmark .

**Comment by eriknordmark** [comment]
> BTW, I managed to get a few more of the functions converted. The only remaining ones are `UploadBlockListToBlob()` and `UploadPartByChunk()`. Those in turn are used by:
> 
> ```go
> 	case SysOpPutPart:
> 		err = ep.processAzureUploadByChunks(req)
> 	case SysOpCompleteParts:
> 		err = ep.processPutBlockListIntoBlob(req)
> ```
> 
> Do we still need those?

Yes, because zedUpload is also vendored into the Zededa commercial controller and it uses the upload parts.

**Comment by deitch** [comment]
> Yes, because zedUpload is also vendored into the Zededa commercial controller and it uses the upload parts.

No problem. I managed to figure it out anyways. I do not have an Azure account to even begin to test it though.

**Comment by giggsoff** [comment]
> > Also, would it make sense to do the vendor into pkg/pillar as part of the same PR so we can have the various EVE tests use the new code?
> 
> It is a bit difficult to do. `pkg/pillar` views it as a completely different library. It might be easier to do it in 2 stages.

What the problem you can see here? You can run `make proto-vendor` and add files to git.

**Comment by deitch** [comment]
Thanks for sharing the tests @eriknordmark ; they all pass now. I had to make some tweaks, so good thing it caught them.

**Review by eriknordmark — COMMENTED** [review]
LGTM

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by deitch** [comment]
@eriknordmark I would hold off on merging these into pillar. @naiming-zededa found some performance issues. Functionally, everything works, but performance-wise, I am trying to replicate his issue. I will either open a new one, or comment here that it is good.

**Comment by deitch** [comment]
Interesting. I did a run on a Linux node in AWS. Without delay, the two of them (deprecated and new) run pretty close to the same. With an artificial 1500ms outbound delay on each packet introduced by `tc`, I get the following over many minutes:

* deprecated: settles down to ~0.60 MB/s before eventually timing out with the known reset issue that this fixes
* new: settles down to ~0.40 MB/s (but of course does not time out)

I am not sure what this is, but deserves deeper inspection.

**Pull request merged**
