### PR TITLE
Introducing read-write grub.cfg on CONFIG partition

### PR DESCRIPTION
**Pull request by rvs**
This allows us to have grub.cfg on the CONFIG partition that can be used to store tweaks to the boot process that are specific to either a given device or a series of devices (since you can put grub.cfg into the configuration partition of the installer).

The motivation here is that we already have one instance where we need to pass different tweaks to Xen on different boxes and these tweaks are not compatible between the boxes (IOW, settings that are OK for one box will hang the 2nd one and vice versa).

The downside here seems to be small enough - since we're always guaranteed to have a CONFIG partition on the device, there doesn't seem to be a way to hijack that search command to read from something else but device's own CONFIG partition.

### CODE REVIEW

**Comment by rvs** [comment]
Hey @gianlzed -- can you please take a look as well?

**Comment by glguida** [comment]
> Hey @gianlzed -- can you please take a look as well?

if you mean @glguida yes :)

**Comment by deitch** [comment]
It took me a bit to figure out what this is doing. It looks like you aren't directly sourcing `grub.cfg` off of the `/config` partition, but rather still keeping the same initial `grub.cfg` baked in, but with the ability for it to search in the config partition for `/config/grub.cfg` and source it as overrides?

That makes sense. I do have a few questions:

* Can we document this flow somewhere in the docs? 
* What are the security implications? Beforehand, the `grub.cfg` was baked in on an immutable image on an immutable filesystem. Now it can be overridden at will on a read-write partition. There are things to be considered here, or, at the very least, documented openly.

**Comment by glguida** [comment]
> * What are the security implications? Beforehand, the `grub.cfg` was baked in on an immutable image on an immutable filesystem. Now it can be overridden at will on a read-write partition. There are things to be considered here, or, at the very least, documented openly.

I think that this is a valid concern, but the config mutation can be a much bigger problem in general for an EVE system. While this can cause a system not to boot, in general any modification to config can easily render the system unreachable, so I guess it's a wider problem of EVE.

I am not really an expert on what's living on the config/ partition, and if there's a discussion/review on what lives in config/ and why, I'd like to be part of it.

**Comment by rvs** [comment]
Hey @nordmark @gianlzed @deitch 

> Would it be useful to add a doc/ file which gives an example of how this can be used to set some option?

Great idea -- in fact, let me rejiggle our top-level CONFIG.md to start with a section on /config partition. I'll include this part there as well.

> What are the security implications

This is, of course, my biggest obsession here. Hence wanting to have as many eyes on this as possible. On one hand it feels that we're now relaxing the constraints of read-only grub.cfg that is baked into the IMGA and IMGB partitions. On the other hand I don't think it opens up any additional attack vectors since the trampoline grub.cfg (the one in UEFI partition) is already read-write and easily accessible by any potential attacker.

Makes sense?

I'll wait a day more, provide documentation and plan to merge it tomorrow unless anybody has any additional concerns.

**Comment by deitch** [comment]
> Great idea -- in fact, let me rejiggle our top-level CONFIG.md to start with a section on /config partition. I'll include this part there as well.

That is a great idea. I assume you didn't get to it yet? I want to have a chance to take a look.

> On one hand it feels that we're now relaxing the constraints of read-only grub.cfg that is baked into the IMGA and IMGB partitions. On the other hand I don't think it opens up any additional attack vectors since the trampoline grub.cfg (the one in UEFI partition) is already read-write and easily accessible by any potential attacker

That is a fair point. Well, is UEFI read-write? Why is that? I get that from the firmware's perspective it is r/w, but we easily could insist on it being read-only and validate it (tpm PCRs or even our own hashing algorithms) to validate that it has not changed.

Maybe a description of the current boot process with diagrams (you know that I love those) and the proposed one? 

There is a part of me that wants to keep it immutable, and have a file in `/config` that allows the changing of certain parameters, almost like a key-value file, in config if we need it, something like `.tfvars`. The more realistic part of me realizes that is more security theatre. It will have enough that you can override a lot anyways and make it complexity without value.

I think the bigger question is do we want to allow it at all? In other words, is EVE's model not one of "it gets baked at the factory or install (which we know can be an expensive truck roll), if you want to change it, wipe it clean and reinstall, which is how you protect the device: make it immutable except for approved apps running on it."

Does this not violate that concept? What is the use case for these per-device "tweaks"?

**Comment by rvs** [comment]
Hey @gianlzed @eriknordmark and @deitch -- as per your requests I finally updated the docs and provided sample configs under /conf.

To answer @deitch question:

> I think the bigger question is do we want to allow it at all? In other words, is EVE's model not one of "it gets baked at the factory or install (which we know can be an expensive truck roll), if you want to change it, wipe it clean and reinstall, which is how you protect the device: make it immutable except for approved apps running on it."

I think we should allow it under these very conditions. IOW, the content of CONFIG partition (including grub.cfg) gets baked during the install phase and from that point on is treated as read-only. As for UEFI partition we can enforce it via various measurements that can be further validated. None of it contradicts what this PR brings to the table -- but all of it will have to be implemented once we get to it ;-)

**Pull request merged**
