### PR TITLE
sync eden tests and use docker image of Eden

### PR DESCRIPTION
**Pull request by giggsoff**
sync eden tests (empty volumes, VLAN test) and use docker image of Eden instead of building

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by giggsoff** [comment]
Sorry, missed some files to add into commit. Now they are inside.

**Review by eriknordmark — APPROVED** [review]
Run eden again

**Comment by rvs** [comment]
LGTM

**Pull request merged**
