### PR TITLE
generate proto related go/python/vendor files

### PR DESCRIPTION
**Pull request by naiming-zededa**
Signed-off-by: Naiming Shen <naiming@zededa.com>
- need this before submit newlog changes in zedcloud and eve
- used Avi's Makefile change to generate those files
- bringing the proto auto generated files up to date

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
So as part of this PR you verified that Avi's PR works? Or did I misunderstand?

**Comment by deitch** [comment]
So can we merge that one in?

**Comment by naiming-zededa** [comment]
> So as part of this PR you verified that Avi's PR works? 
yes, i patched in Avi's diff, it works. So yes I have verified his patch.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
