### PR TITLE
WIP [RFC]: ACRN boot

### PR DESCRIPTION
**Pull request by glguida**
This is just a request for comment. It would allow master, after we get Jack patches merged, to build basic ACRN-based EVE images if HV=acrn is passed to makefile.

Still very temporary, but ready enough to discuss the approach.

There are only two commits of interest here:  9eb4317 and 
4b3efff

The first one creates per-hypervisor (rather than grub-specific) grub.cfg, the other massages the makefile and the build system.

### CODE REVIEW

**Comment by deitch** [comment]
First of all, I like the approach overall. Explicitly picking your hypervisor with `make HV=<hypervisor>` is good and clean. I have minor nits with it, e.g. 

```makefile
ROOTFS_YML_xen=images/rootfs.yml
ROOTFS_YML_acrn=images/acrn-rootfs.yml
```

Why should `rootfs.yml` be the Xen one, while the named one is for `acrn`? I find it confusing. Let's have explicit for all hypervisors, i.e. 

```makefile
ROOTFS_YML_xen=images/xen-rootfs.yml
ROOTFS_YML_acrn=images/acrn-rootfs.yml
```

The fact that we pick one over the other is a function of the defined `HV` value, and the fact that xen is the default is just a function of the Makefile.

That having been said, can we flip it to `rootfs-xen.yml` and `rootfs-acrn.yml`, to make it easier on humans? This way they all group together in `ls`` or a Finder/Explorer window. 

Similarly, we probably should have `pkg/kernel-acrn/` and `pkg/kernel-xen.` Make them easy to see.

Ideally, we would have one `pkg/kernel/` with build information that can handle either, but if those are too far apart, we can keep them separate, but let's make them equal first-class citizens.

Nice work!

In the same vein,

**Comment by glguida** [comment]
Avi, thanks for your comments!

Yes renaming files to something more sensible was definitely outside the scope of the RFC. Probably even HV should be changed to something more esplicative.

As for kernel I think we should insist that pig/kernel is the generic one, and the ACRN one is the special.

Changing names and moving files around would’ve complicated the patch and distracted from the mechanism, so I didn’t do that here.

**Comment by deitch** [comment]
> should insist that pig/kernel is the generic one

Not for me; I am Jewish, so no pig. I could do `pkg/kernel` though. :-)

(got to love auto-correct....)

**Comment by deitch** [comment]
> Yes renaming files to something more sensible was definitely outside the scope of the RFC. 

Yeah, I might have delved too deeply into your implementation rather than concept.

> Probably even HV should be changed to something more esplicative.

Nah, I like `HV`. Using the full `HYPERVISOR` would be way too long. It was a good choice.

> As for kernel I think we should insist that pkg/kernel is the generic one, and the ACRN one is the special.

That implies a lot about the expected value of xen vs acrn. If we are positive that the main focus is xen, and acrn is an additional, then sure. If we might do other things, or acrn is first-class citizen here and fully supported, then we should have unbiased naming conventions.

It really isn't about naming; it is about long-term focus and support.

**Comment by glguida** [comment]
> > should insist that pig/kernel is the generic one
> 
> Not for me; I am Jewish, so no pig. I could do `pkg/kernel` though. :-)
> 
> (got to love auto-correct....)

Yes, my phone is somehow biased toward animals. It’s really insisting that I should talk about ducks all the time, for some mysterious reason!

**Comment by deitch** [comment]
My daughter loves animals; she will want your phone. 😃

**Comment by glguida** [comment]
> > Yes renaming files to something more sensible was definitely outside the scope of the RFC.
> 
> Yeah, I might have delved too deeply into your implementation rather than concept.
> 
> > Probably even HV should be changed to something more esplicative.
> 
> Nah, I like `HV`. Using the full `HYPERVISOR` would be way too long. It was a good choice.
> 
> > As for kernel I think we should insist that pkg/kernel is the generic one, and the ACRN one is the special.
> 
> That implies a lot about the expected value of xen vs acrn. If we are positive that the main focus is xen, and acrn is an additional, then sure. If we might do other things, or acrn is first-class citizen here and fully supported, then we should have unbiased naming conventions.
> 
No, no, that’s not what’s happening. Pkg/kernel is essentially a vanilla kernel, has the xen bits turned on but can be booted without it, too. It is in this sense a generic one and not tied to Xen.

Suppose we want to enable KVM, we could do that in pkg/kernel without problems.

The ACRN kernel is a special branch, released by acrn, with the explicit need to be used in ACRN. Xen used to be the same way for a very long time, requiring a special kernel form dom0.
In this sense the acrn kernel is acrn specific.

> It really isn't about naming; it is about long-term focus and support.
 Yes, it is about long term. In the long term I’d like to use the same kernel for both hypervisors.

**Comment by deitch** [comment]
> No, no, that’s not what’s happening. Pkg/kernel is essentially a vanilla kernel, has the xen bits turned on but can be booted without it, too. It is in this sense a generic one and not tied to Xen.

> Suppose we want to enable KVM, we could do that in pkg/kernel without problems.

yeah, that makes sense. OK, thanks for clarifying.

**Comment by rvs** [comment]
Hey @glguida -- now that I merged #303 and #315 can you please rebases this PR on the latest master?

Also, would it make more sense to actually keep grub.cfg where it is and simply override it for ACRN via /config/grub.cfg ?

**Comment by glguida** [comment]
> Also, would it make more sense to actually keep grub.cfg where it is and simply override it for ACRN via /config/grub.cfg ?

Rather than using /config, I am actually creating a /EFI/BOOT/grub-hv.cfg override. This is because as opposed to /config it should be really a static configuration -- and also without it horrible things would happen because Xen is not present.

I'll am about to rebase and test one last time before sending the PR, so we can continue the discussion there.

**Pull request closed without merging**
