### PR TITLE
Propagate PRs onto 6.8

### PR DESCRIPTION
**Pull request by giggsoff**
To resolve issue with large volume creation, we are forced to put PRs #2153 and #2151 onto 6.8 branch.

### CODE REVIEW

**Review by zededa-yuri — APPROVED** [review]
looks good to me

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by rvs** [comment]
Is there a need to do 6.8.1 release? If so who's asking for it @giggsoff ?

**Comment by giggsoff** [comment]
> Is there a need to do 6.8.1 release? If so who's asking for it @giggsoff ?

It was Vijay Subramanian. He want to use it for profiles demo. But actually, I am waiting for his testing of this additions in master.

**Comment by rvs** [comment]
Cool -- keep me posted on when 6.8.1 needs to be cut @giggsoff

**Pull request merged**
