### PR TITLE
hybrid mbr rework

### PR DESCRIPTION
**Pull request by giggsoff**
Put config and inventory partitions onto hybrid MBR to be available from Windows

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by zededa-yuri — COMMENTED** [review]
Sounds awesome!

But could you explain what you actually did here?

**Comment by zededa-yuri** [comment]
> And from Windows we cannot access others. I put config and inventory partitions onto MBR (if they are defined).

Still feels a bit like a hack to me. Maybe it is better to fix our GPT that Windows can access it? Of course ancient versions from 10 years ago do not support MBR, but I guess that's ok.

**Comment by giggsoff** [comment]
> > And from Windows we cannot access others. I put config and inventory partitions onto MBR (if they are defined).
> 
> Still feels a bit like a hack to me. Maybe it is better to fix our GPT that Windows can access it? Of course ancient versions from 10 years ago do not support MBR, but I guess that's ok.

Our GPT works well, but we are forced to use hybrid MBR to support old BIOS hardware.

**Comment by zededa-yuri** [comment]
Ah, sorry the misunderstanding. We already doing hybrids for some other use-cases. Fine then. 

But it would be great to explain in the commit message why you are doing this in the commit message. And the line you put in the PR 
```
Put config and inventory partitions onto hybrid MBR to be available from Windows
```
deserves to be the header of the commit

**Comment by Insei** [comment]
Tested on rpi4, no problems were found.

**Comment by rvs** [comment]
Thanks @Insei -- the problem is older devices -- I need to do a few test runs before this can be merged in.

**Review by eriknordmark — COMMENTED** [review]
LGTM but I'd like @rvs to take a look.

**Comment by rvs** [comment]
Closing this in favor of #2300

**Pull request closed without merging**
