### PR TITLE
allow airgapped switch network instances

### PR DESCRIPTION
**Pull request by eriknordmark**
Somehow this had fallen off the truck; used to work a while back.

### CODE REVIEW

**Review by rvs — APPROVED** [review]
Would be great to add Eden test for this so that it doesn't fall off the truck again. @sadov @giggsoff any thoughts on this?

Other than that -- LGTM

**Comment by sadov** [comment]
@rvs @nordmark how may look such test?

**Comment by rvs** [comment]
I think all you need to do @sadov is to create an Eden config according to the specification that this PR addressed -- you can also take a look at the commercial controller and what configs it creates when asked for an airgapped switch network.

**Comment by giggsoff** [comment]
I added 'none' type of uplink into https://github.com/lf-edge/eden/pull/593, so, will wait for merge.
@rvs do we have any plan of tagged version of EVE (with this commit) to update it inside Eden?

**Comment by rvs** [comment]
> do we have any plan of tagged version of EVE (with this commit) to update it inside Eden?

well, this is in master -- hence getting released on the next train (6.5.0) that is expected to happen tomorrow @giggsoff

**Pull request merged**
