### PR TITLE
[WIP] bump edge-containers to support baseos-in-oci

### PR DESCRIPTION
**Pull request by deitch**
This PR will be the final baseos-in-OCI images PR.

I say, "will be", because it almost works, but I wanted the PR open so people can look at it.

"Almost works", as it installs correctly but doesn't actually reboot, working on it.

There is nearly a thousand files changed, but they are all just versions of dependencies in `vendor/`. Only three changes matter:

* `pkg/pillar/cmd/volumemgr/create.go`: just changed a pass-by-value to pass-by-reference
* `pkg/pillar/zboot/zboot.go`: just changed a pass-by-value to pass-by-reference
* latest versions of lf-edge/edge-containers and its dependency deislabs/oras

### CODE REVIEW

**Comment by deitch** [comment]
Yetus failed, but Actions doesn't show the single (or few) lines of failure anywhere.

**Comment by deitch** [comment]
This works!

**Comment by deitch** [comment]
I am going to leave this as `[WIP]` until we can get a test in on it (assuming that we already test image upgrade). Does someone know where/how that test is, and I can add this one?

**Review by eriknordmark — APPROVED** [review]
LGTM

I assume the vendor updates are driven by the new containerd etc code.
Testing will show if a new logrus version etc causes issues anywhere.

**Comment by eriknordmark** [comment]
@deitch maybe there are too many files for yetus to be able to do the annotations? Can you grep for the two files you changed in the artifacts which yetus lets you download?

**Comment by deitch** [comment]
> maybe there are too many files for yetus to be able to do the annotations? Can you grep for the two files you changed in the artifacts which yetus lets you download?

I managed to download it, everything is in `patch-revive-result.txt`. It complains about all of the functions on `zboot.go`. Pain to fix them now, but I will get it done.

```
pkg/pillar/zboot/zboot.go:47:1: comment on exported function Reset should be of the form "Reset ..." https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:109:1: exported function SetCurpart should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:113:1: comment on exported function GetCurrentPartition should be of the form "GetCurrentPartition ..." https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:130:1: exported function GetOtherPartition should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:163:1: exported function IsCurrentPartition should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:169:1: exported function IsOtherPartition should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:175:1: comment on exported function GetPartitionState should be of the form "GetPartitionState ..." https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:188:1: exported function IsPartitionState should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:215:1: exported function GetPartitionDevname should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:245:1: comment on exported function IsCurrentPartitionStateActive should be of the form "IsCurrentPartitionStateActive ..." https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:251:1: exported function IsCurrentPartitionStateInProgress should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:256:1: exported function IsCurrentPartitionStateUpdating should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:261:1: comment on exported function IsOtherPartitionStateActive should be of the form "IsOtherPartitionStateActive ..." https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:267:1: exported function IsOtherPartitionStateInProgress should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:272:1: exported function IsOtherPartitionStateUnused should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:277:1: exported function IsOtherPartitionStateUpdating should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:303:1: exported function SetOtherPartitionStateUpdating should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:308:1: exported function SetOtherPartitionStateUnused should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:313:1: exported function GetCurrentPartitionDevName should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:318:1: exported function GetOtherPartitionDevName should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:323:1: exported function WriteToPartition should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:392:1: comment on exported function MarkCurrentPartitionStateActive should be of the form "MarkCurrentPartitionStateActive ..." https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:433:1: exported function GetShortVersion should have comment or be unexported https://revive.run/r#exported
pkg/pillar/zboot/zboot.go:438:1: comment on exported function GetLongVersion should be of the form "GetLongVersion ..." https://revive.run/r#exported
```

**Comment by deitch** [comment]
Fixed everything

**Comment by rvs** [comment]
> Fixed everything

Yoda man @deitch -- 10x so much!!!

**Review by rvs — APPROVED** [review]
LGTM. Now @deitch -- can you also please create and Eden test for this? (obviously a separate PR going into Eden itself). @giggsoff and @sadov can help with the logistics.

**Comment by deitch** [comment]
> can you also please create and Eden test for this?

Definitely. I am going to open an issue on Eden to track it.

**Comment by deitch** [comment]
Sigh, yetus again. Patched (I hope)

**Comment by deitch** [comment]
I fixed the yetus issues, maybe I just don't know how to read the files?

**Comment by deitch** [comment]
@rvs should we get this in? I can deal with the eden issue linked separately.

**Comment by rvs** [comment]
Yup -- lets get this in. We can watchout for the fallout (if any) on master

**Pull request merged**
