### PR TITLE
An OCI image with repeated shas results in in duplicate MaybeRemoveVerifierImage

### PR DESCRIPTION
**Pull request by eriknordmark**
@giggsoff running the eden tests as specified in #1472 now passes

The key fix in the first commit.
The dual refcount is also something we could hit in theory.

The other commits are related to the journey to get here - including some unit tests which I assume will run in jenkins (can't run on the laptop due to permissions).

### CODE REVIEW

**Comment by giggsoff** [comment]
Hi, @eriknordmark. Unfortunately, the error still exists (actually, I try your commit on top of master (5b1d0b24)).
And again modification like this solves my problem:
```
diff --git a/pkg/pillar/cmd/volumemgr/updatestatus.go b/pkg/pillar/cmd/volumemgr/updatestatus.go
index 42468f5e7..73f498165 100644
--- a/pkg/pillar/cmd/volumemgr/updatestatus.go
+++ b/pkg/pillar/cmd/volumemgr/updatestatus.go
@@ -341,8 +341,8 @@ func doUpdateContentTree(ctx *volumemgrContext, status *types.ContentTreeStatus)
                }
 
                leftToProcess := 0
-               blobStatuses := lookupBlobStatuses(ctx, status.Blobs...)
-               for _, blob := range blobStatuses {
+               for _, blobSHA := range status.Blobs {
+                       blob := lookupBlobStatus(ctx, blobSHA)
                        // if the blob was not yet loaded, we ignore it
                        if blob.State != types.LOADED {
                                log.Infof("doUpdateContentTree(%s): blob %s not yet loaded", status.Key(), blob.Sha256)

```
Maybe we have some duplicates inside `status.Blobs`?

**Comment by giggsoff** [comment]
As I can see, I have the same sha in layers of the problem image (two last layers):
```
docker image inspect itmoeve/phoronix-test:1.0 -f '{{.RootFS.Layers}}'
[sha256:2ce3c188c38d7ad46d2df5e6af7e7aed846bc3321bdd89706d5262fefd6a3390 sha256:ad44aa179b334bbf4aeb61ecef978c3c77a3bb27cb28bcb727f5566d7f085b31 sha256:35a91a75d24be7ff9c68ce618dcc933f89fef502a59becac8510dbc3bf7a4a05 sha256:a4399aeb9a0e1ddf9da712ef222fd66f707a8c7205ed2607c9c8aac0dbabe882 sha256:d2724bb7095247911d9921cad00dc96f87ee3f6ee9239cdad266563d0acdeeb3 sha256:bc560da3effb94f7583920a0a0d518fc4262eacb81a1ee83c15d39a83ac05e56 sha256:bc560da3effb94f7583920a0a0d518fc4262eacb81a1ee83c15d39a83ac05e56]
```
and it depends on [this line](https://github.com/itmo-eve/eden/blob/83e6688586c873feae6b9fca4e9a427418bc1cc5/tests/phoronix/image/Dockerfile#L15) which actually do nothing...

**Comment by eriknordmark** [comment]
> As I can see, I have the same sha in layers of the problem image (two last layers):

@giggsoff 
That is supposed to work; the sha will be repeated in the contentTreeStatus->Blobs and each one of them gets a refcount.
But clearly from the logs the refcount on the verifier does go to 2.

I've been fixing the logs around pubsub today so I can make more sense of the logs.Let's see what I find once I finish fighting with docker content trust in the EVE build

**Review by rvs — COMMENTED** [review]
LGTM and major, MAJOR props for the unit tests @eriknordmark !

**Pull request merged**
