### PR TITLE
collect-info.sh: Added /persist Directory Listing to Debug Script.

### PR DESCRIPTION
**Pull request by OhmSpectator**
Updated collect-info.sh to include a detailed listing of the /persist directory for enhanced debugging information.

### CODE REVIEW

**Review by rouming — APPROVED** [review]
Please update the version number in the script.

**Review by rene — APPROVED** [review]
LGTM

**Comment by OhmSpectator** [comment]
> Please update the version number in the script.

done

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
