### PR TITLE
Without lisp rules that computed packet checksums are no longer requi…

### PR DESCRIPTION
**Pull request by gkodali-zededa**
…red.

Signed-off-by: Gopi krishna Kodali <gkodali@zededa.com>

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
LGTM.

Did you run this through the integration tests aka eveimagecheck?

**Comment by gkodali-zededa** [comment]
> LGTM.
> 
> Did you run this through the integration tests aka eveimagecheck?

I did not run automated test. I tested network connectivity with one container and one vm.
Will run the smoke test on my image.

**Review by rvs — APPROVED** [review]
LGTM. @gkodali-zededa -- you sure the Xen side of it was only for LISP benefit? I thought we had some other reason -- but my recollection is vague.

**Comment by gkodali-zededa** [comment]
@nordmark The following tests passed with my image.

16:36:03  ------------- PASSED TESTS --------------------------------
16:36:03  
16:36:03  1.  test_oneapp  --appname=nginxbundle --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:07:59.056782
16:36:03  2.  test_oneapp  --appname=znginx --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:08:17.653573
16:36:03  3.  test_oneapp  --appname=alpine-vol-check --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:12:21.152832
16:36:03  4.  test_oneapp  --appname=ubuntu-bionic-18.04v2 --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:20:21.099430
16:36:03  5.  test_network_instance  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:00:08.017334
16:36:03  6.  test_app_upgrade  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:09:09.946426
16:36:03  7.  test_azure_iotedge  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:01:35.309174
16:36:03  8.  test_cloud_init  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:01:30.596905
16:36:03  9.  test_device_status  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:06:41.940799
16:36:03  10.  test_acls  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:24:21.584434
16:36:03  11.  test_baseos  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:28:25.238988
16:36:03  12.  test_app_nat  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:05:47.6873812020-09-04 11:05:58,308 - ztest-run - DEBUG - Main Loop: Done running Tests
16:36:03  
16:36:03  13.  test_app_switch  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:06:00.264920
16:36:03  14.  test_app_assigned_usb  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:05:01.087642
16:36:03  15.  test_app_purge_bad  --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:04:07.435982
16:36:03  16.  test_multiapps  --appname=zcliContainer --appname=ubuntu-xenial-16.04 --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:21:34.001174
16:36:03  17.  test_multiapps  --appname=zcliContainer --appname=nginxbundle --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:14:14.768493
16:36:03  18.  test_multiapps  --appname=ubuntu-bionic-18.04v2 --appname=ubuntu-xenial-16.04 --no-pdb-on-failure --user=ztest@acme.com --password=Admin@1234 --influx-host-port=8086 --image=0.0.0-bridge-gr-8b43cc2d-dirty-2020-09-02.07.39-xen-amd64 --loglevel=debug --device=colfax-sm300-gw5
16:36:03           duration: 0:30:07.172071

**Comment by gkodali-zededa** [comment]
> LGTM. @gkodali-zededa -- you sure the Xen side of it was only for LISP benefit? I thought we had some other reason -- but my recollection is vague.

@rvs As far as I can remember, @nordmark added the xen nic optimizations related configurations, checksum rules for lisp. I saw app traffic flowing through fine with my image that has this code removed.

**Pull request merged**
