### PR TITLE
eden tests sync

### PR DESCRIPTION
**Pull request by petr-zededa**
Sync of Eden tests.
New tests inside:

1. Update eve image from oci
2. ACL test with particular host access to
3. Port forward test with NAT hairpin

Signed-off-by: Petr Fedchenkov <petr@zededa.com>

### CODE REVIEW

**Comment by petr-zededa** [comment]
Seems, we have [problems](https://github.com/lf-edge/eve/actions/runs/677860266) for now with reverting to "snapshot" version.

**Review by rvs — APPROVED** [review]
LGTM, but @giggsoff -- can you please come up with some kind of a plan so we can stop doing these syncs and treat EVE as the single source of truth for test scripts at least?

**Comment by zed-sadov** [comment]
@rvs it seems that such a transition could seriously complicate and slow down the development of EDEN&EDEN tests:
https://github.com/lf-edge/eve/pull/1970#issuecomment-795232049
At least at the present time when the harmonization of the EDEN tests and the ztests is carried out.

**Review by rvs — APPROVED** [review]
let it test

**Comment by sadov** [comment]
The new OCI image update mechanism seems to be not very stable. In my tests, I got 13 unsuccessful runs versus 2 successful ones with a diagnostics like this:
```
swList:{partitionLabel:"IMGB"  partitionDevice:"/dev/sda3"  partitionState:"unused"  status:DELIVERED  shortVersion:"6.0.0-kvm-amd64"  swErr:{description:"installDownloadedObject(6cbe57aa-22f6-44ff-9a06-c87b27596502): InstallWorkResult error, exception while installing: error pulling 6cbe57aa-22f6-44ff-9a06-c87b27596502-lfedge/eve@sha256:62bcf1010248b7565d4b0a0b19253e40c3d4bc2c9695758037ac60c469dbc528 from containerd: image \"6cbe57aa-22f6-44ff-9a06-c87b27596502-lfedge/eve@sha256:62bcf1010248b7565d4b0a0b19253e40c3d4bc2c9695758037ac60c469dbc528\": not found" timestamp:{seconds:1616511407  nanos:778871834}}  downloadProgress:100  userStatus:FAILED}
```

**Comment by deitch** [comment]
> The new OCI image update mechanism seems to be not very stable. In my tests, I got 13 unsuccessful runs versus 2 successful ones with a diagnostics like this:

I would like us to figure that out and ensure it is 100% stable. Do we have a lot more logs than that?

**Comment by sadov** [comment]
> I would like us to figure that out and ensure it is 100% stable. Do we have a lot more logs than that?

Yes, sure – one of EDEN test log and info obtained during the test:
[info.003.log](https://github.com/lf-edge/eve/files/6203559/info.003.log)
[update_eve_image_oci.003.log](https://github.com/lf-edge/eve/files/6203561/update_eve_image_oci.003.log)

**Comment by deitch** [comment]
@sadov I have gone through those logs with a finetooth comb. I cannot see why it would have shown fail.

Have we ever successfully gotten it to fail on a device (or qemu), or something we can exec into?

If you look at the important lines of [info.003.log](https://github.com/lf-edge/eve/files/6203559/info.003.log), you see:

* L1028: the download is marked as DELIVERED, which means it should be in containerd, timestamp is seconds:1616413859  nanos:998366668
* L1088: the error you cited above, `installDownloadedObject(a81dcac1-c321-4a96-a13f-b8a266476965): InstallWorkResult error, exception while installing: error pulling a81dcac1-c321-4a96-a13f-b8a266476965-lfedge/eve@sha256:62bcf1010248b7565d4b0a0b19253e40c3d4bc2c9695758037ac60c469dbc528 from containerd: image \"a81dcac1-c321-4a96-a13f-b8a266476965-lfedge/eve@sha256:62bcf1010248b7565d4b0a0b19253e40c3d4bc2c9695758037ac60c469dbc528\": not found"`. timestamp is seconds:1616413860  nanos:310615130

Clearly the latter happens almost 0.5 seconds after the former, so it _should_ work.

If you say it happens sometimes, but not all the time, I suspect a timing issue. As far as I know, containerd doesn't return with the image created until it is, well, created. So perhaps we send the signal back from volumemgr too soon?

I really would like to be able to recreate this with lots of debug logging, including on containerd.

**Comment by deitch** [comment]
Actually, at this point, I would be happy with a failure on a device with log set to debug or trace.

**Comment by petr-zededa** [comment]
The [last attempt](https://github.com/lf-edge/eve/pull/1986/checks?check_run_id=2190947945) to do image update from oci failed with timeout, but I see inside artifacts, that we miss couple of minutes to be success (image had inprogress state).
But in logs I see `createContentTreeStatus(cd272e56-a064-4dee-9130-cefdbdf46bda): datastoreConfig for 95d31193-5fb1-43a2-88bc-0428ffc9a611 not found lookupDatastoreConfig(95d31193-5fb1-43a2-88bc-0428ffc9a611) error: Get(zedagent/DatastoreConfig) unknown key 95d31193-5fb1-43a2-88bc-0428ffc9a611`. If I correctly understand, this results in a delayed retry (and may be the cause of timeout).

**Comment by zed-sadov** [comment]
> Actually, at this point, I would be happy with a failure on a device with log set to debug or trace.

Sounds like a suggestion for improving the test. @deitch  please describe what steps needs to take to get such logs that you need. Perhaps such improved diagnostics will be useful as an automatically triggered failure script and for other tests. With such an improved test, one could simply run it in a loop and analyze the failures.

**Comment by petr-zededa** [comment]
I add `#eden-test` inside approval message body as a trigger for run tests with debug log level.

**Comment by deitch** [comment]
> Sounds like a suggestion for improving the test. @deitch please describe what steps needs to take to get such logs that you need. Perhaps such improved diagnostics will be useful as an automatically triggered failure script and for other tests. With such an improved test, one could simply run it in a loop and analyze the failures.

I like that idea. When I run tests manually, and I am recreating a failure, I just do

```
eden controller edge-node update --config debug.default.remote.loglevel=trace
eden controller edge-node update --config debug.default.loglevel=trace
```

and then I have the maximum logs

**Comment by zed-sadov** [comment]
> I like that idea. When I run tests manually, and I am recreating a failure, I just do
> 
> ```
> eden controller edge-node update --config debug.default.remote.loglevel=trace
> eden controller edge-node update --config debug.default.loglevel=trace
> ```
> 
> and then I have the maximum logs

In this case, do we just need to put these commands at the beginning of the script, or do we need to do this before onboarding?

**Comment by deitch** [comment]
I don't think they work before onboarding. In any case, I run them right before the start of a process that leads to a failed test, e.g. right before running `eveimage-update`.

**Comment by sadov** [comment]
> I don't think they work before onboarding. In any case, I run them right before the start of a process that leads to a failed test, e.g. right before running `eveimage-update`.

@giggsoff what do you think about adding such diagnostics to your test (maybe with toggling some kind of env. variable)?

**Comment by giggsoff** [comment]
Maybe I miss something, but what about https://github.com/lf-edge/eve/pull/1986#issuecomment-807630480? In case of failure during first attempt, we can add `#eden-debug` to new review and run tests with debugging.

**Comment by deitch** [comment]
@zed-sadov @giggsoff can we open a new tracking issue for the "sometimes OCI fails with the specific error"? Please upload the log files you shared with me in Slack. We just need the large one.

I have made some headway, but I don't want to pollute this issue with the details of resolving that one.

**Comment by zed-sadov** [comment]
Seems good - 5 update_eve_image_oci tests passed.

**Comment by deitch** [comment]
Thanks!

**Comment by petr-zededa** [comment]
Well, so now we know the problem of oci test and seems, that it get round by changes on Eden side. And upcoming edits will allow us to bypass it in the future.
Any another suggestions after our long conversation here?

**Review by rvs — APPROVED** [review]
The only question I have left @petr-zededa is when do you want to merge this? ;-) In fact, let me kick tests off once again.

**Comment by petr-zededa** [comment]
They have been removed inside https://github.com/lf-edge/eden/pull/568

**Comment by rvs** [comment]
> They have been removed inside lf-edge/eden#568

Ok, I'm confused now @petr-zededa -- are you saying that this PR can now be closed?

**Comment by petr-zededa** [comment]
> Ok, I'm confused now @petr-zededa -- are you saying that this PR can now be closed?

My apologies. I sent a comment to the wrong thread.

**Pull request merged**
