### PR TITLE
extract more info for reboot reason and separate reboot stack

### PR DESCRIPTION
**Pull request by eriknordmark**
Signed-off-by: eriknordmark <erik@zededa.com>

### CODE REVIEW

**Comment by rvs** [comment]
Hey @nordmark I need to take a bit of a closer look here, ok?

**Comment by eriknordmark** [comment]
@rvs Looks like there are some odd yetus and build failures.
Yetus shows "Artifact not found"
build fails in a vendor arm directory; are we building for arm or is that a red herring?

**Comment by rvs** [comment]
We are not yet building on ARM @nordmark -- not sure what that is all about

**Comment by rvs** [comment]
LGTM

**Pull request merged**
