### PR TITLE
Update all pending agents after pubsub enhancement

### PR DESCRIPTION
**Pull request by archishou**

### CODE REVIEW

**Comment by archishou** [comment]
@eriknordmark Build seems to be failing because
`cmd/baseosmgr/baseosmgr.go:463:13: status.MissingDatastore undefined (type types.BaseOsStatus has no field or method MissingDatastore)
`
but I don't remember changing anything that has to do with that. Are those changes from a previous commit that I didn't merge correctly or something else?

**Comment by eriknordmark** [comment]
> @eriknordmark Build seems to be failing because
> `cmd/baseosmgr/baseosmgr.go:463:13: status.MissingDatastore undefined (type types.BaseOsStatus has no field or method MissingDatastore) `
> but I don't remember changing anything that has to do with that. Are those changes from a previous commit that I didn't merge correctly or something else?

That must be because of a mismerge at your end. Srinibas removed the MissingDatastore booleans since they are no longer needed.

**Comment by eriknordmark** [comment]
@archishou  If you look at the diffs you'll see that they are different than the diffs you had for the original PR, which you closed.

**Comment by archishou** [comment]
I'm confused as to why there are conflicts, I completed a merge to the latest version of the repo locally and ran into no conflicts. 

I did the following:
Added the needed commits to the update-agents branch
Then checked out my master branch
Updated my master branch to reflect the latest version 
Checkout the update-agents branch
Merged the master branch into update-agents

After merging there were no conflicts

What am I missing here?

**Comment by archishou** [comment]
@rvs take a look when you can please

**Comment by eriknordmark** [comment]
@archishou If you can resolve the conflicts I will pull this.

**Comment by rvs** [comment]
Hey @archishou at this point the easiest way is to: pull the diff of your existing PR by downloading https://github.com/lf-edge/eve/pull/181.diff

Try to apply it on the current master, fix any kind of conflicts and finally submit a brand new PR. 

Don't waste your time trying to fix this one.

**Comment by archishou** [comment]
I did that in the new PR. No conflicts. I'm so confused

**Pull request closed without merging**
