### PR TITLE
sync Eden tests

### PR DESCRIPTION
**Pull request by giggsoff**
issue eve epoch to receive info
run GCP with vTPM
use google-github-actions/auth with deprecation of service_account_key
rework background tests to break sequence on error

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by giggsoff** [comment]
Observing artifacts inside failed test gives me:
1. EVE was rebooted (during creating of container's volume)
2. we get "unexpected end of json" in this case after reboot
3. Eden did not catch the reboot
will work on that items.

**Review by eriknordmark — APPROVED** [review]
Run eden

**Review by rvs — COMMENTED** [review]
LGTM

**Pull request merged**
