### PR TITLE
Update go to 1.18.5

### PR DESCRIPTION
**Pull request by giggsoff**
In order to upgrade go to version 1.18.5 we should bundle it into eve-alpine.
This PR contains two commits:

1. Bundling go 1.18.5 from Alpine 3.16
2. Update packages to use go 1.18.5

### CODE REVIEW

**Comment by deitch** [comment]
I get the second part. The first part has me confused. I think you are trying to get the go 1.18.x bundled apk from alpine packages, but since we use alpine 3.15, while apk only has go 1.18.x bundled with alpine 3.16, we are forcibly adding the apk 3.16 repository so we can get go 1.18.

Then everything downstream (second part) can just `apk add go` (well, use `eve-deploy-alpine.sh` to do the same thing).

That makes sense.

Here is what I don't understand:

1. Is there a reason not to just upgrade our alpine base to 3.16 and get go 1.18 without the fancy repo shenanigans?
2. Why do we need the `ALPINE_VERSION` var? Is that to enable different packages to use different bases? Is that a good idea, or can we just eliminate it by having everyone use the same version?
3. I know you didn't change it here, but I cannot figure out [these 2 lines](https://github.com/lf-edge/eve/pull/2762/files#diff-7c1ec7307689e5c17d29680d48109312c8a7e58c323b5e2af2c4b9dcd994ac18R1-R2) from `pkg/eve/Dockerfile`:

```dockerfile
ARG EVE_BUILDER_IMAGE=lfedge/eve-alpine:6.7.0
FROM ${EVE_BUILDER_IMAGE} AS cache
```

This Dockerfile is the source to `lfedge/eve-alpine`; isn't it circular to rely on itself? What is the source?

**Comment by giggsoff** [comment]
> 1. Is there a reason not to just upgrade our alpine base to 3.16 and get go 1.18 without the fancy repo shenanigans?

I tried to describe the problem here in the last paragraph: https://github.com/lf-edge/eve/pull/2758#discussion_r943262538. In general, do we really want to update all packages if we will decide to pick only few ones from the new release? Why to not be more precise?

> 2. Why do we need the `ALPINE_VERSION` var? Is that to enable different packages to use different bases? Is that a good idea, or can we just eliminate it by having everyone use the same version?

Is you question about variable inside `eve-alpine-deploy.sh`? If so, I found the variable here and it fits my needs to cache another mirror with go package and use that mirror to install go version I need.

> 3. I know you didn't change it here, but I cannot figure out [these 2 lines](https://github.com/lf-edge/eve/pull/2762/files#diff-7c1ec7307689e5c17d29680d48109312c8a7e58c323b5e2af2c4b9dcd994ac18R1-R2) from `pkg/eve/Dockerfile`:
> 
> ```dockerfile
> ARG EVE_BUILDER_IMAGE=lfedge/eve-alpine:6.7.0
> FROM ${EVE_BUILDER_IMAGE} AS cache
> ```
> 
> This Dockerfile is the source to `lfedge/eve-alpine`; isn't it circular to rely on itself? What is the source?

It seems we have an open Issue from you about circular reference: https://github.com/lf-edge/eve/issues/2087
Let me describe my understanding here. The main goal solving by eve-alpine package is pinning of package versions. We want to re-use the same versions of packages regardless of updates on Alpine side. We have specific check to not override existing packages [here](https://github.com/lf-edge/eve/blob/157e774fe132c90ea353adb0f79cb9d561e487cb/pkg/alpine/build-cache.sh#L19-L22). But we need some kind of source to compare, we call it cache and it is just previous build of eve-alpine with packages bundled into. For sure, we can use for example `FROM alpine:3.16 as AS cache`, but it will have nothing in cache directory and will download all packages from Alpine which is not expected behavior.

**Comment by giggsoff** [comment]
Just to check what will happen, I [made](https://github.com/giggsoff/eve/pull/45) update of eve-alpine to 3.16 and start re-basing of another packages on top of 3.16 eve-alpine. I was _lucky_ to hit [the problem](https://github.com/giggsoff/eve/runs/7838243649?check_suite_focus=true#step:5:1593) with the first one I changed (pkg/acrn):
```
core/mevent.c: In function 'mevent_notify':
core/mevent.c:121:21: error: 'c' may be used uninitialized [-Werror=maybe-uninitialized]
  121 |                 if (write(mevent_pipefd[1], &c, 1) <= 0)
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from core/mevent.c:38:
/usr/include/unistd.h:51:9: note: by argument 2 of type 'const void *' to 'write' declared here
   51 | ssize_t write(int, const void *, size_t);
      |         ^~~~~
core/mevent.c:114:14: note: 'c' declared here
  114 |         char c;
      |              ^
cc1: all warnings being treated as errors
```
For this particular example it looks like some changes in gcc checks between 10.2.1 (Alpine 3.13) and 11.2.1 (Alpine 3.16) and I'm forced to make additional changes somewhere...
And unfortunately such problems will cover not only pkg/acrn. `pkg/uefi` also failed with `vla-parameter` warning (treated as error) in my experiments. Did not try other packages.

**Comment by eriknordmark** [comment]
> For this particular example it looks like some changes in gcc checks between 10.2.1 (Alpine 3.13) and 11.2.1 (Alpine 3.16) and I'm forced to make additional changes somewhere...

Which gcc version should we be using to compile the kernel? Are we getting that gcc from Alpine as well or the kernel build pulls in a specific gcc version?

**Comment by eriknordmark** [comment]
> I tried to describe the problem here in the last paragraph: [#2758 (comment)](https://github.com/lf-edge/eve/pull/2758#discussion_r943262538). In general, do we really want to update all packages if we will decide to pick only few ones from the new release? Why to not be more precise?

We might need to update other alpine packages as well, e.g., busybox to take care of some CVEs
If we start doing that we'll end up with a unique combination of package versions which would not be used by anybody else.

**Comment by giggsoff** [comment]
> Which gcc version should we be using to compile the kernel? Are we getting that gcc from Alpine as well or the kernel build pulls in a specific gcc version?

We use gcc bundled into eve-alpine (10.2.1 from Alpine 3.13 for now): https://github.com/lf-edge/eve/blob/157e774fe132c90ea353adb0f79cb9d561e487cb/pkg/kernel/kernel_config-5.10.x-x86_64#L5

**Comment by deitch** [comment]
> It seems we have an open Issue from you about circular reference: https://github.com/lf-edge/eve/issues/2087

I opened that a year ago? I completely forgot. Well, we never addressed it.

> We want to re-use the same versions of packages regardless of updates on Alpine side.

Almost, but not 100%. We do not want to re-use the same versions; we want to re-use the same bits. You might actually have meant that. What we are trying to prevent is not just this scenario:

1. Today on `alpine:3.16`, I run `apk add foo`; I get version 1.2.3
2. Tomorrow on `alpine:3.16` (unchanged), I run `apk add foo`; I get version 1.2.6 because the default version changed.

The above is bad, but we are worried about something even worse:

1. Today on `alpine:3.16`, I run `apk add foo`; I get version 1.2.3
2. Tomorrow on `alpine:3.16` (unchanged), I run `apk add foo`; I get version 1.2.3 _which has different bits_ because Alpine package maintainers rebuilt and reshipped 1.2.3 with different source.

The second is the harder problem.

**Comment by deitch** [comment]
> In general, do we really want to update all packages if we will decide to pick only few ones from the new release? Why to not be more precise?

I agree. What we really want is the following:

```dockerfile
FROM alpine:3.13
RUN apk fetch go@1.17.5
```

And maybe a different day do:

```dockerfile
FROM alpine:3.13
RUN apk fetch go@1.18.7
```

and then later:

```dockerfile
FROM alpine:3.16
RUN apk fetch go@1.18.7
```

We want to decouple _package_ versions from _alpine_ versions. I don't have to change my macOS version to change my golang version; why should I have to do that for Alpine? 

But Alpine just doesn't work that way. So I understand what you are trying to do.

My question is, are we stuck by the reality of Alpine? Will what we are doing dig us into a deeper hole of odd package maintainance? I guess as long as your solution works, we are OK.

Somewhat relatedly, why is the directory `mirrors/3.13`? 3.13?

**Comment by giggsoff** [comment]
> Just to check what will happen, I [made](https://github.com/giggsoff/eve/pull/45) update of eve-alpine to 3.16 and start re-basing of another packages on top of 3.16 eve-alpine. 

After additional investigation, I managed to build all packages, unfortunately diff is large and partially looks not as good as expected: https://github.com/lf-edge/eve/compare/master...itmo-eve:eve:alpine-3.16.
But seems we have another problem with riscv64 packages (with eve-alpine for riscv64), we have no packages for Alpine 3.16 on the resource defined here https://github.com/lf-edge/eve/blob/d8abba4a93344fb42f066dc912549a2412aec945/build-tools/src/scripts/Dockerfile.alpine.bootstrap#L17
[working](https://gitlab.alpinelinux.org/giggsoff/aports/-/commits/v3.16.2-riscv64) on compiling of Alpine 3.16 packages for riscv64 arch (as expected another pack of patches required here and there).

**Comment by zedi-pramodh** [comment]
@giggsoff do we need RISCV64 for now at least ?  Is it possible to just comment it out and not even include in the build ?

**Comment by deitch** [comment]
I don’t know that we have need. Even if we do, we shouldn’t hold up moving all of eve forward without any production dependency right now. But I could be wrong. I think @rvs knows about riscv here. 

If that is all that is broken, and everything else passes, it would be a good thing to move ahead. 

That having been said, I’m liking @giggsoff ’s viewpoint. We should be able to update alpine independently from the package versions.

**Comment by deitch** [comment]
@giggsoff how goes this? I am looking forward to seeing this in, but also seeing the independent usage of loading apk repos in the 3 `pkg/` Dockerfiles move to eve-alpine.

**Comment by giggsoff** [comment]
Closing in favor of #2780

**Pull request closed without merging**
