### PR TITLE
Use pcie-pci-bridge for the same iommu group

### PR DESCRIPTION
**Pull request by giggsoff**
I can see `qemu-system-x86_64:/run/domainmgr/xen/xen1.cfg:268: vfio 0000:00:14.5: group 5 used in multiple address spaces` when we try to pass multiple devices from the same iommu group into VM. Seems to resolve this problem we should move them behind the pcie-pci-bridge.

cc @mikem-zed

### CODE REVIEW

**Review by rvs — CHANGES_REQUESTED** [review]
Hm. I think I need a bit more problem description here. And also @mikem-zed to eyeball the change in PCI topology you're proposing here.

**Comment by mikem-zed** [comment]
> 

this is a pretty well know issue for multifunction devices. e.g this patch work for QEMU has pretty good explanation
https://patchwork.kernel.org/project/qemu-devel/patch/1505156192-18994-2-git-send-email-wexu@redhat.com/

one way to resove it is to place a device behind a pci-pci bridge so its address space become isolated from the rest of PCI bus

**Comment by eriknordmark** [comment]
> > 
> 
> UPDATE: we get errors like following trying to assign functions from one device to separate VMs (audio and video on NVIDIA card is a good example)
> 
> > vfio error: 0000:07:00.1: group 20 used in multiple address spaces
> 
> even though functions are placed into separate IOMMU groups they share the same address space on IOMMU
> 
> this is a pretty well know issue for multifunction devices. e.g this (not accepted) patch work for QEMU has pretty good explanation https://patchwork.kernel.org/project/qemu-devel/patch/1505156192-18994-2-git-send-email-wexu@redhat.com/
> 
> one way to resolve it is to place a device behind a pci-pci bridge so its address space become isolated from the rest of PCI bus

@mikem-zed is this sharing of address space something we can detect (from spec.sh or otherwise?)
Our fallback position is that the hardware model needs to be tested and if it turns out that some devices must be assigned together then the user can edit the model file manually. (but if we have a way to detect it even better.)

**Comment by mikem-zed** [comment]
Close this PR in favor of https://github.com/lf-edge/eve/pull/3369

**Pull request closed without merging**
