### PR TITLE
Bumping Xen to 4.15.0

### PR DESCRIPTION
**Pull request by rvs**
This is to get us testing on RCs of Xen 4.15.0 -- it is supposed to come out sometime in April 2021

### CODE REVIEW

**Review by lf-edge-eve — APPROVED** [review]
let it test. again.

**Review by lf-edge-eve — APPROVED** [review]
let it test some more

**Comment by eriknordmark** [comment]
@rvs the test results from April 1st look fine.
Is there something else needed to clear the WIP?

**Comment by rvs** [comment]
Yeah @eriknordmark -- I'm basically holding this off as a placeholder for a final 4.15 release (which should be a matter of a week or so now)

**Comment by rvs** [comment]
Xen 4.15.0 just got releases -- removing WIP tag from the PR and waiting for one more round of tests before pulling

**Review by lf-edge-eve — APPROVED** [review]
let it test

**Pull request merged**
