### PR TITLE
Refactoring of dependency checking during packages build

### PR DESCRIPTION
**Pull request by giggsoff**
When we want to build one package (for example pillar), we run `make pkg/pillar` and our expectation is that we will build pillar. But instead we build all dependencies as well, which is not required since we decided to not use templates and to embed dependencies versions directly into Dockerfile of package.
Let's move dependency checking  into `make pkgs` target where we want to build all packages automatically. This way we will speed up the build process (dramatically for the first run, noticeable for subsequent runs).
If we really need changes from another packages to build we should build the dependency explicitly (for example, using `make pkg/dom0-tools pkg/pillar`).

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by deitch** [comment]
I am trying to wrap my head around how this works.

Currently, as you described above, if I want to build `pkg/pillar`, it depends on other things (e.g. `pkg/strongswan`). So `make pkg/pillar` ensures that strongswan was built as well, so when it calls the Dockerfile for pillar, it finds it. This is make at its best, handling dependency management.

With the change here, if I `make pkg/pillar`, then strongswan will not be built.

* If strongswan was unchanged, that is fine; the Dockerfile will refer to something published and pull it down.
* If strongswan was changed, it will fail, since it is not published and cannot be found.

The current method prevents that issue. The price we pay is that it tries to build strongswan as well. But it doesn't build it `--force`, and with the changes to linuxkit you are bringing in (maybe brought in already?), that should be a near-zero-cost operation, as it sees it in registry and does not rebuild it or even pull it.

So what is it that makes this faster?

**Comment by giggsoff** [comment]
Building dependencies made sense when we had a Dockerfile template. But with https://github.com/lf-edge/eve/pull/2353 merged we have no templates. We unlinked versions and for example right now we have `FROM lfedge/eve-dom0-ztools:417d4ff6a57d2317c9e65166274b0ea6f6da16e2 as zfs` in pillar's Dockerfile, but `./build-tools/bin/linuxkit pkg show-tag pkg/dom0-ztools` indicates another tag (`lfedge/eve-dom0-ztools:f87a5e7357c37753a40252afd827166bd6407813`). So having `lfedge/eve-dom0-ztools:f87a5e7357c37753a40252afd827166bd6407813` built (or even pulled) does not make sense in case of building pillar.
Even if I will change something in `pkg/strongswan` (which is way more rare compare to pillar's changes) as you mentioned above, it will not affect `pkg/pillar` (as we do not use templates) directly.

I had no plan to remove `--force` flag. My expectation is to build pillar, when I run `make pkg/pillar`. I may have uncommitted changes/changes not in git while development. I just want to build the package. We can try to avoid usage of `--force` flag for dependencies, not for explicit intent to build. Will it make sense? It may solve the problem.

Few measurements on my PC (`time make pkg/pillar`) with changes from PR vs without:

1. after `docker rm -f --volumes linuxkit-builder&&rm -rf ~/.linuxkit`: 2m44,813s vs 9m15,422s
2. with change in go code (just one comment): 1m17,327s vs 2m10,048s
3. no changes in go code: 0m9,452s vs 0m44,811s

**Comment by giggsoff** [comment]
Opened another approach to reduce time with unset of `--force` flag for dependencies: https://github.com/lf-edge/eve/pull/2926. It is quite slower, but keep the dependency logic in place. 
cc @deitch

**Comment by deitch** [comment]
We were building all dependencies with `--force`? No wonder it took so long. I couldn't understand why it would take so much longer if nothing has changed.

I like the idea of "A depends on B, so we build B before building A." `make` was built for precisely this. But `make` also assumes that, if B hasn't changed, then don't rebuild it.

It seems to me like `--force` for all builds is very wasteful, so let's look at your #2926 first.

**Comment by giggsoff** [comment]
Let's close this and work on #2926

**Pull request closed without merging**
