### PR TITLE
Added new datastore types

### PR DESCRIPTION
**Pull request by prishabh**
1. For Azure blob datastore

### CODE REVIEW

**Comment by zed-rishabh** [comment]
> What's the difference between ZededaS3 and S3?

For ZededaS3 datastore type, we will not store credentials in the table. API keys and password will be read from the mustache file.

**Comment by rvs** [comment]
Hey @zed-rishabh I still don't understand why this needs to be propagated all the way to EVE's API. What you're describing sounds like a controller feature that has nothing to do with EVE.

**Comment by zed-rishabh** [comment]
> Hey @zed-rishabh I still don't understand why this needs to be propagated all the way to EVE's API. What you're describing sounds like a controller feature that has nothing to do with EVE.

Hey @rvs Removed separate datastore type for Zededa managed S3. We will handle it on the controller side. I updated the PR. Please take a look.

**Comment by zed-rishabh** [comment]
> Looks good. Do you have latest shared/zedupload already in EVE?

Yes.

**Comment by zed-rishabh** [comment]
> I think you need to add code in downloader.go to support DsAzureBlob, plus figure out some tests. Are you planning on doing that as part of this PR or a separate one?

We will do it in separate PR.

**Comment by zed-rishabh** [comment]
> > > I think you need to add code in downloader.go to support DsAzureBlob, plus figure out some tests. Are you planning on doing that as part of this PR or a separate one?
> > 
> > 
> > We will do it in separate PR.
> 
> Do you already have a tracker story for that?



> > > I think you need to add code in downloader.go to support DsAzureBlob, plus figure out some tests. Are you planning on doing that as part of this PR or a separate one?
> > 
> > 
> > We will do it in separate PR.
> 
> Do you already have a tracker story for that?

Added https://www.pivotaltracker.com/story/show/168131784.

**Pull request merged**
