### PR TITLE
Fix an issue in Edgeview not getting App interface IP address

### PR DESCRIPTION
**Pull request by naiming-zededa**
- backport ##4352
- due to the change of multiple port in zedrouter, the AppNetAdapterList.AllocatedIPv4Addr was changed to AssignedAddresses, do the same change

### CODE REVIEW

**Review by OhmSpectator — APPROVED** [review]
Looks like a 1-to-1 cherry-pick of the original commit

**Review by OhmSpectator — COMMENTED** [review]
@naiming-zededa, could you please cherry-pic commit like this?

```
git cherry-pick -x a54bfb3c0c119bc62e65b94c7a4deccc64c45a63
```

We don't need GH PR number in the commit message. And it's better to stick to the original one.

**Comment by OhmSpectator** [comment]
> ok, let me retry.


https://github.com/lf-edge/eve/blob/74e74ddeae9a1482658a7f7757c761bebccea68d/pkg/pillar/hypervisor/qmp.go#L30

(just kidding)

**Comment by naiming-zededa** [comment]
> > ok, let me retry.
> 
> https://github.com/lf-edge/eve/blob/74e74ddeae9a1482658a7f7757c761bebccea68d/pkg/pillar/hypervisor/qmp.go#L30
> 
> (just kidding)

Haha, but the above commands of hash does not seem to bring in the vendor files...

**Comment by OhmSpectator** [comment]
> Haha, but the above commands of hash does not seem to bring in the vendor files...

Sure, for the vendor file, you can try to cherry-pick 3769a4285101a6d0696499489f6de18f333b0443 or just rerun the command and create a new commit with the result.

**Pull request closed without merging**
