### PR TITLE
mini-yetus : Improve error reporting

### PR DESCRIPTION
**Pull request by shjala**
Improve error reporting in mini-yetus.sh script and don't exit if files doesn't exist. Instead, print an error message and continue. This can happen if the current branch is built on top of the source branch but source branch has diverged and some files are not present in the current branch. This changes allow the script to atleast run yetus on the files that do exist in the current branch.

### CODE REVIEW

**Review by OhmSpectator — APPROVED** [review]
Looks reasonable

**Comment by OhmSpectator** [comment]
@shjala, could you please rebase it on top of the master? I want to check how the fixes in workflow introduced in another PR behave...

**Comment by shjala** [comment]
> @shjala, could you please rebase it on top of the master? I want to check how the fixes in workflow introduced in another PR behave...

sure. What happened to eden? it is all red.

**Review by OhmSpectator — APPROVED** [review]
Let's run the tests once more... The change itself should not break the tests, but it will be useful to know that the tests are red.

**Comment by OhmSpectator** [comment]
@yash-zededa, any ideas about what happens with Eden tests on master?
```
make[2]: Entering directory '/home/runner/actions-runner/_work/eve/eve/eden/tests/workflow'
mkdir -p /home/runner/actions-runner/_work/eve/eve/eden/dist/tests/workflow/
/home/runner/actions-runner/_work/eve/eve/eden/dist/bin/eden-linux-amd64 utils template eden.workflow.tests.txt > workflow.default.txt
EDEN_TEST=small /home/runner/actions-runner/_work/eve/eve/eden/dist/bin/eden-linux-amd64 utils template eden.workflow.tests.txt > workflow.small.txt
EDEN_TEST=large /home/runner/actions-runner/_work/eve/eve/eden/dist/bin/eden-linux-amd64 utils template eden.workflow.tests.txt > workflow.large.txt
cp -a *.yml *.txt testdata /home/runner/actions-runner/_work/eve/eve/eden/dist/tests/workflow/
```

**Comment by yash-zededa** [comment]
> @yash-zededa, any ideas about what happens with Eden tests on master?
> 
> ```
> make[2]: Entering directory '/home/runner/actions-runner/_work/eve/eve/eden/tests/workflow'
> mkdir -p /home/runner/actions-runner/_work/eve/eve/eden/dist/tests/workflow/
> /home/runner/actions-runner/_work/eve/eve/eden/dist/bin/eden-linux-amd64 utils template eden.workflow.tests.txt > workflow.default.txt
> EDEN_TEST=small /home/runner/actions-runner/_work/eve/eve/eden/dist/bin/eden-linux-amd64 utils template eden.workflow.tests.txt > workflow.small.txt
> EDEN_TEST=large /home/runner/actions-runner/_work/eve/eve/eden/dist/bin/eden-linux-amd64 utils template eden.workflow.tests.txt > workflow.large.txt
> cp -a *.yml *.txt testdata /home/runner/actions-runner/_work/eve/eve/eden/dist/tests/workflow/
> ```
> 
> ```
> Run actions/download-artifact@v4
>   with:
>     github-token: ***
>     name: eve-kvm-amd64-generic
>     path: artifacts
>     merge-multiple: false
>     repository: lf-edge/eve
> Downloading single artifact
> Error: Unable to download artifact(s): Not Found
> ```

Found the issue raising PR to fix it.

**Review by eriknordmark — APPROVED** [review]
Try fixed  get run id.

**Comment by OhmSpectator** [comment]
Waiting for a runner to pick up this job... Already 1 hour... Looks suspicious.

**Comment by yash-zededa** [comment]
> Waiting for a runner to pick up this job... Already 1 hour... Looks suspicious.

Most of runners wer

**Comment by yash-zededa** [comment]
Sorry, closed by mistake.

@OhmSpectator the runners were occupied with the lf-edge master run. Few jobs are started now. 

The issue is fixed now.


```
Download artifact has finished successfully
Run docker load -q -i artifacts/eve-kvm-amd64-generic.tar
  docker load -q -i artifacts/eve-kvm-amd64-generic.tar
  docker image ls
 ```

**Review by OhmSpectator — APPROVED** [review]
Ok, the PR helped to fix another issue, thanks)

**Pull request merged**
