### PR TITLE
[WIP] volumes and garbage collection

### PR DESCRIPTION
**Pull request by eriknordmark**
Please review the commits separately @zed-rishabh @deitch 
1st is a missing piece of logic to ensure that we don't redownload but wait for a VerifyImageStatus. Needs to be carried into the CAS code
2nd is a minor log reduction (some app instances to tons of DNS lookups)
3rd was discovered when the CAS code is using the CurrentSize and TotalSize; they are swapped
4-6 is a sequence of pieces to 1) pupulate the PersistImageStatus in volumemgr based on content in /persist/*/verified 2) use that internally and as a way to tell verifier to delete an unused file 3) cleanup other GC mechanisms for verifier 4) simplify the downloader GC mechanism to be immediate

### CODE REVIEW

**Comment by deitch** [comment]
The currentSize/totalSize confusion had me laughing. Every time I touched it, I needed to look up which is which. Your solution - just use a normal name - makes so much sense.

**Comment by deitch** [comment]
If I understood the "do not redownload" code, this is the "async" format we discussed.

1. On startup, volumemgr scans all existing files, and creates a `PersistImageStatus` for each
2. verifier has a handler for `volumemgr/PersistImageStatus` which catches those, and in turn creates a `verifier/VerifyImageStatus`
3. When volumemgr runs:
    * if it finds a `VerifyImageStatus`, things work as normal (no change)
    * if it finds no `VerifyImageStatus` but yes `PersistImageStatus`, it waits for the `VerifyImageStatus` to exist, which triggers the handler
    * if it finds none of either, proceed and download (as current)

If I understood it correctly, this requires volumemgr to be aware of the directory of the verified files. We worked pretty hard in the recent past to eliminate that knowledge, so that verifier can place its final verified files anywhere it wants (under its sole control), and volumemgr just accepts whatever it gets in `VerifyImageStatus`.

Can we reverse it a bit? I think this would work equally well.

1. verifier, on startup, does the scan (since it alone knows where things are) and publishes `VerifyImageStatus` (as usual)
1. verifier, on completion of its scan, publishes a single `PersistImageComplete` that indicates it has completed its scan
1. volumemgr looks for `PersistImageComplete` (single item). If it finds none, it knows verifier has not completed its scan, so wait. If it finds one, scan complete, continue.
1. volumemgr looks for `verifier/VerifyImageStatus`, proceed as usual
1. volumemgr registers a handler for `verifier/PersistImageComplete`, to trigger all of its `doUpdateContentTree()` again, thus causing downloads that were held up before.

I don't mind writing this up, if it helps.

Thoughts?

**Comment by eriknordmark** [comment]
> * verifier has a handler for `volumemgr/PersistImageStatus` which catches those, and in turn creates a `verifier/VerifyImageStatus`

No, the verifier only tracks the PersistImnageStatus using a delete handler; the verifier deletes the verified file when the PersistImageStatus is unpublished by the volumemgr. Separately there is a VerifyImageConfig/Status exchange between the two. The only way the PersistImageStatus is used in that case is for the verifier to realize (by calling loolkupPersistImageStatus) that the file already exists hence it is done; no need to move from pending and do actual verification.

**Comment by eriknordmark** [comment]
> * if it finds a `VerifyImageStatus`, things work as normal (no change)

Note that "No change" includes volumemgr publishing a PersistImageStatus when it has received a VerifyImageStatus. That is necessary so that volumemgr can later delete that to cause volumemgr to delete the file.

**Comment by eriknordmark** [comment]
let me 1) split the minor things (like the size swap) in a separate PR 2) redo the GC one so we don't need any PersistImage* objects and have the verifier do the directory scan and publish the result as VerifyImageStatus with RefCount=0. Should be simpler.

**Comment by eriknordmark** [comment]
Replaced by PR1161

**Pull request closed without merging**
