### PR TITLE
alpine spice libraries

### PR DESCRIPTION
**Pull request by giggsoff**
Integration of `spice-dev` and `spice-server` and their dependencies into `eve-alpine`. We need them to build and use `qxl-vga` device in qemu.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by rvs** [comment]
And why do we need qxl-vga exactly?

**Comment by giggsoff** [comment]
> And why do we need qxl-vga exactly?

We need it to support dynamic resolution change inside Windows guests.

**Comment by rvs** [comment]
> We need it to support dynamic resolution change inside Windows guests.

And why is that needed all of a sudden? ;-)

**Comment by giggsoff** [comment]
Seems, 800x600 is not comfortable there

**Pull request closed without merging**
