### PR TITLE
GitHub Actions: build.yml: add platform parameter

### PR DESCRIPTION
**Pull request by uncleDecart**
This parameter allows us to build RT flavor of EVE and publish it as well as NVIDIA, Pollux and IMX flavours of EVE for ARM

### CODE REVIEW

**Comment by uncleDecart** [comment]
As per request by @rouming and @rene

**Review by rouming — APPROVED** [review]

**Comment by eriknordmark** [comment]
@uncleDecart for some reason the PR doesn't run the build workflow with these changes (hence get-run-id fails)

**Review by eriknordmark — CHANGES_REQUESTED** [review]
I see there are conflicts to resolve

**Comment by uncleDecart** [comment]
@rouming I added also platform to buildondemand action which we can invoke manually to try it out

**Review by rouming — APPROVED** [review]
Thanks!

**Review by eriknordmark — APPROVED** [review]
Try to approve, but I didn't see the build run from Roman's approval so it looks like the issue is still present.

**Comment by eriknordmark** [comment]
> Try to approve, but I didn't see the build run from Roman's approval so it looks like the issue is still present.

Yes, the build still does not produce output hence get run id fails.

**Review by eriknordmark — CHANGES_REQUESTED** [review]
Build works, but the eden pr workflow fails across the board with
Error: Unable to download artifact(s): Artifact not found for name: eve-kvm-amd64

**Review by eriknordmark — APPROVED** [review]
Try again

**Comment by uncleDecart** [comment]
Okay, we will have to change eve artefact name. On it...

**Comment by eriknordmark** [comment]
> Try again

And it failed with the same issue again:
Error: Unable to download artifact(s): Artifact not found for name: eve-kvm-amd64

@uncleDecart  I will politely ignore this PR until I get a positive confirmation that this issue has been fixed.

**Review by rouming — APPROVED** [review]

**Comment by uncleDecart** [comment]
@eriknordmark tests started to work, failures seems not related to changes in GitHub Actions. Image is pulled and tests are ran on the PR image.

**Comment by eriknordmark** [comment]
> @eriknordmark tests started to work, failures seems not related to changes in GitHub Actions. Image is pulled and tests are ran on the PR image.

Thanks. I'll merge this.

**Comment by uncleDecart** [comment]
Merge conflict with this PR https://github.com/lf-edge/eve/pull/4041. Eden should be bumped to 0.9.9 first and then this PR should be updated

**Pull request merged**
