### PR TITLE
pkg/fscrypt: bump up version v0.2.4 -> v0.3.4

### PR DESCRIPTION
**Pull request by rouming**
This patch bumps up fscrypt version from v0.2.4 to v0.3.4. There are two things done here:

1. Change fscrypt SHA in Dockerfile to the v0.3.4 tag
2. Adopt our local patches for the newest version of the fscrypt

From software engineering perspective this commit is rather boring (update package from older version to newer, we do this often, who cares) but motivation of this change goes far deeper. Here is the story.

Noticeable fscrypt evolution happened in version v0.2.6, where v2 policies began to be supported. A few lines from the fscrypt release notes related to the 0.2.6 version:

```
  The big feature in this release is support for v2 kernel encryption
  policies. With the release of Linux 5.4, the kernel added a
  [new type of policy](https://www.kernel.org/doc/html/latest/filesystems/fscrypt.html)
  that makes `fscrypt` much easier to use.  For directories using
  these new policies:

    [ cut ]

    * The policies are no longer tied to the buggy kernel keyring API.
        * This removes the need for users to run `keyctl link` or to
          reconfigure `pam_keyinit`.
        * Some systemd related bugs will no longer be an issue.
```

How is this change important to EVE? What does it fix?

On ext4 EVE unlocks /persist/vault folder (where all customer volumes and images are safely kept) utilizing old 0.2.4 version of fscrypt, so kernel keyring API was used (so called v1 policies).

Since /persist/vault folder was unlocked by the pillar proces from the pillar service container, kernel keyring was bound to that process and that mount namespace, not across the system. Very interesting side effect of this behaviour is that if a file exists in the inode cache, then file can be read by any process from any namespace, but if caches are empty, then process receives ENOKEY (132) "Required key not available" errno.

Short illustration of the problem:

```
 # eve enter debug
 # cat /persist/vault/volumes/177eafd2-0bdd-498a-9369-20531f6cd344\#0.container/ug > /dev/null
 # echo 2 > /proc/sys/vm/drop_caches
 # cat /persist/vault/volumes/177eafd2-0bdd-498a-9369-20531f6cd344\#0.container/ug > /dev/null
 cat: can't open '/persist/vault/volumes/177eafd2-0bdd-498a-9369-20531f6cd344#0.container/ug': Required key not available
```

The problem spreads even further: after cache eviction files can't be accessed from the shim VM as well:

```
 # touch /mnt/test
 touch: /mnt/test: Required key not available

 # cat /mnt/ug
 cat: can't open '/mnt/ug': Required key not available

```
Entering container from the shim VM also stops working, because required /mnt/entrypoint-pid file can't be created:

```
 # eve-enter-container
 Error: PID file '/mnt/entrypoint-pid' not found. Container did not start?

```
So the whole issue could eventually result in not only being unable to enter the container, but also causing the shim VM to crash if the inode cache on the host was evicted and the shim VM was rebooted.

Also same issue is observed on docker (worth reading!): 
https://github.com/google/fscrypt/issues/128

Switching to the new fs keyring (v2 policies, starting from v0.2.6 of the fscrypt) eliminates described problem and unlocks vault across the system.

### CODE REVIEW

**Comment by shjala** [comment]
Seem harmless to me if the following tests are passing : both successfully and unsuccessfully upgrade a node which has vault config and encrypted volumes to a EVE version that contains this changes.

**Comment by rouming** [comment]
> Seem harmless to me if the following tests are passing : both successfully and unsuccessfully upgrade a node which has vault config and encrypted volumes to a EVE version that contains this changes.

I've tested 2 cases:

1. Installed fresh EVE with policies v2 (newest fscrypt v0.3.4)
2. Upgrade from EVE with policies v1 (fscrypt v0.2.4) to the v2 (fscrypt v0.3.4)

These works. Did not test downgrade, which we do not officially support.

**Comment by shjala** [comment]
No downgrade, just fail the upgrade (like fail to pass attestation) and revert back to pre-upgrade version, just to be sure we don't leave any lasting effects from an failed upgrade (which we shouldn't with RO file system and no change to /config, just to be safe).

**Comment by rouming** [comment]
So what's tested:

1. Installed fresh EVE, fscrypt v0.2.4 (`zboot curpart` shows 'IMGA')
2. Upgraded to the rootfs with these commits, so fscrypt v0.3.4, created new file in vault just in case (`zboot curpart` shows 'IMGB')
3. Rebooted, which causes system to switch again to 'IMGA' (`zboot curpart` shows 'IMGA'). Vault unsealed, container has been started, all works.

JFYI But once v2 policies are used (freshly installed EVE with these commits), we can't switch back to the old fscypt, because compatibility in the tool is broken: the tool can't recognize metadata policies and complains. So downgrade won't be possible (which we don't support anyway!)

cc: @eriknordmark @shjala

**Comment by eriknordmark** [comment]
> JFYI But once v2 policies are used (freshly installed EVE with these commits), we can't switch back to the old fscypt, because compatibility in the tool is broken: the tool can't recognize metadata policies and complains. So downgrade won't be possible (which we don't support anyway!)

@rouming when would we start using v2 policies?

A customer might upgrade from EVE version 9.X to a future version on EVE-OS which has the new version of fscrypt and potentially also starts using v2 policies. Can we avoid using v2 policies while the EVE-OS image is in Testing state? Once we are past that state it will not fallback to the older image.

**Comment by rouming** [comment]
> > JFYI But once v2 policies are used (freshly installed EVE with these commits), we can't switch back to the old fscypt, because compatibility in the tool is broken: the tool can't recognize metadata policies and complains. So downgrade won't be possible (which we don't support anyway!)
> 
> @rouming when would we start using v2 policies?
> 
> A customer might upgrade from EVE version 9.X to a future version on EVE-OS which has the new version of fscrypt and potentially also starts using v2 policies. Can we avoid using v2 policies while the EVE-OS image is in Testing state? Once we are past that state it will not fallback to the older image.

Do we always unlock the vault on early pillar start?  Or unlock happens if first encrypted image is ready to be unlocked? 
The thing is that v1 policies created by the old version of fscrypt do no harm and will be used by the new fscrypt without any modifications (so we can swing in both directions from versions to versions). But policies generated by the new fscrypt  (even the v1 policy) is not backwards compatible with the old fscrypt (I checked that). That means, that if vault policies are created by the new version of fscrypt  - we are screwed. But if we always unlock vault on early start, that means that highly the v1 policies metadata are already in the ".fscrypt" folder, so failed upgrade should be safe.

**Comment by eriknordmark** [comment]
> Do we always unlock the vault on early pillar start? Or unlock happens if first encrypted image is ready to be unlocked? 

If no PCRs change then we can immediately unseal the key and unlock the vault. But that does not happen when there was an EVE-OS update.

In the update case we start doing the remote attestation and when that is accepted by the controller and we receive the encrypted escrowed key back, then we unlock the vault (and reseal the key under the new PCRs). We allow some minutes for this to handle short network outages, but in any case the device needs to reach the controller during the first 10 minutes otherwise if will assume there might be a network device driver problem in the new EVE-OS and fall back.

We don't start any app instances until the vault is unlocked.

> The thing is that v1 policies created by the old version of fscrypt do no harm and will be used by the new fscrypt without any modifications (so we can swing in both directions from versions to versions). But policies generated by the new fscrypt (even the v1 policy) is not backwards compatible with the old fscrypt (I checked that). That means, that if vault policies are created by the new version of fscrypt - we are screwed. But if we always unlock vault on early start, that means that highly the v1 policies metadata are already in the ".fscrypt" folder, so failed upgrade should be safe.

When would we create a v2 policy? As you say we will already have a v1 policy for /persist/vault. Does that mean we'd only create a v2 policy if we rm -rf /persist/vault; reboot?

**Comment by shjala** [comment]
What I meant by "avoiding lasting changes" is upgrade failing for some reason other than TPM after we upgrade to V2, if this case is possible we should move the vault upgrade to be the last stage of upgrade-test.

**Comment by rouming** [comment]
@eriknordmark 
> When would we create a v2 policy? As you say we will already have a v1 policy for /persist/vault. Does that mean we'd  only create a v2 policy if we rm -rf /persist/vault; reboot?

Correct, if vault was setup once (/persist/vault/.fscrypt folder was created and populated with metadata), then metadata won't be modified. So we create a v2 policy **only** if the vault was not setup before.

@shjala 
> What I meant by "avoiding lasting changes" is upgrade failing for some reason other than TPM after we upgrade to V2, if this case is possible we should move the vault upgrade to be the last stage of upgrade-test.

metadata in .fscrypt folder is not modified once created. So we should be all safe to use this metadata in the newest fscrypt version and then suddenly switch back to the old fscrypt.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by rouming** [comment]
Our Makefile (`make pkgs` in particular) does not respect any dependencies, so building of `pillar` happens earlier than `fscrypt`, but pillar depends on the fscrypt, so build fails. I split this PR on two: this one contains update of the fscrypt and should be merged first, so SHA will be known prior the pillar build.

**Pull request merged**
