### PR TITLE
Made makeusbconf work against /dev/ on Linux

### PR DESCRIPTION
**Pull request by eriknordmark**
@gianlzed @glguida so you see any issues with changing make-raw this way?

### CODE REVIEW

**Comment by rvs** [comment]
I am surprised @nordmark -- this time I actually tested it on a stand-alone physical Linux machine with a 8Gb stick and it worked very well.

What issues are you seeing?

**Comment by glguida** [comment]
I don’t see anything wrong with it, but I don’t really know what you’re trying to achieve nor what the problems with the previous usb conf were

**Comment by rvs** [comment]
Ping @nordmark any additional data on what problem you're seeing?

**Comment by rvs** [comment]
Another point @nordmark -- based on our email exchange -- can you please reduce this PR to just the PATH tweak and the doc change?

I'm fixing the other part separately (since it is not related to how we call sgdisk but the fact that it is now filtering the output).

**Comment by eriknordmark** [comment]
> Another point @nordmark -- based on our email exchange -- can you please reduce this PR to just the PATH tweak and the doc change?

Done

**Pull request merged**
