### PR TITLE
[WIP][EXPERIMENTAL] Upmerging xen-tools to xen 4.17.2

### PR DESCRIPTION
**Pull request by mikem-zed**
This is an experimental change and it is not expected to be merged. We can even move to 4.18 when it comes out. It has **QEMU 8.0.2**

- I had to build ninja from source since Alpine dropped as support for it in 3.8

FIXME:
- Rebase CPU pinning patches

Highlights:
- QEMU 7.0.0
- libgcc instead of musl

Looking at XEN release page  at https://downloads.xenproject.org/release/xen/ I would expect XEN 4.18.0 in December this year. It will contain 8.x.y QEMU version. FYI @OhmSpectator , @rouming

### CODE REVIEW

**Review by rouming — APPROVED** [review]
@OhmSpectator can help with merging his cpu pinning patches. In general we need the fresh qemu as well.

**Comment by OhmSpectator** [comment]
I also like the fact libgc is used here, not muscle. It would be useful, particularly for the CPU pinning feature.

**Comment by mikem-zed** [comment]
failing test is expected. I did not modify them so they expect stuff I've removed from the template

**Comment by OhmSpectator** [comment]
@christoph-zededa also mentioned the following changes:
```
./xen-tools/Dockerfile:ENV XEN_VERSION 4.15.0
./xen/Dockerfile:ENV XEN_VERSION 4.15.0
```

**Comment by mikem-zed** [comment]
I've switched to my personal GH account @rucoder and closing this PR in favor of https://github.com/lf-edge/eve/pull/3534

**Pull request closed without merging**
