### PR TITLE
Update eve api vendor and go mod files

### PR DESCRIPTION
**Pull request by zedi-pramodh**
Bump eve api after the PR https://github.com/lf-edge/eve-api/pull/65

### CODE REVIEW

**Review by naiming-zededa — COMMENTED** [review]
since Andrew is almost done w/ the eve-api change, maybe should wait for that.

**Comment by OhmSpectator** [comment]
@zedi-pramodh, could you please rebase on the latest master so the new GitHub workflow works correctly?

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by zedi-pramodh** [comment]
Amended the commit since eve-api changed again with PR
https://github.com/lf-edge/eve-api/pull/63

**Comment by zedi-pramodh** [comment]
> @zedi-pramodh, could you please rebase on the latest master so the new GitHub workflow works correctly?

I did rebase yesterday only :) things changed again !!

**Comment by zedi-pramodh** [comment]
> I did rebase yesterday only :) things changed again !!

Rebase done and amended the commit.

**Review by naiming-zededa — COMMENTED** [review]
LGTM

**Comment by OhmSpectator** [comment]
Fix the commit message, please =)
https://github.com/lf-edge/eve/actions/runs/10619453990/job/29437072620?pr=4181
Expect that, looks good =)

**Pull request merged**
