### PR TITLE
Fixed Proto files to import correctly

### PR DESCRIPTION
**Pull request by kalyan-nidumolu**
Currently, each proto file is compiled using its own directory ( -I <dir of proto file> ) as the base directory. This doesn't not allow definitions from other directories to be imported.

This change is to compile the protofiles with the "proto" directory as base. This allows filed from other sub-directories to be imported into one-another. 

Removed the 2 duplicated types ( PhyIpType and PhyIoUsage) in Info.proto and instead import them from config/devmodel.proto ( as is the original intention )

### CODE REVIEW

**Comment by kalyan-nidumolu** [comment]
Zedcloud changes will be done when we vendor the API into zedcloud. And that will happen when this merges up. I will take care of that too.

**Comment by kalyan-nidumolu** [comment]
> This is not urgent. Can be done 3 months from now.
> And zedcloud needs some amount of change, right?

Any reason for waiting for 3 months?

**Comment by rvs** [comment]
Conceptually this looks fine to me @kalyan-nidumolu -- I'd like to see why yetus protochecks failed tho (asked @aw-was-here). Also I'd like to understand whether there's a reason to delay it as @eriknordmark is pointing (personally I don't see any danger of committing it now -- but may be I'm missing something).

**Comment by aw-was-here** [comment]
Basically, Apache Yetus needs some fixes, in particular apache/yetus#105 and apache/yetus#107.  As soon as the next release happens (hopefully within a week or so), upgrading to that release and changing the appropriate settings on the command line should make this PR pass.

**Comment by kalyan-nidumolu** [comment]
Created proto/common - and moved the two common definitions there.. And both Config and info use those definitions. Please review..

**Comment by rvs** [comment]
This makes sense to me. @eriknordmark I think this can be merged. @zedvijay does this look reasonable on the controller side?

**Comment by zedvijay** [comment]
The diff itself is looks good. Can we try importing in zedcloud and see if it builds.

**Comment by kalyan-nidumolu** [comment]
> The diff itself is looks good. Can we try importing in zedcloud and see if it builds.

Zedcloud also needs changes - a Makefile change - and some code changes to account for data structure package changes ( common.PhyIoType Vs config.PhyIoType ) etc..

I had a hacked up set of changes previously to understand what needed to be changed in the makefile and I could make it compile..

**Comment by rvs** [comment]
> I had a hacked up set of changes previously to understand what needed to be changed in the makefile and I could make it compile..

Hey @kalyan-nidumolu can you please share that in a branch so we can take a look?

**Comment by kalyan-nidumolu** [comment]
I don't have it now.. deleted the branch..
It was a simple change to Makefile.proto-api. Am hacking it up again ..Will
raise a WIP-DO_NOT_MERGE PR for that..

Thanks,
Kalyan

**Comment by kalyan-nidumolu** [comment]
Merging up - Vijay is fine with the diffs too.

**Pull request merged**
