### PR TITLE
Zfs performance patches

### PR DESCRIPTION
**Pull request by zededa-yuri**
For the reference, these patches can be found in my [zfs fork](https://github.com/zededa-yuri/zfs/tree/2.1.2-smoothing-v3)

    Some of these patches are already in the upstream ZFS repo, others are
    in the process of getting there. We will remove at least some of these
    patches with the next release of ZFS.

    Patches significantly reduce the write amplification, therefore less
    data needs to be written, and fewer uneccessary syncs issued.

    Another feature introduced in the patches is write bandwidth smoothing
    algorithm which prevents huge latency spikes under the heavy load on
    the storage.

# Testing done

```
$ make HV=zfs-kvm pkg/kernel pkg/pillar pkg/storage-init live run

linuxkit-525400123456:~# cat /sys/module/zfs/parameters/zfs_smoothing_scale
50000
linuxkit-525400123456:~# cat /sys/module/zfs/parameters/zfs_smoothing_write
5
```

### CODE REVIEW

**Review by zedi-pramodh — APPROVED** [review]
LGTM,  except change the commit message where you are referring to XFS instead of ZFS.

**Comment by zededa-yuri** [comment]
> LGTM, except change the commit message where you are referring to XFS instead of ZFS.

Hah, that's a stupid typo :). Thanks for noticing

**Review by zedi-pramodh — APPROVED** [review]
LGTM

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
