### PR TITLE
[10.4 stable] Prevent deferred queue from growing

### PR DESCRIPTION
**Pull request by rouming**
Backport of the #4017 PR.

### CODE REVIEW

**Review by eriknordmark — CHANGES_REQUESTED** [review]
Good to have the PR reference in the descriptions.
But we should also have the original master commit in the commit messages.
(And if you do that with git cherry-pick -x I suspect that would have carried the DCO signature across as well.)

In any case, the DCO needs to be fixed.

**Comment by rouming** [comment]
> Good to have the PR reference in the descriptions.

Will add once master is merged, otherwise SHA may change.

**Comment by rouming** [comment]
> In any case, the DCO needs to be fixed.

Something already unfixable:

```
Commit sha: 6d2ae04, Author: eriknordmark, Committer: eriknordmark; The sign-off is missing.
```

**Comment by eriknordmark** [comment]
> > In any case, the DCO needs to be fixed.
> 
> Something already unfixable:
> 
> ```
> Commit sha: 6d2ae04, Author: eriknordmark, Committer: eriknordmark; The sign-off is missing.
> ```

FWIW that is bogus from more than one perspective:
1. The link which GH provides to that commit does not work
2. The actually commit is https://github.com/lf-edge/eve/commit/6d2ae048cd037bfe7229b3a6e21928e6f7f77cf1 which is not a commit added by this PR.

 I don't know what's broken in GH. Let's see  what happens when you update the commit descriptions if DCO still has issues.

**Pull request merged**
