### PR TITLE
bump to go 1.13.5

### PR DESCRIPTION
**Pull request by deitch**
It has much better output messages for module issues.

Have not had a chance to do a full build with this quite yet

### CODE REVIEW

**Comment by rvs** [comment]
Hey @deitch can we close this now?

**Comment by kalyan-nidumolu** [comment]
Why?? Not upgrading to 1.13.5 ??

Thanks,
Kalyan

**Comment by rvs** [comment]
Because there's absolutely no value in 1.13.x at this point and a lot of downside.

**Comment by rvs** [comment]
Because there's absolutely no value in 1.13.x at this point and a lot of downside @kalyan-nidumolu

**Pull request closed without merging**
