### PR TITLE
[9.4-stable] Add Support for Persistent OVMF Settings in Pillar

### PR DESCRIPTION
**Pull request by OhmSpectator**
Backport of https://github.com/lf-edge/eve/pull/4261.

A new version of #4269 , as the previous PR, targeted the 9.4-stable-EOS branch and prevented our workflows from being triggered (as the branch name had "-EOS" postfix).

### CODE REVIEW

**Comment by OhmSpectator** [comment]
I don't see this workflow running
https://github.com/lf-edge/eve/blob/9.4-stable/.github/workflows/danger.yml
Strange.

**Comment by OhmSpectator** [comment]
Maybe it's the problem. Found in the "PR build" workflow summary. 
```
[Deprecation notice: v1, v2, and v3 of the artifact actions](https://github.com/lf-edge/eve/actions/runs/10990471810/workflow)
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "eve-kvm-amd64", "eve-kvm-arm64", "eve-mini-riscv64", "eve-xen-amd64", "eve-xen-arm64".
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

**Comment by OhmSpectator** [comment]
@uncleDecart, @milan-zededa, could you recommend a quick fix here? I need the danger workflow to run to publish the artefact to dockerhub so that tests can use them...

**Comment by uncleDecart** [comment]
@OhmSpectator danger should've been triggered after successful PR build

**Comment by uncleDecart** [comment]
> Maybe it's the problem. Found in the "PR build" workflow summary.
> 
> ```
> [Deprecation notice: v1, v2, and v3 of the artifact actions](https://github.com/lf-edge/eve/actions/runs/10990471810/workflow)
> The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "eve-kvm-amd64", "eve-kvm-arm64", "eve-mini-riscv64", "eve-xen-amd64", "eve-xen-arm64".
> Please update your workflow to use v4 of the artifact actions.
> Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> ```

They were still uploaded, you can see them in artifacts on summary page in PR/Build action [here](https://github.com/lf-edge/eve/actions/runs/10990471810?pr=4276)

**Comment by uncleDecart** [comment]
And I don't see any workflows triggered [here](https://github.com/lf-edge/eve/actions?query=branch%3A9.4-stable)

**Comment by OhmSpectator** [comment]
@uncleDecart yep. I need to understand how to push artifacts into docker hub, so they are available by docker pull in another tool (ztest).

**Comment by uncleDecart** [comment]
> @uncleDecart yep. I need to understand how to push artifacts into docker hub, so they are available by docker pull in another tool (ztest).

Quickest fix I think would be to locally run `make eve` which will push containers to your local setup and then running ztest on that same machine will pull local container. In order to push artefacts into docker hub we will need credentials, so it's not a way to go. I'll check now the wfs...

**Comment by OhmSpectator** [comment]
> > @uncleDecart yep. I need to understand how to push artifacts into docker hub, so they are available by docker pull in another tool (ztest).
> 
> Quickest fix I think would be to locally run `make eve` which will push containers to your local setup and then running ztest on that same machine will pull local container. In order to push artefacts into docker hub we will need credentials, so it's not a way to go. I'll check now the wfs... 

My understanding is that the danger workflow push into dockerhub. But it's not called for some reason

**Comment by OhmSpectator** [comment]
It's just a matter of fact. The workflows are broken in 9.4. We cannot do our regular releases here.

**Comment by OhmSpectator** [comment]
@yash-zededa, could you help with this? We need assistance with GH Actions for the upcoming release after merging this PR. At the moment it looks like it will not work.

**Review by eriknordmark — APPROVED** [review]
Manually ran ztests on two devices overnight as a regression test since the workflows are not working well. Passed.

**Comment by yash-zededa** [comment]
@eriknordmark @OhmSpectator Are we expecting more releases for the 9.4 branch ? We can we can modify the Jenkins job to get the artefacts directly from github. I don't think it would be a direct approach but maybe we can figure out a way for this.

**Comment by OhmSpectator** [comment]
> @eriknordmark @OhmSpectator Are we expecting more releases for the 9.4 branch ? We can we can modify the Jenkins job to get the artefacts directly from github. I don't think it would be a direct approach but maybe we can figure out a way for this.

We need to create only one release. Exactly from the state now. Then we move it to EOS again. That's my understanding.

**Pull request merged**
