### PR TITLE
github workflow : add code coverage report

### PR DESCRIPTION
**Pull request by shjala**

### CODE REVIEW

**Comment by eriknordmark** [comment]
Should we merge this PR and see what reports it produces? It seems like it can't generate reports until it has a baseline to compare with.

**Comment by shjala** [comment]
@eriknordmark I think we should. Btw it reported some more detailed stats [here](https://app.codecov.io/gh/lf-edge/eve/commit/2ad24af03b8a37a609e805601e051008f24356ac/tree/pkg).

**Review by uncleDecart — APPROVED** [review]
LGTM,

We can also publish results and show them in GitHub's readme

**Review by OhmSpectator — COMMENTED** [review]
Wow, looks cool! =)
The only thing: when I click on the links added automatically, I do not see any details...
Meanwhile, the link you have provided in a comment looks fine.

**Comment by shjala** [comment]
> when I click on the links added automatically, I do not see any details... 

@OhmSpectator I think it is because it has no baseline to compare the current code coverage with, it needs at least one PR merged, then from next one it compare code coverage to parent which is top of master.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
