### PR TITLE
Moving xen-tools into a separate service

### PR DESCRIPTION
**Pull request by rvs**
This is a work in progress of separating xen-tools into a separate service (which will allow us much greater flexibility in supporting alternative hypervisors in their tools).

Amazingly enough, it even works as-is -- but for now it mostly serves as an illustration of how I plan to deconstruct pillar -- so don't merge -- just review.

What should be of interest here is how I implemented xl and xentop in this new arrangement -- those are basically done as cross-service execs -- let me know if y'all have better ideas.

Finally, doing this made me realize that our watchdog handling is all screwed up -- this will be my next project to unscrew (unless @adarsh-zededa wants to help)

### CODE REVIEW

**Comment by deitch** [comment]
I don't understand why this helps? Instead of running the xen commands from within pillar directly, we still have the commands in pillar, but they worm their way out of the chroot in pillar by calling the mounted `/hostfs/` and into the other xen-tools container, and execute the commands there. The xen-tools container, on the other hand, has no service, just some infinite loop of `while true; do sleep 60; done`.

I definitely am missing something in understand what this is supposed to do? Are you trying to separate the execution of an ECO from within pillar itself, so that eventually it can be Xen or straight docker container or ACRN or KVM or anything at all?

**Comment by rvs** [comment]
Two reasons this is done @deitch (btw as I said -- this is still WIP -- so things will get refined quite a bit before this is merged):

> The xen-tools container, on the other hand, has no service, just some infinite loop of while true; do sleep 60; done.

That container contains at least 3 services that are very Xen specific (xendstored, consoled and qemu Dom0). All those services need to be split away from pillar so that we can dynamically manage whether they are needed to begin with or not. We also need to do logging for those services as part of this container, etc. etc. The loop at the end you see is there just as placeholder for now to do proper log extraction from these services (that is coming today).

> Are you trying to separate the execution of an ECO from within pillar itself, so that eventually it can be Xen or straight docker container or ACRN or KVM or anything at all?

Yup. That's the ultimate goal. To the point where we may even move domainmanager itself into this container (at which point it'll be renamed domainmgr I guess)

**Comment by rvs** [comment]
On and one more thing @deitch -- this also brings us one step closer to having a reasonably fully functional qemu without Xen (which will make it blazingly fast). The other part is splitting watchdog -- which I'll be doing today.

**Comment by rvs** [comment]
Ok, I'm really, really confused now. This is waaay too massive of a change in our dependencies based on a really tiny change in go.mod. I think we need to look into this a bit more @naiming-zededa @nordmark

**Comment by deitch** [comment]
> That container contains at least 3 services that are very Xen specific (xendstored, consoled and qemu Dom0). All those services need to be split away from pillar so that we can dynamically manage whether they are needed to begin with or not. We also need to do logging for those services as part of this container, etc. etc. The loop at the end you see is there just as placeholder for now to do proper log extraction from these services (that is coming today).

That makes sense @rvs . I didn't grok it based on what was there, but I get it now. So the goal in the end is to have pillar being generic (non-Xen-specific) eve management. It will then route a request that says, "start this ECO (OCI container or VM)" to whichever form of manager is appropriate - Xen, runc, firecracker, whatever.

> To the point where we may even move domainmanager itself into this container (at which point it'll be renamed domainmgr I guess)

I am not sure about that. I think the basic control idea of domainmgr - start and stop domains, etc. - belongs in pillar. The actual implementation of starting and stopping belongs in a Xen management container, or a runc management container, or a firecracker management container, etc.

Is the goal in the end then that _everything_ capable will be in a full eve build? Or would I create a build that is for Xen, and a separate one that is for kvm, etc.? Obviously _pillar_ itself is unified and single, but are all of the containers that control the different kinds of virtualization available on all builds, just sometimes unused? Or do we only include the ones we want for a given build?

As long as we are here, and I understand what you are doing, I really dislike the "worming" of xl from inside pillar via `/hostfs` to domainmgr. It keeps them tightly tied, etc. Is there a way we can do message passing? E.g. fire a message from domainmgr in pillar that says, "start ECO with ID X using virtualization of type Xen (or type kvm or...)" that the other one can pick up. Can we leverage pubsub for this?

Conversely, you could be planning that precisely, just separating it out into multiple PRs to keep it sane?

**Comment by deitch** [comment]
> this also brings us one step closer to having a reasonably fully functional qemu without Xen (which will make it blazingly fast)

And doable on cloud VMs and other places, which will make our dev cycle much quicker.

**Comment by deitch** [comment]
> This is waaay too massive of a change in our dependencies based on a really tiny change in go.mod

I have been seeing this for some time now @rvs . I don't know where/when it started, but if I add even a single new dependency, such that `go.mod` changes, I do `go mod vendor`, and then manually check each and every dependency to only include the ones that my change PR brought in.

I think we need a single PR that does nothing but `go mod vendor`, makes sure everything works, and thus brings it all up to date.

**Comment by rvs** [comment]
This is now closed in favor of #625 -- lets focus our energy on a new and improved one.

**Pull request closed without merging**
