### PR TITLE
fix alpine cache creation

### PR DESCRIPTION
**Pull request by rucoder**
this PR is required for XEN/QEMU upgrade

### CODE REVIEW

**Comment by eriknordmark** [comment]
Looks like riscv build is having issues finding 3/.16 packages. Let me re-run in case it was a fluke.

**Comment by rucoder** [comment]
> Looks like riscv build is having issues finding 3/.16 packages. Let me re-run in case it was a fluke.

I think I know why it fails:

`RUN cp /mirror/${ALPINE_VERSION}/rootfs/etc/apk/repositories /etc/apk` expects 3.16, not v3.16. this is how it was populated by `if [ -n "$packages" ]; then build-cache.sh "$p" "/mirror/$(dirname "$p")" "$packages"; fi`

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by milan-zededa** [comment]
@mikem-zed Do we still need [this](https://github.com/lf-edge/eve/blob/master/pkg/alpine/mirrors/3.16/main#L148) if ninja is provided by samurai package?

**Pull request merged**
