### PR TITLE
[9.4-stable] Backport #3607 (eventlog entries from measure-config)

### PR DESCRIPTION
**Pull request by shjala**
This is backport of #3607 .

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
Do we need this for troubleshooting PCR differences? Or is there some other reasons for backporting it?

**Comment by shjala** [comment]
Yes, for troubleshooting PCR-14 mismatches, without these changes anything measure-config measures won't be part of the TPM event log.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
The three yetus complaints are in unmodified code so ignoring them.

**Pull request merged**
