### PR TITLE
Stage1 patch to support volume mount.

### PR DESCRIPTION
**Pull request by adarsh-zededa**
Stage1 receives mount details from rkt, but there was no code to handle it. Added a patch in stage1-xen to read mount details and appropriately mount it in stage2.

This code is exactly the same (except few minor changes) as in stage1-fly which handles mount properly.
Source of stage1-fly code: https://github.com/rkt/rkt/blob/a2f63178ee7749a4e90a2882744774dbd03bb425/stage1_fly/run/main.go#L291 

After this patch in stage1-xen, mounting volumes will work according to rkt's documentation: https://coreos.com/rkt/docs/latest/subcommands/run.html#mount-volumes-into-a-pod

### CODE REVIEW

**Comment by kalyan-nidumolu** [comment]
> Hey @adarsh-zededa -- I don't understand why are we implementing Docker-style Volumes where agreement was to implement disk-style (VM-style) volumes for now.
> 
> Please explain what feature are you trying to implement.

@rvs - EVE donwloads the image, mounts it on a loop device and passes in the directory. But the passed in directory itself is mounted from Qcow2 image..

Is there a better way to do this?

**Comment by rvs** [comment]
@kalyan-nidumolu why do you need all that complexity when you can simply hook it up as a disk and then mount inside the init script within the DomU itself?

**Comment by rvs** [comment]
Hey @adarsh-zededa it seems that the PR got into a state where it can't be applied cleanly

**Comment by rvs** [comment]
https://github.com/lf-edge/eve/pull/555 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help. 

Can you please squash all your changes and create a brand new PR?

**Comment by adarsh-zededa** [comment]
> #555 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.
> 
> Can you please squash all your changes and create a brand new PR?

Sure @rvs. Moved changes to #590. Closing this PR.

**Pull request closed without merging**
