### PR TITLE
[WIP] Add recover-tpm tool to debug container

### PR DESCRIPTION
**Pull request by shjala**

### CODE REVIEW

**Comment by rouming** [comment]
My only advice is: could you please add a few words about the tool in higher level docs, like docs/DEBUG.md or docs/SECURITY.md, because to reach the pkg/debug/docs can be difficult, but having a few words in docs/ can have more chances to be read.

**Comment by eriknordmark** [comment]
I see some yetus issues in 
https://github.com/lf-edge/eve/actions/runs/7874772444?pr=3756

**Comment by shjala** [comment]
I'm going to rework this, major changes to come.

**Comment by shjala** [comment]
see https://github.com/lf-edge/eve/pull/3867

**Pull request closed without merging**
