### PR TITLE
native pcap - no more CGO - take two

### PR DESCRIPTION
**Pull request by deitch**
A redo of #756 with the "infinite packets" problem fixed.

A small PR with a big impact.

* Remove zedbox's dependency on github.com/google/gopacket/pcap, replacing it with github.com/packetcap/go-pcap . This eliminates any CGO dependency
* Remove libpcap and libpcap-dev from the Dockerfiles
* Change `CGO_ENABLED=0`

When this is done, we will be able to get cross-compilation of pillar with just changing the GOOS or GOARCH. This means building locally on Mac or Linux, etc., support for lots of different devices, and more things.

@eriknordmark found the memory issue initially, while @naiming-zededa found the infinite packets that drove it. Beyond CI, this needs their sign-off that it:

* does not create the memory issues
* does not create the "infinite packets"
* _does_ capture the DNS packets correctly

### CODE REVIEW

**Comment by naiming-zededa** [comment]
@deitch checked this patch on my device, does see the DNS packet snooping behave correctly, the infinite looping is gone; although the DHCP snooping is not working (port 67) in this patch.

**Comment by rvs** [comment]
This looks reasonable to me. @eriknordmark shall we pull it?

**Comment by deitch** [comment]
I’m working with @naiming-zededa on a last round of validation. I’d like either his sign off here (or my writing that he signed off to me directly) before we merge in

**Comment by deitch** [comment]
@naiming-zededa found one other issue. It has been updated. I am awaiting his final signoff.

**Comment by naiming-zededa** [comment]
@deitch both dns and dhcp tested good now. thanks.

**Comment by deitch** [comment]
Thanks for finding those issues Naiming. I really appreciate it.

**Pull request merged**
