### PR TITLE
Fix download musl file and include tgz

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

This does not completely fix cross-compile - there still are CGO issues related to pcap, I am working on those - but it solves one step of it.

### CODE REVIEW

**Comment by deitch** [comment]
@aw-zededa can you take a look at this error from yetus?

```
pkg/pillar/README.md: 3: MD034/no-bare-urls Bare URL used [Context: "https://www.lfedge.org/project..."]:pkg/pillar/README.md:: 48:: MD029/ol-prefix Ordered list item prefix [Expected: 1; Actual: 3; Style: 1/1/1]
```

It is inside a quote block, so it should ignore it. Here is the original:

```
> Other Notes:
>
> 3. You should pin and reproduce any version of these toolchains yourself -- old binaries might not be archived. Don't trust random third-party binaries :)
```

**Comment by deitch** [comment]
@aw-zededa also this:

https://1533-182198941-gh.circle-artifacts.com/0/tmp/yetus-out/whitespace-eol.txt

where it says 

```
pkg/pillar/README.md:47:> 
```

Same section as above. It is a block quote, so it should leave it alone.

**Comment by rvs** [comment]
Hey @deitch I'm fine with this -- but I'm not particularly happy about +73Mb landing in our git tree. Folks from India and China already complained about time it takes to check things out.

So... I'm wondering if we should perhaps just maintain a few docker containers with this stuff. IOW, the containers will come from GitHub only when you do cross compiling and won't make everyon pay the price of extra 73m in the repo.

We used to have build-time package in the past -- so perhaps we can  re-introduce them.

**Comment by deitch** [comment]
> I'm not particularly happy about +73Mb landing in our git tree

Neither am I. I worked through late last night on using the semi-official docker images http://hub.docker.com/r/muslcc/x86_64, but they had been compiled and structured in a way that assumed you only ever would build them _inside_ those containers. I got pretty far copying things over (see below), but in the end it struggled with the assembler. Apparently, `gcc` is _compiled_ with a particular path to `as`, which cannot be overridden run-time. It therefore ran the usual local one, rather than the aarch64-cross-compile one.

I liked the idea of using the image from the docker hub, since:

* you can content-address it by sha256, avoiding the issue of it changing name under the covers or even disappearing unless someone aggressively deletes it from the hub
* it is cached locally, so even if it is heavy to download, that is just once
* it fits nicely in the multi-stage build file

I had to do something like this:

```Dockerfile
FROM muslcc/x86_64:aarch64-linux-musl as cross-gcc

FROM golang:${GOVER}-alpine as build
RUN apk update
# ... more here skipped
ARG CROSS_GCC=/aarch64-linux-musl
COPY --from=cross-gcc ${CROSS_GCC} ${CROSS_GCC}
COPY --from=cross-gcc /bin/gcc ${CROSS_GCC}/bin
COPY --from=cross-gcc /libexec ${CROSS_GCC}/libexec
COPY --from=cross-gcc /lib/gcc ${CROSS_GCC}/lib/gcc
RUN ln -s ${CROSS_GCC} ${CROSS_GCC}${CROSS_GCC}
# ... etc
```

It worked up until the assembler. If you know of any way to get gcc to point to a different assembler run-time, I would be happy to take it.

Short of that, as you wrote:

> I'm wondering if we should perhaps just maintain a few docker containers with this stuff

Yes, I was thinking about that too. We even can get away with just one repo with "build-stuff" and have multiple images built out of there.

Can you get us a git repo `lf-edge/eve-builders` or `lf-edge/eve-build-tooling` and one or more repos in docker hub? For now, in docker hub, just `lfedge/eve-cross-builder` is fine; I will tag them appropriately. We apparently have lots of repos there.

Let me know when it is up and I will take care of it.

Just pointing out that `github.com/lf-edge/eve` and `github.com/lf-edge/eve-pillar` and `github.com/lf-edge/eve-cross-builder` and... starts to get tedious; if we had a proper github org `github.com/lf-eve/` or similar that everything went under, this would be cleaner.

**Comment by deitch** [comment]
Yes, @rvs I have it. cross-builders is ready. It can download from `musl.cc` for any target arch, builds the docker images and pushes it out.

Once you have a github repo ready for me that I can push the source to, and a docker hub repo ready for me to push images to, we can close this one out. I will replace it with something much nicer and cleaner that is docker image based.

**Comment by rvs** [comment]
Hey @deitch  https://hub.docker.com/r/lfedge/eve-cross-builder is created

**Comment by rvs** [comment]
Also @deitch can you please resubmit the patch (you can re-use this PR) with the cross-builders stuff?

**Comment by deitch** [comment]
Yup, will resubmit. Did you set up the github repo too? I need that one. The stuff is so simple and independent, it doesn't make sense to mix it in here.

**Comment by rvs** [comment]
I am actually not convinced these builder Docker files need to be in a separate GitHub repo. Can you perhaps show what you have in mind first @deitch  ?

**Comment by deitch** [comment]
> I am actually not convinced these builder Docker files need to be in a separate GitHub repo. Can you perhaps show what you have in mind first @deitch ?

Actually it is a single `Dockerfile` with multiple `--build-arg` invocations. Quite light, but does what we need.

Do you really want to go through an entire lengthy review process for eve, not to mention its extensive and growing CI, to update docker hub images that are not related to it at that time? I can see doing that when you include/change them in pillar via a different hashed tag, but at build time? it will just slow it down.

**Pull request closed without merging**
