### PR TITLE
link to docker is changed

### PR DESCRIPTION
**Pull request by mperov**
EVE is supported by various operating systems so README should have universal links to dependences.
New link to docker has manuals to any operating systems.

### CODE REVIEW

**Comment by mperov** [comment]
@rvs what do you think about this link?

**Comment by mydatascience** [comment]
Please sign the commit

**Comment by mperov** [comment]
@mydatascience I can't understand why DCO failed my pull request. I generated via gpg keys, added them to GitHub. When I create commit GitHub show me that commit is verified! But when I create pull request DCO fail it... You can see my fork of EVE and make sure

**Comment by mperov** [comment]
@rvs @mydatascience I understood what the problem. I used command `git commit -S ...` but I should use `git commit -s ...`

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
