### PR TITLE
vtpm : add a simple fuzzing harness

### PR DESCRIPTION
**Pull request by shjala**
Add a simple harness to fuzz vtpm server using LibFuzzer.

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
Is the intent to later use this as part of the build of the vtpm server?

**Comment by shjala** [comment]
@eriknordmark fuzzers usually have to run for a longer time (for example 36h+) to get a good code coverage, so my intention is to build this manually and run it separately. I ran it for a few days on my laptop and got 95%+ code coverage with no bugs yet.

**Comment by eriknordmark** [comment]
> @eriknordmark fuzzers usually have to run for a longer time (for example 36h+) to get a good code coverage, so my intention is to build this manually and run it separately. I ran it for a few days on my laptop and got 95%+ code coverage with no bugs yet.

Can you add basically the above to pkg/vtpm/fuzz/README.md?

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
