### PR TITLE
Fix loglevel confusion

### PR DESCRIPTION
**Pull request by eriknordmark**
*PLEASE* review only the first commit (which is tiny).

The second commit is generated automatically by running these commands across the pillar directories:
sed -i'' 's/log.Info/log.Function/' *.go
sed -i'' 's/log.Debug/log.Trace/' *.go
sed -i'' 's/Log.Info/Log.Function/' *.go
sed -i'' 's/Log.Debug/Log.Trace/' *.go

Plus the second commit has one line manually changed from Debug to Trace at
https://github.com/eriknordmark/eve/blob/39dcc0a3578e91806c807c32c7d75532e2a57792/pkg/pillar/worker/worker.go#L18

As log-level documentation #1634 is pulled to master I'll update it (in this PR or a separate one) to make it match this implementation. This addresses the "future changes" in that PR.

### CODE REVIEW

**Comment by deitch** [comment]
`log.Function` ? That is a bit of an odd naming. Why not just `log.Debug`/`Debugf`?

**Comment by eriknordmark** [comment]
> `log.Function` ? That is a bit of an odd naming. Why not just `log.Debug`/`Debugf`?

Because that was previously used to mean Trace??

I can change Function->Debug now that Debug has been changed to Trace, however, that will result in some suprises in outstanding PRs which add or change log calls.
With a new name introduced (whether it is "Function" or something else; FTrace, Trace0) it means that the old Info and Debug are deleted from the LogObject hence any outstanding PRs will fail to build and be corrected instead of working differently.

So I'm open for name suggestions, but I prefer to not use Debug for the above reason.

**Comment by deitch** [comment]
> So I'm open for name suggestions, but I prefer to not use Debug for the above reason.

I get the why, but is it worth creating the confusion? This will, essentially, look different from just about every other bit of software out there, increasing the onboarding cost for future contributors.

If we have to, do one PR to change `Debug` to `Trace`, then a future one for `Info` to `Debug`.

**Comment by eriknordmark** [comment]
> If we have to, do one PR to change `Debug` to `Trace`, then a future one for `Info` to `Debug`.

If we're going to do two PR (with a month more in between to flush out outstanding PRs) I'd prefer to do Function to Debug in the second one.

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
