### PR TITLE
Fixed manifest size in reported total filesize

### PR DESCRIPTION
**Pull request by zed-rishabh**
Signed-off-by: zed-rishabh <rgupta@zededa.com>

### CODE REVIEW

**Comment by deitch** [comment]
Will this work? I foresee an issue. For example if you pull `alpine:3.10`, the results could be different since `img` refers to the index, but the raw manifest is resolved to what actually is the image downloaded for your arch/os.

**Comment by zed-rishabh** [comment]
> Will this work? I foresee an issue. For example if you pull `alpine:3.10`, the results could be different since `img` refers to the index, but the raw manifest is resolved to what actually is the image downloaded for your arch/os.

It is working fine with alpine:3.10 also. I verified it.

**Comment by deitch** [comment]
I’m not complaining then. 😃 

Can you check that the actual manifest fits with what is in the file? If you want to do a simple download using the underlying library, I’ve got a simple utility that can pull any image at https://github.com/deitch/ocidist

**Comment by zed-rishabh** [comment]
> I’m not complaining then. 😃
> 
> Can you check that the actual manifest fits with what is in the file? If you want to do a simple download using the underlying library, I’ve got a simple utility that can pull any image at https://github.com/deitch/ocidist

Yes, both are identical.

**Pull request merged**
