### PR TITLE
Bump eve alpine

### PR DESCRIPTION
**Pull request by christoph-zededa**

### CODE REVIEW

**Comment by eriknordmark** [comment]
Looks like the build has issues of the form:
: /home/ubuntu/actions-runner/_work/eve/eve/dist/amd64/0.0.0-pr3928-dea670a8/installer/EFI: Succeeded
./tools/makeconfig.sh /home/ubuntu/actions-runner/_work/eve/eve/dist/amd64/0.0.0-pr3928-dea670a8/installer/config.img "0.0.0-pr3928-dea670a8" conf/DevicePortConfig conf/grub.cfg.tmpl conf/onboard.cert.pem conf/onboard.key.pem conf/root-certificate.pem conf/server conf/v2tlsbaseroot-certificates.pem
Unable to find image 'lfedge/eve-mkconf:46f3092ae249ee00da2612e368c5e7637922376d' locally
docker: Error response from daemon: manifest for lfedge/eve-mkconf:46f3092ae249ee00da2[61](https://github.com/lf-edge/eve/actions/runs/9176167849/job/25243458716#step:8:62)2e368c5e7637922376d not found: manifest unknown: manifest unknown.

**Comment by rene** [comment]
> Looks like the build has issues of the form: : /home/ubuntu/actions-runner/_work/eve/eve/dist/amd64/0.0.0-pr3928-dea670a8/installer/EFI: Succeeded ./tools/makeconfig.sh /home/ubuntu/actions-runner/_work/eve/eve/dist/amd64/0.0.0-pr3928-dea670a8/installer/config.img "0.0.0-pr3928-dea670a8" conf/DevicePortConfig conf/grub.cfg.tmpl conf/onboard.cert.pem conf/onboard.key.pem conf/root-certificate.pem conf/server conf/v2tlsbaseroot-certificates.pem Unable to find image 'lfedge/eve-mkconf:46f3092ae249ee00da2612e368c5e7637922376d' locally docker: Error response from daemon: manifest for lfedge/eve-mkconf:46f3092ae249ee00da2[61](https://github.com/lf-edge/eve/actions/runs/9176167849/job/25243458716#step:8:62)2e368c5e7637922376d not found: manifest unknown: manifest unknown.

@eriknordmark , it looks like some dependency order problem.... @christoph-zededa , if you move the update of pkg/mkconf/Dockerfile to a separated PR I think this one should work....

**Comment by rene** [comment]
Kicking again the amd64 build...

**Comment by rene** [comment]
@christoph-zededa , amd64 build is failing because of pkg/uefi and it's not related to the alpine package... you will need to remove it from this PR as well....

https://github.com/lf-edge/eve/actions/runs/9191506107/job/25287301023?pr=3928#step:8:23860

**Comment by christoph-zededa** [comment]
> @christoph-zededa , amd64 build is failing because of pkg/uefi and it's not related to the alpine package... you will need to remove it from this PR as well....
> 
> https://github.com/lf-edge/eve/actions/runs/9191506107/job/25287301023?pr=3928#step:8:23860

Thank you! Yesterday I've built it locally and everything but the verification image was successful.

**Comment by rene** [comment]
> > @christoph-zededa , amd64 build is failing because of pkg/uefi and it's not related to the alpine package... you will need to remove it from this PR as well....
> > https://github.com/lf-edge/eve/actions/runs/9191506107/job/25287301023?pr=3928#step:8:23860
> 
> Thank you! Yesterday I've built it locally and everything but the verification image was successful.

The problem resides on a submodule library from EDK2: https://git.cryptomilk.org/projects/cmocka.git

Their git server seems to be offline:

```sh
$ git clone https://git.cryptomilk.org/projects/cmocka.git
Cloning into 'cmocka'...
fatal: unable to access 'https://git.cryptomilk.org/projects/cmocka.git/': The requested URL returned error: 500
```

Probably it was online yesterday.... maybe it's just a matter of wait them to restart their git server...

**Comment by christoph-zededa** [comment]
> Probably it was online yesterday.... maybe it's just a matter of wait them to restart their git server...

And now they're back :-)

**Comment by eriknordmark** [comment]
Build is still having issues when re-running:
: /home/ubuntu/actions-runner/_work/eve/eve/dist/amd64/0.0.0-pr3928-15a982d8/rootfs.tar: Succeeded
: /home/ubuntu/actions-runner/_work/eve/eve/dist/amd64/0.0.0-pr3928-15a982d8/installer/rootfs.img: Begin
./tools/makerootfs.sh imagefromtar -t /home/ubuntu/actions-runner/_work/eve/eve/dist/amd64/0.0.0-pr3928-15a982d8/rootfs.tar -i /home/ubuntu/actions-runner/_work/eve/eve/dist/amd64/0.0.0-pr3928-15a982d8/installer/rootfs.img -f squash -a amd64
Unable to find image 'lfedge/eve-mkrootfs-squash:1c718d751d9f9e57b5e45db7ee07895973c3521f' locally
docker: Error response from daemon: manifest for lfedge/eve-mkrootfs-squash:1c718d751d9f9e57b5e45db7ee07895973c3521f not found: manifest unknown: manifest unknown.

**Comment by eriknordmark** [comment]
@christoph-zededa did you change something in the force push today? If so we can try re-approving (instead of re-running)

**Comment by christoph-zededa** [comment]
> @christoph-zededa did you change something in the force push today? If so we can try re-approving (instead of re-running)

I did, I re-added the update for pkg/uefi as their git server is now reachable again (https://github.com/lf-edge/eve/pull/3928#issuecomment-2125257177 )

**Review by rene — APPROVED** [review]
Approving again to see if it builds as it is now....

**Comment by christoph-zededa** [comment]
https://github.com/lf-edge/eve/actions/runs/9208196058/job/25338125484?pr=3928#step:3:1804
```
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/bin/eden-linux-amd64 .
/opt/hostedtoolcache/go/1.18.10/x64/pkg/tool/linux_amd64/link: signal: killed
```
;-(

**Pull request merged**
