### PR TITLE
Edgeview App needs latest pillar vendor files

### PR DESCRIPTION
**Pull request by naiming-zededa**
- import the latest changes in zedroutertypes.go for app IP display to work
- fix an issue of single instance JWT file but user specifying instance number > 1

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM.

Is the missing instid > 1 check a regression from earlier? I'm asking to determine whether this is something we should consider backporting to stable releases.

**Comment by milan-zededa** [comment]
> LGTM.
> 
> Is the missing instid > 1 check a regression from earlier? I'm asking to determine whether this is something we should consider backporting to stable releases.

I think we should also backport this to 11.0 (if it is going to be stable release). Otherwise app command will not work in that particular version due to underlay renaming.

**Comment by naiming-zededa** [comment]
> LGTM.
> 
> Is the missing instid > 1 check a regression from earlier? I'm asking to determine whether this is something we should consider backporting to stable releases.

this thing has been there for quite a while. I only saw this issue with debug Andrew's problem starting a tcp session. I don't think this is a big deal.

**Comment by naiming-zededa** [comment]
> > LGTM.
> > Is the missing instid > 1 check a regression from earlier? I'm asking to determine whether this is something we should consider backporting to stable releases.
> 
> this thing has been there for quite a while. I only saw this issue with debug Andrew's problem starting a tcp session. I don't think this is a big deal.

if needed, sure. May be this is ok, since we'll make the LTS for version 11 later, and that is more people will use.

**Pull request merged**
