### PR TITLE
An empty IP can be represented using an empty slice or nil, so check for both.

### PR DESCRIPTION
**Pull request by zedi-pramodh**
An empty IP can be an empty string "" or nil
so check for both.

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
Isn't this a backport of a commit in master? If so it would be good to include that hash in the commit message to make it easier to track things.

That's then case even if this is a subset of what was in a commit in master.

**Comment by zedi-pramodh** [comment]
No it's not a back port from master. This code does not exist in the master due to refactoring of code. This code is only in 9.4 and 8.12 branches

**Comment by eriknordmark** [comment]
> No it's not a back port from master. This code does not exist in the master due to refactoring of code. This code is only in 9.4 and 8.12 branches

I see isEmptyIP in pkg/pillar/cmd/zedrouter/ipam.go in master, and that was previously in dnsmasq.go, and the function was changed to check for nil in https://github.com/lf-edge/eve/commit/37205848aa5757a4d90b97ec006d93f087f29b21
Can you add that reference to the commit message?

**Comment by zedi-pramodh** [comment]
Done. I amended the commit message.

**Comment by milan-zededa** [comment]
Description should be: `An empty IP can be represented using an empty slice or nil, so check for both.`
And perhaps the commit description should contain some background on the issue being fixed, something like:
```
An incorrectly performed IP-emptiness check may lead to zedrouter trying to stop metadata server which has not been yet started, resulting in panic triggered from log.Fatal.
```

**Comment by zedi-pramodh** [comment]
Amended the commit, please check

**Review by milan-zededa — APPROVED** [review]

**Pull request merged**
