### PR TITLE
add boot to installer

### PR DESCRIPTION
**Pull request by giggsoff**
Seems, we miss files in boot needed for RPi4 boot process

#2021 

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by giggsoff** [comment]
Open question for me here: do we need u-boot.bin in `/boot` for amd64? https://github.com/lf-edge/eve/blob/1af1a093b18dd9ceae8eded16455ce8d053f6675/pkg/u-boot/Dockerfile#L32

**Review by rvs — CHANGES_REQUESTED** [review]
Interestingly enough @giggsoff -- this wasn't an oversight -- this was done on purpose. I am still not convinced we should be in business of managing *firmware*  when doing the netboot route. Otherwise /boot content is going to end up on all those Packet ARM servers -- that's not good. We really need to treat RPi4 as an exception at this point and make presence of those files conditional in iPXE

Makes sense?

**Comment by Insei** [comment]
> Interestingly enough @giggsoff -- this wasn't an oversight -- this was done on purpose. I am still not convinced we should be in business of managing _firmware_ when doing the netboot route. Otherwise /boot content is going to end up on all those Packet ARM servers -- that's not good. We really need to treat RPi4 as an exception at this point and make presence of those files conditional in iPXE
> 
> Makes sense?

We can use this when booting on LAN, however without TFTP on LAN, Rpi4 won't be able to boot after installation, is this the right approach?

And when we make a live-raw image for ARM architecture, these files are present in EFI partition.

**Comment by rvs** [comment]
Live image is for RPi only @Insei -- so that's fine. I don't think I understood your other comment, tho.

**Comment by Insei** [comment]
> Live image is for RPi only @Insei -- so that's fine. I don't think I understood your other comment, tho.

After network installation on Rpi4, we get not bootable device, if bootable blobs has been removed from TFTP.

**Pull request closed without merging**
