### PR TITLE
maintainers: Add Nikolay, Roman, and Rene

### PR DESCRIPTION
**Pull request by eriknordmark**
As stated in the email to the EVE and EVE-TSC mailing lists.

### CODE REVIEW

**Review by deitch — APPROVED** [review]

**Comment by OhmSpectator** [comment]
Commit message: Niklay -> Nikolay
=D

**Comment by eriknordmark** [comment]
> Commit message: Niklay -> Nikolay =D

Oops - fixed.

**Review by OhmSpectator — APPROVED** [review]

**Review by milan-zededa — APPROVED** [review]
Nice, more power rangers

**Comment by deitch** [comment]
Welcome!

**Pull request merged**
