### PR TITLE
Migrating fscrypt build to use lfedge/eve-alpine

### PR DESCRIPTION
**Pull request by cshari-zededa**
Signed-off-by: Hariharasubramanian C S <cshari@zededa.com>

### CODE REVIEW

**Comment by cshari-zededa** [comment]
> Hey @cshari-zededa -- I have a related suggestion here. Would it be OK with you if we actually discontinue fscrypt as a standalone package and just build it as one of the stages of building pillar?
> 
> By now I don't remember the reason for why we wanted this to be a standalone package (I apologize if I somehow was the reason ;-)) but perhaps it now makes sense to pull it in (which also simplify the build mechanics)
> 
> Btw, none of it changes the usefulness of updating our alpine cache -- so that I'm obviously +1 on.

Hi @rvs, 
We have kept it as a separate package since we had to patch fscrypt (to get rid of some PAM dependencies, not applicable for our platform, and also some improvements w.r.t. key rotation of raw-key format). The patch files are under pkg/fscrypt.

If we move it to pkg/pillar, we probably need to have to move the patch directory to pkg/pillar as well.

Thanks
Hari

**Comment by rvs** [comment]
Cool! @cshari-zededa -- if you have no reasons to keep it as a separate package for your workflow -- then I'll follow with a PR to move it to pillar (since I'm refactoring stuff in pillar anyway). Holler if you disagree.

Also, seems like the build is failing (haven't looked why)

**Comment by cshari-zededa** [comment]
> Cool! @cshari-zededa -- if you have no reasons to keep it as a separate package for your workflow -- then I'll follow with a PR to move it to pillar (since I'm refactoring stuff in pillar anyway). Holler if you disagree.

Yes, I agree.

> 
> Also, seems like the build is failing (haven't looked why)

Fixed the build issue.

**Comment by cshari-zededa** [comment]
> Is this still WIP or is it ready to pull?

Ready to pull.

**Pull request merged**
