### PR TITLE
First step towards enabling EVE deployments via docker-compose

### PR DESCRIPTION
**Pull request by rvs**
This now allows one to type make run-compose and have a lot of fun.

Seriously, though -- there's still quite a bit of work left in making pillar services do the right thing in this type of environment -- but the first results are pretty promising.

### CODE REVIEW

**Comment by deitch** [comment]
Ah, so this is not to run 10 containers _inside_ an eve device via compose? But rather to spin up the eve components independently as containers _without_ having a device (real or virtual)? I like this, have wanted this since day 1. 

Two questions:

* As you are working through this @rvs, can you create a tracking issue with a checklist of everything that needs to be done to make it work? That will allow everyone to know state, but also allow us to divvy up the work.
* What did you do for pubsub? We have it abstracted out and pluggable, but did you just stick with Unix-domain sockets and filesystem, and mount them in via volumes, for now?

**Comment by rvs** [comment]
> As you are working through this @rvs, can you create a tracking issue with a checklist of everything that needs to be done to make it work? That will allow everyone to know state, but also allow us to divvy up the work.

Embarrassed to admin that I actually don't know what you mean ;-) can you show what you mean?

> What did you do for pubsub? We have it abstracted out and pluggable, but did you just stick with Unix-domain sockets and filesystem, and mount them in via volumes, for now?

Yup. It pretty much worked out of the box in that setup (given some of the improvements that @eriknordmark provided for breaking containers apart).

**Comment by deitch** [comment]
> Yup. It pretty much worked out of the box in that setup (given some of the improvements that @eriknordmark provided for breaking containers apart).

Awesome!

**Comment by deitch** [comment]
> can you show what you mean?

Sure @rvs I created one #734 . The checklist needs to be expanded significantly. People can take ownership of items on the checklist, we can link to PRs that solve them, and check them when done. When every item on the checklist is complete, we are done and can close the tracking issue.

**Comment by rvs** [comment]
Thanks @deitch -- I now see what you meant -- and I'll be checking off some of those boxes ASAP.

**Pull request merged**
