### PR TITLE
Removing hard coded count of TSC members

### PR DESCRIPTION
**Pull request by GregChase**
Signed-off-by: Greg Chase <greg@zededa.com>

### CODE REVIEW

**Comment by deitch** [comment]
Still has the signature issue.

**Comment by GregChase** [comment]
I'm still trying to figure out how to do signing via the web interface on
github.  Luckily this isn't code that requires a copyright.

-Greg

**Comment by eriknordmark** [comment]
Any progress on getting the signoff in place?

**Comment by GregChase** [comment]
I wasn't able to figure out how to 1) use this plugin properly or 2) apply
it after the fact.

That being said, my commit  is clearly not code, just a text doc, so
signing should be an issue here.

-Greg

**Comment by rvs** [comment]
Good point @GregChase -- let me just pull it as-is

**Pull request merged**
