### PR TITLE
Update rpi patches in new-kernel package

### PR DESCRIPTION
**Pull request by Insei**
Added lost patch for rpi: uart swap like in raspberry/linux.
Renamed patch with device tree for rpi uno.
Fixed patch with tpm module for rpi4 so that git am can be used.

### CODE REVIEW

**Comment by Insei** [comment]
Re-run PR build workflow please, everything should be ok.

**Comment by eriknordmark** [comment]
Do you have a Uno that you can test this on?

**Review by eriknordmark — APPROVED** [review]
LGTM but please specify whether Uno and regular RPI4 have been tested.

**Comment by Insei** [comment]
> Do you have a Uno that you can test this on?

All this changes is not applicable to UNO platform. I only rename old patch without changes.

> but please specify whether Uno and regular RPI4 have been tested.

All these changes are tested by me on rpi4.

**Comment by Insei** [comment]
@eriknordmark re-run eden \ integration test workflow please, everything should be ok. Thanks

**Review by eriknordmark — APPROVED** [review]
Run eden again

**Pull request merged**
