### PR TITLE
Fix an issue in Edgeview not getting App interface IP address

### PR DESCRIPTION
**Pull request by naiming-zededa**
- due to the change of multiple port in zedrouter, the AppNetAdapterList.AllocatedIPv4Addr was changed to AssignedAddresses, do the same change
- update the vendor files for pkg/pillar in pkg/edgeview

Signed-off-by: Naiming Shen <naiming@zededa.com>
(cherry picked from commit a54bfb3c0c119bc62e65b94c7a4deccc64c45a63)

### CODE REVIEW

**Comment by naiming-zededa** [comment]
resubmitted this PR for backporting to 13.4.0 stable

**Comment by OhmSpectator** [comment]
And the second commit? =)
```
git cherry-pick -x 3769a4285101a6d0696499489f6de18f333b0443
```

**Comment by naiming-zededa** [comment]
do this in
 Naiming backport3 4352 #4377

**Comment by naiming-zededa** [comment]
> do this in Naiming backport3 4352 #4377

why not ;-) submitted, please check

**Pull request closed without merging**
