### PR TITLE
replace C based PAC processing with go

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

[proxy auto-config](https://en.wikipedia.org/wiki/Proxy_auto-config) (PAC) is the configuration for processing proxy information. It is written in JS, which required us to have a JS engine in pillar. We previously used [duktape](https://duktape.org), which is written in C, thus requiring `CGO_ENABLED=1` and cross-compilation. 

By replacing it with a go-pac, we eliminate the need for `CGO_ENABLED=0`, taking us one step closer to simple full cross-compile.

It also simplifies the code significantly.

All of our `zedpac` tests pass, although the return error message is slightly shorter, so those error messages in the tests needed to be adjusted.

### CODE REVIEW

**Comment by deitch** [comment]
In retrospect, I probably should have done this in 2 commits: one for the code changes and one for the `vendor/` files. Next time.

**Comment by rvs** [comment]
Hey @deitch one reason I passed on go-pac before is because it increased the size of zedbox quite a bit. Can you please provide before and after size of zedbox for this patch?

Also, I didn't quite catch whether the tests are still passing or not.

**Comment by deitch** [comment]
> Also, I didn't quite catch whether the tests are still passing or not.

Yes, tests are passing. I had some yetus issues, so it took a few runs to get it working.

> Can you please provide before and after size of zedbox for this patch

Yup, will do.

**Comment by deitch** [comment]
Also rebasing.

**Comment by deitch** [comment]
OK, it _was_ passing...

**Comment by deitch** [comment]
This is odd:

```
sudo apt-get update; sudo apt-get install -y qemu-utils
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
Exited with code 100
```

Looks like just a circleci thing. I don't have write permissions (of course). @rvs, can you restart build?

**Comment by rvs** [comment]
Definitely a Circle issue -- I've seen it before. As for perms you should have those. Let me dig in GH ACLs.

**Comment by deitch** [comment]
And failed again with same message. Strange.

**Comment by deitch** [comment]
> Can you please provide before and after size of zedbox for this patch

Here you go:

```
$ ls -l 
-rwxr-xr-x  1 adeitcher  staff  35595120 Jun 26 19:50 zedbox-c
-rwxr-xr-x  1 adeitcher  staff  37078936 Jun 26 19:43 zedbox-go
$ du -s -h *
 34M	tmp/zedbox-c
 35M	tmp/zedbox-go
```

Just under 1.5MB in size difference.

**Comment by rvs** [comment]
One small favor: can you also compared them compressed (a simple gz will suffice)

**Comment by deitch** [comment]
```
-rw-r--r--  1 adeitcher  staff  15327877 Jun 26 19:56 tmp/zedbox-c.gz
-rw-r--r--  1 adeitcher  staff  15525223 Jun 26 19:56 tmp/zedbox-go.gz
```
197346 bytes difference

**Comment by deitch** [comment]
> That said, I'd like to hear @eriknordmark and @kalyan-nidumolu on what kind of testing will be required to validate that this change in PAC implementation won't break any kind of real world scenarios.

I as well. In theory, since it has a contract API, it should just work. I also reran all of our `zedpac_test.go` test cases (as does CI), so again, it should work. But "should work" is the second most dangerous phrase in engineering (right after, "how hard could it be" :-) ).

**Comment by deitch** [comment]
Looks like our circleci env is messed up :-(

**Comment by rvs** [comment]
Well, @deitch not anymore :-)

**Comment by deitch** [comment]
Nice! And all checks pass. Just awaiting the merge.

The only thing left in `pkg/pillar` that uses `CGO` is `google/gopacket`, but that is a doozy. Well, one step at a time.

**Comment by rvs** [comment]
I think you're running into github limitation on showing changes this big (and that's why we should always put vendor updates into a separate commit). What I recommend is to fetch a https://github.com/lf-edge/eve/pull/114.patch and apply it locally to review

**Comment by deitch** [comment]
I really should have done it in 2 commits. Oh well.

I am rebasing.

**Comment by deitch** [comment]
And rebased

**Pull request merged**
