### PR TITLE
zpool upgrade after EVE-OS upgrade

### PR DESCRIPTION
**Pull request by giggsoff**
Upgrading persist pool to the latest version on EVE image testing done.
Also includes /etc/zfs-release file for future checks on versions of zfs

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
I we do the zpool upgrade when we mark the new IMGx as active and the user later determines that the applications have some issue on the new EVE/ZFS version, then they can not do back to the previous version (assuming that there was a new version of ZFS with some new feature in the on-disk format thus zpool upgrade did some permanent change).

Thus this seems way too soon to do the zpool upgrade. Maybe it should be driven by wanting some new feature from the new on-disk format, or wait for a year after having moved to a new ZFS version??

**Comment by giggsoff** [comment]
> I we do the zpool upgrade when we mark the new IMGx as active and the user later determines that the applications have some issue on the new EVE/ZFS version, then they can not do back to the previous version (assuming that there was a new version of ZFS with some new feature in the on-disk format thus zpool upgrade did some permanent change).
> 
> Thus this seems way too soon to do the zpool upgrade. Maybe it should be driven by wanting some new feature from the new on-disk format, or wait for a year after having moved to a new ZFS version??

Well, so it looks like there are several options here:

1. Make upgrade as an explicit command sent from controller
2. Defer upgrade with configurable option (with EVE Runtime Configuration Properties defaulted to i.e. an hour)
3. Do not implement it right now and wait for real use-case and prepare explicit upgrade-converter workflow with checks for current pool version, new pool version and what will be potentially broken/improved during upgrade.

**Comment by eriknordmark** [comment]
> Well, so it looks like there are several options here:
> 
> 1. Make upgrade as an explicit command sent from controller
> 2. Defer upgrade with configurable option (with EVE Runtime Configuration Properties defaulted to i.e. an hour)
> 3. Do not implement it right now and wait for real use-case and prepare explicit upgrade-converter workflow with checks for current pool version, new pool version and what will be potentially broken/improved during upgrade.

I think it is a combination of 1 and 3. I think what might have sense now is to report the version of the zpool in the info API so that we can see if devices installed with different versions of EVE-OS ends up with different zpool versions.
My understanding is that the zpool upgrade isn't needed until you need some new features from the pool (as opposed to new features in ZFS which does not need new info recorded on the disk), and that this should be done explicitly. But also that it would make sense to be able to upgrade to a specific zpool version (as opposed to the most recent supported by the running ZFS version). I don't know if ZFS supports such an "upgrade-to" command.

But we do have time; I don't know how many zpool versions we've seen per decade but I think it is a lot less than one per year.
My 2 cents.

**Comment by zedi-pramodh** [comment]
After discussion with Erik I learned that customers can explicitly choose to switch between different EVE images (different from upgrades) for various reasons. In such scenario running zpool upgrade command could lead to loss of access to the pool. Let's defer this commit for future until we work through the workflows. One option is to provide a zpool upgrade option from the controller, in such cases user is aware of the consequences.

**Comment by rvs** [comment]
> Let's defer this commit for future until we work through the workflows. 

Do you want to keep PR open? Would be a bit more tidy if we can close it -- but I'm fine either way @zedi-pramodh

**Comment by zedi-pramodh** [comment]
I think we can close this PR and revisit when we need it.

**Pull request closed without merging**
