### PR TITLE
Deactivating the container instance if qemu process is crashed

### PR DESCRIPTION
**Pull request by zed-rishabh**
Signed-off-by: zed-rishabh <rgupta@zededa.com>

### CODE REVIEW

**Comment by kalyan-nidumolu** [comment]
Hi Erik,

The issue is - When qemu crashes - rkt containers are left in a weird
state. Rkt Pod and Xl Create are up - But the container is not actually
running. If we have to restart, we need to bring the container down and
then restart. So, when we detect the error - the idea is to actually halt
the container and put it in error state.

Is there a better way to do this?

Thanks,
Kalyan

**Comment by eriknordmark** [comment]
It makes sense to create a new cleanup function, and call that function when the qemu process has died. Such a function should just do a xl destroy (no need to try a shutdown) and cleanup whatever rkt state there is.

**Comment by rvs** [comment]
Can this PR be closed @zed-rishabh ?

**Comment by zed-rishabh** [comment]
> Can this PR be closed @zed-rishabh ?

@rvs, @kalyan-nidumolu is looking into it.

**Comment by zed-rishabh** [comment]
Closing this PR.

**Pull request closed without merging**
