### PR TITLE
renamed the input param to eve_image

### PR DESCRIPTION
**Pull request by yash-zededa**
Renamed the param to eve_image and workflow name for the call. This param will be passed to eden workflows.

Eden PR: https://github.com/lf-edge/eden/pull/881

### CODE REVIEW

**Review by uncleDecart — APPROVED** [review]
LGTM, but it's not just smoke tests, I would name it `Eden test suite`

**Comment by milan-zededa** [comment]
> LGTM, but it's not just smoke tests, I would name it `Eden test suite`

Or maybe let's just call the workflow `Eden` and job `test_suite`, then it will be for example: `Eden / test_suite / Smoke tests (ext4, false)`

**Comment by yash-zededa** [comment]
> LGTM, but it's not just smoke tests, I would name it `Eden test suite`

Renamed it to test suite

**Comment by uncleDecart** [comment]
@yash-zededa I agree with @milan-zededa this naming is better than mine, could you rename it for last time and then we'll merge it

**Review by uncleDecart — APPROVED** [review]
LGTM

**Review by milan-zededa — APPROVED** [review]

**Review by eriknordmark — CHANGES_REQUESTED** [review]
With this we will have two workflows with the name "Eden" until we remove the old.
Can we not name this one "Eden test" so that we can tell them apart without looking at the name of the workflow file?

**Comment by yash-zededa** [comment]
> With this we will have two workflows with the name "Eden" until we remove the old. Can we not name this one "Eden test" so that we can tell them apart without looking at the name of the workflow file?

@eriknordmark that was the initial plan. We will stick to that. 

@milan-zededa This PR is for testing so that the existing workflows are not impacted. We can fix all the naming convention once we are ready to move to the new WF.

**Review by uncleDecart — APPROVED** [review]
I'm alright with this naming convention for now

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
