### PR TITLE
Google Storage Datastore

### PR DESCRIPTION
**Pull request by giggsoff**
Google Storage Datastore implementation.

As of API current version expect in DatastoreConfig:
Dpath - bucket name
ApiKey - project name (required for upload)
Password - content of service account json (plain or base64-encoded) with Storage Object Viewer role for download (Storage Admin for test)

### CODE REVIEW

**Review by rvs — APPROVED** [review]
LGTM structurally -- deferring to @eriknordmark for a more comprehensive review

**Comment by giggsoff** [comment]
Any comments/suggestions on this?

**Review by eriknordmark — APPROVED** [review]
LGTM.
Note that the two yetus complaints should be ignored since this PR follows the style used for that enum definition and we don't want to change all of that as part of this PR.

@petr-zededa you have some conflicts to resolve though.

**Comment by giggsoff** [comment]
Resolved conflicts, they seem to have appeared recently.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
