### PR TITLE
avoid ca certs nil pointer

### PR DESCRIPTION
**Pull request by giggsoff**
In case of nil `ctx.TlsConfig.RootCAs` we can hit nil pointer dereference while appending proxy certificates.

cc @naiming-zededa

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
@petr-zededa do you have a stack trace indicating why UpdateTLSProxyCerts is being called before the init function has set up the ctx.TlsConfig.RootCAs? I think it makes more sense to find that and close the hole there.

**Comment by giggsoff** [comment]
> @petr-zededa do you have a stack trace indicating why UpdateTLSProxyCerts is being called before the init function has set up the ctx.TlsConfig.RootCAs? I think it makes more sense to find that and close the hole there.

Having nil there is not an [error](https://cs.opensource.google/go/go/+/refs/tags/go1.16.10:src/crypto/tls/common.go;drc=520f3b72db7befab2028d9a47376267cf2d274a9;l=596), but we cannot append to it.

**Comment by giggsoff** [comment]
@naiming-zededa thank you for your comment. Can you please open another PR with your changes? Also seems reasonable to add some check for nil to UpdateTLSProxyCerts (just return false, not panic).

**Comment by naiming-zededa** [comment]
sure @petr-zededa, will do.

**Pull request closed without merging**
