### PR TITLE
hypervisor/kvm: Add multidevs=remap option to 9P share

### PR DESCRIPTION
**Pull request by rene**
This commit adds the option 'multidevs=remap' to handle multiple devices shared across the same 9p export and avoid file ID collision. This change will fix the following QEMU's warning:

qemu-system-x86_64: warning: 9p: Multiple devices detected in same VirtFS export, which might lead to file ID collisions and severe misbehaviours on guest! You should either use a separate export for each device shared from host or use virtfs option 'multidevs=remap'!

### CODE REVIEW

**Review by OhmSpectator — COMMENTED** [review]
Do we really have these warnings? It looks strange to me. I would expect each fsdev section of the QEMU template to correspond to a dedicated 9p export... In this case, the only way to get this collision is to have the same .FileLocation for different disks. Do we support it?

**Comment by OhmSpectator** [comment]
I want to be sure we are not hiding a real problem by suppressing the warning.
Yep, I read the documentation, and that's exactly what confuses me. As you have mentioned, to see the warning, several different devices should be shared with one 9p export. As far as I understand, a fsdev section of the QEMU template corresponds to one 9p export. And in this case the only way to get the collision is to have the same device (volume image in our case) shared with several fsdev devices. And this use case looks suspicious to me.

**Comment by rene** [comment]
> I want to be sure we are not hiding a real problem by suppressing the warning. Yep, I read the documentation, and that's exactly what confuses me. As you have mentioned, to see the warning, several different devices should be shared with one 9p export. As far as I understand, a fsdev section of the QEMU template corresponds to one 9p export. And in this case the only way to get the collision is to have the same device (volume image in our case) shared with several fsdev devices. And this use case looks suspicious to me.

I've figured out what is going on. I've deployed a container image that provides 2 disk images (totally supported and operational). In this case one image is mount as the rootfs of the container (/) and the other should be mount on /vol2. From inside the container VM we can see the following mounts (just an excerpt, we are just interested in the `share_dir` ones):

```
~ # mount
rootfs on / type rootfs (rw)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=10240k,nr_inodes=248418,mode=755)
share_dir on /mnt type 9p (rw,dirsync,relatime,mmap,access=client,trans=virtio)
share_dir on /dev/eve type 9p (rw,dirsync,relatime,mmap,access=client,trans=virtio)
devtmpfs on /mnt/rootfs/dev type devtmpfs (rw,nosuid,noexec,relatime,size=10240k,nr_inodes=248418,mode=755)
share_dir on /mnt/rootfs/dev/eve type 9p (rw,dirsync,relatime,mmap,access=client,trans=virtio)
sysfs on /mnt/rootfs/sys type sysfs (rw,relatime)
```

`/mnt` is where EVE extracts all the files from the container, including its rootfs (/mnt/rootfs). However, other volumes are put inside /mnt/rootfs/dev/eve, which will be provided to the container at /dev/eve/volumes/.... (you can take a look here to see the implementaiton: https://github.com/lf-edge/eve/blob/master/pkg/pillar/containerd/oci.go#L438), this location will be mount as a bind from /mnt/rootfs/dev/eve). So we will have multiple mounts (although /mnt/rootfs/dev/eve is a bind) under the same 9p share (_share_dir_). Notice that by using the remap option, we are not masking any problem, we are allowing multiple devices under the same 9p share in the proper way... so I still think we should enable it....

**Review by eriknordmark — APPROVED** [review]
LGTM

**Review by OhmSpectator — APPROVED** [review]
Thanks for the investigation! Now I see it's a legit use case, and I do not see an option to do device-per-export mounts as it's recommended in the documentation (due to the nested nature of the mounts). All in all, it looks good to me.

**Pull request merged**
