### PR TITLE
Remove lisp from starting in EVE

### PR DESCRIPTION
**Pull request by gkodali-zededa**
Testing done:
1) Base os update worked fine.
2) VM app create worked (booted), app delete also worked.

EVE image size came down by about 25MB with this change.

Signed-off-by: Gopi krishna Kodali <gkodali@zededa.com>

### CODE REVIEW

**Comment by gkodali-zededa** [comment]
> Can you check how much more memory is available after boot?
> 
> Also, I think you've removed the overlay code and IsZedmanager from zedrouter, but I don't see it being removed from types. And when you do I suspect you'll find code in zedagent which can be removed.
> 
> The handlelookupparam.go is presumably not needed any more. I think that was just to create the AppNetworkConfig with IsZedmanager set to true.

Did more clean up and committed the code. Thanks!

**Comment by rvs** [comment]
This looks reasonable to me @gkodali-zededa -- but given we're trying to stabilize 5.9.0 I propose we pull this right after we cut 5.9.0

**Comment by rvs** [comment]
Actually, now that I've had some time to think about it -- I've got one question before this can be merged: it appears that we're removing the very notion of what it is to have an OverlayNetwork on EVE. If that's the case -- it feels a bit premature since we're going to very much experiment with hooking up Tailscale in place of LISP.

Now, that integration is expected to be much more lightweight and closer to what we do with CloudNetork for SrongSWAN, etc. but even then -- don't we need the underlying plumbing around OverlayXXX for it still?

Unless I'm confused -- this seems a bit too far reaching in what is getting removed. @gkodali-zededa @eriknordmark -- please comment.

**Comment by gkodali-zededa** [comment]
> Actually, now that I've had some time to think about it -- I've got one question before this can be merged: it appears that we're removing the very notion of what it is to have an OverlayNetwork on EVE. If that's the case -- it feels a bit premature since we're going to very much experiment with hooking up Tailscale in place of LISP.
> 
> Now, that integration is expected to be much more lightweight and closer to what we do with CloudNetork for SrongSWAN, etc. but even then -- don't we need the underlying plumbing around OverlayXXX for it still?
> 
> Unless I'm confused -- this seems a bit too far reaching in what is getting removed. @gkodali-zededa @eriknordmark -- please comment.

I'm not

**Comment by gkodali-zededa** [comment]
> Actually, now that I've had some time to think about it -- I've got one question before this can be merged: it appears that we're removing the very notion of what it is to have an OverlayNetwork on EVE. If that's the case -- it feels a bit premature since we're going to very much experiment with hooking up Tailscale in place of LISP.
> 
> Now, that integration is expected to be much more lightweight and closer to what we do with CloudNetork for SrongSWAN, etc. but even then -- don't we need the underlying plumbing around OverlayXXX for it still?
> 
> Unless I'm confused -- this seems a bit too far reaching in what is getting removed. @gkodali-zededa @eriknordmark -- please comment.

I was not part of any earlier discussions (if any) about Tailscale in EVE. But after a quick reading about tailscale & wireguard, I understand that much of the registration/allocation required is already done by tailscale software. This replaces components like volga in cloud for public key registration and subsystems in EVE for EID generation and registration. If I understand it right tailscale has similar features as Lisp albeit different implementation. I would like to see what @eriknordmark thinks about this.

**Comment by eriknordmark** [comment]
@rvs we initially added overlay and underlay networks as the only two different types of networks. Since then we've introduced the network instance concept, and we use that to capture the cloud aka VPN connectivity. Thus I think we can capture an overlay aka mesh network without a separate overlay concept in the app instance config and zedrouter. But I'm looking over that code to see if it has some pieces which are specific to overlays and not specific to a LISP overlay to make sure we are not accidentally loosing something. Stay tuned.

**Comment by eriknordmark** [comment]
@rvs The only specific overlay code we have which is not specific to lisp is the adding and removing of a host route. We might need that for over overlays if e.g. there is 100.X.Y.Z/8 subnet and various devices has various values of X.Y.Z.

@gkodali-zededa can you preserve deleteAppInstaneOverlayRoute() as dead code and create a dead/unused addAppInstanceOverlayRoute() with the corresponding route add code?

**Comment by gkodali-zededa** [comment]
> @rvs The only specific overlay code we have which is not specific to lisp is the adding and removing of a host route. We might need that for over overlays if e.g. there is 100.X.Y.Z/8 subnet and various devices has various values of X.Y.Z.
> 
> @gkodali-zededa can you preserve deleteAppInstaneOverlayRoute() as dead code and create a dead/unused addAppInstanceOverlayRoute() with the corresponding route add code?

@nordmark Done. overlay route add was not deleted before. Cloud NI uses parts of it. Restored the overlay route delete code.

**Comment by gkodali-zededa** [comment]
@eriknordmark @rvs Let me know if the PR looks ok to you now.

**Comment by rvs** [comment]
LGTM @gkodali-zededa -- @eriknordmark ready to merge?

**Comment by eriknordmark** [comment]
I don't see remaining code for cloud NI which adds an overlay route using
	if isIPv6 {
		subnetSuffix = "/128"
	} else {
		subnetSuffix = "/32"
	}
Perhaps it is missing the IPv6 support?

But we can pull this now and worry about that later.

**Pull request merged**
