### PR TITLE
github-wf: prevent builds from triggering on workflow and markdown file changes

### PR DESCRIPTION
**Pull request by yash-zededa**
Added .github/workflows to CODEOWNERS for automatic review and approval.

Modified eden.yml to skip tests when there changes are made to the github/workflows. This prevents unnecessary builds triggered by updates to workflows and markdown files.

Workflows changes should now be handled separately from code changes to ensure proper handling.

### CODE REVIEW

**Comment by OhmSpectator** [comment]
Changes in CODEOWNERS make sense to be in a separate commit.

**Comment by yash-zededa** [comment]
> Changes in CODEOWNERS make sense to be in a separate commit.

If we include the CODEOWNERS file without merging this PR, it would unnecessarily trigger builds and Eden tests. Therefore, I've incorporated all the changes into this PR. 

In the future, we can create separate PRs for any updates to CODEOWNERS to maintain a clean history.

**Review by uncleDecart — APPROVED** [review]
LGTM

**Comment by OhmSpectator** [comment]
Ok. let it be...

**Review by OhmSpectator — APPROVED** [review]

**Pull request merged**
