### PR TITLE
Implement EVE AppStatus Led blinks

### PR DESCRIPTION
**Pull request by ppallap**
This commit only supports model SIEMENS AG.SIMATIC IPC127E
	Uses LED 3 (the one labeled as L3 MAINT) for application state.
	1) If no application has even started booting that LED will be off.
	2) If one or more applications is in error state, then the LED will be solid red.
	3) If there is no error
		If EVE has moved all of the applications to the booted or running state, then solid green
		If some applications are in the halting state, then blinking orange.
		If some applications are in the init state, then blinking green.

Signed-off-by: Pramodh Pallapothu  <pramodh@zededa.com>

### CODE REVIEW

**Comment by ppallap** [comment]
This commit implements feature proposed here:
https://wiki.lfedge.org/display/EVE/Display+EVE+application+status+using+LEDs

**Review by eriknordmark — APPROVED** [review]
Let it test

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by rvs** [comment]
Hey @ppallap -- sorry for coming late to this -- LGTM, but I'd like to request that you update [files in `docs/` folder](https://github.com/lf-edge/eve/blob/master/docs/LED-INDICATION.md)  based at least on this snippet in the proposal:

Can you please send a separate PR with that?

```
Mapping to IPC127
Suggestion is to use LED 3 (the one labeled as L3 MAINT) for application state.

If no application has even started booting that LED will be off. 
If one or more applications is in error state, then the LED will be solid red.
If there is no error
If EVE has moved all of the applications to the booted or running state, then solid green
If some applications are in the halting state, then blinking orange.
If some applications are in the init state, then blinking green.
```

**Comment by ppallap** [comment]
Hi @rvs - yes will submit a new PR for doc update.

**Pull request merged**
