### PR TITLE
Bump dom0-ztools: disk group change

### PR DESCRIPTION
**Pull request by andrewd-zededa**
part 2 of https://github.com/lf-edge/eve/pull/3996

### CODE REVIEW

**Comment by andrewd-zededa** [comment]
ok, amd64 build jet failed not related to the change:
```
#3 resolve image config for docker.io/docker/buildkit-syft-scanner:stable-1
Error: error building "lfedge/eve-acrn-kernel:ea77a29869f19dfd83e1ca495099013b0df746f1": error building for arch amd64: failed to solve: DeadlineExceeded: failed to do request: Head "https://registry-1.docker.io/v2/docker/buildkit-syft-scanner/manifests/stable-1": dial tcp 54.196.99.49:443: i/o timeout
2024/06/26 07:08:40 error during command execution: error building "lfedge/eve-acrn-kernel:ea77a29869f19dfd83e1ca495099013b0df746f1": error building for arch amd64: failed to solve: DeadlineExceeded: failed to do request: Head "https://registry-1.docker.io/v2/docker/buildkit-syft-scanner/manifests/stable-1": dial tcp 54.196.99.49:443: i/o timeout
make: *** [Makefile:1019: eve-acrn-kernel] Error 1
Error: Process completed with exit code 2.
```

go tests still having issues but havent dug in all the way yet

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
The go tests are failing because we failed to build in master (due to bpftrace not building)
@christoph-zededa I'm re-running https://github.com/lf-edge/eve/actions/runs/9674377506 to see if the bpftrace build passes on a second try.

**Comment by milan-zededa** [comment]
Looks like the ZFS/volumes test is fixed by this.

**Pull request merged**
