### PR TITLE
accept hashes when pulling from containerd

### PR DESCRIPTION
**Pull request by deitch**
When pulling packages from a registry, it is standard to check the hashes when they are pulled to make sure they are valid and unchanged. The hashing is expensive but necessary.

When pulling from a local containerd, it is an unnecessary expensive process.

This tells the puller - when creating VM volumes from locally stored VM images, or when creating a new baseos image on a device - to just trust containerd's hashes and not recalculate them. This cuts the processing time for larger images by a factor of 4-6 or more.

### CODE REVIEW

**Review by rvs — APPROVED** [review]
LGTM -- let run Eden and Ring0

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by deitch** [comment]
@rvs do you understand the error from eden? It is [here](https://github.com/lf-edge/eve/pull/1638/checks?check_run_id=1376575026), with the relevant output:

```
        # Send command to update eveimage (4.696s)
        > message 'EVE update request'
        message: EVE update request
        > eden -t 10m controller edge-node eveimage-update file:///home/runner/work/eve/eve/dist/default-eve/rootfs-5.12.4-kvm-amd64.squashfs -m adam://
        [stdout]
        time="2020-11-09T21:47:37Z" level=info msg="new datastore created a7f27bdf-a63e-4c40-be5e-115275f5f9d6"
        time="2020-11-09T21:47:37Z" level=info msg="Start uploading into eserver of file:///home/runner/work/eve/eve/dist/default-eve/rootfs-5.12.4-kvm-amd64.squashfs"
        time="2020-11-09T21:47:41Z" level=info msg="Waiting for SHA256 calculation"
        time="2020-11-09T21:47:41Z" level=info msg="Image uploaded with size 234 MB and sha256 d2c9c683bfa946486b489cd0fccd60ac8db1ad3c04bc70d37ef89954dd551497"
        time="2020-11-09T21:47:41Z" level=info msg="new image created dc77a107-c8a1-47ba-9955-d1e0bba6ab4f"
        time="2020-11-09T21:47:41Z" level=info msg="new base os created dc77a107-c8a1-47ba-9955-d1e0bba6ab4f"
        time="2020-11-09T21:47:42Z" level=info msg="config updated /home/runner/.eden/devUUID-5961b1b8-11aa-4817-8069-4678f6d4cbf6.json"
        time="2020-11-09T21:47:42Z" level=info msg="state updated /home/runner/.eden/state-ed953dbb-13d2-48dc-874e-8be6f1325046.yml"
        # Check stderr, it must be empty (0.000s)
        > ! stderr .
        # Run monitoring of Info messages to obtain info with PartitionState inprogress or active and previously defined ShortVersion (1201.206s)
        > message 'Waiting for EVE update...'
        message: Waiting for EVE update...
        > test eden.lim.test -test.v -timewait 1200 -test.run TestInfo -out InfoContent.dinfo.SwList[0].ShortVersion 'InfoContent.dinfo.SwList[0].PartitionState:inprogress|active InfoContent.dinfo.SwList[0].ShortVersion:5.12.4-kvm-amd64'
        testProg: /home/runner/work/eve/eve/dist/bin/eden.lim.test
        [stdout]
        Log/Info/Metric Test
        === RUN   TestInfo
            lim_test.go:184: Wait for info of default number=1 timewait=1200
            testContext.go:240: WaitForProc terminated by timeout 20m0s
        --- FAIL: TestInfo (1200.00s)
        FAIL
        [stderr]
        time="2020-11-09T21:47:43Z" level=info msg="config updated /home/runner/.eden/devUUID-5961b1b8-11aa-4817-8069-4678f6d4cbf6.json"
        time="2020-11-09T21:47:43Z" level=info msg="state updated /home/runner/.eden/state-ed953dbb-13d2-48dc-874e-8be6f1325046.yml"
        [exit status 1]
        FAIL: ../update_eve_image/testdata/update_eve_image.txt:40: unexpected command failure
        
--- FAIL: TestEdenScripts (0.00s)
    --- FAIL: TestEdenScripts/update_eve_image (1230.74s)
```

**Review by eriknordmark — APPROVED** [review]
LGTM (let's see if tests run again)

**Comment by deitch** [comment]
I just pushed a minor change. There was a case where you could get a zero-size buffer passed to `io.CopyBuffer`, so I made sure that doesn't happen. Let's let the tests run, and I am testing that specific case as well.

**Comment by deitch** [comment]
Nice! All CI clean.

**Pull request merged**
