### PR TITLE
[13.4] enable vfio multifunc

### PR DESCRIPTION
**Pull request by christoph-zededa**
Backport #4394

### CODE REVIEW

**Comment by christoph-zededa** [comment]
as suggested by @OhmSpectator in https://github.com/lf-edge/eve/pull/4394#issuecomment-2514360336

but it also feels like a feature and not a bugfix, feel free to discuss ;-)

**Review by OhmSpectator — APPROVED** [review]
Test it!!

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by christoph-zededa** [comment]
> Test it!!

Will do and notify when done.

**Comment by christoph-zededa** [comment]
> > Test it!!
> 
> Will do and notify when done.

It works!

**Pull request merged**
