### PR TITLE
LTE fallback hampered by missing resolv.conf

### PR DESCRIPTION
**Pull request by eriknordmark**
The build pacthes /usr/lib/dhcpcd/dhcpcd-hooks/20-resolv.conf to get one which doesn't clobber the global /etc/resolv.conf, but does create the per-interface files.

### CODE REVIEW

**Comment by rvs** [comment]
Hey @nordmark -- lets do it during the apk build/install phase -- I think that would be a perfect middle ground. I'll send a diff a bit later today, ok?

**Comment by eriknordmark** [comment]
> Hey @nordmark -- lets do it during the apk build/install phase -- I think that would be a perfect middle ground. I'll send a diff a bit later today, ok?

Trying to wrap this up. Do you have a diff? If not I'll propose one.

**Comment by eriknordmark** [comment]
@rvs I put code in Dockerfile.in to generate the new file. Please review

**Comment by rvs** [comment]
Hey @eriknordmark -- as we've discussed yesterday -- if you could replace sed with an explicit patch file that'd be awesome.

LGTM otherwise

**Pull request merged**
