### PR TITLE
GH Action - Clean step in Publish Action

### PR DESCRIPTION
**Pull request by dautovri**
Clean step in publishing workflow. Important for self-hosted runners. 
Signed-off-by: Ruslan Dautov <dautov2@gmail.com>

### CODE REVIEW

**Review by giggsoff — APPROVED** [review]

**Review by eriknordmark — APPROVED** [review]
LGTM

**Review by rvs — CHANGES_REQUESTED** [review]
You probably need to make sure this always runs (even if the previous steps fail)

**Comment by dautovri** [comment]
> You probably need to make sure this always runs (even if the previous steps fail)

Yes, good point! Thank you, changed and added one more clean step.

**Comment by giggsoff** [comment]
> > You probably need to make sure this always runs (even if the previous steps fail)
> 
> Yes, good point! Thank you, changed and added one more clean step.

Assume we can use something like this: https://github.com/lf-edge/eve/blob/f415f206f090c8a282dee933779ca8631ffc99b9/.github/workflows/eden.yml#L104

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
