### PR TITLE
downloader: Add the image URL into the error message.

### PR DESCRIPTION
**Pull request by OhmSpectator**
In the case the URL of the image cannot be parsed for any reason, put it to the error message, so the user can see what can be the issue.

### CODE REVIEW

**Comment by rouming** [comment]
Almost good. `ociRepositorySplit()` on error path returns empty strings, so does not make any sense to print them.

**Comment by OhmSpectator** [comment]
Print only the error returned by the ociRepositorySplit function.
Add the original URL to the error message returned by the function.

**Review by rouming — APPROVED** [review]
Looks good.

**Review by eriknordmark — COMMENTED** [review]
Looks good, but is the issue only for OCI images? 
When we download from S3, Azure, https etc do we print the URL on failure?

**Comment by OhmSpectator** [comment]
> Looks good, but is the issue only for OCI images?
> When we download from S3, Azure, https etc do we print the URL on failure?

I can check it if you want. But the bug I'm fixing in the scope of this PR is an error in the debug message on the OCI URLs handling (previously it printed an empty string). It's requested by the CS team, See EV-383 for the details.

**Comment by rouming** [comment]
This one PR is a request by the CS team: show the correct url on error path. I merge this since the change does exactly what was requested.

**Pull request merged**
