### PR TITLE
pkg: grub: arm64: moving to 2.06

### PR DESCRIPTION
**Pull request by Insei**
pkg: grub: arm: moving to 2.06 

* Use grub tag instead of commit for arm64 and riscv64
* Remove duplicate patches from patches.riscv64.2.06, the same patches are in the patches.2.06 folder
* Rename patches.`<arch>`.`<version>` folders to patches-`<arch>`-`<version>`
* Replace dt fixup efi protocol patch to aarch64 patches folder.
* Use portable module list for all platforms
* Grub verify module is no longer available for build under arm with grub version 2.06 
* Now coreutils package is used for arm too

Signed-off-by: Aleksandrov Dmitriy <goodmobiledevices@gmail.com>

### CODE REVIEW

**Comment by Insei** [comment]
Not tested yet, awaiting build

**Comment by Insei** [comment]
All fixed and tested on arm  (RPi4).

**Review by rvs — APPROVED** [review]
LGTM. Let it test.

**Comment by rvs** [comment]
Actually, before I can merged this -- please make sure to kill `patches.riscv64` folder in grub pkg @Insei

**Comment by Insei** [comment]
@rvs done

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
