### PR TITLE
Fix: tty not found error for COM passthrough

### PR DESCRIPTION
**Pull request by roja-zededa**
Adding agetty in build pkgs xen-tools/Dockerfile to fix "tty not found" error

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by roja-zededa** [comment]
@eriknordmark Could you please kickoff the remaining tests?

**Comment by eriknordmark** [comment]
> @eriknordmark Could you please kickoff the remaining tests?

It passed all the eden tests earlier today. See https://github.com/lf-edge/eve/actions/runs/11445356764?pr=4391
But still running the tests which actually do serial port passthrough. Should have results in an hour or so.

**Comment by eriknordmark** [comment]
It failed with the same error as before.
But I wonder if the issue that backend = "tty" should now be backend = "serial". I'm giving that a try.

**Comment by roja-zededa** [comment]
> It failed with the same error as before. But I wonder if the issue that backend = "tty" should now be backend = "serial". I'm giving that a try.

This PR fixes the error in my local node where an app tries to have a direct attachment to the COM serial port.  Coud you please share the error trace?

**Comment by eriknordmark** [comment]
FWIW to get it to work on the devices in the lab we use for regression testing we need the backend=serial. Note that when running on a virtual platform we use backend=serial already, 
So that might be why you are not seeing the second issue?

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
