### PR TITLE
Update eve-lib and eve-api

### PR DESCRIPTION
**Pull request by rouming**
update eve-libs sha to the latest, generate vendors.

### CODE REVIEW

**Review by deitch — APPROVED** [review]

**Review by milan-zededa — APPROVED** [review]

**Comment by eriknordmark** [comment]
FWIW the unit tests are failing with
Running tests on github.com/lf-edge/eve/pkg/pillar
go: finding module for package golang.org/x/text/cases
vendor/github.com/lf-edge/eve-libs/reconciler/reconciler_api.go:13:2: cannot query module due to -mod=vendor

I'm kicking them to run again.

**Comment by eriknordmark** [comment]
FWIW the arm64 and amd64 (but not riscv) builds failed similarly:

**Comment by eriknordmark** [comment]
#0 0.066 Running go vet
#29 0.690 go: finding module for package golang.org/x/text/cases
#29 0.970 vendor/github.com/lf-edge/eve-libs/reconciler/reconciler_api.go:13:2: cannot query module due to -mod=vendor

**Comment by rouming** [comment]
The eve-api has to be updated as well. but that leads to another error in the netdump code. Probably some API incompatibility

**Comment by rouming** [comment]
Difference to the previous version:
* Also update eve-api, otherwise compilation fail
* Also fix API call in netdump.go, otherwise compilation fail (cc: @milan-zededa )

**Review by milan-zededa — APPROVED** [review]

**Comment by rouming** [comment]
Can we restart tests? not sure why they are failing

**Review by milan-zededa — APPROVED** [review]

**Comment by milan-zededa** [comment]
I've restarted all failed checks.

**Comment by rouming** [comment]
Difference to the previous version:
* After make proto-vendor there were some new files, which had to be added. Always forget to check the git status.

**Review by milan-zededa — APPROVED** [review]

**Pull request merged**
