### PR TITLE
add a log in zedclient for tls peer certs

### PR DESCRIPTION
**Pull request by naiming-zededa**
Signed-off-by: Naiming Shen <naiming@zededa.com>
- help the debugging of issues of proxy to see if the peer has MiTM or not

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM
Do we know that this information from the cert is sufficient to identify it? I don't know how much of this the TLS proxies make up vs. preserve from the origin certificate.

**Comment by naiming-zededa** [comment]
> LGTM
> Do we know that this information from the cert is sufficient to identify it? I don't know how much of this the TLS proxies make up vs. preserve from the origin certificate.

i put some example in stories/178399431. we should be able to tell

**Comment by naiming-zededa** [comment]
copy some testing output, for the normal case, one of the certs:
"msg\":\"Peer certificate:(0) Issuer: CN=Cloudflare Inc ECC CA-3,O=Cloudflare\\, Inc.,C=US, Subject: CN=zededa.net,O=Cloudflare\\, Inc.,L=San Francisco,ST=California,C=US, NotAfter: 2022-05-30 23:59:59 +0000 UTC\"

and in a testing MiTM case, one of the certs:
msg:Peer certificate:(2) Issuer: CN=Zed Poclab,OU=Poclab,O=Zededa,L=Santa Clara,ST=CA,C=US,1.2.840.113549.1.9.1=#0c19736f6c7574696f6e2e7465737473407a65646564612e636f6d, Subject: CN=Zed Poclab,OU=Poclab,O=Zededa,L=Santa Clara,ST=CA,C=US,1.2.840.113549.1.9.1=#0c19736f6c7574696f6e2e7465737473407a65646564612e636f6d, NotAfter: 2022-05-24 08:26:26 +0000

**Review by rvs — COMMENTED** [review]
LGTM! Nice bit of telemetry!

**Pull request merged**
