### PR TITLE
[11.0-stable] pillar: Release CPUs on domain activation failure

### PR DESCRIPTION
**Pull request by OhmSpectator**
Backport https://github.com/lf-edge/eve/pull/3952 into 11.0.

### CODE REVIEW

**Comment by rouming** [comment]
@OhmSpectator don't forget to target the 12.0-stable as well.

**Review by rouming — APPROVED** [review]

**Comment by OhmSpectator** [comment]
> target


As I understand, we don't have 12.0 stable. As far as I understand, we accumulate fixes now and will make a stable release based on one of 12.* tags. And this fix is a part of 12.3. Or am I wrong?

**Comment by rouming** [comment]
We have a branch now: eve/12.0-stable. If you need to backport there - please do that as well.

**Comment by OhmSpectator** [comment]
@rouming, yep, I see it now. Will do.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
