### PR TITLE
double commit for 6.6 of azure blob PRs

### PR DESCRIPTION
**Pull request by naiming-zededa**

### CODE REVIEW

**Comment by rvs** [comment]
Hey @naiming-zededa what commits in master does this correspond to? You don't have to re-submit the PR, but in the future please do ```git cherry-pick -x XXX``` when you do branch patching. Making it MUCH easier to track what came from where.

**Comment by naiming-zededa** [comment]
> Hey @naiming-zededa what commits in master does this correspond to? You don't have to re-submit the PR, but in the future please do `git cherry-pick -x XXX` when you do branch patching. Making it MUCH easier to track what came from where.

PR#2163 and PR# 2170. right somehow last time i tried 'git cherry-pick' it failed for some reason, and i didn't figure that out

**Comment by rvs** [comment]
PRs are a GitHub construct -- I can't validate chery-picks by PR #s alone (well I can -- but that requires a lot of extra sleuthing). Next time lets make sure everything that gets submitted as a patch gets submitted via git cherry-pick -x.

Sounds good @naiming-zededa ?

**Comment by naiming-zededa** [comment]
Sure @rvs will try cherry-pick again next time

**Pull request merged**
