### PR TITLE
Added package specifier to protocols

### PR DESCRIPTION
**Pull request by fredrik-jansson-se**
I've compiled the protocols for Rust using prost (https://crates.io/crates/prost and https://crates.io/crates/prost-build). 

Prost requires a package specifier in each protocol file.

If this PR is accepted, it will be easier for other users to compile and use the protocols in prost/tonic.

### CODE REVIEW

**Comment by rvs** [comment]
This looks very reasonable @fredrik-jansson-se -- but let me build the resulting go/python/java files first to see before and after picture.

In the meantime, any chance you can share what are you planning to do with EVE Rust-wise -- I've been Rust curious for a long time and this could be an awesome project for me to start digging more.

**Comment by fredrik-jansson-se** [comment]
Hi Roman,

I think project EVE looks very interesting as a platform and I basically wanted to learn and start understanding how it works. My way of understanding stuff usually starts with reading the docs, but pretty quick comes down to coding :) so I started hacking a controller in Rust. I use the QEMU version of EVE, thanks for putting that together, makes is very simple to get started!

For almost all my hacking, I tend to use Rust (I'm an old c++ guy). I haven't gotten very far yet, and not sure I'll ever do, but it did strike me that someone else might be interested in compiling the protocols for Rust, and tonic (prost) is one of the major protobuf implementations for Rust.

So no real project yet, if that changes I'm happy to share!

**Comment by deitch** [comment]
Hi @fredrik-jansson-se . I have the Rust book sitting on my desk ever since one of the Oxide founders convinced me a while ago, and then I met some of the key Rust people at QCon London last year. I heard that Oxide is building real firmware in Rust, and I know of people using it as a primary source for wasm with real usage.

I _really_ like the idea of eve having `api/rust/` in addition to `api/go/` and `api/python/`.

As for a controller, we have a reference implementation in [adam](github.com/lf-edge/adam) so I don't know that we need another controller so much, but I don't think anyone will object either. On the other hand, if we could think of a really good use case for the API that isn't already covered, and can be built in rust, that would be a double win. Any ideas? Roman too?

**Comment by fredrik-jansson-se** [comment]
Hey, just generated the language bindings and "vendored" the go source. Tests, except yetus, pass.

**Comment by rvs** [comment]
Hi @fredrik-jansson-se -- thanks for the background and welcome to the community! Btw, you may find out Slack channels a good place to hang out as well: http://lfedge.slack.com/ (channels start with #eve-)

Btw, I'm very much in the same situation Avi is -- just looking for a good project around EVE to give it a go in Rust.

**Comment by fredrik-jansson-se** [comment]
Thanks guys! 

I'm sure we'll find a rust project! :)

**Pull request merged**
