### PR TITLE
Update linuxkit to have a fix for riscv64

### PR DESCRIPTION
**Pull request by giggsoff**
We noticed that publish workflow stuck on building of packages for riscv64. This has been resolved in https://github.com/linuxkit/linuxkit/pull/3820. Also PR includes check to rebuild linuxkit on version update.

### CODE REVIEW

**Comment by deitch** [comment]
I think he is fixing your issue @eriknordmark 

Why touch the file? Would it be easier to just report the lkt version by running it? This way `make` would know how to handle it, I guess?

**Comment by giggsoff** [comment]
> Why touch the file? Would it be easier to just report the lkt version by running it? This way `make` would know how to handle it, I guess?

I am not sure:
```
$ ./build-tools/bin/linuxkit version
linuxkit version unknown
commit: unknown
```

**Comment by giggsoff** [comment]
Let's wait for https://github.com/linuxkit/linuxkit/pull/3821, seems my previous attempt is not aligned well with our complex source tree.

**Comment by deitch** [comment]
Why is this still Draft?

**Review by deitch — APPROVED** [review]

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
