### PR TITLE
[9.4-stable] Backport timeout improvements

### PR DESCRIPTION
**Pull request by rene**
Backport to 9.4-stable the following PRs:

https://github.com/lf-edge/eve/pull/3428
https://github.com/lf-edge/eve/pull/3518
https://github.com/lf-edge/eve/pull/3509

In order to avoid unwanted triggers from watchdog.

### CODE REVIEW

**Review by rouming — APPROVED** [review]

**Comment by milan-zededa** [comment]
@rene Which change in this PR is fixing the watchdog that was observed: `"msg": "file /run/volumemgrmetrics.touch was not changed in 506 seconds (more than 500)"`

**Review by OhmSpectator — APPROVED** [review]
We need more backported fixes!

**Comment by rene** [comment]
> @rene Which change in this PR is fixing the watchdog that was observed: `"msg": "file /run/volumemgrmetrics.touch was not changed in 506 seconds (more than 500)"` ?

It won't fix @milan-zededa , I'll open another PR to fix that, anyways this PR is needed to improve the timeouts, specially the qemu img convert...

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
