### PR TITLE
Making rsyslog block on boot until it fully comes up + local loging

### PR DESCRIPTION
**Pull request by rvs**
The first commit is pretty self-explanatory -- it simply moved waitforsyslog from pillar to rsyslog package

The second commit introduces a small window of local logging under /persist/rsyslog/syslog.txt
NOTE that this is not meant to be a replacement for what us under /persist/IMGA/log but rather a window into the *current* syslog messages. Hence we don't have to put it under /persist/PARTITION

Finally, the size of syslog.txt is caped at 10Mb which means that the total storage budget for this local debug facility is 20Mb (this includes a log-rotate like capability that will rotate ~10Mb worth of local logs into  /persist/rsyslog/syslog.prev.txt and start a new /persist/rsyslog/syslog.txt)

### CODE REVIEW

**Comment by rvs** [comment]
@gkodali-zededa yup -- well actually we'll have <20Mb in two files each <10Mb

**Comment by gkodali-zededa** [comment]
> @gkodali-zededa yup -- well actually we'll have <20Mb in two files each <10Mb

Sure, that makes sense. Thanks for the patch.

**Comment by eriknordmark** [comment]
Why do we need text file if Rsyslogd already buffers?

**Comment by rvs** [comment]
Text files are mirrors (peephole if you will) of current rsyslog queues. As the PR says -- this is a very useful tool for in-place debugging (including debugging rsyslog itself) but it is NOT a replacement for full fledged controller-based log management.

Look at it this way -- when you don't see something in the logs on the controller side -- the first thing you'll check is this file.

**Comment by eriknordmark** [comment]
Great and I ve already used this file to debug things

**Pull request merged**
