### PR TITLE
alpine 3.14

### PR DESCRIPTION
**Pull request by giggsoff**
Updating eve-alpine to be based on alpine 3.14

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by giggsoff** [comment]
I am still testing it to keep all packages for our needs, but @rvs can you please tell me, should I get rid of 3.13 in this case and what to do with `EVE_BUILDER_IMAGE` and https://github.com/lf-edge/eve/pull/2160/files#diff-7c1ec7307689e5c17d29680d48109312c8a7e58c323b5e2af2c4b9dcd994ac18R8 here? I should modify/remove them in next PR?

**Comment by deitch** [comment]
Be extremely careful of the faccess2 issues with musl. 

I've got a bit of the log here at https://github.com/linuxkit/linuxkit/pull/3702

**Comment by giggsoff** [comment]
> Be extremely careful of the faccess2 issues with musl.
> 
> I've got a bit of the log here at [linuxkit/linuxkit#3702](https://github.com/linuxkit/linuxkit/pull/3702)

If I correctly understand, we need to use new `linuxkit/runc` with moving onto 3.14. Is it correct, @deitch?

**Review by rvs — CHANGES_REQUESTED** [review]
What is the goal of this PR @giggsoff ?

**Comment by deitch** [comment]
Correct. You need runc >= r95 if I recall correctly. That hasn't been merged into linuxkit due to a /dev/console issue. See linked.

**Comment by giggsoff** [comment]
> What is the goal of this PR @giggsoff ?

For example to have go 1.16 out of box.

**Comment by rvs** [comment]
Upgrading Alpine is typically pretty disruptive for us @giggsoff -- so I would say that just bumping Go wouldn't qualify (since it is SOOO easy to do it out of bound). In fact, I think we should always plan for the Alpine upgrade as part of the release planning. Hopefully we can conduct one soon.

**Comment by giggsoff** [comment]
> Upgrading Alpine is typically pretty disruptive for us @giggsoff -- so I would say that just bumping Go wouldn't qualify (since it is SOOO easy to do it out of bound). In fact, I think we should always plan for the Alpine upgrade as part of the release planning. Hopefully we can conduct one soon.

Got it, work on preparation of next steps (corrections inside packages) give me the same thoughts. Also, as Avi said, we must wait for stabilization inside linuxkit. So, I will keep it in draft for now and will subscribe on other changes to keep going.

**Comment by giggsoff** [comment]
> Correct. You need runc >= r95 if I recall correctly. That hasn't been merged into linuxkit due to a /dev/console issue. See linked.

Interesting, I do required changes in other packages https://github.com/itmo-eve/eve/commit/0c4bdbb41b471959bab2136b57f152d9365d9a44, build EVE with them and have no problems with current lkt/runc, If anybody want to try, I pushed images: `itmoeve/eve:0.0.0-pkgs-try-0c4bdbb4-xen-amd64` and `itmoeve/eve:0.0.0-pkgs-try-0c4bdbb4-kvm-amd64`.
One drawback: it is required to have docker 20.10.0+ as builder (without it I cannot build pkg/debug where we re-build musl).

**Comment by giggsoff** [comment]
> Upgrading Alpine is typically pretty disruptive for us @giggsoff -- so I would say that just bumping Go wouldn't qualify (since it is SOOO easy to do it out of bound). In fact, I think we should always plan for the Alpine upgrade as part of the release planning. Hopefully we can conduct one soon.

@rvs Can we plan our updating somehow? go 1.16 have changed default behavior of memory reclaiming: https://go-review.googlesource.com/c/go/+/267100/ which is what we need to avoid unexpected OOM.

**Comment by rvs** [comment]
Sure, but there's no way this will be a quick transition -- so for the issue you're working on -- I suggest you pull Go from their own website into our build container. I think that'd be the best option for now @giggsoff

**Comment by giggsoff** [comment]
> Sure, but there's no way this will be a quick transition -- so for the issue you're working on -- I suggest you pull Go from their own website into our build container. I think that'd be the best option for now @giggsoff

Created separate PR: https://github.com/lf-edge/eve/pull/2213

**Comment by rvs** [comment]
Should this one be closed then @giggsoff ?

**Pull request closed without merging**
