### PR TITLE
Enhance install script to support clustered-storage

### PR DESCRIPTION
**Pull request by zedi-pramodh**
1. Added new parameter eve_install_clustered_storage_sizeGB  
2. Creates a ZVOL of size eve_install_clustered_storage_sizeGB  and mounts ext4 on that volume.
3. That volume is where all k3s components persist the data. See pkg/k3s/cluster-init.sh

Tested
=======
Installation and verified all k3s  components start.

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
I think we should reverse this knob to instead be the space to reserve for the non-.
(eve_install_kubevirt_reserve_for_eve)
And as this moves closer to prodction we can presumably determine that automatically (5G for /persist/newlog and a bit more). That makes more sense than having to know how big the perist pool is.

But even today I think the install script should determine the eve_flavor and only honor this setting when that is kubevirt.

**Comment by eriknordmark** [comment]
> Sorry I did not see this comment. I am not 100% clear on your suggestion eve_install_kubevirt_reserve_for_eve. Are you saying using that parameter we reserve some space for eve components and use rest for clustered storage ?

Correct.
Then we can later figure out a reasonable non-zero default for this, and none of it will depend on the size of the total storage.

**Comment by zedi-pramodh** [comment]
Ok then why do we even need  eve_install_kubevirt_reserve_for_eve ?  Basically if it is a kubevirt hv type we can set the following defaults as part of installation.

1) ZFS reserved space (5%) 
2) EVE reserved space (say 20GB)

The rest can we used for clustered storage.  Since no customer is going to use kubevirt image for many more months we can adjust the 2) internally until we find the optimal value.

**Comment by eriknordmark** [comment]
> 2\. EVE reserved space (say 20GB)

Do we currently have an argument for this?

**Comment by zedi-pramodh** [comment]
I do not see anything in https://github.com/lf-edge/eve/blob/master/docs/BOOTING.md

**Comment by zedi-pramodh** [comment]
Tested installation:

2023-06-06 21:49:20 : EVE-OS installation started
2023-06-06 21:49:20 : Nuked partition tables on nvme0n1
2023-06-06 21:49:20 : Nuked partition tables on sda
2023-06-06 21:49:20 : Nuked partition tables on sdb
2023-06-06 21:49:25 : Installing EVE-OS on device nvme0n1
2023-06-06 21:49:25 : Installing persist on disk(s) sda,sdb
2023-06-06 21:49:25 : EVE install server : zedcloud.alpha.zededa.net
2023-06-06 21:49:25 : INFO: RANDOM_DISK_UUIDS = 
2023-06-06 21:49:25 : SKIP_ZFS_CHECKS = true
2023-06-06 21:49:25 : Kubevirt image installing ZFS and EVE reserved storage sizeGB 100
2023-06-06 21:49:25 : ZFS raid level: 
2023-06-06 21:49:29 : Installing ZFS filesystem, MULTIPLE_DISKS = true
2023-06-06 21:50:04 : Creating ZFS pool with raid level: 
2023-06-06 21:50:04 : Pool creation command:  /dev/sda /dev/sdb true 100
2023-06-06 21:50:04 : Preparing ZFS pool and mounts
2023-06-06 21:50:04 : Creating clustered-storage
2023-06-06 21:50:04 : AvailableGB : 1438  ReservedGB : 100
2023-06-06 21:50:04 : Creating clustered-storage volume of size 1338G
2023-06-06 21:50:05 : Formatting /dev/zd0 to ext4
2023-06-06 21:50:15 : mount_part PART = CONFIG DISK = nvme0n1 TARGET = /config
2023-06-06 21:50:16 : SOFT_SERIAL = 5aafe05f-8e79-4a5c-9796-c689bdbd9bf3
2023-06-06 21:50:16 : mount_part PART = INVENTORY DISK = sdc TARGET = /run/INVENTORY
2023-06-06 21:50:16 : EVE-OS installation will store report to USB inside /INVENTORY/5aafe05f-8e79-4a5c-9796-c689bdbd9bf3
2023-06-06 21:50:18 : No TPM; Generating soft device certificate
2023-06-06 21:50:24 : EVE-OS installation completed, device will now reboot/poweroff

**Comment by eriknordmark** [comment]
> I do not see anything in https://github.com/lf-edge/eve/blob/master/docs/BOOTING.md

What were you looking for? That file does show e.g., the zfs-related install grub options and you added the new option to it.

**Review by eriknordmark — CHANGES_REQUESTED** [review]
LGTM but some yetus issues to fix.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
