### PR TITLE
Revert switch to miekg

### PR DESCRIPTION
**Pull request by christoph-zededa**
Reverting this for now as internal testing ended up in crashing eve

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
Kick off tests

**Comment by christoph-zededa** [comment]
Looks to me like https://github.com/lf-edge/eve/pull/3125/commits/282e373516518e661a18b0527d2270ddb73fcad0 was merged after the build run but before the eden tests have been started.

**Review by eriknordmark — APPROVED** [review]
Kick off tests

**Comment by eriknordmark** [comment]
@christoph-zededa @milan-zededa see https://github.com/lf-edge/eve/pull/3096/files#r1155254358 for why this needs to be backed out. Only question is whether we can fix the issue before April 4th when we'll be cutting the next build, or whether we should go ahead with this back out PR.

**Comment by eriknordmark** [comment]
Actually let me pull this in so there is no need to rush a fix.

**Pull request merged**
