### PR TITLE
qemu: Enable writeback caching for volumes

### PR DESCRIPTION
**Pull request by temerkhanov**
- Enable writeback cache support in QEMU-based VMs

### CODE REVIEW

**Comment by rvs** [comment]
Hey @temerkhanov -- is there any point in merging this instead of #1567 ? In general -- I would also like to understand performance implications of both of these a bit better. Can you please elaborate in more details?

**Comment by temerkhanov** [comment]
This one is a "compatible" change which can run on all supported kernel versions. However, it uses the POSIX-compatible AIO implementation which is pthread-based with all the implications of this approach.

**Comment by rvs** [comment]
Hey @temerkhanov -- now that I merged https://github.com/lf-edge/eve/pull/1567 I am not sure what to do with this one. I guess we can just keep it here for now if the other one gives us any issues.

**Comment by temerkhanov** [comment]
We might want to push it into some branch if needed.

**Comment by rvs** [comment]
I knew this would come in handy ;-) thanks for thinking ahead @temerkhanov

**Pull request merged**
