### PR TITLE
remove dead HasEncap and Ipv4Eid

### PR DESCRIPTION
**Pull request by eriknordmark**
@gkodali-zededa The comment says this was used for VPN and LISP, but I see no use of it after LISP was removed. Do you know if VPN ever used this HasEncap to reduce the MTU?

Removing unused field and associated code since only LISP ever used this.

### CODE REVIEW

**Comment by gkodali-zededa** [comment]
@nordmark Yes, I think Srinibas used this for dealing with MTU issue in case of strongswan.

**Comment by eriknordmark** [comment]
> @nordmark Yes, I think Srinibas used this for dealing with MTU issue in case of strongswan.

@gkodali-zededa I spent some time looking through the history and I only see this being used for Mesh where only Mesh sets HasEncap and the dummy interface is only created when HasEncap. So the comment about it being used for IPsec/Cloud seems to never have been true. Thus I think we can remove it.

**Review by gkodali-zededa — APPROVED** [review]
LGTM

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
