### PR TITLE
[PROTOTYPE] Attempt to use Intel SGX seal to bound on CPU

### PR DESCRIPTION
**Pull request by giggsoff**
In order to enforce security we can try to use Intel SGX to [seal](https://www.intel.com/content/www/us/en/developer/articles/technical/introduction-to-intel-sgx-sealing.html) device key. We will remove stored device key after the first reboot and store only sealed key on disk and will unseal the key into in-memory directory
 on boot and bind this directory instead of on-disk.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
@giggsoff do you have any document which explains what the security properties would be of this approach?

**Comment by eriknordmark** [comment]
> > @giggsoff do you have any document which explains what the security properties would be of this approach?
> 
> The sdk uses [AES-GCM](https://github.com/intel/linux-sgx/blob/4887b30b519d7bfc9f5de6e6330bc0034cce3d75/common/inc/sgx_tseal.h#L106-L113), more precise [Rijndael128GCM](https://github.com/intel/linux-sgx/blob/4887b30b519d7bfc9f5de6e6330bc0034cce3d75/sdk/tseal/tSeal_internal.cpp#L83) to encrypt the input data. Information about the key is available in [SGX Programming Reference 5.4.1](https://www.intel.com/content/dam/develop/external/us/en/documents/329298-002-629101.pdf): EGETKEY instruction returns a 128-bit secret key from the processor specific key hierarchy. So the main idea here is that without non-volatile encrypted memory we can seal the data using key derived from processor fuses and store it in unencrypted storage. And we will able to unseal the data only using the same CPU.

That's cool.

It would be good to have at least an email writeup about this sent to the eve mailing list.
I'll take a closer look at the SGX document - I wonder whether we can also use this to effective node-lock /persist/vault to that CPU key hierachy by doing something similar for the vault (just trying to understand the possibilities here.)

**Comment by mikem-zed** [comment]
it seems it is being deprecated by Intel https://www.techspot.com/news/93006-intel-sgx-deprecation-impacts-drm-ultra-hd-blu.html

**Comment by rouming** [comment]
As mentioned by @mikem-zed SGX Intel has deprecated SGX in the 11th, 12th generations of Core processors:
https://github.com/intel/linux-sgx/issues/760#issuecomment-1023896658
@giggsoff @eriknordmark seems PR can be closed

**Comment by giggsoff** [comment]
I put my report on Intel SGX here: https://wiki.lfedge.org/display/EVE/Intel+SGX+usage+to+seal+sensitive+data+using+fuses+of+CPU. This PR is just a prototype, so feel free to close.

**Pull request closed without merging**
