### PR TITLE
[12.0-stable] pillar/assignableadapters: clear error strings

### PR DESCRIPTION
**Pull request by christoph-zededa**
1. create two usb adapters with collision
2. change the usbaddr of one of the adapters

now the collision should be gone, but
as the error string for both adapters has been set, it was not cleared

### CODE REVIEW

**Review by OhmSpectator — APPROVED** [review]
Could you please use the `-x` when cherry-picking commits?
It's minor. Rather than that - fine.

**Comment by OhmSpectator** [comment]
@christoph-zededa don't we have to port it into 11.0-stable?

**Comment by christoph-zededa** [comment]
> @christoph-zededa don't we have to port it into 11.0-stable?

I don't see the affected code in `11.0-stable`

**Comment by OhmSpectator** [comment]
@christoph-zededa can we close this PR for now, if you want to replace it with a new one?

**Comment by christoph-zededa** [comment]
> @christoph-zededa can we close this PR for now, if you want to replace it with a new one?

I will use this PR, but now it is in draft.

**Review by OhmSpectator — COMMENTED** [review]
Could you please take the commit hash from the master branch, not from the original feature branch?

**Comment by christoph-zededa** [comment]
> Could you please take the commit hash from the master branch, not from the original feature branch?

done

**Review by OhmSpectator — APPROVED** [review]
Let's ignore the Yetus complaints, as the commit cherry-picked one-to-one.
Running the tests

**Pull request merged**
