### PR TITLE
Issues templates of better organization

### PR DESCRIPTION
**Pull request by dautovri**
Issue templates are helpful when you want to provide guidance for opening issues while allowing contributors to specify the 
content of their issues.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

Signed-off-by: Ruslan Dautov <dautov2@gmail.com>

### CODE REVIEW

**Comment by rvs** [comment]
Hey @kgiori can you please click https://github.com/dautovri/eve/issues then "New Issue" and see if the proposed workflow makes sense to you?

**Comment by kgiori** [comment]
> Hey @kgiori can you please click https://github.com/dautovri/eve/issues then "New Issue" and see if the proposed workflow makes sense to you?

Makes sense except I was a little confused on the meaning of the bullet items. I responded...

**Comment by dautovri** [comment]
> > Hey @kgiori can you please click https://github.com/dautovri/eve/issues then "New Issue" and see if the proposed workflow makes sense to you?
> 
> Makes sense except I was a little confused on the meaning of the bullet items. I responded...

@kgiori, thank you for your points. Please have a look. https://github.com/dautovri/eve/issues 
I added your changes.

**Comment by rvs** [comment]
LGTM. @kgiori once your blessing is in -- we can merge this

**Comment by kgiori** [comment]
> LGTM. @kgiori once your blessing is in -- we can merge this

LGTM. It's all good now except one tweak that is independent -- the top of the security policy (linked to by the "View policy" button) should include an email of where to send the reports. I'll try to help figure out what that email address should be...

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
