### PR TITLE
 [9.4-stable] Estimating Memory Overhead Before Domain Creation

### PR DESCRIPTION
**Pull request by OhmSpectator**
It's a backport of https://github.com/lf-edge/eve/pull/3588 into 9.4.

As dependencies the following PRs are also backported: #3192, #3383, #3504.

### CODE REVIEW

**Review by eriknordmark — CHANGES_REQUESTED** [review]
If we are going to backport this then I think it makes sense to add what is needed to make it do the same thing as in master, hence adding in 
> The 9.4 version has no reworked overhead estimation introduced later by @rucoder, so I used the old implementation to get it. This implementation does not take adapters into account.

But we also need to make sure that the new and better estimation does not cause failures in the field. For the code in master we can defer full testing until we get ready for the next LTS release, but for a patch we have do to all of that testing up front.

**Comment by OhmSpectator** [comment]
> If we are going to backport this then I think it makes sense to add what is needed to make it do the same thing as in master, hence adding in

The idea was just to port the changes that take overhead into account before we creating the Domain, without porting all the changes we did since then to estimate the overhead itself. I'll try to port all the necessary patches, but they can require some extra patches to be ported as dependencies. For example, PCI-refactoring.
FYI, @rouming.

**Comment by OhmSpectator** [comment]
The list of PRs to be backported: #3504, #3383, #3192

**Comment by OhmSpectator** [comment]
The list of the commits to be backported:

Processing PR #3192...
PR #3192 - Master Hash: a5fd5dc1e67c8b69b6b67931fe5f906694acde67
PR #3192 - Master Hash: 75498fd9960fd3af2847dfef7498d64b45db490e
PR #3192 - Master Hash: 12c34eb25efc08a44db63f28805ff40e5042e6e0
PR #3192 - Master Hash: abdfbdc91d1cc144cf8baa9dad8b1486443ef2f3
PR #3192 - Master Hash: 03c915e654491cbcc35a795ac9f049000c511c79
PR #3192 - Master Hash: c2930400a0b763a93b9269b85ee32dbbe4b584de
PR #3192 - Master Hash: ca600998c7cb0ea8fe1375faf71e4baf3b0a6e39
PR #3192 - Master Hash: ca20849b5fc96db54b400f4c49508ecd2b9f3ce4
Processing PR #3383...
PR #3383 - Master Hash: 10f3ba666fe45258533c265b0e81516a5c694ca6
PR #3383 - Master Hash: c79d3fe8d57b65d0f0958219f234636dec6fb8e7
Processing PR #3504...
PR #3504 - Master Hash: c79d3fe8d57b65d0f0958219f234636dec6fb8e7

**Comment by OhmSpectator** [comment]
@eriknordmark, backporting #3192 is a pain as it involves API and vendors update... Are we 100% sure we need it?.. @rouming, as far as I understand, you do not find it helpful to solve the current user issue we are addressing in the PR?

**Comment by eriknordmark** [comment]
> @eriknordmark, backporting #3192 is a pain as it involves API and vendors update... Are we 100% sure we need it?.. @rouming, as far as I understand, you do not find it helpful to solve the current user issue we are addressing in the PR?

My concern is that we don't backport it we will have unique memory calculations in the different releases which means that reproducing/debugging/fixing any future issues in this are will be more painful since master, 9.4 and 10.4 will behave slightly differently.

**Comment by OhmSpectator** [comment]
@eriknordmark 10.4 is not a problem and I have already updated the PR, including all the necessary commit. But 9.4 has more to packport, including these API-updating commits. I still have no good idea, of how to port vendors changes...

**Comment by eriknordmark** [comment]
> @eriknordmark 10.4 is not a problem and I have already updated the PR, including all the necessary commit. But 9.4 has more to packport, including these API-updating commits. I still have no good idea, of how to port vendors changes...

One question is whether there are additional changes to the API which you don't want in the patch. If not you can just do
 cd pkg/pillar; go get -u github.com/lf-edge/eve-api
for recent builds which use eve-api.
For older ones you can apply the diffs to the proto files, commit, make proto proto-vendor; commit
(since you can't cherry-pick from eve-api into eve/api.)

**Comment by OhmSpectator** [comment]
@eriknordmark, as far as I understand, we have switched to the dedicated eve-api repo only in the 10.6 version, so here, taking into account I'm porting to 9.4, I have to regenerate proto manually...
Actually, I have already tried to do it... I'm kind of surprised that the list of the changes that appear as the result is very different from what I see in the corresponding commit here: https://github.com/lf-edge/eve/commit/12c34eb25efc08a44db63f28805ff40e5042e6e0

**Comment by OhmSpectator** [comment]
Ok, I was wrong about the list of the changes... https://github.com/lf-edge/eve/commit/12c34eb25efc08a44db63f28805ff40e5042e6e0 is an unrelated commit from another PR, just with the same title. Ok, looks fine then.

**Comment by OhmSpectator** [comment]
All the related commits from #3192, #3383 and #3504 are added.

**Comment by eriknordmark** [comment]
If a user sees an error of the form
Remaining memory bytes %d app instance needs %d"
OR
App instance needs %d bytes but only have %d; waiting for one or more halting app instances to free up %d bytes

then as a workaround they can set the   memory.apps.ignore.check config property from the controller.

**Review by eriknordmark — APPROVED** [review]
Kick of tests

**Comment by OhmSpectator** [comment]
Rebased on top of 9.4-stable. The new target version contains the fix for ARM builders that unblocks us from running ztests.

**Review by rouming — APPROVED** [review]

**Pull request merged**
