### PR TITLE
Simplifying build all tags for EVE

### PR DESCRIPTION
**Pull request by rvs**
Pretty trivial changes to build all tags scripts reflecting transition to LF Edge.

This is required to keep building on our own ARM build server.

### CODE REVIEW

**Comment by rvs** [comment]
Hey @nordmark and @deitch -- please take a look. I'd like to merge this soon so we can re-enable ARM builds on our own private server.

**Comment by deitch** [comment]
@rvs what does this file do and how is it used? I cannot find it referenced anywhere in the repo, including Makefiles or any docs.

**Comment by rvs** [comment]
This is just a helper script for (mostly home grown) CI/CD systems. Things like Circle wouldn't need it -- since they would typically build all the required branches and tags by themselves (without requiring an extra script for iterating over those).

In short -- this is an obscure script for obscure CI/CD systems. I really want to get rid of it once we migrate our ARM build to something like Drone https://discourse.drone.io/t/cant-seem-to-authenticate-with-github/4798/3

**Comment by deitch** [comment]
Ah, got it. Cool.

**Pull request merged**
