### PR TITLE
complete libs and api move to separate repo

### PR DESCRIPTION
**Pull request by deitch**
edgeview and newlog needed to wait for the previous PR with updated `pkg/pillar`. Now that is done, we can update them, and the last traces of `eve/libs` and `eve/api` are moved.

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Review by eriknordmark — CHANGES_REQUESTED** [review]
But the build is failing:
#11 26.59 vet: ./network.go:172:26: item.ACLDependList undefined (type "github.com/lf-edge/eve/pkg/pillar/types".UnderlayNetworkStatus has no field or method ACLDependList)

Maybe @naiming-zededa can take a look at that?

**Comment by deitch** [comment]
Check with @uncleDecart ; I think he knows what is going on.

**Comment by milan-zededa** [comment]
@deitch `ACLDependList` was removed during zedrouter refactoring. There are other fields that edgeview should be now using to get the same info. I will open another PR with your commit + my commit that will fix the build.

**Comment by deitch** [comment]
@milan-zededa thank you, that is fine. If you prefer a PR with a commit that just fixes the edgeview dependency on `ACLDependList`, and then I can rebase this PR on that one once it is merged in, that is fine, too. Whatever is easiest.

**Comment by milan-zededa** [comment]
> > @milan-zededa thank you, that is fine. If you prefer a PR with a commit that just fixes the edgeview dependency on `ACLDependList`, and then I can rebase this PR on that one once it is merged in, that is fine, too. Whatever is easiest.
> 
> @milan-zededa @deitch @naiming-zededa who is fixing edgeview so we can proceed?

I will try to do it this week - turned out there is more things that need to change, so a bit more work than originally expected. Then I may need help from @naiming-zededa to retest edgeview locally.

**Comment by milan-zededa** [comment]
Superseded by https://github.com/lf-edge/eve/pull/3396

**Pull request closed without merging**
