### PR TITLE
Jetson nano: make usb work

### PR DESCRIPTION
**Pull request by Insei**
Now load firmware from rootfs does not work, so I put the xusb firmware for Jetson nano in the kernel.

### CODE REVIEW

**Comment by rvs** [comment]
I don't think this would be ever acceptable @Insei -- we need to figure out a way to load it from the filesystem

**Comment by Insei** [comment]
Then we remain indefinitely without video and usb on jetson nano.

**Comment by rvs** [comment]
> Then we remain indefinitely without video and usb on jetson nano, this is sad. Close PR.

I don't see why this follows -- there are legitimate ways of making this work without polluting the kernel

**Comment by Insei** [comment]
> > Then we remain indefinitely without video and usb on jetson nano, this is sad. Close PR.
> 
> I don't see why this follows -- there are legitimate ways of making this work without polluting the kernel

But loading firmware from rootfs doesn't work.  Are there other ways?

**Pull request closed without merging**
