### PR TITLE
Added test files for files in /types

### PR DESCRIPTION
**Pull request by archishou**

### CODE REVIEW

**Comment by rvs** [comment]
Hey @archishou it looks like you need to update go.mod with testify package and also vendor it in. You can do it in one go by running:
```
   $ cd pkg/pillar
   $ go mod vendor
```
and then commit all the files it brings in as a separate commit.

Makes sense?

**Comment by rvs** [comment]
You're on the right track -- but you still need to vendor these files in  @archishou 

Like I said -- just run go mod vendor

**Comment by archishou** [comment]
I ran go mod vendor but I saw no changes to the /vendor folder it should add a directory labeled stretchr/testify inside the github.com folder correct?

**Comment by archishou** [comment]
Im not sure if I'm doing something wrong or if its something wrong with my workspace.

**Comment by archishou** [comment]
Looks like everything passed, let me know if there is anything else.

**Comment by rvs** [comment]
Hey @archishou it appears that one of the tests you contributed is failing. Can you please take a look at #82 I just filed?

**Pull request merged**
