### PR TITLE
Pull commits into 6.8

### PR DESCRIPTION
**Pull request by giggsoff**
Pull series of commits into 6.8 branch

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
Why do we need to patch "update riscv64 publish workflow with new eve-alpine
"?

**Comment by giggsoff** [comment]
> Why do we need to patch "update riscv64 publish workflow with new eve-alpine
> "?

Because we update eve-alpine inside one of commits, and we need them to be in sync (you can see the problem here https://github.com/lf-edge/eve/pull/2166).

**Comment by giggsoff** [comment]
Seems, Eden works well with changes: https://github.com/itmo-eve/eden/actions/runs/1143434938

**Review by eriknordmark — APPROVED** [review]
Let it test.

**Comment by giggsoff** [comment]
Seems we need to pull fix of port_forward test into Eden from https://github.com/lf-edge/eden/pull/656#issue-689716262, added.

**Comment by eriknordmark** [comment]
> Seems we need to pull fix for port_forward test into Eden tests directory from [lf-edge/eden#656 (comment)](https://github.com/lf-edge/eden/pull/656#issue-689716262), added.

Does it make sense doing that as part of this PR?

**Comment by giggsoff** [comment]
> > Seems we need to pull fix for port_forward test into Eden tests directory from [lf-edge/eden#656 (comment)](https://github.com/lf-edge/eden/pull/656#issue-689716262), added.
> 
> Does it make sense doing that as part of this PR?

Yes, it is bug fix

**Review by eriknordmark — APPROVED** [review]
Try getting actions to run again

**Pull request merged**
