### PR TITLE
Updating zfs initialization to accomodate /persist (as opposed to /var/persist)

### PR DESCRIPTION
**Pull request by rvs**
This is just a quick cleanup for /var/persist -> /persist migration in Dom0

### CODE REVIEW

**Comment by rvs** [comment]
Hey @eriknordmark -- I'll be trying to trigger Eden run on this one to see how it would go. Please don't approve it yet. I'd like to see how multiple approvals trigger Actions (so I approve from yet another account first).

**Review by lf-edge-eve — APPROVED** [review]
LGTM (at least to a robot)

**Comment by rvs** [comment]
Hey @eriknordmark -- looks like the Eden tests are passing -- can you please give it another approval (well unless you actually don't want to approve it ;-)) so I can see how it triggers the Action (or doesn't).

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
