### PR TITLE
Added download progress for the containers

### PR DESCRIPTION
**Pull request by zed-rishabh**
Signed-off-by: zed-rishabh <rgupta@zededa.com>

### CODE REVIEW

**Comment by zed-rishabh** [comment]
> Hahaha! This is such an elegant solution. I’ve been working with the library owners to add formal download progress, and this just bypasses the issue. Nicely done.
> 
> Of course, this doesn’t solve the percentage complete issue, does it? Even if we know total bytes downloaded, it doesn’t give us percentage, does it?

I am not sure about the percentage complete issue, what is it? I tested these changes with an ignition container of size 750MB approx. And download progress is clearly visible on UI and in logs like 12%,22%,67% so on.

**Comment by deitch** [comment]
How? This reports byte count downloaded , but for percentage you need the total expected. Where did you get that?

**Comment by zed-rishabh** [comment]
> How? This reports byte count downloaded , but for percentage you need the total expected. Where did you get that?

manifestsDescImg function in oci utils returns the size of the image along with manifest.
https://github.com/lf-edge/eve/blob/a66e3291235e26126bba82763ba1a20d7b114c90/pkg/pillar/zedUpload/ociutil/common.go#L12

**Comment by deitch** [comment]
Oh. I wrote that. I just forgot!

**Comment by zed-rishabh** [comment]
> Oh. I wrote that. I just forgot!

Yeah, we are calculating size by adding sizes in the config and layers.

**Pull request merged**
