### PR TITLE
NIM should not wait for more than 60 seconds for dhcpcd to exit. Wait…

### PR DESCRIPTION
**Pull request by gkodali-zededa**
… for 60 seconds and then issue a kill and move on

NOTE: Still testing this fix.

Signed-off-by: Gopi krishna Kodali <gkodali@zededa.com>

### CODE REVIEW

**Comment by gkodali-zededa** [comment]
> releasing

@nordmark On the setup I have seen logs being dumped with "[1708]: received SIGPIPE" log message.
1708 here is the PID of dhcpcd running on port eth1

dhcpcd release failed with the following error.
dhcpcd command [--release eth1] failed exit status 1 output sending signal ALRM to pid 1708\nwaiting for pid 1708 to exit\npid 1708 failed to exit\n

---------------------------------------------------------------------------------------------
I think there is a slight different between how dhcpcd on device is started by device and what you did as part of your experiment.
dhcpcd on device is forced to background (daemonize) immediately after start.
With your experiment it is not daemonized. This may have caused the difference in behavior.

**Comment by gkodali-zededa** [comment]
Vijay S has tested image with this fix on his setup. The nim.touch reboot issue is not seen with this fix.

**Comment by eriknordmark** [comment]
> dhcpcd command [--release eth1] failed exit status 1 output sending signal ALRM to pid 1708\nwaiting for pid 1708 to exit\npid 1708 failed to exit\n

So dhcpcdh --release already waited? Then we shouldn't need to wait but instead repeat the release and see if it works later.
I don't understand with the SIGALRM didn't work in that case.

It could be that the setting of Stdout and Stderr in the background case is plain wrong (I added that in the last round of changes just to avoid duplicate logging).

**Comment by eriknordmark** [comment]
I'd prefer determining the root cause before changing things. 
the dhcpcd source code might shine a light on whether it will be in a state where it ignores SIGLARM

**Pull request closed without merging**
