### PR TITLE
debug: Enable gpertools

### PR DESCRIPTION
**Pull request by temerkhanov**
Add gperftools to the build to facilitate memory profiling

### CODE REVIEW

**Review by rvs — CHANGES_REQUESTED** [review]
Hey @temerkhanov -- it seems that your build breaks, but on top of that I'd like to ask you two questions:
  * what usage are you envisioning for these tools -- please provide examples
  * what is the delta in size before/after in debug package
?

**Comment by temerkhanov** [comment]
gperftools is there mainly for pprof which is a useful memory profiler. Of course, we can go for massif, but having 2 memory profilers might prove convenient - especially, pprof can provide some convenient visualizations.

**Comment by rouming** [comment]
@eriknordmark can we close this? once needed - we know where to find and reopen.

**Comment by eriknordmark** [comment]
Closing based on @rouming's suggestion

**Pull request closed without merging**
