### PR TITLE
use VGA to resolve VNC issue

### PR DESCRIPTION
**Pull request by giggsoff**
In case of Windows 10 with we have problems with image via VNC
image

Change from cirros-vga to the VGA solve the problem.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by rvs — APPROVED** [review]
no reason not to try this -- let it test

**Comment by giggsoff** [comment]
Forgot to update version of package inside Dockerfile of pkg/eve. Old problem, resolved after moving to eve-alpine.

**Comment by rvs** [comment]
Hey @giggsoff -- can you please send this PR against master and I can then manually pull it into required branch after talking to Raghu

**Comment by giggsoff** [comment]
I changed base branch and rebased my branch.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by giggsoff** [comment]
> Hey @giggsoff -- can you please send this PR against master and I can then manually pull it into required branch after talking to Raghu

Hi, @rvs. Seems, that you pick wrong commit into [5.21.6](https://github.com/lf-edge/eve/commit/5bf20cffd5adca0219eddd597a8a591596dcc7c5). It has no changes inside Dockerfile. Can you please pick this one: https://github.com/lf-edge/eve/commit/fcc5d37f9cdc26acf2c825393491ffd355baba41

**Comment by giggsoff** [comment]
Seems, https://github.com/lf-edge/eve/pull/2038 also resolve the problem with versions inside Dockerfile

**Comment by rvs** [comment]
I didn't pick anything into 5.21.6 @giggsoff

**Comment by rvs** [comment]
You need to resubmit into 5.21.6 today

**Comment by giggsoff** [comment]
But it is here on the top: https://github.com/lf-edge/eve/commits/5.21.6. Do you suggest me to open PR or I can wait for https://github.com/lf-edge/eve/pull/2038?

**Comment by rvs** [comment]
Ah! So it appears that @eriknordmark pulled your master one which confused me into pulling the other into the branch :-(

**Pull request merged**
