### PR TITLE
[11.0 stable] Implement propagation of IP routes into apps via DHCP

### PR DESCRIPTION
**Pull request by milan-zededa**
It was strongly requested to make the propagation of static/connected IP routes available in the EVE 11.0 LTS version. This PR must therefore break the rule of not backporting new features (hopefully a one-time exception).

Original PR with the description of the feature: https://github.com/lf-edge/eve/pull/3690

### CODE REVIEW

**Comment by milan-zededa** [comment]
@uncleDecart I had to update EVE APIs in 11.0 and it brought also some patch envelopes changes. Hopefully it does not break anything.

**Review by eriknordmark — COMMENTED** [review]
Can you check whether there are other API additions which arrive with this and in particular whether there was some api_capability value defined between 11.0.X and the route propagation one?

**Comment by milan-zededa** [comment]
> Can you check whether there are other API additions which arrive with this and in particular whether there was some api_capability value defined between 11.0.X and the route propagation one?

Luckily there were no API capabilities added between what 11.0 has and route propagation.
API update brought few patch envelopes additions (metrics). But as I understand it, it has no effect on what is implemented in 11.0 for this feature.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
