### PR TITLE
GitHub Actions: Bump Eden version to 0.9.10

### PR DESCRIPTION
**Pull request by milan-zededa**
Release notes can be found here:
 https://github.com/lf-edge/eden/releases/tag/0.9.10

There is only one small patch fixing one of the initial steps of smoke tests.

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
@milan-zededa can you rebase this on master or otherwise twiddle it to see if that triggers the build workflow to run.

**Comment by milan-zededa** [comment]
> @milan-zededa can you rebase this on master or otherwise twiddle it to see if that triggers the build workflow to run.

So unfortunately we had to disable build workflows for PRs that make changes to workflow files: https://github.com/lf-edge/eve/pull/4051
This is due to introducing docker login into the workflow. It depends on repo secrets (dockerhub username/password), which for a PR are accessible only when its workflows are triggered with [pull_request_target](https://runs-on.com/github-actions/pull-request-vs-pull-request-target/). However, this comes with a security risk - anyone can change the workflow yml file, add step with `echo ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}` and open a PR, which would start the build actions and the secret would be revealed. To avoid this, @yash-zededa disabled build workflows for PRs that change workflow files. This is of course not ideal, because we cannot test the changes until we merge. He has some ideas how to improve this and will implement them in the near future.

**Comment by milan-zededa** [comment]
> > @milan-zededa can you rebase this on master or otherwise twiddle it to see if that triggers the build workflow to run.
> 
> So unfortunately we had to disable build workflows for PRs that make changes to workflow files: #4051 This is due to introducing docker login into the workflow. It depends on repo secrets (dockerhub username/password), which for a PR are accessible only when its workflows are triggered with [pull_request_target](https://runs-on.com/github-actions/pull-request-vs-pull-request-target/). However, this comes with a security risk - anyone can change the workflow yml file, add step with `echo ${{ secrets.RELEASE_DOCKERHUB_TOKEN }}` and open a PR, which would start the build actions and the secret would be revealed. To avoid this, @yash-zededa disabled build workflows for PRs that change workflow files. This is of course not ideal, because we cannot test the changes until we merge. He has some ideas how to improve this (run build **after** approval) and will implement them in the near future.

**Comment by eriknordmark** [comment]
Did this pass the Eden tests as good as before when run as part of the Eden PR which did this change? (Sorry can't dig it up myself - only have phone access )

**Comment by milan-zededa** [comment]
> Did this pass the Eden tests as good as before when run as part of the Eden PR which did this change? (Sorry can't dig it up myself - only have phone access )

Yes it did.

**Pull request merged**
