### PR TITLE
Debugging Volume Creation Post-Reboot through Enhanced Logging

### PR DESCRIPTION
**Pull request by OhmSpectator**
This pull request encompasses a series of commits aimed at addressing a potential issue with volume creation following a system reboot. These changes primarily revolve around enhancing logging mechanisms in various modules, with a particular focus on the volumemgr module. By improving the clarity and detail of logs, this PR seeks to facilitate easier identification and resolution of issues related to volume management post-reboot.

### CODE REVIEW

**Review by deitch — APPROVED** [review]
Ugh, I wish we did not have to do this.

**Comment by OhmSpectator** [comment]
> Ugh, I wish we did not have to do this.
I am interested in the concept of simplified debugging through the decoupling of Pillar. How exactly do you see it?
I hope it's a proper place to discuss it...

**Comment by deitch** [comment]
It isn't the right place to discuss it. Let's set up a conversation around it offline.

**Review by eriknordmark — APPROVED** [review]
This is fine with me.
An alternative would be to move some of these (like the change to TotalSize from some non-zero value) into the LogModify function for VolumeStatus, but that wouldn't capture which code did the modification. And it wouldn't help with tracking down how ContentType is set/changed.
So let's go with these changes as is.

**Pull request merged**
