### PR TITLE
Optionally set proxy when building

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

This saves the need for individual builders behind proxies to modify their `Dockerfile` to do builds; just set an environment var when running `make`

Please review @rvs; cc @jren1

**Note:** This _only_ sets it for creating the `eve-build-<USER>` image. It doesn't do the package ones yet. That requires more work, but I want this one in first, have real users (like @jren1) sign off, then we can expand to others with one more PR.

### CODE REVIEW

**Comment by rvs** [comment]
In general, LGTM (sans yetus flagged issues). I have to ask though: how do you plan on tackling the linuxkit side of it? Any (even if preliminary) ideas?

**Comment by deitch** [comment]
This is strange @rvs . I was waiting for you to review or comment, yet didn't get any GitHub notification, and it was 6 days ago. I was wondering why.

**Comment by deitch** [comment]
> sans yetus flagged issues

Those are unrelated to this build. Looks like someone made those changes at some point and ignored the yetus alerts, or yetus missed it. We shouldn't fix in this PR, but separately.

**Comment by deitch** [comment]
> how do you plan on tackling the linuxkit side of it? Any (even if preliminary) ideas?

Same approach, hopefully even same env vars. Once we get this merged in, then extend to the other ones (there are ~4 other makefiles or similar that need it in the EVE repo), and we get sign off that it works from people using proxies (e.g. @jren1), then we can push it into lkt as well.

**Comment by deitch** [comment]
Rebased. Back to you @rvs

**Comment by jren1** [comment]
Just test this patch: It can't pass all_proxy variable to docker.

test patch to show the all_proxy:
diff --git a/pkg/xen-tools/Dockerfile b/pkg/xen-tools/Dockerfile
index 713479d7..db5cd792 100644
--- a/pkg/xen-tools/Dockerfile
+++ b/pkg/xen-tools/Dockerfile
@@ -38,8 +38,15 @@ RUN mkdir -p /out
 
 WORKDIR /xen
 RUN ./configure --prefix=/usr --disable-xen --disable-qemu-traditional --disable-docs --disable-stubdom --enable-9pfs
+RUN echo http_proxy:$http_proxy
+RUN echo all_proxy:$all_proxy

then make pkg/xen-tool and I got this:
Step 18/28 : RUN echo http_proxy:$http_proxy
 ---> Running in de323a0e2ab5
http_proxy:http://lion.sh.intel.com:4097/
Removing intermediate container de323a0e2ab5
 ---> a2403363339f
Step 19/28 : RUN echo all_proxy:$all_proxy
 ---> Running in d1e637489df6
all_proxy:

**Comment by deitch** [comment]
Separate issue is that changing build-args doesn't seem to invalidate the cache.

**Comment by deitch** [comment]
Why do you need `all_proxy`, @jren1 ? It isn't a standard http/s proxy env var (unlike `http_proxy`, `https_proxy`, `no_proxy`). As far a I can tell, it is used primarily by `curl` (and its derivatives) for using a socks proxy, but `curl` also does support `http_proxy` and `https_proxy`.

In any case, it isn't part of the standard docker `build-args, see [here](https://github.com/moby/moby/blob/3735ea7b765901fbae6b96efbedda11f43cf72d9/builder/dockerfile/buildargs.go#L13-L22)

**Comment by jren1** [comment]
> Why do you need `all_proxy`, @jren1 ? It isn't a standard http/s proxy env var (unlike `http_proxy`, `https_proxy`, `no_proxy`). As far a I can tell, it is used primarily by `curl` (and its derivatives) for using a socks proxy, but `curl` also does support `http_proxy` and `https_proxy`.

When I built pkg/xen-tools, it will try to git clone git://xx trees, for example:
"
GIT=git /xen/tools/firmware/../../scripts/git-checkout.sh git://xenbits.xen.org/seabios.git rel-1.12.0 seabios-dir
Cloning into 'seabios-dir-remote.tmp'...
"
My git proxy script will use all_proxy (all_proxy = socks://xxx:1080 ), please refer to:
https://github.com/jren1/eve/blob/acrn_eve/pkg/xen-tools/oe-git-proxy

Do you have idea on how to use https_proxy or http_proxy to git clone git://  trees?
If yes, we don't need the all_proxy.

**Comment by deitch** [comment]
> My git proxy script will use all_proxy (all_proxy = socks://xxx:1080 )

Ok, I see it (thanks for the link). `all_proxy` is commonly used to refer to socks proxies, and the git cloning protocol when not http/s is a bit of a pain. Your usage of a script and socks proxy makes perfect sense.

Given that building any of these images may need to support http/https proxy (apk), or socks (non-http/s), I am going to standardize on passing all of them to all images we build. Unfortunately, `docker build` does not have `all_proxy` (the socks "standard") as a built-in build-arg, only `http_proxy`,`https_proxy`,`ftp_proxy`,`no_proxy`, so it will require adding to the `Dockerfiles, but no big deal.

I will add one update to this PR, we will merge, then extend to the others.

**Comment by deitch** [comment]
Rebased on master, and added `all_proxy` to enable handling socks proxy at build time. 

@rvs, once this passes CI (minus the 2 yetus errors that are not part of this PR and should be fixed separately), we can merge it in, then apply it to the other Dockerfiles as a separate PR, and then tackle it in linuxkit. Once that is done, anyone will be able to use any proxies at any time in the process just by setting the right env vars when running `make` commands, or by doing `make HTTP_PROXY=...` etc.

**Comment by rvs** [comment]
Hey @deitch -- so far our policy has been that if a problematic code gets touched whoever touches it is on the hook to provide a fix. I know this is sort of unfair -- but that's the only way we can keep improving.

On a more practical side -- I can't even merge easily with the checks failing

**Comment by deitch** [comment]
> I know this is sort of unfair

Heh. I don't care about the unfair per se. The parts that bother me are:

* we mix in changes to this PR that are completely unrelated to it
* it means that the prior state was not a "known good state". 

If we ran CI through the prior state, it would not pass. That is a bad place to be.

Let's get a clean separate PR for those two lines and then rebase this.

**Comment by deitch** [comment]
Done in #238 : that passes, we merge it, rebase this, all should be good.

**Comment by deitch** [comment]
Excellent. _Now_ CI passes. :-)

Let's get this merged in, I will apply to the other builds, and we will have full proxy support. Keeping our partners happy @jren1 :-)

**Comment by deitch** [comment]
Thanks @eriknordmark

**Pull request merged**
