### PR TITLE
pillar: drop pillar-patches and switch to the lf-edge/go-qemu repo

### PR DESCRIPTION
**Pull request by rouming**
We have the pkg/pillar/pillar-patches folder which main goal is to patch vendors. Now the folder contains only patches for the digitalocean/go-qemu repo. We created a fork of this repo under the lf-edge account, so this PR switches pillar to the lf-edge/go-qemu repo and drops 'pillar-patches' folder.

CC: @OhmSpectator

### CODE REVIEW

**Comment by OhmSpectator** [comment]
Looks good. I also checked the target repo of zededa/go-qemu. Looks fine.
However, I have yet to test it locally.
Thanks for switching.

**Review by OhmSpectator — APPROVED** [review]
I've tested it locally. Looks fine.
I'm curious why some dependencies have disappeared from go.sum (github.com/fatih/camelcase, github.com/digitalocean/libvirt) if we haven't changed the base version of the go-qemu repo. But as far as it works, it's fine. Apparently we just haven't run `go mod tidy` in a while.

**Comment by rouming** [comment]
> I've tested it locally. Looks fine. 

Thanks for testing that. 

> `go mod tidy` in a while.

That what I did, some forgotten leftovers presumably

**Comment by eriknordmark** [comment]
Shouldn't we ask to have this at lf-edge/eve-go-qemu instead of under zededa/go-qemu? If so, can you ask LF-Edge to create that github repo?

**Comment by rouming** [comment]
Difference to the previous version:
* Switch to the lf-edge/go-qemu, instead of the zededa account

**Review by OhmSpectator — APPROVED** [review]
I hope this time, we finally have everything in place...

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by rouming** [comment]
Difference to the previous version:
* Rebase on current master

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
