### PR TITLE
refer to the latest release of the eden tests

### PR DESCRIPTION
**Pull request by yash-zededa**
There are few changes done in the eden tests and we have a new release 0.9.3.  This PR is to bump up the release version to 0.9.3

### CODE REVIEW

**Comment by uncleDecart** [comment]
Eden 0.9.3 release [notes](https://github.com/lf-edge/eden/releases/tag/0.9.3)

Let's see how wf are running

**Review by uncleDecart — APPROVED** [review]

**Review by eriknordmark — COMMENTED** [review]
Can this effect the codereview workflow?
It failed even after a re-run:
https://github.com/lf-edge/eve/actions/runs/7020023426/job/19101848629#step:3:7
and it has been fine for a week or two.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by uncleDecart** [comment]
@eriknordmark not really, every workflow is separate job, checking their own code.

**Pull request merged**
