### PR TITLE
Introduced PubSubIntf, to abstract out PubSub module for writing simpler unit tests.

### PR DESCRIPTION
**Pull request by kalyan-nidumolu**
I changed one Publication and Subscription in zedmanager to illustrate the changes needed.
Once this is aqpproved, will go ahead and change all uses of Publication and Subscription.

Signed-off-by: Kalyan Nidumolu <kalyan@zadeda.com>

### CODE REVIEW

**Comment by deitch** [comment]
Two comments, one small, one large.

* small: by convention in go, interfaces are properly named, while implementations have longer, more descriptive names. In this case, I would call the interface `Subscription` and the specific implementation `SubscriptionImpl` or similar.
* large: we have a deeper redo awaiting signoff at #458, which includes all of the comments you and @nordmark had, and actually keeps these as concrete implementations, while making the driver an interface. 

We really should finish that off first.

**Comment by kalyan-nidumolu** [comment]
Hi Avi.. Thanks for the comments.. comments inline..

> Two comments, one small, one large.
> 
> * small: by convention in go, interfaces are properly named, while implementations have longer, more descriptive names. In this case, I would call the interface `Subscription` and the specific implementation `SubscriptionImpl` or similar.

[Kalyan] Makes sense.. If the basic structure is fine, I can make he change in the followup PR when I change all the places.. The main idea is to get a consensus on this.

> * large: we have a deeper redo awaiting signoff at #458, which includes all of the comments you and @nordmark had, and actually keeps these as concrete implementations, while making the driver an interface.
> 
> We really should finish that off first.

[Kalyan] Agree.. But that needs more careful review testing. IIUC - these are not mutually exclusive changes. The idea is to get this in first, which will allow me to get going on some unit tests. Whenever PR #458 is ready to merge, it can merge up. It will be SubscriptionImpl anyways..

**Comment by kalyan-nidumolu** [comment]
@deitch - Curious..

"small: by convention in go, interfaces are properly named, while implementations have longer, more descriptive names. In this case, I would call the interface Subscription and the specific implementation SubscriptionImpl or similar."

Curious.. Where did you see this convention? This doesn't mention such convention:
https://golang.org/doc/effective_go.html

More practically, wondering if it is worth to change the name at this point? There would be a lot of churn. The current name ( SubscriptionIntf, PublicationIntf ) are quite clear in themselves?

**Comment by deitch** [comment]
> Where did you see this convention? 

It isn’t official, but it’s used in just about every serious golang project.

**Pull request merged**
