### PR TITLE
Move measure-config to the bottom of the list

### PR DESCRIPTION
**Pull request by mikem-zed**
It would be quite risky to fix the original issue because a lot of logic must be moved  

This is not really and issue but I have created a PR to move measure-config down in the list

Signed-off-by: Mikhail Malyshev <mikem@zededa.com>

### CODE REVIEW

**Comment by shjala** [comment]
Error is still present.

**Review by eriknordmark — APPROVED** [review]
A yetus blanks item to fix, otherwise LGTM

**Comment by mikem-zed** [comment]
> A yetus blanks item to fix, otherwise LGTM

this change doesn't fix a problem completely because we generate certificates on TPM when pillar starts. so this bug was always here. However we do not run live images in production so we never seen it before

**Comment by eriknordmark** [comment]
> this change doesn't fix a problem completely because we generate certificates on TPM when pillar starts. so this bug was always here. However we do not run live images in production so we never seen it before

OK, but this order still makes more sense to me.
FWIW there is a yetus blanks complaint to fix, then we can merge this.

**Review by eriknordmark — APPROVED** [review]
LGTM but some blanks complaints

**Pull request merged**
