### PR TITLE
Removed '\n' from the logs of ipcmonitor

### PR DESCRIPTION
**Pull request by zed-rishabh**
Signed-off-by: zed-rishabh <rgupta@zededa.com>

### CODE REVIEW

**Comment by zed-rishabh** [comment]
> output

Sure, I will test it out. Thanks!

**Comment by rvs** [comment]
Hey @zed-rishabh -- any chance we can resolve this one in some way?

**Comment by zed-rishabh** [comment]
> Hey @zed-rishabh -- any chance we can resolve this one in some way?

Hey @rvs , I will verify these changes today.

**Comment by zed-rishabh** [comment]
'\n' is needed in ipcmonitor. just verified it. Closing this one.

**Pull request closed without merging**
