### PR TITLE
[WIP] LVM support for EVE

### PR DESCRIPTION
**Pull request by mikem-zed**
this is an experimental support of LVM and not a fully tested/functioning implementation. if the changes seems to risky/ugly we can at least merge it into a separate branch.

### CODE REVIEW

**Review by rvs — CHANGES_REQUESTED** [review]
Hey @mikem-zed I thought you also planned to include some changes in the pillar code for LVM support? Has it been deemed unnecessary or do you plan to do it in a separate PR or update this PR at some point?

In general -- what I see in this PR seems manageable enough (although I do have a few suggestions for refactoring). Still, before I do a proper review here -- please let me know if this is all we need or some pillar changes are still pending?

**Comment by mikem-zed** [comment]
> Hey @mikem-zed I thought you also planned to include some changes in the pillar code for LVM support? Has it been deemed unnecessary or do you plan to do it in a separate PR or update this PR at some point?
> 
> In general -- what I see in this PR seems manageable enough (although I do have a few suggestions for refactoring). Still, before I do a proper review here -- please let me know if this is all we need or some pillar changes are still pending?

@rvs Pillar changes are still required however they will be minimum. I'm going to submit a separate PR for that.

**Comment by rvs** [comment]
Hey @mikem-zed -- I'd like to know when are you planning to submit the other PR so we can take a decision on this one as well.

**Comment by rouming** [comment]
@eriknordmark @mikem-zed I assume we don't need this for now? let's close and if LVM support is needed we reopen the pr (FYI: I'm like a hostess with a broom trying to put abandoned or not used things to the cellar :)

**Comment by eriknordmark** [comment]
@mikem-zed can you close this?

**Comment by mikem-zed** [comment]
closing this one because we are not going to add LVM support to EVE

**Pull request closed without merging**
