### PR TITLE
Re-enable liburing support

### PR DESCRIPTION
**Pull request by temerkhanov**
Re-enable liburing support in master

### CODE REVIEW

**Comment by rvs** [comment]
Hey @temerkhanov -- I'm confused -- last time we tried this in master we ran into issues with our default kernel collapsing NOT when io_uring got used but simply when qemu would initialize it. Has anything changed?

**Comment by temerkhanov** [comment]
It has been fixed in the upstream code some time before 5.4.72

**Review by rvs — APPROVED** [review]
LGTM

**Comment by rvs** [comment]
Hey @temerkhanov -- as I predicted -- the PR failed:

```
[  229.267521][    C0] ------------[ cut here ]------------
[  229.268091][    C0] list_add double add: new=ffff8880203690e0, prev=ffff888022bd8ae8, next=ffff8880203690e0.
[  229.268652][    C0] WARNING: CPU: 0 PID: 0 at lib/list_debug.c:31 __list_add_valid+0x5b/0x67
[  229.269251][    C0] Modules linked in: dummy cfg80211 cdc_acm cdc_mbim cdc_ncm qmi_wwan cdc_wdm usbnet mii qcserial usb_wwan usbserial hwmon_vid [last unloaded: zlua]
[  229.269991][    C0] CPU: 0 PID: 0 Comm: swapper/0 Tainted: P        W  O      5.4.51-linuxkit #1
[  229.270603][    C0] Hardware name: Google Google Compute Engine/Google Compute Engine, BIOS Google 01/01/2011
[  229.271140][    C0] RIP: e030:__list_add_valid+0x5b/0x67
[  229.271501][    C0] Code: c7 c7 fd aa 29 82 e8 27 c4 c1 ff 0f 0b 31 c0 c3 48 39 f8 75 19 48 89 f2 4c 89 c1 48 89 fe 48 c7 c7 4d ab 29 82 e8 08 c4 c1 ff <0f> 0b eb df 48 39 fa 74 e2 b0 01 c3 48 8b 17 48 89 fe 48 8b 47 08
[  229.272502][    C0] RSP: e02b:ffffc90040003d58 EFLAGS: 00010082
[  229.272878][    C0] RAX: 0000000000000000 RBX: ffff8880203690e0 RCX: 0000000000000007
[  229.273453][    C0] RDX: 0000000000000000 RSI: ffffc90040003c2c RDI: ffff88802dc17260
[  229.273910][    C0] RBP: ffff888022bd8ae8 R08: 0000000000000000 R09: ffffffff82afddd7
[  229.274393][    C0] R10: 0000000000000016 R11: ffffc90040003043 R12: ffff8880203690e0
[  229.274982][    C0] R13: ffff888022bd8af8 R14: 0000000000000000 R15: 0000000000000000
[  229.275453][    C0] FS:  00007fc2d4c5dde8(0000) GS:ffff88802dc00000(0000) knlGS:0000000000000000
[  229.275945][    C0] CS:  10000e030 DS: 0000 ES: 0000 CR0: 0000000080050033
[  229.276476][    C0] CR2: 00007fa87687cb00 CR3: 0000000022b6a000 CR4: 0000000000040660
[  229.276954][    C0] Call Trace:
[  229.277234][    C0]  <IRQ>
[  229.277619][    C0]  list_add+0x15/0x2e
[  229.277928][    C0]  io_queue_async_work+0x68/0x9b
[  229.278271][    C0]  io_poll_wake+0xbf/0xcf
[  229.278592][    C0]  __wake_up_common+0xaf/0x113
[  229.279040][    C0]  __wake_up_common_lock+0x7a/0xb1
[  229.279390][    C0]  evtchn_interrupt+0x88/0xb9
[  229.279731][    C0]  __handle_irq_event_percpu+0x7c/0x15a
[  229.280093][    C0]  handle_irq_event_percpu+0x30/0x6f
[  229.280565][    C0]  handle_irq_event+0x38/0x56
[  229.280894][    C0]  handle_edge_irq+0xb4/0xd3
[  229.281223][    C0]  generic_handle_irq+0x20/0x23
[  229.281679][    C0]  __evtchn_fifo_handle_events+0x12f/0x16a
[  229.282050][    C0]  __xen_evtchn_do_upcall+0x47/0x73
[  229.282402][    C0]  xen_evtchn_do_upcall+0x27/0x36
[  229.282744][    C0]  xen_do_hypervisor_callback+0x29/0x40
[  229.283217][    C0]  </IRQ>
[  229.283494][    C0] RIP: e030:xen_hypercall_sched_op+0xa/0x20
[  229.283865][    C0] Code: 51 41 53 b8 1c 00 00 00 0f 05 41 5b 59 c3 cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc 51 41 53 b8 1d 00 00 00 0f 05 <41> 5b 59 c3 cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc
[  229.284898][    C0] RSP: e02b:ffffffff82403ea0 EFLAGS: 00000246
[  229.285283][    C0] RAX: 0000000000000000 RBX: 0000000000000000 RCX: ffffffff810013aa
[  229.285854][    C0] RDX: 0000000000000001 RSI: 0000000000000000 RDI: 0000000000000001
[  229.286314][    C0] RBP: 0000000000000000 R08: 0000000000000000 R09: 0000000000000000
[  229.286779][    C0] R10: 0000000000007ff0 R11: 0000000000000246 R12: 0000000000000000
[  229.287352][    C0] R13: ffffffff82a150a0 R14: ffff88802ee60640 R15: 0000000000000000
[  229.287810][    C0]  ? xen_hypercall_sched_op+0xa/0x20
[  229.288163][    C0]  ? xen_safe_halt+0xc/0x13
[  229.288493][    C0]  ? default_idle+0x1b/0x2c
[  229.288934][    C0]  ? do_idle+0xf3/0x210
[  229.289248][    C0]  ? do_idle+0x7/0x210
[  229.289560][    C0]  ? cpu_startup_entry+0x1d/0x1f
[  229.290014][    C0]  ? start_kernel+0x4f0/0x515
[  229.290345][    C0]  ? default_get_nmi_reason+0x3/0x3
[  229.290691][    C0]  ? xen_start_kernel+0x50a/0x515
[  229.291034][    C0] ---[ end trace 6823393e5da86f48 ]---
```

**Review by rvs — CHANGES_REQUESTED** [review]
The kernel crash is still in place

**Comment by temerkhanov** [comment]
We have an outdated kernel version in the master branch which doesn't have the necessary patches

**Pull request merged**
