### PR TITLE
[11.8] Bump eden workflows to 0.9.8

### PR DESCRIPTION
**Pull request by uncleDecart**
In case we want to backport patches, 0.9.3-stable branch was created Ideally it should not happen, since tests are using branch and state at which they were released, but mechanism was broken, so branch was created

CC: @deitch @eriknordmark

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
Seems like it is still looking for danger. See https://github.com/lf-edge/eve/actions/runs/7891819915/job/21537489180?pr=3761

**Comment by uncleDecart** [comment]
@eriknordmark can you run tests? Let's see how it goes

**Review by eriknordmark — APPROVED** [review]
Run eden

**Pull request merged**
