### PR TITLE
expand workflows to run on releases branches

### PR DESCRIPTION
**Pull request by giggsoff**
Seems we cannot build PRs and publish or run tests in our release branches. In this PR I expand trigger to work with them

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
Don't we need to relax this for the other workflows which restrict to master? I thought I saw the same pattern elsewhere.

**Comment by giggsoff** [comment]
> Don't we need to relax this for the other workflows which restrict to master? I thought I saw the same pattern elsewhere.

Good point, fixed

**Review by eriknordmark — APPROVED** [review]
let it test

**Review by eriknordmark — APPROVED** [review]
Run eden again

**Review by rvs — COMMENTED** [review]
LGTM

**Pull request merged**
