### PR TITLE
Update edge-view and newlog to use EVE APIs from the new repo

### PR DESCRIPTION
**Pull request by milan-zededa**
Moving edgeview and newlog from `lfedge/eve/api` to `lfedge/eve-api`.

Some pillar/types on which Edgeview depends were changed during the Zedrouter refactoring. Please note that these types
are not persisted, so we do not concern ourselves with backward compatibility (as it would significantly limit development).
~~Therefore, it is crucial to use the correct version of Edgeview when connecting to a device with a particular EVE version (for all Edgeview commands to work properly).~~ The Edgeview changes done in this PR only affects the server side, meaning that users will not have to update the client-side container.

Supersedes PR https://github.com/lf-edge/eve/pull/3380

### CODE REVIEW

**Review by deitch — APPROVED** [review]
LGTM.

**Review by christoph-zededa — APPROVED** [review]

**Review by eriknordmark — APPROVED** [review]
LGTM

**Review by naiming-zededa — APPROVED** [review]
LGTM

**Comment by milan-zededa** [comment]
Marking this as stable since without the second commit of this PR, the `app` command of the edgeview will not work on EVE 10.4.0.
Still keeping this as draft until I have completed testing...

**Comment by milan-zededa** [comment]
Tested Edgeview, specifically the `app` that is updated by the PR and all seems to be working fine. Also did some formatting improvements for the output of this command for better readability.

**Pull request merged**
