### PR TITLE
Support user-selected probe method for cellular ports

### PR DESCRIPTION
**Pull request by milan-zededa**
With recent API enhancements, user is able to select cellular network probing method (ICMP or TCP, possibly more in the future).
Previously, it was possible to enter only IP address and always use ICMP to probe the connectivity status.

See: https://github.com/lf-edge/eve-api/blob/106b1d6b72e6d27e8ad4a8f5e23dea49e368a2a7/proto/config/netconfig.proto#L114-L132

### CODE REVIEW

**Comment by milan-zededa** [comment]
It seems that Yetus/golangcilint does not support Go 1.22
However, we are already using this Go version for pillar and I would like to keep it unified across packages.

**Review by eriknordmark — APPROVED** [review]
LGTM
Do we check that a port is always set for the TCP probes? I didn't see a default TCP port in the diffs.

**Comment by eriknordmark** [comment]
FWIW in attempt 2 yetus failed with golangcilint
pkg/wwan/mmagent/level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: go: downloading go1.22 (linux/amd64)\ngo: download go1.22 for linux/amd64: toolchain not available\n"
pkg/wwan/mmagent/level=warning msg="Failed to discover go env: failed to run 'go env': exit status 1"

**Comment by milan-zededa** [comment]
> LGTM Do we check that a port is always set for the TCP probes? I didn't see a default TCP port in the diffs.

Yes, port number is required for TCP probe and we do not have default value: https://github.com/lf-edge/eve/blob/master/pkg/pillar/cmd/zedagent/parseconfig.go#L565

**Pull request merged**
