### PR TITLE
Introducing versioned rootfs

### PR DESCRIPTION
**Pull request by rvs**
This is just a preview for now -- please let me know what do you think @eriknordmark @deitch @kalyan-nidumolu (I need to add one more tweak before it can be merged)

These two commits introduce a versioned rootfs and get rid of ugly hacks for NEW_KERNEL and rpi builds.

Now, all the rootfs images share the common core rootfs.yml.in which can be further tweaked (by providing real, honest patches under images/) into hypervisor specific rootfs images.

Once everything is said and done, under dist/ARCH/installer you'll get:
   * rootfs.img -> rootfs-HYPERVISOR.img
   * rootfs-HYPERVISOR.img -> rootfs-FULL_VERSION.img

Obviously, symlinks are maintained based on the latest builds

### CODE REVIEW

**Comment by deitch** [comment]
I do like the change - there was too much inconsistency in the naming structures, getting hard to grasp - and I also like the moving of `NEW_KERNEL` versioning and such out of `parse-pkgs.sh`. I also like how there no longer needs to be a special target in the `Makefile` for `pkg/kernel`; it is like all the other `pkg/%` targets.

I think it would have been better to have the `parse-pkgs.sh` / `pkg/kernel/` cleanup and the rootfs versioning in two distinct PRs, but so be it.

The only part that bothers me is the `.patch` files. I don't object to patch files per se, but I have some issues with it in this use case:

* yml (and json) lend themselves quite well to jsonPatch and its variants (see what kubernetes does in this space, especially with its strategic-merge patch), and so we could have files that say just, "add these in to this section". 
* the `rootfs.yml.in` still is "Xen-ish first" and "acrn (or other hypervisors) modify me." I think `rootfs.yml.in` should be neutral, nothing Xen-specific in there, only the completely common stuff, and each modifier (acrn, rpi,kvm, xen, whatever) should have a patch that adds what it needs.

For example, looking [here](https://github.com/lf-edge/eve/pull/849/files#diff-40e351dbf49aaf2cca71b542885e3954R6), it has to "replace" `KERNEL_TAG` with `ACRN_KERNEL_TAG`, or [here](https://github.com/lf-edge/eve/pull/849/files#diff-40e351dbf49aaf2cca71b542885e3954R24) it has to remove `xen-tools`. Instead, there should be nothing there, and `rootfs-xen.yml.in.patch` can add in `xen-tools` if it is needed.

It makes them all equal citizens, but it also makes the patch files much simpler.

For now, I would just do the latter - make the patches equal across the board - and we can look at simpler and more robust patching alternatives after this PR merges in.

**Comment by deitch** [comment]
Also builds are failing.

**Comment by rvs** [comment]
> I think it would have been better to have the parse-pkgs.sh / pkg/kernel/ cleanup and the rootfs versioning in two distinct PRs, but so be it.

@deitch your wish is my command ;-) #852 is a separate new-kernel one

> yml (and json) lend themselves quite well to jsonPatch and its variants (see what kubernetes does in this space, especially with its strategic-merge patch)

I am super curious about this approach. Tell you what, let me merge this one with a good ol' patch, but can you please provide me with info on how we can apply this k8s like ymlpatch thing to what we do?

**Comment by rvs** [comment]
Btw @deitch another alternative I was considering is to use something like mustache template for a single rootfs definition file that would be customized through sections of the said template.

What do you think?

**Comment by rvs** [comment]
Last call on this @eriknordmark @deitch -- likely to merge this today.

**Comment by deitch** [comment]
> your wish is my command ;-) #852 is a separate new-kernel one

:-) 

Thanks, it made it much easier to review them.

**Comment by deitch** [comment]
> I am super curious about this approach. Tell you what, let me merge this one with a good ol' patch, but can you please provide me with info on how we can apply this k8s like ymlpatch thing to what we do?

Will do. I will open a simple PR for it as soon as I can find some breathing room in the next few days.

**Comment by deitch** [comment]
And, yes, definitely cool with merging this with patch files and then considering an alternate approach after; incremental is the best.

> the rootfs.yml.in still is "Xen-ish first" and "acrn (or other hypervisors) modify me." I think rootfs.yml.in should be neutral, nothing Xen-specific in there, only the completely common stuff, and each modifier (acrn, rpi,kvm, xen, whatever) should have a patch that adds what it needs.

You didn't respond to this.

**Comment by rvs** [comment]
> the rootfs.yml.in still is "Xen-ish first" and "acrn (or other hypervisors) modify me." I think rootfs.yml.in should be neutral, nothing Xen-specific in there, only the completely common stuff, and each modifier (acrn, rpi,kvm, xen, whatever) should have a patch that adds what it needs.

@deitch actually it isn't that Xen specific (aside from pulling Xen binary itself) xen-tools are currently being used by KVM.

I guess what I'm trying to say is that while I agree with this point it is not just a simple matter of rootfs manifest update at the moment -- it is more of a fundamental refactoring (that I'm happy to do, btw -- but not as part of this PR).

**Comment by deitch** [comment]
> that Xen specific (aside from pulling Xen binary itself) xen-tools are currently being used by KVM

Fair enough. OK, I was looking at it just from the perspective of `rootfs.yml`.

**Comment by deitch** [comment]
> I will open a simple PR for it

Better yet, I will open an issue for discussing it correctly.

**Pull request merged**
