### PR TITLE
Sorting storage config and status before comparing

### PR DESCRIPTION
**Pull request by zed-rishabh**
Storage disks in the config and status can be in any order, it is not necessary
that they will be available in the same order. So before starting comparision, we
need to sort both config and status structures. Currently, we are sorting on the
basis of Image UUID.

Signed-off-by: zed-rishabh <rgupta@zededa.com>

### CODE REVIEW

**Comment by zed-rishabh** [comment]
If it looks good, I will do the same for the rest of the files.

**Comment by kalyan-nidumolu** [comment]
What tests did u run? Can you provide the EveImageCheck link?

**Comment by zed-rishabh** [comment]
> What tests did u run? Can you provide the EveImageCheck link?

EveImageCheck no. 45, currently in the queue. I will update the link once it will be done.

**Comment by zed-rishabh** [comment]
> I wouldn't have an issue with sorting things locally to perform the comparison by doing a deep copy of the slices. But here you are sorting the config (and status) which will change the order in which the virtual disks and vifs are presented to the domU. You can't do that. It can break the domU in terrible ways, corrupt data on the virtual disks, violate security assumptions when the domU has multiple network interfaces with different properties.)
> 
> Is there a bug where the current comparison (of the unsorted lists) is causing an issue?
> 
> Was this introduces by zedcloud starting to sort these arrays? (I think that needs to be backed out FWIW for the same reasons.)

@eriknordmark No, I am not facing any issues with unsorted data. The thinking was why EVE is dependent on the order sent by the controller. A controller can send data in any order in config and EVE will sort it at its end. But if these changes can cause issues, we can close this PR.

**Comment by rvs** [comment]
Yeah @zed-rishabh -- I think this needs to be closed and the contract with the cloud ordering needs to be enforced

**Comment by zed-rishabh** [comment]
> Yeah @zed-rishabh -- I think this needs to be closed and the contract with the cloud ordering needs to be enforced

@rvs Ok, Thanks!

**Comment by kalyan-nidumolu** [comment]
Ah.. Thanks for pointing out.. Missed it.. I was mainly thinking as an
optimization for detecting the changes

The main issue here, if we change the order is - We are mapping the volumes
provided to the mount points provided by the Manifest in order. That would
be broken..

Thanks,
Kalyan

**Pull request closed without merging**
