### PR TITLE
native pcap - no more CGO

### PR DESCRIPTION
**Pull request by deitch**
A small PR with a big impact.

* Remove zedbox's dependency on github.com/google/gopacket/pcap, replacing it with github.com/packetcap/go-pcap . This eliminates any CGO dependency
* Remove libpcap and libpcap-dev from the Dockerfiles
* Change `CGO_ENABLED=0`

When this is done, we will be able to get cross-compilation of pillar with just changing the `GOOS` or `GOARCH`. This means building locally on Mac or Linux, etc., support for lots of different devices, and more things.

@adarsh-zededa is running initial tests. If @kalyan-nidumolu or @rvs or @eriknordmark knows how to test the DNS filtering - which is the main affected area - please do so.

### CODE REVIEW

**Comment by deitch** [comment]
FYI, the filters in use - especially the ones for `status.Type == types.NetworkInstanceTypeSwitch` - have not been fully tested. I will get it into go-pcap if needed.

**Comment by deitch** [comment]
Already seeing an issue with the filter. Please hold on testing.

**Comment by deitch** [comment]
Note: Change in size of `zedbox`:

* old size  : 55877584
* new size: 52413962

**Comment by eriknordmark** [comment]
> @adarsh-zededa is running initial tests. If @kalyan-nidumolu or @rvs or @eriknordmark knows how to test the DNS filtering - which is the main affected area - please do so.

@naiming-zededa Do you have some instruction for how to test the DHCP/DNS snooping feature?

**Comment by naiming-zededa** [comment]
@eriknordmark no automated testing. was inside App, doing nslookup to various places and monitor the log message from the DNS snooping; and for dhcp, the app with switch-net, see if we get IP address in UI in both NetworkInstance page, and also the App page itself (there is a bug i need to fix in this area, Vijay reported that)

**Comment by deitch** [comment]
I had no idea how to test that. I know there is an issue with the specific filters we use (see [here](https://github.com/lf-edge/eve/pull/756#issuecomment-600043661)), but once that is in place, I didn't know how to test.

**Comment by naiming-zededa** [comment]
@deitch let me import your patch, and try to play with some apps to see.

**Comment by deitch** [comment]
@naiming-zededa hold on for a few days until I can fix those filters

**Comment by naiming-zededa** [comment]
@deitch sure

**Comment by rvs** [comment]
This is really awesome @deitch -- very much looking forward for this to merge soon! Big deal for us to be able to have native go builds

**Comment by deitch** [comment]
@rvs wrote:

> very much looking forward for this to merge soon! Big deal for us to be able to have native go builds

It has been on my todo list for a long time. I have been gathering up the pieces slowly. Your breaking out of lisp into a separate container helped.

I got the last pieces in @naiming-zededa @adarsh-zededa . Once CI clears, this should be good for testing. Also rebased on latest master.

**Comment by deitch** [comment]
CI all clear!

**Comment by naiming-zededa** [comment]
@deitch I have tested your pcap branch on my device, both DNS snooping and DHCP snooping works as before.

**Comment by rvs** [comment]
This is awesome @naiming-zededa 

Hey @eriknordmark if you don't have any further objections -- I'll be merging it ASAP

**Pull request merged**
