### PR TITLE
add a queuelock to be used by nim

### PR DESCRIPTION
**Pull request by eriknordmark**
Will use this to make sure that nim does one activity at a time (verify current DPC, test a new DPC, update DPCL based on new config from zedagent etc).

### CODE REVIEW

**Comment by rvs** [comment]
LGTM

**Comment by rvs** [comment]
Quick question @eriknordmark -- what do you plan to use specifically for in min? Can you give a brief summary of operations that are currently suffering without this in place?

**Comment by eriknordmark** [comment]
> Quick question @eriknordmark -- what do you plan to use specifically for in min? Can you give a brief summary of operations that are currently suffering without this in place?

We have lots of complexity in nim due to things like testing a new DevicePortConfig at index zero (which is a multi-step process waiting for DHCP etc) and while doing that zedagent provides a new DevicePortConfig, which becomes the new index zero.
To handle this nim has code to check if the entry that was tested moved etc.

The thrird activity we do is to periodically verify that the connectivity still works, and the forth is to check (if we are not running the highest priority DevicePortConfig) if a higher priority DPC is now working.
queuelock will be used to ensure that we do one of those at a time.

**Comment by gkodali-zededa** [comment]
LGTM

**Pull request merged**
