### PR TITLE
Makefile: run tests with race condition detection

### PR DESCRIPTION
**Pull request by christoph-zededa**
this change runs go tests with '-race' in order
to find race conditions between go routines

### CODE REVIEW

**Comment by eriknordmark** [comment]
@milan-zededa looks like this is finding some potential issues in uplinkprober code.

**Comment by eriknordmark** [comment]
Should we rebase this and try it again @christoph-zededa ?

**Comment by christoph-zededa** [comment]
> Should we rebase this and try it again @christoph-zededa ?

Still see something with:
* uplinkprober 
* attestation
* pubsub

Shall I close the PR and create a new one instead of letting this hang around?

**Comment by milan-zededa** [comment]
Somehow I missed this.. I will check the uplinkprober UTs.

**Comment by eriknordmark** [comment]
@shjala can you look into the attestation ones?

**Comment by milan-zededa** [comment]
Fix for uplinkprober test: https://github.com/lf-edge/eve/pull/3339

**Comment by shjala** [comment]
@eriknordmark sure.

**Comment by eriknordmark** [comment]
Looks like we need to fix at least the RestartCounter in pubsub to use locks/atomics. But there might be some additional data race there as well.

**Comment by shjala** [comment]
@christoph-zededa could you do a rebase?

**Comment by rouming** [comment]
@christoph-zededa ping?

**Comment by christoph-zededa** [comment]
@rouming clonk.

```
✖  pubsub (22.544s)
✖  dpcmanager (1m56.44s)
```
still pubsub has the race condition ...

**Comment by christoph-zededa** [comment]
> @christoph-zededa could you do a rebase?

sry, @rouming just reminded me; now it is rebased.
The fix by @milan-zededa fixes the uplinkprober issue successfully.

**Comment by milan-zededa** [comment]
@christoph-zededa I will have a look at `TestDPCWithReleasedAndRenamedInterface`

**Review by milan-zededa — APPROVED** [review]

**Review by eriknordmark — APPROVED** [review]
LGTM
Are there issues or stories to fix the tests listed as broken in go-test.sh?

**Pull request merged**
