### PR TITLE
do not sync in reboot

### PR DESCRIPTION
**Pull request by giggsoff**
Reboot may hang during sync and go beyond our timeout

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by rvs — APPROVED** [review]
LGTM

**Review by eriknordmark — COMMENTED** [review]
I wonder whether it would be safer to kick of a sync() from a separate goroutine (to make sure it doesn't block) and not completely get rid of the sync.

**Comment by eriknordmark** [comment]
> I wonder whether it would be safer to kick of a sync() from a separate goroutine (to make sure it doesn't block) and not completely get rid of the sync.

I just verified and we already do a syscall.Sync in agentlog.RebootReason so that should be sufficient.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
