### PR TITLE
Create a new encrypted folder /persist/vault

### PR DESCRIPTION
**Pull request by cshari-zededa**
- Right now creating an empty folder
 - This is part of staging effort to move all edge container app bits (images/volumes) into a single encrypted folder

Signed-off-by: Hariharasubramanian C S <cshari@zededa.com>

### CODE REVIEW

**Comment by rvs** [comment]
Hey @cshari-zededa -- see my comments on your doc -- I don't think "move all" strategy will work for us. This needs to be tied into Volume manager functionality.

Now, I'll let you decide whether you need to create this folder to begin with or not (up-front setting up may need to be done out of vaultmngr) but lets first talk about e2e here before we embark on a particular path. @eriknordmark @deitch and @adarsh-zededa are probably folks who need to be pulled into this convo as well.

**Comment by deitch** [comment]
>  I don't think "move all" strategy will work for us

Huh? All I see here is a new vault being set up?

**Comment by rvs** [comment]
I was reacting to the following part of the description:

> This is part of staging effort to move all edge container app bits (images/volumes) into a single encrypted folder

Makes sense @deitch ?

**Comment by deitch** [comment]
Yup.

**Pull request merged**
