### PR TITLE
kernel: add support for cellular modems in arm64 builds

### PR DESCRIPTION
**Pull request by Insei**
Not tested yet, but in theory this is all we need to support cellular modems in arm64 builds

Signed-off-by: Aleksandrov Dmitriy <goodmobiledevices@gmail.com>

### CODE REVIEW

**Comment by milan-zededa** [comment]
Thanks @Insei, will give it a try and put a feedback here...

**Comment by rouming** [comment]
@rene @Insei folks, since you work with arm now, any chances this can be verified and merged? I don't think we need to keep this pr open (otherwise it will be never closed) if no one is interested in this cellular modems. Once there is a requirement (or user) - it is not a rocket science to enable these kernel options and get it merged.

**Comment by milan-zededa** [comment]
@rouming I will test it later this week. This came from me actually, just to be able to test LTE modem with RPi4.

**Comment by rouming** [comment]
@milan-zededa thanks for clarification. Once tested please don't forget to publish results here: do me merge or close.

**Comment by rouming** [comment]
@milan-zededa did you have any chances to test this?

**Review by milan-zededa — APPROVED** [review]
Tested using RPI4 with Sierra Wireless EM7565 LTE modem connected over USB and wwan connectivity worked without issues.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Pull request merged**
