### PR TITLE
[WIP] Just a fail test

### PR DESCRIPTION
**Pull request by zed-sadov**
Signed-off-by: Oleg Sadov <oleg@zededa.com>

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
@zed-sadov Is this something you want to merge? Or have it be approved so it will run through the eden tests?

**Comment by zed-sadov** [comment]
@eriknordmark -- it's just for test:
https://www.pivotaltracker.com/story/show/176909592/comments/222482788
The EDEN test workflow should have a predictable failure at the beginning and we should see annotated diagnostics.

**Review by rvs — APPROVED** [review]
LGTM. Let it test then @zed-sadov @eriknordmark

**Comment by rvs** [comment]
Hey @zed-sadov -- please take a look -- is this the output you're expecting?

**Comment by zed-sadov** [comment]
I still don't understand what we expecting. Is it good for you?

**Comment by rvs** [comment]
Well it isn't just me @sadov -- do you think YOU can quickly diagnose what is Eden complaining about looking at the annotations alone?

**Pull request closed without merging**
