### PR TITLE
Split zfs pool info to zfsmanager

### PR DESCRIPTION
**Pull request by giggsoff**
We should not depend on info publishing interval for sending zfs pool
status info. So we should split data structures filling and call info
publishing on change.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by zedi-pramodh** [comment]
Does these changes effect anything we are display in Zedcloud now ? I mean does zedcloud and UI interfaces need to change because of this change ?

**Comment by giggsoff** [comment]
> Does these changes effect anything we are display in Zedcloud now ? I mean does zedcloud and UI interfaces need to change because of this change ?

No, change affect internal logic in EVE

**Comment by rvs** [comment]
LGTM

**Pull request merged**
