### PR TITLE
[8.12 stable] Bump kernel 5.10.186

### PR DESCRIPTION
**Pull request by rouming**
We have a suspect on memory leak in skbuf extension in the kernel, which might be fixed in quite a leak fixes commits (the log between 5.10.76 .. 5.10.186). And in general this is a good practice to update the kernel.

### CODE REVIEW

**Review by christoph-zededa — APPROVED** [review]

**Comment by eriknordmark** [comment]
@rouming you have a DCO issue on this PR

**Comment by rouming** [comment]
> DCO

whats DCO? Digitally Controlled Oscillator? :) I have an issue on 7.9.0, so 8.12 LTS is a good candidate.

**Comment by rouming** [comment]
ah the DCO which checks the signs off, sorry, I'm always confused with terms and abbreviations. 
Not me this time, with the 8.12 is the usual problem, it says: "Commit sha: [594d62a](https://github.com/lf-edge/eve/pull/3351/commits/594d62a0b792a1978e2346d657c0fd62c413af8e), Author: Ruslan Dautov, Committer: Ruslan Dautov; The sign-off is missing."

**Comment by shjala** [comment]
> Digitally Controlled Oscillator?

[Close](https://tortel.li/post/insecure-scope/) actually ;)

**Comment by rouming** [comment]
> > Digitally Controlled Oscillator?
> 
> [Close](https://tortel.li/post/insecure-scope/) actually ;)

"Conclusion
Do not expose your RIGOL oscilloscopes to the internet."

oh gosh I'm in danger :)

**Comment by rouming** [comment]
btw @shjala did you complete this one https://microcorruption.com ? I did many years ago, very proud of myself :)

**Comment by rouming** [comment]
This github dco is broken. I changed one file (not commit message) and pushed everything - now dco is satisfied, and what's interesting is that previously it complained about a Ruslan's commit (indeed without the signoff), but now it does not find it. Weird.

**Pull request merged**
