### PR TITLE
Deprecating unused fields of baseos api

### PR DESCRIPTION
**Pull request by zed-rishabh**

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
Can you check if there is code in Adam and/or the Zededa controller which fills in these fields?

**Comment by zed-rishabh** [comment]
> Can you check if there is code in Adam and/or the Zededa controller which fills in these fields?

Zededa controller is not filling it up but I need to with on Adam side.

**Comment by rvs** [comment]
It is actually less on Adam side and more on Eden side -- Adan by itself is not filling anything up -- it just uses whatever config Eden prepares @zed-rishabh

**Review by rvs — APPROVED** [review]
LGTM -- but please make sure to check with Eden team.

**Comment by mydatascience** [comment]
We are fine as Eden team

**Review by eriknordmark — APPROVED** [review]
Thanks

**Review by rvs — COMMENTED** [review]
LGTM

**Pull request merged**
